### ISSUE TITLE
Are vulnerability scan results for Official Images still shown on Docker Hub?

### ISSUE THREAD

**Issue by mtttcgcg** [docker/docs#10151]
File: [docker-hub/official_images.md](https://docs.docker.com/docker-hub/official_images/)
I do not see any vulnerability scan results from any of the Official Images I looked at after signing in with my Docker account.

**Comment by milesc** [comment]
Wondering the same.  I see in [docker-hub/release-notes.md](docker-hub/release-notes.md) that missing scan results is a known-issue, but it's been listed as such for almost 6 months now.  Any plan to fix?

**Comment by thaJeztah** [comment]
@pkennedyr @ddebroy ptal

**Comment by gillbee** [comment]
Any progress on this issue?  Should the scan results be available for all official images ?  Not seeing any result on the amazon linux official images.
