### ISSUE TITLE
Add documentation for new bridge driver option

### ISSUE THREAD

**Issue by arkodg** [docker/docs#10298]
https://github.com/docker/libnetwork/pull/2317 introduced a new bridge option `com.docker.network.bridge.inhibit_ipv4` that should be documented (related to https://github.com/moby/moby/issues/30053)

File: [network/bridge.md](https://docs.docker.com/network/bridge/)

**Comment by thaJeztah** [comment]
These are being included in "master" through https://github.com/docker/docker.github.io/issues/10298, so should be documented for the 20.03 release
