### ISSUE TITLE
Tutorial is incorrect.

### ISSUE THREAD

**Issue by mswilson4040** [docker/docs#10300]
File: [engine/examples/dotnetcore.md](https://docs.docker.com/engine/examples/dotnetcore/)

This tutorial does not work. I end up just getting the below output.

> It was not possible to find any installed .NET Core SDKs
> 
> Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
> 
> https://aka.ms/dotnet-download

Clearly it can't find the dotnet sdk but I definitely have it installed on my machine and I followed the instructions in the tutorial. There's a step missing and I don't know enough about docker to even start to troubleshoot this.

This tutorial needs some significant help.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this as the content is being removed from the docs.
Please check out the new guide at
https://docs.docker.com/language/dotnet/
