### ISSUE TITLE
Mismatching gpg signing key for ubuntu xenial arm64 packages

### ISSUE THREAD

**Issue by truls** [docker/docs#10333]
File: [install/linux/docker-ce/ubuntu.md](https://docs.docker.com/install/linux/docker-ce/ubuntu/)

The manual instructs to add the gpg 0EBFCD88 but the arm64 docker packages for ubuntu xenial are in fact signed with the key 7EA0A9C3F273FCD8. I had to run 

```
gpg --recv-keys 7EA0A9C3F273FCD8 --keyserver sks.keyserver.org
gpg --export --armor 7EA0A9C3F273FCD8 | apt-key add - 
```

in order to get `apt update` to complete successfully

**Comment by thaJeztah** [comment]
ping @arkodg @tiborvass PTAL
