### ISSUE TITLE
RFE: Uniform number formatting for .RunningFor / .Status / etc?

### ISSUE THREAD

**Issue by ANogin** [docker/docs#10336]
File: [engine/reference/commandline/ps.md](https://docs.docker.com/engine/reference/commandline/ps/)

docker ps currently prints human-readable strings ("days/hours/minutes/seconds") for {{.RunningFor}}  and {{.Status}} fields. Is there a way to have it to print the age of the container is seconds, so that this can be consumed by the other scripts? I am guessing it might be possible already (although perhaps I am wrong?), which is why I am filing this against the docs.

**Comment by linarnan** [comment]
maybe use: 
`docker inspect swss | jq '[.[]| .State.StartedAt]' `
