### ISSUE TITLE
Add example of HEX encoded URL values for the proxy config in the docs

### ISSUE THREAD

**Issue by kfortner** [docker/docs#10367]
File: [config/daemon/systemd.md](https://docs.docker.com/config/daemon/systemd/)

Systemctl requires different escape characters than a URL does so a proxy var with special URL characters needs to have then escaped with the hex equivalent and the systemctl escapes.

A backslash in domain\user becomes domain%5Cuser but this breaks systemctl because of the % sign.

If you need for systemctl with a url and special chars is domain%%5Cuser (Notice the DOUBLE %).

`[Service]`
`Environment="HTTP_PROXY=http://domain%%5Cuser:complex%%23pass@proxy.example.com:8080/"`

**Comment by LiamMahoney** [comment]
Just spent the past two hours banging my head against my desk trying to get docker setup behind my corporate proxy thinking I was mad. I found Kenneth's solution on a different site and it fixed my issue. +1 to it getting mentioned in the documentation. 

Thanks @kfortner!

**Comment by kfortner** [comment]
I submitted a pull request to hopefully get this updated.

[https://github.com/docker/docker.github.io/pull/11701](https://github.com/docker/docker.github.io/pull/11701)
