### ISSUE TITLE
Remove all stopped containers command is misleading

### ISSUE THREAD

**Issue by kkrull** [docker/docs#10403]
File: [engine/reference/commandline/rm.md](https://docs.docker.com/engine/reference/commandline/rm/)

In the section about removing all _stopped_ containers, it says to remove those containers identified by `docker ps -aq` -- but that won't that also include containers that are still running?  `docker ps -aq` by itself certainly shows running containers on my machine, with `docker-engine` 19.03.5.

**Comment by thaJeztah** [comment]
attempting to remove containers that are still running won't succeed, so they won't be removed.

Probably (reading from my phone) that section should recommend using the `docker container prune` command for that purpose (and a better example for when combining `docker ps -q .. ` with `docker rm` can be useful.
