### ISSUE TITLE
Containers can be attached and detached from user-defined networks on the fly

### ISSUE THREAD

**Issue by KarimBenyelloul** [docker/docs#10421]
File: [network/bridge.md](https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge)

We can read that 

> During a container s lifetime, you can connect or disconnect it from user-defined networks on the fly. To remove a container from the default bridge network, you need to stop the container and recreate it with different network options.

However in my lab, I was able to disconnect the default bridge network from a simple container . Im in docker version 19.03.6, build 369ce74a3c. 
am I missing something ? or the documentation is wrong ? 

many thanks, 
karim

**Comment by kaandirenBilgi** [comment]
@KarimBenyelloul I am having the same confusion on my local and some other virtual environments. Could you find the reason?
