### ISSUE TITLE
Environment replacement seems to be supported in RUN/CMD/etc

### ISSUE THREAD

**Issue by imba-tjd** [docker/docs#10439]
### Problem description

The doc says:

```
Environment variables are supported by the following list of instructions in the Dockerfile:

    ADD
    COPY
    ENV
    EXPOSE
    FROM
    LABEL
    STOPSIGNAL
    USER
    VOLUME
    WORKDIR

as well as:

    ONBUILD (when combined with one of the supported instructions above)
```

But as I tested, `RUN` and `CMD` also support it.

```
FROM alpine
ENV MYENV=HELLO
RUN echo $MYENV
CMD echo $MYENV
```

### Problem location

* https://docs.docker.com/engine/reference/builder/#environment-replacement
* https://github.com/docker/docker-ce/blob/master/components/cli/docs/reference/builder.md#environment-replacement

---

Because this is not a editorial issue and I don't think I have enough knowledge of Docker, I choose to open this issue rather than a PR.

**Comment by alexey-igrychev** [comment]
Environment replacement is also supported for `ARG` dockerfile instruction.
