### ISSUE TITLE
Add POSTGRES_HOST_AUTH_METHOD to docker-compose

### ISSUE THREAD

**Issue by AthulMuralidhar** [docker/docs#10529]
File: [compose/rails.md](https://docs.docker.com/compose/rails/)
- The current doc does not set the auth method for the postgres instance and hence we get
![Screenshot from 2020-03-28 16-50-01](https://user-images.githubusercontent.com/35686547/77827131-33c42a80-7114-11ea-8c5f-f4e8fe5a9131.png)

- But after specifying the `POSTGRES_HOST_AUTH_METHOD` to `trust` like so:
``` db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
```
- We are able to get the db container up and running:
![Screenshot from 2020-03-28 16-52-25](https://user-images.githubusercontent.com/35686547/77827190-84d41e80-7114-11ea-9af3-9fd115d567ee.png)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this as the content is being removed from the docs repo.
