### ISSUE TITLE
-a flag does not respect my choice of which standard streams to attach to the standard streams of the process running in the container.,

### ISSUE THREAD

**Issue by angelgruevski** [docker/docs#10575]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/)
The documentation for running containers in foreground mode say that we can use the flag '-a' to attach the terminal emulator/console standard streams to the standard streams of the process running inside the container.

Let's take the following example:
`docker container run --tty -a stdout --interactive ubuntu:bionic /bin/bash`
According to my understanding of things, the flags mean the following:

- tty allocates virtual terminal, which means it formats the STDOUT, STDIN and STDERR coming from the started shell in the container suitable for displaying on a terminal emulator (the one running locally on my computer)
- a stdout attaches/pipes the STDOUT stream of  the process running inside the container, shell in this example, to the STDOUT stream of my terminal emulator
- interactive keeps the STDIN stream of the process running inside the container, the shell, open even if we are not piping/attaching the STDIN stream from the terminal emulator running on my computer to the STDIN stream of the shell running inside the container

Given the explanation above, I should not be able to pass commands to the shell running inside the container, because I did not attach/piped the STDIN of my terminal emulator running locally on my computer to the STDIN of the shell running inside the container, BUT, I am able to pass commands to the shell in the container and it executes them.

Can someone add additional explanation why is that the case? Tldr; I can pass commands to the process running inside the container even though I did not attach STDIN stream of my terminal emulator running on my computer locally, to the STDIN stream of the process (shell in the example) running inside the container.

**Comment by thaJeztah** [comment]
the `-i` / `--interactive` options attaches `STDIN`. Perhaps the description should be tweaked somewhat.

Is there a specific use-case you're trying to solve? Curious why you're using the combination of only attaching `stdout`, but also passing `--interactive`

**Comment by angelgruevski** [comment]
There isn't any specific use-case.
The Docker description for "-a" states that using this flag we can attach STDIN, STDOUT and STDERR, while "-i" flag keeps STDIN stream open even if we are not attached to that stream.

The confusing part is, it seems that "-i" not only keeps STDIN open, but it also attaches us to that stream even if we do not use "-a STDIN".
