### ISSUE TITLE
Document where ARG variable expansion can be used

### ISSUE THREAD

**Issue by PerMildner** [docker/docs#10666]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/) `https://docs.docker.com/engine/reference/builder/#using-arg-variables` "Using ARG variables" has no information at all about where `ARG` variables can be used. Instead it contains and links to information about where `ENV` variables can be used (and the linked-to documentation at `https://docs.docker.com/engine/reference/builder/#environment-replacement` does not mention `ARG` variables at all).

(Related, the reference for `ENV` (https://docs.docker.com/engine/reference/builder/#env) does not contain any information about where `ENV` variables can be used, not even the link that is used in the `ARG` entry.)

**Comment by kkirsche** [comment]
Relates to moby/moby#40830
