### ISSUE TITLE
This is showing precise ubuntu and a version of Postgres no longer maintained. Please update

### ISSUE THREAD

**Issue by genslein** [docker/docs#10888]
File: [engine/examples/postgresql_service.md](https://docs.docker.com/engine/examples/postgresql_service/)

Precise (Ubuntu 12.04 EOL)
Postgresql 9.3 EOL

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. Closing this as the content is being removed from the docs.
You can find updated samples at https://github.com/docker/awesome-compose/
