### ISSUE TITLE
why docs/docker.github.io:latest is outdated?

### ISSUE THREAD

**Issue by yunielrc** [docker/docs#10939]
https://hub.docker.com/r/docs/docker.github.io/tags

![Screenshot from 2020-06-01 13-49-04](https://user-images.githubusercontent.com/28462092/83438045-c6cc5a00-a40e-11ea-9c9f-3212c3ad0c0f.png)

**Comment by thaJeztah** [comment]
I suspect this is because we switched to a different release pipeline for the docs.

@StefanScherer wdyt? should we push an image during build, or should we configure auto-builds for the repository?

**Comment by StefanScherer** [comment]
We could push an image whenever we publish the docs.
Maybe here https://github.com/docker/docker.github.io/blob/master/.github/workflows/build-published.yml

**Comment by thaJeztah** [comment]
Perhaps auto builds would be easy as well, as it would be independent from that flow (and we wouldn't have to pass credentials in the pipeline just for that 🤔)

**Comment by yunielrc** [comment]
devops practice: continuos delivery :)
