### ISSUE TITLE
Document availability of socks5 proxy in various files

### ISSUE THREAD

**Issue by WiGeeky** [docker/docs#11005]
### Problem description

Docker added support for socks since the version 1.11.0 ([Release notes](https://docs.docker.com/engine/release-notes/prior-releases/#1110-2016-04-13)) onward. But since the release, no proper documentation has been added mentioning such support.

- an issue at the Moby project ([24708](https://github.com/moby/moby/issues/24708)) suggests an edit must be applied to `config/daemon/systemd.md`
-  the documentation on using Docker client through a proxy (`network/proxy.md`) also makes no mention of the socks support either.

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/config/daemon/systemd/#httphttps-proxy

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/network/proxy/

### Project version(s) affected
Docker Engine 1.11.0+ ([docker/docker-ce 20366](https://github.com/moby/moby/pull/20366))

### Suggestions for a fix
a pull request is needed to add mentions (and usage examples with a socks5 proxy instead of HTTP) of the feature, to help make it more usable. I added a question on [AskUbuntu](https://askubuntu.com/questions/1251157/how-can-i-use-docker-with-socks5-in-ubuntu/1251158#1251158) on this but it'd be better to have that info on the docs website.

**Comment by luo-geng** [comment]
+1
