### ISSUE TITLE
Update Install Docker Compose page to include sample Dockerfile for building alpine linux and mention availability of docker image docker/compose:${VERSION}

### ISSUE THREAD

**Issue by dcs3spp** [docker/docs#11025]
File: [compose/install.md](https://docs.docker.com/compose/install/)

The documentation states that 

> For alpine, the following dependency packages are needed: py-pip, python-dev, libffi-dev, openssl-dev, gcc, libc-dev, and make. 

On Alpine 3.12+ py-pip appears to only install Python 3 pip and python-dev is not available. However, python2-dev and python3-dev packages are available.

Managed to eventually get docker image built using the Dockerfile below that uses Alpine linux.
``` docker
ARG BUILD=19.03.11
FROM docker:$BUILD

ARG DOCKER_COMPOSE_VERSION=1.26.0

RUN apk update \
    && apk add --no-cache --update make py3-pip \
    \
    && apk add --no-cache --update --virtual .docker-compose-deps \
      gcc \
      libc-dev \
      libffi-dev \
      python3-dev \
      openssl-dev \
    \
    && pip install -U docker-compose==${DOCKER_COMPOSE_VERSION} \
    \
    && apk del .docker-compose-deps \
    && rm -rf `find / -regex '.*\.py[co]' -or -name apk`
```

Also discovered that there is a docker image available by pulling  image *docker/compose:${VERSION}*. This defaults to alpine linux. It appears that there is also a Debian variant by pulling *docker/compose:debian-${VERSION}. To save some time, it might be worth mentioning this on the "Install Docker Compose" page.

**Comment by aevesdocker** [comment]
Closing issue as it refers to content that is no longer in the docs
