### ISSUE TITLE
Passing multiple secret information

### ISSUE THREAD

**Issue by wladimirguerra** [docker/docs#11043]
File: [develop/develop-images/build_enhancements.md](https://docs.docker.com/develop/develop-images/build_enhancements/) doesn't describe the situation when there is more than one secret to be passed to container.

The questions are:

1) Should all secrets be on the file pointed by `id`? 
In that case, a shell script example to put the data on environment variables should be given to help those with low experience on shell.
Something like:

```
use_secrets.sh

#!/bin/bash
set -euo pipefail
SECRET_FILE=/run/secrets/keys
if [ -f "$SECRET_FILE" ]; then
  while read -r line; do declare "$line";
  done < "$SECRET_FILE"
fi
```
where `/run/secrets/keys` contains `key=value` pairs for each line.

The `Dockerfile` should have then:
```
# Mount the secret to /run/secrets:
RUN --mount=type=secret,id=keys ./use_secrets.sh
```

2) Or is it possible to set `--secret` more than once, like:

` docker build --no-cache --progress=plain --secret id=my1stsecret,src=my1stsecret  --secret id=my2ndsecret,src=my2ndsecret`

And the shell script should be:
```
use_secret.sh

#!bin/bash
set -euo pipefail
SECRET_KEY_FILE=/run/secret/$1
if [ -f "$SECRET_KEY_FILE" ]; then
  export "$1"=$(cat "$SECRET_KEY_FILE")
fi
```

The `Dockerfile` should have then:
```
# Mount the secret to /run/secrets:
RUN --mount=type=secret,id=my1stsecret ./use_secrets.sh my1stsecret
RUN --mount=type=secret,id=my2stsecret ./use_secrets.sh my2stsecret
```
the secret files should be:
- `my1stsecret` with content `big sensitive data1`;
- `my2ndsecret` with content `big sensitive data2`;

**Comment by Gerrit-K** [comment]
Just for the record (because I wasn't able to find something on this): yes, it appears to be possible to pass multiple `--secret` flags. Still undocumented, though.

**Comment by nilox94** [comment]
Acording to [Render](https://render.com/docs/docker-secrets) you can mount multiple secrets.
> You can make use of **multiple secret files** by adding more `--mount=type=secret,...`.
