### ISSUE TITLE
improvement on docker buildkit docs

### ISSUE THREAD

**Issue by developer-guy** [docker/docs#11084]
@thaJeztah

**Comment by thaJeztah** [comment]
👆 from a discussion on slack;

> What is the difference between "buildkit" and "docker buildkit" https://docs.docker.com/develop/develop-images/build_enhancements/ & https://github.com/moby/buildkit

My reply;

> They're "the same" (but slightly different context): `BuildKit` is the "build engine"  / "toolkit". It's a seprate project (https://github.com/moby/buildkit), and _can_ be run "standalone", but can also be used as a component in other software. It's a bit similar to Chromium, which is used both by Chrome, Microsoft Edge, Opera (and various other webbrowsers)
>
> `docker` is using BuildKit as the "next generation" build-engine to replace the old "classic" builder (the `docker` daemon has the BuildKit component embedded (compiled in)). It's not yet enable by default, so you need to set `DOCKER_BUILDKIT=1` otherwise the "classic" builder is used.
>
> So the "Docker BuildKit" page you're refering to (https://docs.docker.com/develop/develop-images/build_enhancements/) means `docker build` with the BuildKit engine enabled (`DOCKER_BUILDKIT=1`)


I think it's worth documenting somewhere (perhaps a table/matrix) how these compare (classic builder, "buildkit" builder, buildkit standalone, buildx)
