### ISSUE TITLE
Add minimum docker-compose version for Compose file formats?

### ISSUE THREAD

**Issue by RudolfCardinal** [docker/docs#11249]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

The compatibility matrix, and the later text entries for different Compose file versions, at https://docs.docker.com/compose/compose-file/compose-versioning/ are beautifully clear as to which version of the Docker Engine is required for different Compose file versions. However, it's a bit harder to work out, for many versions (e.g. between 3.5 and 3.7) which version of docker-compose is required. Trawling through the release history (https://github.com/docker/compose/releases) suggests, for example, that you need docker-compose 1.20.0+ for Compose syntax v3.6, and docker-compose 1.22.0+ for syntax v3.7.

This is a "live" problem because, for example, Ubuntu 18.04 LTS comes with docker-compose 1.17.1 by default and so won't work with Compose files beyond 3.5. Would it therefore help to add the minimum docker-compose versions to the docs?

**Comment by aevesdocker** [comment]
Hi @RudolfCardinal I'm closing the issue as it now refers to legacy content and we feel it would not be a valuable addition to the docs. Thank you for your contribution.
