### ISSUE TITLE
Security risk (exposed passwords) when following instructions for secrets

### ISSUE THREAD

**Issue by aqueenan** [docker/docs#11262]
File: [engine/swarm/secrets.md](https://docs.docker.com/engine/swarm/secrets/)

The [Example: Rotate a secret](https://docs.docker.com/engine/swarm/secrets/#example-rotate-a-secret), when referring to the use of `$(</run/secrets/mysql_password)` in the `mysqladmin` commands, incorrectly states that:

> This command reads the old and new password from the files in /run/secrets but **does not expose them on the command line** or save them in the shell history.

In fact the shell executes the `$(<)` expression and puts the result of that expression onto the command line. So anyone with access to `ps` can find out the password.

To demonstrate the problem:

```
$ echo '**mysupersecretpassword**' |sudo docker secret create password -
nxt44wlqpfuucnwfp2sgsun9m

$ sudo docker service create --name exposepassword --secret password --entrypoint 'bash -c "while true; do grep -R $(</run/secrets/password) /; done 2>/dev/null"' ubuntu:latest
n715dwnry2theju5mh15gnacw
overall progress: 1 out of 1 tasks
1/1: running   [==================================================>]
verify: Service converged

$ ps -ef |grep grep
root     1043921 1043903  0 03:53 ?        00:00:00 bash -c while true; do grep -R $(</run/secrets/password) /; done 2>/dev/null
root     1043962 1043921  0 03:53 ?        00:00:00 grep -R **mysupersecretpassword** /
install+ 1044006 1041948  0 03:54 pts/2    00:00:00 grep --color=auto grep

$ sudo docker service remove exposepassword
exposepassword
```

**Comment by thaJeztah** [comment]
Yes, I think this is a limitation of `mysqladmin`, which (afaik) doesn't support passing passwords through stdin.

From [their documentation](https://dev.mysql.com/doc/refman/8.0/en/mysqladmin.html);

> **Warning**
>
> Setting a password using `mysqladmin` should be considered _insecure_. On some
> systems, your password becomes visible to system status programs such as `ps`
> that may be invoked by other users to display command lines. MySQL clients
> typically overwrite the command-line password argument with zeros during their
> initialization sequence. However, there is still a brief interval during which
> the value is visible. Also, on some systems this overwriting strategy is ineffective
> and the password remains visible to `ps`. (SystemV Unix systems and perhaps
> others are subject to this problem.)

Perhaps a note should be added and/or a link to their docs.

That said, a bad actor being able to get access would likely mean that the host was already compromised.


@justincormack @tianon @ltangvald perhaps one of you has suggestions?

**Comment by tianon** [comment]
Yeah, https://dev.mysql.com/doc/refman/8.0/en/password-security-user.html is a good upstream doc on this -- I think the "right" fix here would be to generate an appropriate configuration file for specifying the old password and generating an on-disk SQL file for changing to the new password (preferably in a `tmpfs` so they're never actually on-disk), instead of using `mysqladmin password`.
