### ISSUE TITLE
Not enough to restart docker, I had to disable and enable

### ISSUE THREAD

**Issue by e-g-hategan** [docker/docs#11386]
File: [config/daemon/systemd.md](https://docs.docker.com/config/daemon/systemd/)

For me on CentOS 8 and docker 19.3.12 it was not enough to do `sudo systemctl restart docker`. 
I had to disable and enable for it to pick up the changes.

**Comment by thaJeztah** [comment]
Did you run `sudo systemctl daemon-reload` first? Doing that is needed to load the updated configuration.

**Comment by e-g-hategan** [comment]
yes, I ran 
`sudo systemctl daemon-reload`
`sudo systemctl disable docker`
`sudo systemctl enable docker`

**Comment by thaJeztah** [comment]
What changes did you make to the unit files? Setting the proxy variables, or something else?

**Comment by e-g-hategan** [comment]
Yes, setting proxy variables.
