### ISSUE TITLE
Flash of incorrect theme (FOIT) occurs when viewing docs in dark mode

### ISSUE THREAD

**Issue by jeffslofish** [docker/docs#11468]
### Problem description

With the dark mode theme selected, switching between some pages, causes a "flash of incorrect theme" or "FOIT" in which the screen flashes bright white for a split second before switching to the dark theme. This is annoying and possibly seizure inducing for some.

### Problem location

For example, if you go to https://docs.docker.com/engine/ and then click the second item in the left menu, "Install", the flash of incorrect theme happens.

**Comment by allejo** [comment]
I've submitted #11482, which addresses this problem. If you wouldn't mind helping out, could you navigate through the preview of that PR and see if you find any glaring problems in either theme as a user?

**Comment by jeffslofish** [comment]
Please see my comments in the pull request.
