### ISSUE TITLE
The indentation in the documentation right panel is inadequate.

### ISSUE THREAD

**Issue by gdennie** [docker/docs#11529]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

The indentation in the documentation right panel is inadequate. A collapsing mechanism is recommended as well as emphasis distinction between the major and minor headings.

**Comment by thaJeztah** [comment]
Thanks for reporting; yes, the compose-file reference has grown quite a bit, and may need some improvements to make it easier to navigate 😓
