### ISSUE TITLE
Docker compose -> Using compose in production -> Running compose in a swarm cluster -> link " integration guide." gives a 403 forbidden error  

### ISSUE THREAD

**Issue by PramodKumarYadav** [docker/docs#11522]
Docker compose -> Using compose in production -> Running compose in a swarm cluster -> link " integration guide." gives a 403 forbidden error .

Url of error page is: https://docs.docker.com/compose/production/swarm.md

Text: Sorry, we can't find that page
There might be a mistake in the URL or you might’ve clicked a link to content that no longer exists.

If you think it’s the latter, please file an issue at https://github.com/docker/docker.github.io and let us know what happened. Please also include a link to where the error occurred, if applicable.

**Comment by aevesdocker** [comment]
Closing as issue refers to content that no longer exists
