### ISSUE TITLE
Command line for TLS in Powershell

### ISSUE THREAD

**Issue by 1Dimitri** [docker/docs#11548]
File: [compose/install.md](https://docs.docker.com/compose/install/)
Use of `[Net.ServicePointManager]::SecurityProtocol += [Net.SecurityProtocolType]::Tls12` by adding TLS1.2 to the list of allowed protocols instead of replacing the full list avoid breaking potential other download commands

**Comment by aevesdocker** [comment]
Closing issue as it refers to content that is no longer in the docs
