### ISSUE TITLE
iptables-nft vs iptables-legacy

### ISSUE THREAD

**Issue by harridu** [docker/docs#11612]
Please document docker's requirements wrt nft and legacy iptables. AFAIU modern Distros like Debian10, RedHat 8.2, Ubuntu 20.10, etc come with nft and maybe a wrapper ("iptables-nft"). Old distros don't support nft at all. nft/iptables-nft and legacy iptables are not 100% compatible, so what's the deal?

**Comment by mortn** [comment]
> Old distros don't support nft at all.

Dude, [nftables was introduced with kernel 3.13!](https://kernelnewbies.org/Linux_3.13#head-f628a9c41d7ec091f7a62db6a49b8da50659ec88)
We're just witnessing a pronounced lack of willingness to change in the folks working with linux-based firewalls, firewall scripts, and related functionality in various platforms like Docker. They have simply been critically slow to adopt nftables in favor of iptables. Docker is only one in many systems neglected in that way forcing them to be hacked in many ways.

**Comment by terorie** [comment]
> Old distros don't support nft at all.

That's a bit misleading. Most old distros that aren't completely abandoned support nftables.

Ubuntu 14.04 for example is the oldest version that is still supported with Extended Security Maintenance and even that version has nftables.

The "oldoldstable" Debian 8 "jessie", which did not get regular security updates in over 2 years also supports nftables.

It's unreasonable for Docker to not even acknowledge the existence of nftables in the official docs. Searching for "nftables" on `docs.docker.com` only points to Forum results by users.

**Comment by winkee01** [comment]
by default, docker uses iptables-nft on my machine, ubuntu 20.04

**Comment by electrofloat** [comment]
There's no iptables on my machine (and never will be), only nft
```
iptables --version
Command 'iptables' not found, but can be installed with:
sudo apt install iptables
```
```
 nft --version
nftables v1.0.2 (Lester Gooch)
```
How about that?

**Comment by f0086** [comment]
```/remove-lifecycle stale```
```/lifecycle frozen```
