### ISSUE TITLE
Documentation for Environment Variable based Secret Passing

### ISSUE THREAD

**Issue by chirangaalwis** [docker/docs#11673]
### Problem description
[Support for passing Secrets via environment variables](https://github.com/moby/buildkit/issues/1703) is available in the Docker client. This needs to be properly documented.

### Problem location
The documentation relevant to the issue -> [New Docker Build secret information](https://github.com/docker/docker.github.io/blob/3e767a72b3c48ecd23e1f734a27b7ca7b9cfc3f7/develop/develop-images/build_enhancements.md#new-docker-build-secret-information)

### Project version(s) affected
From Docker Client version `19.03.13` onwards as per https://github.com/docker/cli/pull/2656. Please correct me if I am wrong.

### Suggested assignee
@thaJeztah

**Comment by TBBle** [comment]
I think the CLI support from that linked PR is only in 20.10.0 onwards. https://github.com/moby/moby/pull/41234 for the daemon side also reports 20.10.0.
