### ISSUE TITLE
Missing scale property in docker compose file version 3

### ISSUE THREAD

**Issue by w3dev-dk** [docker/docs#11716]
### Problem description

In a version 3.8 docker compose project I was looking for a way to define `--scale $SERVICE=$NUMBER` either as an environment variable or as part of my yaml file. According to the CLI documentation it should be possible:

>     --scale SERVICE=NUM        Scale SERVICE to NUM instances. Overrides the
>                                `scale` setting in the Compose file if present.

So I just tried to add it and it works. But when I looked up the documentation online then I could not find it at first cause it's only present under the version 2 documentation. Before I make a PR I would just like to know if this is a mistake or if it's in fact is on purpose?

### Problem location

The documentation is present here: https://github.com/docker/docker.github.io/blob/master/compose/compose-file/compose-file-v2.md#scale

But not here: https://github.com/docker/docker.github.io/blob/master/compose/compose-file/index.md

### Project version(s) affected

Docker compose file docs version 3.X

### Suggestions for a fix

Copy the docs from version 2 unless some changes (signature, new features) has happened since then

**Comment by thaJeztah** [comment]
In the v3 syntax, the "scale" property was replaced with the "replicas" property under "deploy" (which holds other properties related to deployment of the service); https://docs.docker.com/compose/compose-file/#deploy

**Comment by w3dev-dk** [comment]
Yes, I'm aware of the `deploy.replicas` property but that only applies for deployments like `docker stack deploy`. `scale` is to my understanding a one to one implementation of `--scale` used together with `docker-compose up`. And as mentioned then it actually works (just not documented online).

As I work with microservices and we always would like to test our application locally with more than one instance then the `scale` property suit our needs perfectly. But I would like to know if it's deprecated and on it's way out or if it's future proof to use it as a general recommendation in our company?

Below works and equals running `docker-compose up --scale app=3`:

```yaml
version: "3.8"

services:
  app:
    image: nginx
    scale: 3
```
