### ISSUE TITLE
how to define image defaults

### ISSUE THREAD

**Issue by datu925** [docker/docs#11758]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

In https://docs.docker.com/engine/reference/run/#general-form, it says:
```
An image developer can define image defaults related to:

detached or foreground running
container identification
network settings
runtime constraints on CPU and memory
```

The subsequent section is all about how to use `docker run` to override these defaults. However, after a bunch of searching, I can't find any reference for how to define those defaults on an image. If this documentation does exist, then I think this section should directly link to it, since naive searches don't bring it up.

**Comment by Nimrod0901** [comment]
Same question here. It seems confusing...
