### ISSUE TITLE
Clarify whether restart_policy.delay works without Swarm-mode

### ISSUE THREAD

**Issue by EnergySRE** [docker/docs#11777]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

I was surprised to discover that restart_policy.delay apparently doesn't work without Swarm-mode. Got this when running `docker-compose up` on the config with a delay set.

```
WARNING: The following deploy sub-keys are not supported and have been ignored: restart_policy.delay
```

Seems like just saying "Swarm only" would suffice.

**Comment by copolycube** [comment]
Hello, I just had the same disappointment :-/

```
docker-compose.yml version: "3.8"
docker-compose version 1.28.5, build c4eb3a1f
Docker version 20.10.3, build 48d30b5
```

**Comment by FireEmerald** [comment]
You should read the documentation of the root section [`deploy`](https://docs.docker.com/compose/compose-file/compose-file-v3/#deploy).

There is written:
> _**deploy**_
>
> Specify configuration related to the deployment and running of services. **This only takes effect when deploying to a swarm with docker stack deploy**, and is ignored by docker-compose up and docker-compose run.

**Comment by EnergySRE** [comment]
Hmmm, okay, thanks for clarifying. This raises a different question thought: if that's true, why does restart_policy.condition work? And are there other parameters that work for docker-compose up? How should the reader know which is which?

**Comment by exokortex** [comment]
> > **This only takes effect when deploying to a swarm with docker stack deploy**, and is ignored by docker-compose up and docker-compose run.

This does not seem to be the case though. If you add a `restart_policy` to a container, `docker-compose up` will attempt restarting it, which is not the case for containers without a `restart_policy`.

**Comment by Achilles0509** [comment]
Yes, seems `restart_policy.condition` and `restart_policy.max_attempts` work.
