### ISSUE TITLE
ECS & ACI Documentation lacks instructions to enable Experimental features

### ISSUE THREAD

**Issue by mjpowersjr** [docker/docs#11845]
### Problem description

Documentation for both Amazon ECS & Azure ACI integration is missing step to properly setup for a Linux environment. I suspect this only impacts Linux, not Docker Desktop for Mac / Windows - but that is just an assumption.

The ECS documentation states you need the following requirements (emphasis mine):

----

### Install the Docker Compose CLI on Linux
The Docker Compose CLI adds support for running and managing containers on ECS.

### Install Prerequisites
**Docker 19.03 or later**

----
I did verify I had the latest release of both Docker & Docker Compose installed (see version information below).

If you follow the instructions for Linux, and you attempt to create a new context - the following error occurs:
```sh
mike@XPS-13-9360:~/projects/otel-collector$ docker context create ecs staging
"docker context create" requires exactly 1 argument.
See 'docker context create --help'.

Usage:  docker context create [OPTIONS] CONTEXT

Create a context
```

In troubleshooting the problem, I found someone else who put in a ticket regarding this. I don't think the user's problem was well understood, as the ticket seems to have been closed without actually solving the underling problem.

https://github.com/docker/compose-cli/issues/847

**It turns out, with the latest released version of the Docker CLI for Linux, you must enable experimental feature support in order to successfully create a ECS context.**

To resolve the problem, I did the following:
1. Configured *experimental* support 

https://github.com/docker/cli/blob/master/experimental/README.md

2. Restarted Docker Daemon
```sh
sudo systemctl restart docker
```
After this change, I was able to successfully create a ECS context:
```sh
mike@XPS-13-9360:~/projects/otel-collector$ docker context create ecs staging
? Create a Docker context using:  [Use arrows to move, type to filter]
> An existing AWS profile
  AWS secret and token credentials
  AWS environment variables
```

### Problem location

 I couldn't find the information I wanted. I expected to find it near the following URL:
* https://docs.docker.com/engine/context/ecs-integration
* https://docs.docker.com/engine/context/aci-integration/

### Project version(s) affected
```sh
mike@XPS-13-9360:~$ docker --version
Docker version 19.03.14, build 5eb3275d40

mike@XPS-13-9360:~$ docker-compose --version
docker-compose version 1.23.2, build 1110ad01
```
### Suggestions for a fix
Please consider adding information about enabling *experimental* features within the documentation.

**Comment by jleclanche** [comment]
Is there anything else than enabling experimental mode in both the server and client required for `docker context create ecs …` to work?
I am going crazy. I got it to work locally but now I'm trying to make it work on Gitlab CI, and, well:

![image](https://user-images.githubusercontent.com/235410/106427932-722f2200-6468-11eb-9aaa-b9cb25d76482.png)

Experimental: true on both client and server…

**Comment by dumar** [comment]
Same problem here with Azure, experimental features enabled. Version: 20.10.1 on Linux

```
docker context create aci azureaci
"docker context create" requires exactly 1 argument.
See 'docker context create --help'.

Usage:  docker context create [OPTIONS] CONTEXT

Create a context
```

**Comment by bmilesp** [comment]
Same error for me on Ubuntu 20.04

**Comment by belvederef** [comment]
The issue is still here on Linux with Docker version 20.10.5

**Comment by shoeb-a-sabur** [comment]
Anyone still having this issue, the solution here worked: https://github.com/docker/docker.github.io/issues/11949#issuecomment-778178431

Please make sure to reload your current shell session by closing/restarting all shell windows.

**Comment by tblevins-pv** [comment]
Perhaps I wasn't restarting the docker Daemon correctly on Mac but I had to follow `mjpowersjr` solution and then uninstall Docker Desktop entirely and reinstall it (it wouldn't update due to some issues)

**Comment by tedz2usa** [comment]
For me, on Linux, I had to install "Docker Compose CLI", (which is different from "Docker Compose" and "Docker Compose V2"):
- https://docs.docker.com/cloud/ecs-integration/#install-the-docker-compose-cli-on-linux
- https://github.com/docker/compose-cli/blob/main/INSTALL.md

Then I had to exit and re-enter the shell to see the `$ docker context create ecs myecscontext` command work successfully.

**Comment by brun0xff** [comment]
> Anyone still having this issue, the solution here worked: [#11949 (comment)](https://github.com/docker/docker.github.io/issues/11949#issuecomment-778178431)
> 
> Please make sure to reload your current shell session by closing/restarting all shell windows.

I have no idea why It's worked because I already docker-compose with `Docker Compose version v2.2.3` installed but now is work.

**Comment by brun0xff** [comment]
> Anyone still having this issue, the solution here worked: [#11949 (comment)](https://github.com/docker/docker.github.io/issues/11949#issuecomment-778178431)
> 
> Please make sure to reload your current shell session by closing/restarting all shell windows.

I've already had the `Docker Compose version v2.2.3` when I tried `docker context create ecs myecscontext`. I installed the docker-compose again as you suggested and it worked. I checked the version and it was the same I was using before. I have no idea why it worked, but thank you.

**Comment by Jaeminst** [comment]
Can I use this `docker ecs setup` in v2?

**Comment by socketbox** [comment]
For those on linux trying to get this to work with ECS:
# [enable `experimental` features in docker ](https://github.com/docker/cli/blob/master/experimental/README.md)
# restart the docker daemon (`systemctl restart docker` or the like)
# [install the docker compose-cli binary](https://github.com/docker/compose-cli/blob/main/INSTALL.md)
# restart the docker daemon (for good measure)
# reinitialize the shell environment (easiest to exit from the current shell and create a new one)
