### ISSUE TITLE
Issue seen with first few logs missing when fluentd in container and in same docker-compose with application

### ISSUE THREAD

**Issue by bkannadassan** [docker/docs#11894]
### Problem description

Write a go program with a simple print statement and start printing with the count. Have fluentd in the same compose and put the application depends on fluentd. When docker-compose up is done first few logs are lost.

Other testing done:
When the application is given 5 seconds before starting to print logs all logs are captured. Hence looks like some logs from fluentd-driver to fluentd container is getting lost when they try coming up simultaneously.

### Problem location

NA

### Project version(s) affected

Any fluentd version
---------------------
NA

**Comment by JonasGroeger** [comment]
We're having the same issue. Our solution / workaround is to start the fluentd container first:

```
docker-compose up fluentd
```

and then start the rest of the services:

```
docker-compose up
```
