### ISSUE TITLE
Could not find 'bundler' (2.1.4) required by your /myapp/Gemfile.lock. (Gem::GemNotFoundException)

### ISSUE THREAD

**Issue by an-pham** [docker/docs#11897]
File: [compose/rails.md](https://docs.docker.com/compose/rails/)
Could not find 'bundler' (2.1.4) required by your /myapp/Gemfile.lock. (Gem::GemNotFoundException)

Should include `RUN gem install bundler` in Dockerfile before `RUN bundle install` to ensure bundler is there when needed

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this as the content is being removed from the docs. You can find updated samples at https://github.com/docker/awesome-compose/
