### ISSUE TITLE
"docker context create" requires exactly 1 argument. when docker context create ecs myecscontext is executed

### ISSUE THREAD

**Issue by heyitspieter** [docker/docs#11949]
File: [engine/context/ecs-integration.md](https://docs.docker.com/engine/context/ecs-integration/)

**Comment by thaJeztah** [comment]
@gtardif PTAL

**Comment by hariseldon78** [comment]
I'm also getting this error on arch linux. I have docker-compose installed, but it seems there is no ecs integration.

**Comment by bmilesp** [comment]
Me too. Ubuntu 20.04.

**Comment by NathTech** [comment]
me too :( Ubuntu 20.04 docker version 19.03.8, build afacb8b7f0

**Comment by NathTech** [comment]
Sorted it, you need to install docker compose https://github.com/docker/compose-cli/blob/main/INSTALL.md which has the ecs integration.

**Comment by shoeb-a-sabur** [comment]
> Sorted it, you need to install docker compose https://github.com/docker/compose-cli/blob/main/INSTALL.md which has the ecs integration.

Thank you @NathTech . This worked for me. For anyone reading, be sure to reload your shell session in order for the changes to take effect.

**Comment by mlyons-diamondage** [comment]
if you came here and are operating on the WSL And everything appears to be up to date, but you still can't do it, try this in a WSL shell: 
```bash
curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
```

**Comment by patrickspiegel** [comment]
For future googlers: If you have copied the command from some website and pasted it into your console, this might help you:
https://stackoverflow.com/a/66648460
