### ISSUE TITLE
Fix outdated syntax rule about quotation marks in env files

### ISSUE THREAD

**Issue by hariharan-oviva** [docker/docs#12000]
File: [compose/env-file.md](https://docs.docker.com/compose/env-file/)

In the syntax rules, it currently says 

> There is no special handling of quotation marks. This means that they are part of the VAL.

But after [v1.26,](https://github.com/docker/compose/blob/master/CHANGELOG.md#1260-2020-06-03) python-dotenv handles the .env file processing, and it allows quotes and they are not a part of the VAL. Correct me if I missed anything, but in my testing this appears to be the case.

This might not be necessary but good to mention as a note.

**Comment by aevesdocker** [comment]
Thanks for reporting the issue. This has now been fixed.
