### ISSUE TITLE
compose versioning document has some issues

### ISSUE THREAD

**Issue by imthenachoman** [docker/docs#12021]
File: [compose/compose-file/compose-versioning.md](https://docs.docker.com/compose/compose-file/compose-versioning/)

- The [Compatibility matrix](https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix) says that the latest version is `3.8` but the document references `3.9` in [examples](https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix)
- https://docs.docker.com/compose/compose-file/compose-versioning/#version-2x-to-3x and https://docs.docker.com/compose/compose-file/compose-versioning/#version-3 say that `extends` has been removed from v3 but I am using `version: "3.9"` with `extends` and it is working as expected

**Comment by kenyon** [comment]
Also, the `version` element has become deprecated, so the examples should be updated to remove the version specification. Probably a lot of the docs should be rewritten to talk about version less prominently.

* https://github.com/compose-spec/compose-spec/pull/82
* https://github.com/compose-spec/compose-spec/pull/125

**Comment by imthenachoman** [comment]
Wait, so the version line is not even needed anymore?
