### ISSUE TITLE
Given docker file path no longer exists on ubntu linux

### ISSUE THREAD

**Issue by dgr8singh** [docker/docs#12031]
File: [engine/install/linux-postinstall.md](https://docs.docker.com/engine/install/linux-postinstall/)

Below given commands in doc are not working because these directories does not exists - 

$ sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
$ sudo chmod g+rwx "$HOME/.docker" -R

After every logout we have to use "$ newgrp docker" add user into docker group.

Following command helped to resolve above issue -
$ sudo chown "$USER":"$USER" /var/run/docker.sock

OS details - 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Comment by crydotsnake** [comment]
Normaly this steps should also work:

Add the Docker group (If not exists) `sudo groupadd docker`
Add your user too the Docker group: `sudo usermod -aG docker $USER`

Reload the changes to the group `newgrp docker `.

Restart your machine and test your docker installation with `docker run hello-world`

**Comment by dgr8singh** [comment]
> Normaly this steps should also work:
> 
> Add the docker group (If not exists): `sudo groupadd docker`
> Add your user too the docker group: `sudo usermod -aG docker $USER`
> 
> Reload the changes to the group: `newgrp docker `.
> 
> Start docker on boot: `sudo systemctl enable docker`
> 
> Restart your machine and test your docker installation with `docker run hello-world`

These commands worked as longer user is logged in. After logout I have to again reload the docker group using : `newgrp docker` else running docker without sudo I was getting permissions issues. 

And is it necessary to enable docker start on reboot ?

**Comment by crydotsnake** [comment]
Yes. Because if not you would need too start the docker service anytime. 

Thats weird.. normaly you only need to run `newgrp docker` one time.
