### ISSUE TITLE
Quickstart Documentation needs updating

### ISSUE THREAD

**Issue by Swift-png** [docker/docs#12163]
File: [compose/aspnet-mssql-compose.md](https://docs.docker.com/compose/aspnet-mssql-compose/)

I think these documents have gotten to the point where they could use an update, the referenced docker image has moved and it's supported anymore plus its no longer possible to generate the sample application that the documentation heavily references.

I managed to get a solution working - but I can't consider it a quick-start due to the extra work I had to do hacking a suitable aspnet site together.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this as the content is being removed from the docs. You can find updated samples at https://github.com/docker/awesome-compose/
A new .net guide has also been added at https://docs.docker.com/language/dotnet/
