### ISSUE TITLE
fix 'version' inside docker-compose.yml file 

### ISSUE THREAD

**Issue by rgiannico** [docker/docs#12190]
File: [compose/django.md](https://docs.docker.com/compose/django/)

This guide suggests using `version: "3.9"` inside the 'docker-compose.yml' file. 
This leads to this error: 

```
$ sudo docker-compose run web django-admin startproject composeexample .
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```
I solved using `version: "2"` inside the  'docker-compose.yml' file. 
I suggest editing the tutorial accordingly

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this as the content is being removed from the docs. You can find updated samples at https://github.com/docker/awesome-compose/
