### ISSUE TITLE
Recommend Buildkit for using multi-stage builds

### ISSUE THREAD

**Issue by dlindenkreuz** [docker/docs#12231]
File: [develop/develop-images/multistage-build.md](https://docs.docker.com/develop/develop-images/multistage-build/)

When people started off using Docker a couple of versions ago, their default is set to not use Buildkit. However, Buildkit is required to properly execute `-t release` stages. Without Buildkit, other stages of the same Dockerfile are executed as well although they shouldn't.

Please add a hint that the described features are only properly usable with Buildkit enabled.

**Comment by cburton-godaddy** [comment]
+1 To this, the difference in how pipelines work are drastically different when using multi stage + `--target` + buildkit.

We were using Jenkins that didn't use buildkit and using `--target` gave us unexpected execution of stages.

**Comment by andreisilviudragnea** [comment]
I have added a deeper explanation [here](https://github.com/andreisilviudragnea/learn-docker) about using multi-stage builds without BuildKit enabled.
