### ISSUE TITLE
Unclear behavior of --network=host on WSL2 Ubuntu 20.04

### ISSUE THREAD

**Issue by unfor19** [docker/docs#12270]
File: [network/host.md](https://docs.docker.com/network/host/)

### According to the docs 

> docker run --network=host ... is supported only on Linux

### My environment

WSL2 Ubuntu 20.04

### Scenarios

- Cannot access the container from host on localhost:80 - makes sense, it is stated in [the docs](https://docs.docker.com/network/network-tutorial-host/)
   ```bash
   docker run --network host --rm --name webserver -d nginx
   curl localhost:80
   # connection refused
   ```

- Can access the container from the host on localhost:80 - also makes sense, exposing with `-p`
   ```bash
   docker run --rm  --name webserver -d -p 80:80 nginx
   curl localhost:80
   # works
   ```

So far so good, all makes sense. Now here's the tricky part-

-  CANNOT access webserver, which makes sense, because the `httpd` container is attached only to the default bridge network, so it can't access containers with `localhost`
   ```bash
   docker run --rm  --name webserver -d -p 80:80 nginx
   docker run --rm httpd:2.4.46 ab -n 100000 -c 10 http://localhost:80/
   # connection refused
   ```
- **CAN access** webserver, **doesn't make sense**, why `--network=host` suddenly works? I thought it's not supported
   ```bash
   docker run --rm  --name webserver -d -p 80:80 nginx
   docker run --rm --network host httpd:2.4.46 ab -n 100000 -c 10 http://localhost:80/
   # works

   docker run --rm --network host httpd:2.4.46 ab -n 100000 -c 10 http://host.docker.internal:80/
   # also works, though super slow, see - https://docs.docker.com/docker-for-windows/networking/#use-cases-and-workarounds
   ```

### Conclusion

The `--network=host` behavior on Windows WSL2 is as follows
- ❌  Doesn't work for **listening** 
- ✔️  Works for making **requests** from a container to the host's network. This means another container has already exposed one of its ports with `-p` or `-P` 

Can anyone confirm the above conclusion? Does it make sense?

**Comment by Jont828** [comment]
I'm using Arch on WSL2 and I think I have a similar issue. When I run a webserver in a container on port 8080, I can access it just fine with `-p 8080:8080` but `--network=host` doesn't work.
