### ISSUE TITLE
CRUCIAL SYNTAX CORRECTION needed for psql role creation.

### ISSUE THREAD

**Issue by vhaegar1526** [docker/docs#12330]
File: [engine/examples/postgresql_service.md](https://docs.docker.com/engine/examples/postgresql_service/)
## Issue Location
`Dockerfile` for containerizing PostgreSQL,  Line:31
```bash
RUN    /etc/init.d/postgresql start &&\
    psql --command "CREATE USER docker WITH SUPERUSER PASSWORD 'docker';" &&\
    createdb -O docker docker
```
## Sticking to the syntax, it should be
```bash
RUN    /etc/init.d/postgresql start &&\
    psql --command="CREATE USER docker WITH SUPERUSER PASSWORD 'docker';" &&\
    createdb -O docker docker
```

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as this content will soon be removed from the docs.
You can find updated samples at https://github.com/docker/awesome-compose
