### ISSUE TITLE
documentation page "Dockerize a CouchDB service" not working any more.

### ISSUE THREAD

**Issue by 111andre111** [docker/docs#12497]
File: [engine/examples/couchdb_data_volumes.md](https://docs.docker.com/engine/examples/couchdb_data_volumes/)

It seems shykes couchdb is not active any more.
https://hub.docker.com/r/shykes/couchdb

In my opinion this should be corrected to e.g.:
https://hub.docker.com/r/apache/couchdb

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as the content will soon be removed in the next publish of the docs and redirect to https://hub.docker.com/_/couchdb/
