### ISSUE TITLE
Docker Compose tutorial incompatible with current docker engine version

### ISSUE THREAD

**Issue by aeromappings** [docker/docs#12491]
File: [compose/gettingstarted.md](https://docs.docker.com/compose/gettingstarted/)

Following the (new user) tutorial, the following error:
docker-compose up
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services: 'web'

Which followed the error:
$ docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

Looking into the compose-file doc, it seems this example format is deprecated.  I hope the example can be updated with the current expected compose-file format.  It's a little overwhelming at the beginning to troubleshoot the file format.. but I'm sure it will come in handy in the future!

Thanks.
Config below VV

/composetest$ docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Fri Dec 18 12:15:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
############################################
docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
###########################################

**Comment by aevesdocker** [comment]
Getting started tutorial has been updated and tested. Closing issue as it all works correctly
