### ISSUE TITLE
Support Windows in the Docker documentation

### ISSUE THREAD

**Issue by SetTrend** [docker/docs#12794]
### Problem description

I thoroughly read through the `dockerfile` reference, the `docker` and `docker-compose` reference, and other parts of the Docker documentation. What really makes it hard for me to grasp Docker is that many terms and examples relate to Linux only.

I'm a Windows programmer, using Docker for Windows. I'm very much acquainted with the Windows operating system for decades. Yet, I never heard about `ulimit` or other terms that don't apply to Windows. The `bash` syntax for reading input from STDIN (`$ docker build - < Dockerfile`), for example, is unfamilar and exotic to Windows programmers like me. Paths like `\etc\hosts` or `\etc\Docker\daemon.json` don't exist on Windows.

This way, the documentation is of no help to Windows programmers. We're left with bare hands, not being taught what to code to achieve the same effect on Windows.

### Suggestions for a fix

I suggest to accompany every Linux code sample (or path, resp.) with a corresponding Windows PowerShell code sample (or path, resp.) and have **(a)** either displayed both adjacent to each other or **(b)** to hide one of them, depending on the web browser's operating system where the documentation is viewed from.

Moreover, for parameters whose name or origin is Linux based there should be a valid brief explanation in Windows terms.

Parameters that don't apply to Windows should be tagged with "does not apply to Windows" or "does not apply to Windows images/containers" in the documentation.

**Comment by justin2004** [comment]
> The bash syntax for reading input from STDIN ($ docker build - < Dockerfile), for example, is unfamilar and exotic to Windows programmers like me.

how would you read from standard input in a windows command shell?


also some of the bash/linux example might work with https://gitforwindows.org/

**Comment by SetTrend** [comment]
> how would you read from standard input in a windows command shell?

You're right. Investigating on the correct syntax I noticed I stumbled over an awkward formulation in the Docker docs:

> Build with -
>
> `$ docker build - < Dockerfile`
>
> "This will read a Dockerfile from STDIN without context."

Actually, this will _**not**_ read a Dockerfile from STDIN. It will read a Dockerfile from the `Dockerfile` file.

I'll try to fix this description and create a PR from it.

**Comment by justin2004** [comment]
> 

    Build with -

    $ docker build - < Dockerfile

    "This will read a Dockerfile from STDIN without context."

Actually, this will not read a Dockerfile from STDIN. It will read a Dockerfile from the Dockerfile file.

in bash  `cat < some.txt`  tells cat to read from STDIN and STDIN is the result of redirection (the contents of a file called some.txt).

**Comment by SetTrend** [comment]
Exactly. Yet, that's the result of a piping operation. It didn't get clear from the documentation that STDIN got redirected first and then that result was fed into `docker build`.

**Comment by SetTrend** [comment]
I reworded the documentation from that page in one of the above pull requests. If it's approved it'll read like this:

> This will pass the provided Dockerfile's content through `STDIN` or pipe.
>
> No context will be sent to the Docker daemon, except for the piped
Dockerfile's content. That content is sent to the Docker daemon by
sendig it as `./Dockerfile` as sole context.
