### ISSUE TITLE
Errors with pg

### ISSUE THREAD

**Issue by Techinek** [docker/docs#13117]
File: [samples/django.md](https://docs.docker.com/samples/django/)
WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Permission denied
Could not open file "pg_xact/0000": Permission denied.
could not access status of transaction 0

Here's what I get after launching docker-compose up.

**Comment by nuriyevn** [comment]
the same problem

**Comment by nuriyevn** [comment]
Looks like we need to remove  all containers  before "docker-compose up". Because they does already exist.
Documentation does not pay attention to this nuance.

docker rm <container_names>

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as this content will soon be removed from the docs.
Please see https://github.com/docker/awesome-compose for samples.
