### ISSUE TITLE
touch command does not work for windows

### ISSUE THREAD

**Issue by Sammeeey** [docker/docs#13124]
File: [language/python/build-images.md](https://docs.docker.com/language/python/build-images/)

Isn't this guide ment to work for alle operating systems?
However it doesn't work for windows since there is no ["touch" command to create a new .py-file](https://docs.docker.com/language/python/build-images/#sample-application)

Maybe there should be a hint for windows users to create the file outside the command line?!

**Comment by tymik** [comment]
@usha-mandya as per discussion in #13136 and the case is addressed there, shall we close this issue then?
