### ISSUE TITLE
404 at /go/guides/%1B[0m

### ISSUE THREAD

**Issue by monitesh** [docker/docs#13146]

**Comment by thaJeztah** [comment]
Can you tell how you arrived at that URL? Was this from the Docker Desktop Dashboard, or did you copy it from somewhere ?

**Comment by thaJeztah** [comment]
Looks related to https://github.com/docker/cli/pull/2857. I suspect this may happen when using a shell that doesn't handle the ANSI escape sequences correctly (those are used to print the output "bold"), and includes the ANSI sequences as-is when copy/pasting the URL.

@monitesh what platform are you using? (windows, mac, linux?) and what shell?


/cc @gtardif @chris-crone

**Comment by usha-mandya** [comment]
Closing this issue as there's no response. Feel free to comment after I close.
