### ISSUE TITLE
SimpleWhaleDemo has workflows already

### ISSUE THREAD

**Issue by Sammeeey** [docker/docs#13144]
### Problem description

When you clone the SimpleWhaleDemo repository you don't have a Github project (on which you can work) yet.
Do you maybe mean to fork the repository?
In this case the workflows (which you would actually like to setup in the following part of the guide) are already set up.

### Problem location

- File: [language/python/configure-ci-cd.md](https://docs.docker.com/language/python/configure-ci-cd/)
- [Setup a Docker project](https://docs.docker.com/language/python/configure-ci-cd/#set-up-a-docker-project)

### Suggestions for a fix

1. Change wording to **fork** (instead of clone) the repository and add instructions to delete the preconfigured workflows to add them yourself.
2. Delete the workflows from the main [SimpleWhaleDemo Project](https://github.com/usha-mandya/SimpleWhaleDemo). So that people can really set them up theirselves.

**Comment by tymik** [comment]
Thank you for the report @Sammeeey, we appreciate it!
Would you like to make a PR with the suggestion no 1?

**Comment by Sammeeey** [comment]
Yes, I will do it.
But I may need some time.

**Comment by Sammeeey** [comment]
Just as a quick feedback:
Currently I don't really work with Docker.
And since I don't know very much about yml files (hence I don't really know the specs provided in the documentation), I'd have a hard time to restructure the documentation.

So if someone want's to solve the issue instead, I'd be very grateful🤗 - just leave a comment below✌
Otherwise I'll maybe do it at some unpredictable point in the future, when I start using Docker again and if I know a little more about yml.
