### ISSUE TITLE
Is "servicediscovery:*" policy correct?

### ISSUE THREAD

**Issue by xihh87** [docker/docs#13151]
File: [cloud/ecs-integration.md](https://docs.docker.com/cloud/ecs-integration/)

On [requirements section](https://docs.docker.com/cloud/ecs-integration/#requirements ), it is required a policy that contains: "servicediscovery:*", but i did not find it on the policy editor.

Is this service correct?

**Comment by seunghyunmoon2** [comment]
it was indeed search for 'Cloud Map'
