### ISSUE TITLE
An example or two would help considerably

### ISSUE THREAD

**Issue by neil-leigh** [docker/docs#13152]
File: [engine/reference/commandline/image_pull.md](https://docs.docker.com/engine/reference/commandline/image_pull/)

An example or two would help considerably. Specifically, for me as total newbie, not clear if I need to add https:// prefix to image location. Thanks.

**Comment by thaJeztah** [comment]
Thanks for reporting; `docker image pull` is an alias of `docker pull`, and we need to consolidate those docs. You can find more examples of these commands on this page, which describes `docker pull`; https://docs.docker.com/engine/reference/commandline/pull/
