### ISSUE TITLE
Specify `deploy -> update_config -> parallelism` default value

### ISSUE THREAD

**Issue by AlexElin** [docker/docs#13180]
### Problem description
Specify deploy -> update_config -> parallelism default value

![image](https://user-images.githubusercontent.com/13061803/125533731-cf831394-75cf-4b2f-b0c6-d4ae9da7b9c7.png)

### Problem location

https://docs.docker.com/compose/compose-file/compose-file-v3/#update_config

**Comment by aevesdocker** [comment]
Hi @AlexElin, thanks for creating the issue. I've checked with the engineering team and they say there is no default value as the attribute is optional

**Comment by pvormittag** [comment]
Given [the current source of the compose API ](https://github.com/docker/docker-ce/blob/44a430f4c43e61c95d4e9e9fd6a0573fa113a119/components/engine/api/types/swarm/service.go#L128-L130), it appears that setting the value to `0` is functionally equivalently to not defining the field. It would be helpful to have this noted in [the documentation](https://docs.docker.com/compose/compose-file/deploy/#update_config)  as well.

```go
// UpdateConfig represents the update configuration.
type UpdateConfig struct {
	// Maximum number of tasks to be updated in one iteration.
	// 0 means unlimited parallelism.
	Parallelism uint64
        ...
```

Aside: I would argue a better API design would be to have default values defined for all inputs, even if the default is `null` or similar. For instance, if you're templating a file, it is often much simpler and more straightforward to set the field to *some* value vs the need for conditional logic on the field being defined or not.
