### ISSUE TITLE
[Node.js docs feedback] Install dependencies inside container

### ISSUE THREAD

**Issue by TrickyC94** [docker/docs#13227]
### Problem description

In [Node.js/Develop ypur app](https://docs.docker.com/language/nodejs/develop/) (and on previous documentation pages) dependecies are installed from the host machine running `npm install ronin-database`. I think that if I'm going to use docker for development I shouldn't have npm installed on my machine.

Let's suppose the example project is stored on git and the node_modules folder is listed on .gitignore file (as usually is), if I clone that repo and run `docker-compose -f docker-compose.dev.yml up --build` I get the following error:

![error](https://user-images.githubusercontent.com/34438876/126874707-a05171e1-d0bc-47d4-9694-6b424b87d616.png)

When the image is built `package.json` is copied inside the image and after that `npm install` is runned which create and populate the node_modules folder inside the image.
Finally, when the container is created a volume is mounted on the container that overwrite the node_modules folder.

### Problem location

- https://docs.docker.com/language/nodejs/develop/

**Comment by tymik** [comment]
@TrickyC94 it would not be an optimal use of the container for local development.
If you'd like to have the `npm install` executed upon build of the image, the `node_modules` would be incorporated into the image - should you want to change a module during the development on your machine, e.g. adding, removing or updating a module, you would have to rebuild the image and recreate the container with the new image, which could result in a long time wasted waiting for the build to finish - developers prefer to avoid that.
Of course you can do it if you are OK with the disadvantages, but it is not a good practice and should not really be suggested in the docs.

**Comment by craig-osterhout** [comment]
Closing based on the previous response and this appears stale.
