### ISSUE TITLE
services.notes Additional property environments is not allowed

### ISSUE THREAD

**Issue by ChunduriAvinash16** [docker/docs#13237]
### Problem location

- I saw a problem on the following URL: https://docs.docker.com/language/nodejs/develop/
- use compose to develop locally  section 
- getting message like
--services.notes Additional property environments is not allowed

**Comment by tymik** [comment]
@ChunduriAvinash16 could you provide more details on how did you get into that issue? Like steps to reproduce?

**Comment by usha-mandya** [comment]
Closing this issue as there's no response. Feel free to comment on the issue after I close.
