### ISSUE TITLE
Dockerfile contains mismatching .net core versions

### ISSUE THREAD

**Issue by idofl** [docker/docs#13248]
File: [samples/dotnetcore.md](https://docs.docker.com/samples/dotnetcore/)

In the Dockerfile snippet, the container image for the SDK is sdk:5.0 but the final container image is aspnet:3.1. The final container image should match the sdk version, therefore it should be aspnet:5.0

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as this content will soon be removed from the docs.
