### ISSUE TITLE
How to create a Dockerfile?

### ISSUE THREAD

**Issue by Bluejanis** [docker/docs#13285]
File: [samples/dotnetcore.md](https://docs.docker.com/samples/dotnetcore/)

Please explain Step 1:
Create a Dockerfile in your project folder. How do we create a dockerfile and what type would it be? Does the name matter?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as the content will be removed from the docs repo.
Please check out the getting started guide for more details about creating a Dockerfile.
https://docs.docker.com/get-started/02_our_app/
