### ISSUE TITLE
Incorrect: host networking driver is not supported on Docker Desktop for Windows

### ISSUE THREAD

**Issue by pelepelin** [docker/docs#13357]
File: [network/host.md](https://docs.docker.com/network/host/)

> The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.

However, on current Docker Desktop for Windows on WSL2, there is a difference between 
```
docker run -it --rm --network host alpine ip addr ls
docker run -it --rm --network bridge alpine ip addr ls
```

More, if I run something like
```
docker run --name redis -d -p 6379:6379 redis:5-alpine
```

Then I can connect to 127.0.0.1:6379 with 
```
docker run -it --rm --network host redis:5-alpine redis-cli -h 127.0.0.1
```
but can't connect without `--network` or with `--network bridge` (unless internal IP or `host.docker.internal` is provided instead).

So it's clear that `host` has some effect, even though it is different from what's expected from Windows host point of view.

**Comment by Jmorjsm** [comment]
This should also be specified on the [network/index.md](https://docs.docker.com/network/) page where it lists the network drivers.
