### ISSUE TITLE
Describe how the various options for healthchecks work

### ISSUE THREAD

**Issue by hwittenborn** [docker/docs#13361]
Im currently working with a project that's using Docker Compose for some tests, and part of that procedure involved using healthchecks so multiple containers could be started up while ensuring that everything actually came up correctly.

Part of the issues that arose were from the lack of documentation for options like `interval` and `timeout`, which I'm personally still not quite sure on how they work.

Originally I though `timeout` was the total time before the healthcheck would just fail, but setting it to something like `3s` with `30s` for the interval quickly proved that false.

I'm looking at these docs in particular: https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck

**Comment by aevesdocker** [comment]
Thanks for contributing @hwittenborn! Closing this issue as this has now been resolved
