### ISSUE TITLE
The "--env-file" option documentation should insist on quotation marks being "escaped" and sent forward

### ISSUE THREAD

**Issue by exophoric** [docker/docs#13398]
File: [engine/reference/commandline/run.md](https://docs.docker.com/engine/reference/commandline/run/)

It seems that to get the behavior most users would expect with env files, variables shouldn't use quotation marks around the value. The examples in the docs are already showing that correctly. Although it's not clear that quotes would be harmful to most use cases as the variable values in the examples are only one word.

**Comment by AnewBeging** [comment]
#13398
