### ISSUE TITLE
Windows wsl docs suggest an unstable alpine configuration

### ISSUE THREAD

**Issue by nico-abram** [docker/docs#13425]
### Problem description
[Alpine linux seems to consider alpine-pkg-glibc "unsupported" and that it "results in undefined behavior"](https://gitlab.alpinelinux.org/alpine/tsc/-/issues/17)

> There is a third-party package which installs glibc in an allegedly
compatible way with musl.  It is our opinion that while this package
can co-exist with musl, the end result of running binary blobs that
combine libraries expecting musl libc with glibc code, without a
proper emulation layer like gcompat, results in undefined behavior.
Accordingly, we are unwilling to provide support for this configuration.
This has been our historic position on the alpine-pkg-glibc project since
its inception, however, due to increased attention and attempts to use it
in production, we feel it appropriate to signal our position more
forcefully.

And the [docker windows wsl docks](https://docs.docker.com/desktop/windows/wsl/) currently recommend that package:
![imagen](https://user-images.githubusercontent.com/24706838/131152444-37378ee2-21b0-4810-ae4c-960d799014c8.png)

### Problem location

- I saw a problem on the following URL: https://docs.docker.com/desktop/windows/wsl/#install

### Suggestions for a fix

The note about musl distros suggests an Alpine configuration that is unstable and undefined behaviour. I feel like this should at the very least warn about this, and ideally there would be a workaround that does not result in a "broken system"

**Comment by aevesdocker** [comment]
Thanks for creating the issue @nico-abram. This has now been addressed in the docs in PR 20189 (linked above). I'm closing this issue now
