### ISSUE TITLE
please add Yarn for webpack

### ISSUE THREAD

**Issue by hideyasu2015** [docker/docs#13497]
File: [samples/rails.md](https://docs.docker.com/samples/rails/)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as the content has been removed from the docs repo.
If the issues still exists, please help open an issue in the Awesome Compose repo so the maintainers can address it.
https://github.com/docker/awesome-compose/tree/master/official-documentation-samples/rails
