### ISSUE TITLE
``lsb_release -cs`` command produces n/a in bullseye distro

### ISSUE THREAD

**Issue by edib** [docker/docs#13562]
File: [engine/install/debian.md](https://docs.docker.com/engine/install/debian/)
When I use add repo command, ``lsb_release -cs`` command produces n/a in bullseye distro

**Comment by thaJeztah** [comment]
Was this a fresh install of Debian Bullseye, or could it have been a system that was previously running a pre-release (or Debian "sid")? I tried reproducing this, but wasn't able to, but have seen `n/a` in some cases where a distro was upgraded and the `/etc/os-release` file was not updated accordingly.

**Comment by usha-mandya** [comment]
Closing this issue as there's no response. Feel free to comment on the issue after I close.
