### ISSUE TITLE
[Python docs feedback]

### ISSUE THREAD

**Issue by 1561316811** [docker/docs#13576]
### Problem description
When i run "docker build --tag python-docker .", i meet : 
ERROR: Could not find a version that satisfies the requirement apturl==0.5.2 (from versions: none)
ERROR: No matching distribution found for apturl==0.5.2

full log:
docker build --tag python-docker .Sending build context to Docker daemon  8.704kB
Step 1/6 : FROM python:3.8-slim-buster
 ---> 954fa26c6b44
Step 2/6 : WORKDIR /app
 ---> Using cache
 ---> 1d88f963f2fd
Step 3/6 : COPY requirements.txt requirements.txt
 ---> Using cache
 ---> 56e48df16b5c
Step 4/6 : RUN pip3 install -r requirements.txt
 ---> Running in 7b1186dc0ed9
ERROR: Could not find a version that satisfies the requirement apturl==0.5.2 (from versions: none)
ERROR: No matching distribution found for apturl==0.5.2
The command '/bin/sh -c pip3 install -r requirements.txt' returned a non-zero code: 1
### Problem location

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

**Comment by craig-osterhout** [comment]
HI @1561316811, it looks like the command to create the requirements.txt file changed shortly after you created this issue.
Does the issue still occur if you create the requirements.txt file using the new command ` pip3 freeze | grep Flask >> requirements.txt`?
https://docs.docker.com/language/python/build-images/#sample-application
