### ISSUE TITLE
WORKDIR creates folder as root

### ISSUE THREAD

**Issue by wotsyula** [docker/docs#13574]
File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/)

`WORKDIR` command automatically creates folders as `root` even if a user is selected using `USER username`. This behaviour is unexpected and should be documented.

```
FROM    ubuntu
RUN     adduser foo
USER    foo
WORKDIR /tmp/foo
```

Creates `/tmp/foo` owned by root

**Comment by wotsyula** [comment]
> @wotsyula what Operating System are you using?

This was on Mac OS - 64bit - Big Slur using whatever flavor of linux Jenkins box/container uses.

**Comment by danBamikiya** [comment]
@wotsyula I've notified the maintainer.

Just to add `COPY` also doesn't copy a file or contents of a directory with `foo` as the owner. The copied files would have their owner as root as specified in the [documentation](https://docs.docker.com/engine/reference/builder/#copy):

![image](https://user-images.githubusercontent.com/58262528/136905597-9c630cd0-9dbb-4722-8129-6458b38d22f5.png)

To copy a file or content of a directory with `foo` user as the owner:

```Dockerfile

FROM ubuntu

RUN adduser foo

USER foo

WORKDIR /tmp/foo

# make non-root user the owner of WORKDIR
RUN chown -R foo /tmp/foo

# make non-root user the owner of copied files
COPY --chown=foo ./build.sh ./tmp/foo

# make non-root user the owner of copied files in a directory
COPY --chown=foo ./content/ ./tmp/foo/content/

```

**Comment by danBamikiya** [comment]
@thaJeztah I'll work on this and link a PR 😃

**Comment by apgiorgi** [comment]
@thaJeztah Buildkit is already applying `USER` instruction to `WORKDIR` since https://github.com/moby/buildkit/pull/1002

This different behaviour between using Buildkit or not can be troublesome and still is, unfortunately, undocumented. Could a "Warning" section be added to the `USER` section of the documentation to describe this behaviour change?
