### ISSUE TITLE
Should change dockerfile 

### ISSUE THREAD

**Issue by phanhuutoan** [docker/docs#13613]
File: [samples/dotnetcore.md](https://docs.docker.com/samples/dotnetcore/)

I using .NET 5.0 and implement follow this instructions, I see the error **The framework 'Microsoft.AspNetCore.App', version '5.0.0' was not found**,
After hours researching I found the solution from here: [https://docs.microsoft.com/vi-vn/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-3.0] 
new **Dockerfile** should be: 
```
# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . .
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "ZeroXTeam.dll"]: 
```

**=> change from the runtime to aspnet**

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as this content will be removed from the docs.
Please see https://github.com/docker/awesome-compose for samples.
