### ISSUE TITLE
kubectl tries to pull image from docker hub

### ISSUE THREAD

**Issue by nelsontky** [docker/docs#13620]
File: [get-started/kube-deploy.md](https://docs.docker.com/get-started/kube-deploy/)

Running `kubectl apply -f bb.yaml` on docker desktop windows (WSL2) gives the following error:
![image](https://user-images.githubusercontent.com/7272103/135286134-b7fc1166-6476-42ea-ab09-5f7c52394817.png)

This is the result of `kubectl` trying to pull the image from docker hub. A quick fix would be to add `imagePullPolicy: Never`  to the `bb.yaml` file.

**Comment by craig-osterhout** [comment]
Fixed by https://github.com/docker/docs/pull/15360
