### ISSUE TITLE
You cannot use environment variables from .env file in the environment: section

### ISSUE THREAD

**Issue by SvendK** [docker/docs#13667]
File: [compose/environment-variables.md](https://docs.docker.com/compose/environment-variables/)

It might just be a stupid setup, but nevertheless: I was writing my docker-compose.yml file for a MS Web API Core docker container with database, and I wanted to save environment variables for the SSL certificate password. I was creating the compose file as follows, and then, to not have the password in the compose file, I was setting an environment variable in the environment section. It wasn't working. I was reading this page, but couldn't figure out what was going on. Until the thought hit me - everywhere in the compose file you can use environment variables from the .env file, but not in the environment: section itself.

Solution is (of cause) to move the whole line including the password to the .env file and then remove the whole line from the compose file. 

Just thought this could be mentioned somewhere here: "You cannot use env variables from an .env file inside the compose file 'environment:' section."

```
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
```

**Comment by MarkusGnigler** [comment]
Hi @SvendK,

could be possible that you're using a wrong environment declare "fromat" in this scenario.

I use this configuration system all the time. My main purpose in doing so is a cleaner searchability especially for docker newbies.

I use always docker-compose version 3 `version: '3'`

Example .env:

```yaml
DATABASE_DB=<YOUR_DB>
DATABASE_USER=<YOUR_USER>
DATABASE_PASSWORD=<YOUR_PASSWORD>
```

Example environment section:

> Special focus on the 'VARIABLE:VALUE' formatting

```yaml
version: '3'

services:

  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
```

Please correct me if i am wrong.

Regards
Markus

**Comment by SvendK** [comment]
Hi Marcus. Thank you for seeing this old issue. It could very well be my syntax :-) I will check up on this as soon as possible and get back here.
