### ISSUE TITLE
The project does not run as it is

### ISSUE THREAD

**Issue by GabrieleLabanca** [docker/docs#13735]
File: [samples/rails.md](https://docs.docker.com/samples/rails/)

I am using LinuxMint 20.2.
In order to make it work (I use Rails 6.1, but I had errors already with the versions in the example), I had to do the following changes in the Dockerfile:
- from ruby 3.0; 
- install npm and `npm install --global yarn`.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as the content has been removed from the docs repo.
If the issues still exists, please help open an issue in the Awesome Compose repo so the maintainers can address it.
https://github.com/docker/awesome-compose/tree/master/official-documentation-samples/rails
