### ISSUE TITLE
Looking for a way to restart a service and apply docker-compose changes

### ISSUE THREAD

**Issue by clouedoc** [docker/docs#13827]
File: [compose/reference/restart.md](https://docs.docker.com/compose/reference/restart/)

**Comment by thaJeztah** [comment]
the `restart` subcommand only restarts the services (stops the containers, and starts them again).

If you made changes to your `docker-compose.yml` file, and want to apply those changes, you can run the `docker-compose up` command again (https://docs.docker.com/compose/reference/up/), which compares the existing containers with the compose-file, and where needed creates updated containers with those changes.

**Comment by clouedoc** [comment]
Thanks for the information. 

Maybe there should be a section on this documentation page that informs visitor that they need to use `docker-compose up` if they want to apply changes to `docker-compose.yml` ?

I'm willing to open a PR for that.

**Comment by thaJeztah** [comment]
I think it's mentioned in the compose getting-started; https://docs.docker.com/compose/gettingstarted/, but let me know if there's something missing in there that would make it clearer

**Comment by clouedoc** [comment]
While they have gone through the README.md, my idea is that many visitors will try to run `docker-compose restart` to apply their `docker-compose.yml` changes.

Adding a warning in the dedicated documentation page will save time for many people instead of requiring them to do some more googling.

![image](https://user-images.githubusercontent.com/13921610/141813530-42b3beb4-b7b5-4de9-bcd1-acb905ab8a55.png)
![image](https://user-images.githubusercontent.com/13921610/141813605-5cdf0e29-c6d0-4305-acae-b8f47b7ba202.png)
