### ISSUE TITLE
platform isn't documented in the compose reference docs

### ISSUE THREAD

**Issue by jrobison-sb** [docker/docs#13865]
File: [compose/compose-file/compose-file-v3.md](https://docs.docker.com/compose/compose-file/compose-file-v3/)

`platform` is one of the available keys for a service: https://github.com/compose-spec/compose-spec/blob/master/spec.md#platform

But it isn't documented anywhere in the doc: https://docs.docker.com/compose/compose-file/compose-file-v3/

**Comment by aevesdocker** [comment]
Thanks for the issue @jrobison-sb `platform` is a new attribute that was introduced in the Compose Spec. The Compose Spec is the latest file format for Compose. Compose-file-v3.md is legacy content.
