### ISSUE TITLE
Outdated docker scan authentication?

### ISSUE THREAD

**Issue by Ayy753** [docker/docs#13877]
File: [get-started/09_image_best.md](https://docs.docker.com/get-started/09_image_best/)

I'm new to docker but it appears the authentication information is outdated for the docker scan service. 
I had to run `docker scan --login` rather than `docker login`
https://forums.docker.com/t/unable-to-docker-scan-failed-to-get-dockerscanid/117745

**Comment by danBamikiya** [comment]
@thaJeztah could this be a version issue? Docker version 20.10.7 says the following when `docker scan --help` is run:

![image](https://user-images.githubusercontent.com/58262528/145040523-a1be1d2d-30b3-45df-9ded-0be10c812c93.png)

but its also possible to authenticate(login) with `docker login`.

**Comment by thaJeztah** [comment]
Let me ask @silvin-lubecki and @glours - they're more familiar with the `docker scan` feature

**Comment by glours** [comment]
@Ayy753 @danBamikiya [this issue was fixed](https://github.com/docker/scan-cli-plugin/issues/176), I'll do a new release right now

**Comment by thaJeztah** [comment]
@glours thanks! After that, can you open a PR in https://github.com/docker/docker-ce-packaging to update the version for our Linux packages as well?

**Comment by danBamikiya** [comment]
> @Ayy753 @danBamikiya [this issue was fixed](https://github.com/docker/scan-cli-plugin/issues/176), I'll do a new release right now

Great

**Comment by glours** [comment]
@thaJeztah yes sure and also one for Docker Desktop, can I add you as reviewer?

**Comment by thaJeztah** [comment]
Of course!

**Comment by glours** [comment]
@Ayy753 @danBamikiya [release done](https://github.com/docker/scan-cli-plugin/releases/tag/v0.10.0), you can download your platform binary and copy it to `~/.docker/cli-plugins` to be unblocked until we prepare all the others packaging

**Comment by danBamikiya** [comment]
> @Ayy753 @danBamikiya [release done](https://github.com/docker/scan-cli-plugin/releases/tag/v0.10.0), you can download your platform binary and copy it to `~/.docker/cli-plugins` to be unblocked until we prepare all the others packaging

Great!

**Comment by craig-osterhout** [comment]
This appears to be fixed, at least in the docs. Any concerns with closing it?
