### ISSUE TITLE
It's the opposite. -v doesn't create a mount point and --mount creates.

### ISSUE THREAD

**Issue by dmitrygrey** [docker/docs#13873]
File: [storage/bind-mounts.md](https://docs.docker.com/storage/bind-mounts/)

Just tested on Docker version 19.03.2, build 6a30dfca03

**Comment by thaJeztah** [comment]
Can you provide more details? It looks to work as expected for me;

```bash
docker run --rm --mount type=bind,src=$(pwd)/no-such-dir,dst=/container-path/ alpine
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /Users/sebastiaan/Projects/runc/no-such-dir.
See 'docker run --help'.

ls -la | grep no-such-dir
# (no output)
```

With `-v`;

```bash
docker run --rm -v $(pwd)/no-such-dir:/container-path/ alpine


ls -la | grep no-such-dir
drwxr-xr-x   2 sebastiaan  staff        64 Dec  2 16:01 no-such-dir
```

**Comment by n3tr4k** [comment]
Not for me
I'm building project on debian 5.15 and docker container is Ubuntu16.  I have had to map some folders from debian to docker container. But passing -v didn't work. Although it was working before fine but stopped after some updates of docker and debian (months passed as I wasn't using that script for a while)  I had to modify script to --mount and it's fine now. The problem that in documentation it says the other way around. That --mount doesn't create mount point (shared folder) but it does. And -v does not.

Docker version 19.03.2, build 6a30dfca03
```shell
docker run --rm -it \
   --mount type=bind,source=$PROJDIR,target=/home/$USER/app,bind-propagation=shared \
   --mount type=bind,source=/opt/shure,target=/opt/shure,readonly,bind-propagation=shared \
   --mount type=bind,source=/home/$USER/.subversion/,target=/home/$USER/.subversion,bind-propagation=shared \
   --workdir /home/$USER/app \
   --user $USER:$USER \
   ubuntu/unit-test:latest \
   /bin/bash -c "ls -a /home/$USER/app; source setup-environment && make -j4 unit"
```

**Comment by thaJeztah** [comment]
`--mount` should not create the host path (but there may have been some bugs where it did); Docker 19.03 is quite an old version of Docker Engine (and `.2` is an early patch release of that version; latest patch release for v19.03 is v19.03.15); do you have a test environment to test on, and are you still able to reproduce the problem on a currently maintained version of Docker (20.10)? If you cannot (yet) upgrade to 20.10, does it still reproduce on the latest 19.03 patch release?

**Comment by usha-mandya** [comment]
Closing this issue as there's no response. Feel free to comment on the issue after I close.
