### ISSUE TITLE
Language specific guide for java - Error on Windows 10 - /bin/sh: ./mvnw: not found

### ISSUE THREAD

**Issue by larsmogren** [docker/docs#13930]
### Problem description
I was trying to follow the Lanugage specific guide for java at https://docs.docker.com/language/java/build-images/
When running "docker build --tag java-docker" on  Windows 10 I got /bin/sh: ./mvnw: not found.

### Problem location

- I saw a problem at the following URL: <Add URL>
 https://docs.docker.com/language/java/build-images/
- I couldn't find the information I wanted. I expected to find it near the following URL <Add the URL and briefly describe how we can improve the existing content>

- Other: <Add details that can help us understand the issue>

### Suggestions for a fix

To fix the issue one has to replace all \r\n with \n in the mvnw file of the sample project Spring Pet Clinic

**Comment by AlbertoLucchesi97** [comment]
> For any n00bs like me who just spent ages looking through the mvnw file trying to figure out where these \r\n were, this is a Windows/Unix line endings thing so 'r' as in 'return' and 'n' as in new line, aka Carriage Return and Line Feed, CR LF - Windows uses CRLF for line endings wheras Unix/Linux only uses LF. In VS Code the fix is as simple as opening the file and pressing a little toggle in the bottom right corner, then saving the file. I'm probably the only person dumb enough not to realise that, but I figured I'd put this here just in case.
> 
> ![image](https://user-images.githubusercontent.com/91951058/177309127-f33732d1-6d3b-4590-b0be-39f7e7c5c762.png)

THANK YOU!
