### ISSUE TITLE
net 2.1 image moved

### ISSUE THREAD

**Issue by yuvallb** [docker/docs#13936]
File: [samples/aspnet-mssql-compose.md](https://docs.docker.com/samples/aspnet-mssql-compose/)

microsoft/dotnet:2.1-sdk is now located in mcr.microsoft.com/dotnet/sdk:2.1

see https://devblogs.microsoft.com/dotnet/net-core-2-1-container-images-will-be-deleted-from-docker-hub/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as this content will soon be removed from the docs.
Please see https://github.com/docker/awesome-compose for samples.
