### ISSUE TITLE
CLI install of Rosetta is not supported on Monterey

### ISSUE THREAD

**Issue by mmllc-jsilverman** [docker/docs#13940]
File: [desktop/mac/apple-silicon.md](https://docs.docker.com/desktop/mac/apple-silicon/)

On Monterey, on an M1 Max Macbook Pro, I get this error message:

```
$  softwareupdate --install-rosetta
Installing Rosetta 2 on this system is not supported.
```

I don't have another Macbook so I don't know if this is a problem with Monterey, the M1 Max, or something else.

**Comment by stevemoser** [comment]
@mmllc-jsilverman You will see this message on an Apple Silicon Mac if you run the install rosetta command in a CLI/Terminal that has 'Open using Rosetta' checked.

**Comment by J3Patel** [comment]
@stevemoser Thanks, I got that issue fixed by unchecking that!

**Comment by alex427** [comment]
@stevemoser thanks,  I have successfully installed after unchecking.
