### ISSUE TITLE
history object of image is not consistent between the configuration.json(<image-id>.json) found in docker save tar file and docker history command

### ISSUE THREAD

**Issue by VivekGadhia** [docker/docs#13950]
### Problem description
I build the image with steps provided at: https://docs.docker.com/language/golang/build-images/

With this image I observed that total number of non empty layers provided in history object of image configuration.json (<image id>.json) which comes in docker save tar file and non empty layers provided by docker history command are not equal.

If we do docker history command for this image, we can see there are total 9 non empty layers but still in docker inspect we get total 11 content hashes. In docker history command we are checking size of each layer to identify whether layer is empty or not. While for the same image if we do docker save and open its image-id.json(configuration) file then we can see there are total 11 non empty layers.

Instructions in Dockerfile like setting Environment variables , specifying command in CMD creating empty layers in image.

Snippet for docker history for this image:
{"Comment":"","CreatedAt":"2021-11-18T00:28:54+05:30","CreatedBy":"/bin/sh -c #(nop)  CMD [\"/docker-gs-ping\"]","CreatedSince":"3 weeks ago","ID":"640dd4373f37","Size":"0B"}

Snippet for image-id.json(configuration) in docker save tar file:
{
			"created": "2021-11-12T17:19:45.079013213Z",
			"created_by": "/bin/sh -c #(nop)  CMD [\"/bin/sh\"]",
			"empty_layer": true
},

### Suggestions for a fix
docker history API also should have "empty_layer" to indicate layer is empty or not.

**Comment by thaJeztah** [comment]
This looks to be a request for the Docker Engine, not the documentation, so better reported in https://github.com/moby/moby

The JSON that's included in the `docker save` output is the information as is stored on-disk in the Docker Engine's local image cache; the  `empty_layer` field is used internally to decide whether or not an history step was a configuration-only step or if it produced an image layer; for `empty_layer` steps, the code can then skip calculating the layer's size; https://github.com/moby/moby/blob/1ba54a5fd0ba293db3bea46cd67604b593f2048b/daemon/images/image_history.go#L31-L50


Is there a specific reason you need the `empty_layer` field, and for which checking the layer's "size" field is not sufficient?

**Comment by usha-mandya** [comment]
Closing this issue as there's no response. Feel free to comment on the issue after I close.
