### ISSUE TITLE
No mentions to the missing flag --tlsverify

### ISSUE THREAD

**Issue by gbalduzzi** [docker/docs#14023]
File: [compose/cli-command-compatibility.md](https://docs.docker.com/compose/cli-command-compatibility/)

In docker-compose v1, you could use the --tlsverify.

After upgrading to v2, all commands run with --tlsverify fail immediately:

```
>  docker compose --tls-verify
unknown flag: --tls-verify
```

Still, the documentation compatibility page I linked does not contain any info about it

**Comment by starkgate** [comment]
Same issue here with docker-compose 2.2.1. It would be nice if the documentation explained it. https://docs.docker.com/compose/reference/

**Comment by aevesdocker** [comment]
Hi @gbalduzzi, the `--tlsverify` flag is now a[ global flag.](https://docs.docker.com/engine/reference/commandline/cli/) Running `docker --tlsverify compose <your-command>` should work
