### ISSUE TITLE
Mistake in the example 

### ISSUE THREAD

**Issue by igor376** [docker/docs#14057]
### Problem location

- I saw a problem at the following URL: (https://docs.docker.com/language/python/run-containers/#stop-start-and-name-containers)

- Other: There is an example: docker stop wonderful_kalam
and after that: docker ps --all
where we can see that docker container continues working, but it must be stopped - we stopped it one command ago.

**Comment by igor376** [comment]
I saw a problem at the following https://docs.docker.com/language/python/run-containers/#stop-start-and-name-containers
There is an example: docker stop wonderful_kalam 
and after that: docker ps --all 
where we can see that docker container continues working, but it must be stopped - we stopped it one command ago.

**Comment by amerixan** [comment]
In the `docker ps --all` command after it is stopped, the output shows that the **wonderful_kalam** container has been stopped by graying it out. I don't think this is a mistake in the documentation.

**Comment by igor376** [comment]
> 

Sorry, but after `docker stop wonderful_kalam` I see status "Up 8 seconds" as after command `docker restart wonderful_kalam`

**Comment by craig-osterhout** [comment]
Fixed by https://github.com/docker/docs/commit/3a2e9e38b632a9dfb08da80b1b07f6d01158b75b
