### ISSUE TITLE
I had to configure host.docker.internal instead of localhost in order to be able to see docker metrics.

### ISSUE THREAD

**Issue by ma250292** [docker/docs#14058]
File: [config/daemon/prometheus.md](https://docs.docker.com/config/daemon/prometheus/)
As Prometheus is running inside a container, I do not understand how it can access the host loopback address using "localhost".
I am using Docker for Windows.

**Comment by amerixan** [comment]
I am guessing you had to configure your Docker daemon like the following:

```json
{
  "metrics-addr" : "host.docker.internal:9323",
  "experimental" : true
}
```
> As Prometheus is running inside a container, I do not understand how it can access the host loopback address using "localhost".

That's a great question.  Maybe the documentation assumes that you have some additional configuration to point your local IP to localhost, but that's unclear.

Can someone from the Docker team clear this up for the OP, please?
