### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by kevinheins** [docker/docs#14071]
The following pages should be updated to include documentation about `depends_on` [Long syntax](https://github.com/compose-spec/compose-spec/blob/master/spec.md#long-syntax-1). Specifically the use of conditions `service_started`, `service_healthy`, and `service_completed_successfully`.

- File: [compose/compose-file/compose-file-v3.md](https://docs.docker.com/compose/compose-file/compose-file-v3/)
- File: [compose/startup-order.md](https://docs.docker.com/compose/startup-order/)

**Comment by thaJeztah** [comment]
The https://docs.docker.com/compose/compose-file/compose-file-v3/ page describes the v3 schema of the compose file. Recent versions of compose and Compose v2 switched to use the "compose spec" specification, which doesn't have a version, and unfortunately not yet has a page within the documentation itself, but can be found on GitHub; https://github.com/compose-spec/compose-spec/blob/master/spec.md

**Comment by csdaraujo** [comment]
This page is also linked on the [FAQ page](https://docs.docker.com/compose/faq/) on Compose docs. At least a warning/note should be added on the [Start Order page](https://docs.docker.com/compose/startup-order/) warning users that this is targeted only to v3 and below.
