### ISSUE TITLE
Page is outdated

### ISSUE THREAD

**Issue by mtrtm** [docker/docs#14075]
File: [engine/reference/commandline/login.md](https://docs.docker.com/engine/reference/commandline/login/)

The page mentions that windows uses "wincred" by default, but it doesn't.  It uses "desktop", whatever that is.

Docker and Kubernetes documentation assume that there is an auth in the config.json, but there isn't.  The page should be updated to have correct info, and it would be nice to add examples of how to get auth out of the credential store on linux and windows

**Comment by thaJeztah** [comment]
The CLI's default on Windows is to look for the `wincred` helper, but on Docker Desktop, the CLI configuration file will contain a setting to use the Docker Desktop credentials helper (which is responsible for integrating authentication with the docker desktop authentication); 


```json
{
  "auths" : {
    "https://index.docker.io/v1/" : {

    }
  },
  "credsStore" : "desktop"
}
```

Some information about credential helpers can be found in this github repository; https://github.com/docker/docker-credential-helpers/
