### ISSUE TITLE
Azure file share mounts cloudstor alternative?

### ISSUE THREAD

**Issue by assaf-grth** [docker/docs#14082]
### Problem description

Based on this issue #9558 removing the suggestion of using cloudstor:azure for using Azure files mount, what is the recommended practice to use to mount an Azure file share as volume to a docker container?

### Problem location

- I saw a problem at the following URL: <Add URL>

- I couldn't find the information I wanted. I expected to find it near the following URL <Add the URL and briefly describe how we can improve the existing content>

- Other: <Add details that can help us understand the issue>

**Comment by ricred** [comment]
Any news on this?

**Comment by assaf-grth** [comment]
FYI, issue is not resolved...
