### ISSUE TITLE
[Python docs feedback]

### ISSUE THREAD

**Issue by dschlimovich** [docker/docs#14136]
### Problem description

I'm currently working on the Python guide. I successfully reached the "Develop you app" step, and encountered that the command for running the MySQL image doesn't work on M1 macs.
* The command described in the documentation is:
```
docker run --rm -d -v mysql:/var/lib/mysql \
  -v mysql_config:/etc/mysql -p 3306:3306 \
  --network mysqlnet \
  --name mysqldb \
  -e MYSQL_ROOT_PASSWORD=p@ssw0rd1 \
  mysql
```

* The error:
```
Unable to find image 'mysql:latest' locally
latest: Pulling from library/mysql
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.
```

### Problem location

- Other: Guide not suitable for M1 macs even though docker now officially supports the ARM architecture

### Project version(s) affected

This problem only affects projects on M1 macs

### Suggestions for a fix

Define a different source for the mysql image that its compatible with the M1 architecture

**Comment by craig-osterhout** [comment]
Hi @dschlimovich, thanks for sharing the issue. 
It appears the default `latest` image should now use a variant that supports ARM. https://github.com/crate/official-images/commit/c5fbba9a7fa62bd2f311b0dcd07bbb795942bdf7 https://hub.docker.com/_/mysql/tags
I don't have an M1 Mac to test it out, so please let us know if it still doesn't work.
