### ISSUE TITLE
Memory limits in compose specification v3 vs. docker-compose

### ISSUE THREAD

**Issue by Fgerthoffert** [docker/docs#14185]
### Problem description

I find the `deploy.resources` documentation confusing, which seems to also generate quite a bit of inaccuracy on other sites. 

I'm specifically referring to this block:
<img width="964" alt="Screen Shot 2022-01-28 at 10 42 37 AM" src="https://user-images.githubusercontent.com/5667028/151576826-adf6c4b9-b043-4c56-9526-7a40e1eb9995.png">

It seems to imply that if you're not using docker swarm (in our situation using `docker-compose` for our CI/tests environments), you cannot set resource limits using v3 of the compose reference.

See below the `LIMIT` values, which seems to contradict the content of the block.

#### Docker-compose v2, no memory limits

```yaml
version: '2.4'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
```

```bash
#> docker-compose up -d
#> docker stats
CONTAINER ID   NAME                     CPU %     MEM USAGE / LIMIT    MEM %     NET I/O       BLOCK I/O         PIDS
065b95320d3b   memory_elasticsearch_1   1.18%     1.291GiB / 9.73GiB   13.27%    1.38kB / 0B   5.01MB / 1.53MB   54
```

#### Docker-compose v2, with memory limits

```yaml
version: '2.4'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    mem_limit: 1gb
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
```

```bash
#> docker-compose up -d
#> docker stats
CONTAINER ID   NAME                     CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O        PIDS
9619260c1211   memory_elasticsearch_1   0.96%     1019MiB / 1GiB      99.48%    1.37kB / 0B   74.2MB / 360MB   59
```
#### Docker-compose v3, without memory limits

```yaml
version: '3.9'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
```

```bash
#> docker-compose up -d
#> docker stats
CONTAINER ID   NAME                     CPU %     MEM USAGE / LIMIT   MEM %     NET I/O     BLOCK I/O     PIDS
ac085effc60d   memory_elasticsearch_1   321.34%   1.31GiB / 9.73GiB   13.46%    876B / 0B   0B / 1.28MB   54
```

#### Docker-compose v3, with memory limits

```yaml
version: '3.9'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    deploy:
      resources:
        limits:
          memory: 1.5G
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
```

```bash
#> docker-compose up -d
#> docker stats
CONTAINER ID   NAME                     CPU %     MEM USAGE / LIMIT   MEM %     NET I/O     BLOCK I/O    PIDS
5307a8b71914   memory_elasticsearch_1   193.63%   1.216GiB / 1.5GiB   81.05%    876B / 0B   0B / 377kB   33
```

### Problem location

- I saw a problem at the following URL: https://docs.docker.com/compose/compose-file/compose-file-v3/#resources

### Project version(s) affected

Using Docker Desktop 4.4.2 (73305)

```bash
% docker -v
Docker version 20.10.12, build e91ed57
% docker-compose -v
docker-compose version 1.29.2, build 5becea4c
```

### Suggestions for a fix

It would be great if the documentation could be a bit clearer in regards to what is or is not supported when using `docker-compose` (i.e. "on non swarm deployments").

Thanks a lot,

**Comment by Fgerthoffert** [comment]
Hi, any updates on this ?
Thanks

**Comment by farhadmammadli** [comment]
Docker compose has a new [Compose Specification](https://docs.docker.com/compose/compose-file/) (most current, and recommended) syntax and memory/cpu limits are described in deploy.resources.limits section. Probably they were intended for docker swarm in v3 specification, but now for both swarm/non-swarm
