### ISSUE TITLE
WSL: Documentation should include a prerequisite to install docker on WSL operating system

### ISSUE THREAD

**Issue by felipe1982** [docker/docs#14191]
File: [desktop/windows/wsl.md](https://docs.docker.com/desktop/windows/wsl/)

on my WSL opensuse machine, I had to run 
`zypper install docker`

otherwise docker commands failed.

**Comment by djs55** [comment]
Thanks for the issue, @felipe1982 . It shouldn't be necessary to run other commands inside the WSL 2 distribution. Could you check: "Whale menu -> Settings -> Resources -> WSL Integrations" to see if your distro is listed and has Docker enabled? Assuming the distro is enabled, could you run
```
ls -l /usr/bin/docker
```
to see what the symlink points to (if anything), and show me the output of `docker ps`? Finally could you also upload a [diagnostic](https://docs.docker.com/desktop/troubleshoot/overview/#diagnose) and quote the ID here?
