### ISSUE TITLE
Document how to configure CA certificate(s) for HTTP proxies

### ISSUE THREAD

**Issue by cocowalla** [docker/docs#14200]
File: [network/proxy.md](https://docs.docker.com/network/proxy/)

Most corporate HTTP proxies use a self-signed CA certificate, allowing traffic interception. However, the Docker proxy docs make no mention of certificates.

AFAIK, for such proxies to work you need to install the certificate inside each and every container, which is a huge PITA. It would be great to have officially sanctioned methods documented.

**Comment by teodorkostov-es** [comment]
You can work with a self-signed CA - just create a new image that has the custom CA in the trust store.

```Dockerfile
FROM registry:2

COPY ca.pem /usr/local/share/ca-certificates/my-ca.crt
RUN chmod 644 /usr/local/share/ca-certificates/my-ca.crt && update-ca-certificates
```

However, any ideas on how to use client certificates for the proxy authentication when the main registry is [configured with `clientcas`](https://docs.docker.com/registry/configuration/#tls)?
