### ISSUE TITLE
Documentation Outdated?: use-a-pre-existing-network section

### ISSUE THREAD

**Issue by sschneiders** [docker/docs#14210]
File: [compose/networking.md](https://docs.docker.com/compose/networking/)

The relevant part is the last section of the text section. (https://docs.docker.com/compose/networking/#use-a-pre-existing-network)

Error: 
"Additional properties are not allowed ('name' was unexpected)"

What works instead:
Replacing "default" with the name of the pre-existing network that should be used worked.

Used versions:
docker-compose: 1.18.0, build 8dd22a9
declared version in file: 'version 3.4'
docker: 20.10.12 build e91ed57

The documentation stated that it should work for version 2 or higher so I thought this information might be useful to someone.

**Comment by aevesdocker** [comment]
Thanks for taking the time to create this issue.

I note that you are using Docker Compose V1 which has reached end-of-life. Please try again with Compose V2 https://docs.docker.com/compose/compose-file/.
