### ISSUE TITLE
docker container ls should point to docker ps

### ISSUE THREAD

**Issue by alan-ls** [docker/docs#14223]
All the details about the options and the examples are under [engine/reference/commandline/ps.md](https://docs.docker.com/engine/reference/commandline/ps/). Since they are aliases there should be a link to the one with all the details.

File: [engine/reference/commandline/container_ls.md](https://docs.docker.com/engine/reference/commandline/container_ls/)

**Comment by danBamikiya** [comment]
Hi @usha-mandya could you direct me on how to fix this? 
I want to write a note that refers users where to go to for examples as found in [/commandline/ps#usage](https://docs.docker.com/engine/reference/commandline/ps/#usage):

![docker_docs_website_issue_4_fix_1](https://user-images.githubusercontent.com/58262528/152662211-f21e7198-c3ad-48cc-844a-5f4238df1b89.png)
