### ISSUE TITLE
Tutorial seems incompatible for pushing complete commits to Github/Bitbucket/etc.

### ISSUE THREAD

**Issue by mavavilj** [docker/docs#14276]
Hello,

I've used the tutorial

File: [samples/django.md](https://docs.docker.com/samples/django/)

to build a Docker + Django + PostgreSQL base installation.

But I think I've noticed that the installation is not compatible with how Github, Bitbucket, and possibly others handle files. It seems to me that files and folders get lost during a `git commit`. As an example, empty folders such as data/db/pg_notify are not added, but the program does seek for them, and therefore losing such files breaks the program.

I have not figured out how to include all the folders and files. It seems like this could be some sort of file permissions issue as well.

But in essence, following a tutorial makes a user expect that these sorts of things should be documented. Perhaps there's room for improvement here?

Something related to this that I found:

https://stackoverflow.com/a/20388370

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as this content will soon be removed from the docs.
Please see https://github.com/docker/awesome-compose for samples.
