### ISSUE TITLE
2FA recovery docs do not match reality

### ISSUE THREAD

**Issue by alxsap** [docker/docs#14303]
File: [docker-hub/2fa/recover-hub-account.md](https://docs.docker.com/docker-hub/2fa/recover-hub-account/)

There is no option "I’ve lost my authentication device" on the https://hub.docker.com/auth/mfa page in the login flow. For me there is only a link "Try another way to sign in" pointing to hub.docker.com.

Any advise how 2FA recovery with the recovery code currently works!?

**Comment by nesjett** [comment]
Same for me. Stuck without beign able to recover....

**Comment by agrandville** [comment]
same issue no ```I’ve lost my authentication device.``` link

**Comment by a-d-smith** [comment]
Did you manage to solve this? I'm in the same position
