### ISSUE TITLE
References to non-existant Bulletin Board app?

### ISSUE THREAD

**Issue by hanzarouth** [docker/docs#14333]
File: [get-started/kube-deploy.md](https://docs.docker.com/get-started/kube-deploy/)

Hi. This tutorial refers to a bulletin board app created in previous step, but the app was actually a todo list. Can you change this page to reflect that? Or am I missing something?

**Comment by craig-osterhout** [comment]
Fixed by https://github.com/docker/docs/commit/87681a7b9946f9994cf8084dfeb3c3b71b023103
