### ISSUE TITLE
Windows Server / docker compose 2

### ISSUE THREAD

**Issue by cabadam** [docker/docs#14431]
File: [compose/cli-command.md](https://docs.docker.com/compose/cli-command/)

The instructions here indicate that installation steps for Windows are not necessary because it is included in Docker Desktop, however I believe that is only true for the desktop Windows operating systems.  Steps still appear to be necessary on Windows Server.

**Comment by cabadam** [comment]
Looking at the docs, this still appears to be relevant.  In fact, the only deployment instruction mentioning Windows Server has a caveat that it is an unsupported method.

**Comment by StefanScherer** [comment]
We have updated the documentation in the meantime. It's listed in the option three -> https://docs.docker.com/compose/install/ and the sub page has steps to download Compose V2 on Windows Server -> https://docs.docker.com/compose/install/other/
