### ISSUE TITLE
Add info: --platform "linux/amd64" flag under step 2 for ARM based chips.

### ISSUE THREAD

**Issue by WillWcchan** [docker/docs#14517]
File: [get-started/06_bind_mounts.md](https://docs.docker.com/get-started/06_bind_mounts/)

```
$ docker run -dp 3000:3000 \
     -w /app -v "$(pwd):/app" \
     --platform "linux/amd64" \
     node:12-alpine \
     sh -c "yarn install && yarn run dev"
```

Similar approach to what was done in Part 7: Multi-container apps.

**Comment by thaJeztah** [comment]
Thanks for opening this ticket!

Setting `--platform=linux/amd64` is not the correct thing to do here, as it would run an amd64 (intel / x86) image on an arm64 machine, which means that Docker Desktop will use "best effort" emulation of a non-matching image.

The reason the `--platform` flag is used in part 7, is that the MySQL 5.7 image does not have an arm64 variant (https://hub.docker.com/_/mysql?tab=tags&page=1&name=5.7), so as a workaround, the `--platform` flag is used to use the intel / x86 variant. I think we should improve that part of the docs to more clearly explain why the platform flag is used.

Ideally, we should update the example to a version of the MySQL image that supports both intel and arm hardware (the MySQL 8 images (Oracle Linux variant) do support ARM, so perhaps that's an option; https://hub.docker.com/_/mysql?tab=tags&page=1&name=8.0-oracle (but we need to check if the example works with the newer version of MySQL)
