### ISSUE TITLE
Cannot run on PlayWithDocker when completing steps on M1 Mac

### ISSUE THREAD

**Issue by dmitry-kabanov** [docker/docs#14546]
File: [get-started/04_sharing_app.md](https://docs.docker.com/get-started/04_sharing_app/)

When I follow the Getting started guide on M1 Mac, it builds and pushed to Docker hub the image based on linux/arm64 architecture.

When I try to use this image on PlayWithDocker, it fails with the following warning:

```
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
```

If I try to open the port 3000 using "Open port" button, I get connection was reset.

When I do `docker ps`, I see that no image was started, although it was just a warning, not an error.

**Comment by SabreenKaur** [comment]
Is there a fix for this issue?

**Comment by pgregoretti** [comment]
I did some research and found a fix for this issue: https://medium.com/geekculture/docker-build-with-mac-m1-d668c802ab96

You need to build the image locally with the `buildx` command so it will compensate for different architectures (like the one in play-with-docker) before pushing it to the repo. I confirmed it worked on my end with the following repo/build: https://hub.docker.com/repository/docker/pgregoretti/getting-started-test
