### ISSUE TITLE
404 at command-line bash completion script

### ISSUE THREAD

**Issue by thalesbruno** [docker/docs#14617]
### Problem description

`404: Not found` at [https://raw.githubusercontent.com/docker/compose/v2.4.1/contrib/completion/bash/docker-compose](https://raw.githubusercontent.com/docker/compose/v2.4.1/contrib/completion/bash/docker-compose)

Arrived at this link via [https://docs.docker.com/compose/completion/#bash](https://docs.docker.com/compose/completion/#bash)

**Comment by nunesvictor** [comment]
Also, will this work with cli-plugins install?

**Comment by davemsh** [comment]
I'm having this issue as well, the provided Curl command results in a 404 error message being dumped into the target file, which makes the shell login mildly unhappy.

**Comment by andreasvh-conceto** [comment]
same issue. For workaround, i commited the script from my old Ubuntu 20 LTS to my public repo. It is the version from march 2022. Feel free to use until this issue is fixed:
```
sudo curl \
    -L https://raw.githubusercontent.com/andreasvh-conceto/docker-completion/main/docker-compose \
    -o /etc/bash_completion.d/docker-compose
```

**Comment by timebotdon** [comment]
> same issue. For workaround, i commited the script from my old Ubuntu 20 LTS to my public repo. It is the version from march 2022. Feel free to use until this issue is fixed:
> ```
> sudo curl \
>     -L https://raw.githubusercontent.com/andreasvh-conceto/docker-completion/main/docker-compose \
>     -o /etc/bash_completion.d/docker-compose
> ```

Thanks. You're a life saver!

**Comment by davemsh** [comment]
This is still happening. Now the URL in the cURL script at https://docs.docker.com/compose/completion/#bash is pointing to v2.6.1, but it remains a 404.

**Comment by isimmons** [comment]
And now its at v2.7.0 and still a 404

Is there another way to get to this file? How are docs being updated with new version without fixing the 404 issue?

**Comment by shakibamoshiri** [comment]
### [Command-line completion](https://docs.docker.com/compose/completion/)
```
curl \
    -L https://raw.githubusercontent.com/docker/compose/v2.7.0/contrib/completion/bash/docker-compose \
    -o /etc/bash_completion.d/docker-compose
 ```
### 404: Not Found

The previous version is gone :|

```
cat /etc/bash_completion.d/docker-compose ; echo
404: Not Found
```

**Comment by hajdukd** [comment]
Just hit the same issue. Im not sure whether downloading from non-official source is safe.

**Comment by davemsh** [comment]
/remove-lifecycle stale

The documentation appears to have been updated to not mention Bash completion anymore at all. Can anyone else verify?
