### ISSUE TITLE
How to escape spaces and quotes in command line arguments

### ISSUE THREAD

**Issue by garricklw** [docker/docs#14612]
File: [compose/environment-variables.md](https://docs.docker.com/compose/environment-variables/)

Hi, I'm having a lot of difficulties getting arguments with spaces and quotes to be accepted by docker-compose, and some documentation would be helpful. 

When using docker-compose version 1.29, I eventually got it working by putting a \ before every space and quote. Note that in my docker-compose I have `command: ${ARG1} ${ARG2}` I couldn't find anything in the docs about having to escape spaces like that.

Now, in docker-compose 2.4.1 (very difficult to upgrade to, docker-desktop re-install didn't update it) I have the same docker-compose syntax, but I'm getting "* error decoding 'Command': invalid command line string" with the same arguments, presumably due to some hidden syntax between command: and the .env file as switching out my previous arguments values with 'foo' allows it to work. Some explicit documentation would be able to help out here.

Thanks for any help.

**Comment by garricklw** [comment]
With some trial and error I found out that adding parentheses () also caused the error

**Comment by antichris** [comment]
@garricklw See the POSIX.1-2017 standard specification on [quoting]. It applies here as well.

[quoting]: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_02
    "POSIX.1-2017: Shell & Utilities § 2.2"
