### ISSUE TITLE
Change status of vfs with exfat storage type

### ISSUE THREAD

**Issue by punyidea** [docker/docs#14615]
Given a recent experience of mine with using docker and exFAT, (see [linked issue](https://github.com/moby/moby/issues/43527)), I think that the storage-driver documentation could include extra information about storage drives without supports for some basic file operations. 
For instance, a note saying that exFAT drives are not friendly with symlinks, used in many linux images, could help reduce time spent trying to get such a program working. Specifically, the note should appear in proximity to the `vfs`storage driver, which currently says it supports any filesystem.

File: [storage/storagedriver/select-storage-driver.md](https://docs.docker.com/storage/storagedriver/select-storage-driver/)

Thanks in advance!

**Comment by wahello** [comment]
I have similar problem. 
OS is macosx 12.3.1.
docker desktop is 4.8.1 (78998)
  
Docker container can not be started if -v external location in exfat disk.
