### ISSUE TITLE
Trouble adding the Docker repo to my apt on Ubuntu 20.04

### ISSUE THREAD

**Issue by kailyisme** [docker/docs#14632]
File: [engine/install/ubuntu.md](https://docs.docker.com/engine/install/ubuntu/)

Under [Install using the repository](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository), under Set up the repository, under step 3 where it asks to run
`echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null`
it does not work for me on Ubuntu LTS 20.04 giving issues that the public key you issue for this repo is not provided.
`Err:3 https://download.docker.com/linux/ubuntu focal InRelease        
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
Hit:11 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease
Reading package lists... Done
W: GPG error: https://download.docker.com/linux/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
E: The repository 'https://download.docker.com/linux/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

I would suggest that people maybe use instead add-apt-repository command like
`sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"`
though i don't know how to get the arch to be dynamic on that line

**Comment by cschaba** [comment]
@kailyisme I had similar problem on Debian 11. 

Here my issue including fix - maybe its same on ubuntu?

https://github.com/docker/docker.github.io/issues/15727

**Comment by thesutex** [comment]
@kailyisme i followed @cschaba lead in his issue (but kept references to ubuntu, not debian), to replaced the steps to

Add Docker’s official GPG key:

 sudo mkdir -p /etc/apt/keyrings
 curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o **/etc/apt/trusted.gpg.d/docker.gpg**
 
Use the following command to set up the repository:

 echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=**/etc/apt/trusted.gpg.d/docker.gpg**] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
