### ISSUE TITLE
Documentation: rhel packages no longer available

### ISSUE THREAD

**Issue by otheus** [docker/docs#14636]
The page https://docs.docker.com/engine/install/rhel/ has obsolete information (or the packages were "accidentally removed?").  It claims that RHEL systems may install the packages through a series of steps. However, the packages for RHEL/x86_64 have been removed from the download sites and mirrors. But the packages for centos are still there, and these will work fine.

```
 sudo yum install -y yum-utils
 sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/rhel/docker-ce.repo

```
should be replaced with:

 ```
sudo yum install -y yum-utils
 sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
```

along with a short explanation as to why the binary packages for RHEL are now found in centos.

**Comment by thaJeztah** [comment]
We never shipped packages for RHEL on x86, but partnered with IBM who are building RHEL packages for s390x (as there's not CentOS variants for that architecture)

There's a banner at the top of that page, explaining that only s390x packages are available, which contains a link to the CentOS page for other architectures;

![FEE89A95-F947-42B7-A9D5-19FAFF5D7A5B](https://user-images.githubusercontent.com/1804568/166155885-faa0ecec-ddf6-4345-aa2e-0c3e3a6db15e.jpeg)

**Comment by otheus** [comment]
Thanks. I suppose I quite literally overlooked the "(i)" box and requirements. I'm still scratching my head over the whole thing -- never before have I encountered a similar situation before. CentOS is a *derivative* distribution, relying on the Redhat-specific SRC.RPM files for everything. If a package fails to install on one and not the other, it's a bug. I'm not absolutely certain, but I'm fairly so that the recent changes to "Stream" will not alter this relationship somehow. I am fairly confident that it is safe  to say that if CentOS provides a package for x86_64 version X, then that package can be installed on x86_64 version X. Thus, although this note is prominent and accurate, it is bizarre in principle.  

Nonetheless, I don't want to overly complain about trivialities. If I were to recommend one simple change, it would be to relabel the page and TOC entry to "Install docker on RHEL/s390x". Fewer false hits perhaps. In the least, forces impatient people like myself to read more carefully :D

**Comment by otheus** [comment]
The situation reminds me of the jingle, "Doors marked _pull_ \ reduce the speed \ of people who push \ before they read" along with[ this classic FarSide cartoon](https://i0.wp.com/banter-latte.com/wp-content/uploads/2020/11/EWBtdddUMAApd1o.jpg?ssl=1).
