### ISSUE TITLE
Documentation is wrong for syntax of .env files

### ISSUE THREAD

**Issue by sammck** [docker/docs#14797]
File: [compose/env-file.md](https://docs.docker.com/compose/env-file/)

"There is no special handling of quotation marks. This means that they are part of the VAL."

This has not been true for some time (maybe v1.28?).  It's easy to demonstrate that single and double-quoted strings are parsed specially.  Single-quoted strings can be multiline.  Double quoted strings support a variety of escapes including "\n" and "\\".

**Comment by aevesdocker** [comment]
Thank you for reporting the issue. Closing as this has now been fixed
