### ISSUE TITLE
Functionality Described Here Is Removed in Docker Compose 3.x Specification

### ISSUE THREAD

**Issue by inelu** [docker/docs#14925]
File: [get-started/08_using_compose.md](https://docs.docker.com/get-started/08_using_compose/)

I would suggest modifying the title to reflect the fact that _depends_on_ with _command_ is no longer available in versions 3.x . The title could be something like this: Control startup and shutdown order in Compose (version 2).

At the beginning of the document I suggest introducing paragraph that informs the readers that this is not longer supported in version 3, and if they want to use this functionality in version 3 they should use healthcheck. Example:

"The instructions on this page only work in version 2 and are no longer supported in higher versions. If you already use version 3.x or above, you can control the startup of your application using the healthcheck (link to healtcheck and depends on service_healthy) option.

UPDATE: the link posted above is incorrect. The correct link is: https://docs.docker.com/compose/startup-order/

**Comment by craig-osterhout** [comment]
Hi @inelu, 
Thanks for sharing the issue. I think the file linked (https://docs.docker.com/get-started/08_using_compose/) in the issue may be incorrect. Did you mean the issue is in this topic, https://docs.docker.com/compose/startup-order/ ?

**Comment by inelu** [comment]
> Hi @inelu, Thanks for sharing the issue. I think the file linked (https://docs.docker.com/get-started/08_using_compose/) in the issue may be incorrect. Did you mean the issue is in this topic, https://docs.docker.com/compose/startup-order/ ?

Sorry, my mistake. Indeed I was referring to the topic you mentioned: https://docs.docker.com/compose/startup-order/
