### ISSUE TITLE
Screenshots present different URL than the intended one

### ISSUE THREAD

**Issue by pankajpatel** [docker/docs#14968]
File: [compose/gettingstarted.md](https://docs.docker.com/compose/gettingstarted/)

This Doc does a great job in explaining the quick start things with docker-compose.

Though, the screenshots depict `localhost:5000` in the URL bar whereas the guide asks to visit `localhost:8000`.

IMO, it will be great to have screenshots with `localhost:8000` as it will avoid any kind of visual confusion.

**Comment by aevesdocker** [comment]
Closing issue as this has now been fixed!
