### ISSUE TITLE
Docker daemon does not start on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by dgarciarubio** [docker/docs#14963]
File: [engine/install/ubuntu.md](https://docs.docker.com/engine/install/ubuntu/)

After carefully following the installation guide in the referenced document, it is not possible to start the docker daemon. The following error is thrown in the console:

```
failed to start daemon: Error initializing network controller: error obtaining controller instance: unable to add return rule in DOCKER-ISOLATION-STAGE-1 chain:  (iptables failed: iptables --wait -A DOCKER-ISOLATION-STAGE-1 -j RETURN: iptables v1.8.7 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain DOCKER-ISOLATION-STAGE-1
 (exit status 4))
```

According to [this blog entry](https://crapts.org/2022/05/15/install-docker-in-wsl2-with-ubuntu-22-04-lts/), this is due to Ubuntu 22.04 LTS using `iptables-nft` instead of `iptables-legacy` by default, which breaks how the docker daemon works apparently.

Maybe the documentation should be updated to reflect that this default behavior must be changed on Ubuntu 22.04 LTS.

**Comment by ukd1** [comment]
Also getting this. Is this likely to get fixed?

**Comment by spicysomtam** [comment]
Me too. A breaker for me. Still not working after setting iptables to legacy

**Comment by etxealaikoion** [comment]
I had the same problem. Found a solution and explained [here](https://serverfault.com/a/1111754/986190)

**Comment by spicysomtam** [comment]
My issue fixed for a while and then I had to upgrade my storage type from `aufs` to `overlay2`. That meant wiping all my images and starting again. Guess I have been using docker a long time and someone decided not to support `aufs` (on ubuntu 22.04) any more (or somehow `aufs` was no longer configured). Rather than waste time figuring out what changed I decided to keep software up to date and switch to `overlay2`. Hope this helps someone.

**Comment by alanpaulkwan** [comment]
Has anyone figured out a solution? I switched to iptables-legacy but I guess Docker employs iptables syntax which is different than what's compatible still with iptables-legacy

I'm loathe to downgreade iptables-legacy

 (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 5566 -j DNAT --to-destination 172.17.0.2:5566 ! -i docker0: iptables v1.8.7 (legacy): unknown option "--to-destination"
