### ISSUE TITLE
IPv6 routes documentation

### ISSUE THREAD

**Issue by joel0** [docker/docs#15013]
File: [config/daemon/ipv6.md](https://docs.docker.com/config/daemon/ipv6/)

I suggest that the IPv6 documentation mention that further configuration is required on the router or host system (NDP proxying or NAT66) for access to the LAN or Internet.

This issue complements #13552.  The RFC 3849 network being used needs more instruction on how to replace it.

**Comment by joel0** [comment]
/remove-lifecycle stale

As far as I'm aware, enabling IPv6 in Docker still does not provide IPv6 Internet access without further configuration.  I still think the documentation should point users somewhere if they need it, or at minimum make the limitation clear.

**Comment by joel0** [comment]
/remove-lifecycle stale

This request is still relevant.

**Comment by joel0** [comment]
I see recent changes have resolved my feedback.  Thanks @dvdksn for the IPv6 docs improvements!

**Comment by dvdksn** [comment]
Cheers @joel0 !
