### ISSUE TITLE
WP complains about an "insecure version of PHP (7.2.2)"

### ISSUE THREAD

**Issue by carlh04426** [docker/docs#15137]
File: [samples/wordpress.md](https://docs.docker.com/samples/wordpress/)

Hello Everyone! :)

Please accept my apologies if I've sent this comment to the wrong place, but the title says it all. I am not particularly concerned since I'm running the container on localhost for development work and not in production, but I remember 'way back when,' at the beginning, when such an event could well have triggered a disastrous diversion *away* from simply getting my bearings to trying to make 'repairs' which just made everything worse. (We've all been there!) Thank you! :)

Carl

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as the content has been removed from the docs repo.
