### ISSUE TITLE
Command has incomplete arguments

### ISSUE THREAD

**Issue by arunpnair** [docker/docs#15190]
File: [engine/security/trust/trust_delegation.md](https://docs.docker.com/engine/security/trust/trust_delegation/)

Under the section **Removing a Delegation**, the command provided as an example `$ docker trust signer remove registry.example.com/admin/demo` must include the signer name **ben** before the repository argument as follows:

 `$ docker trust signer remove ben registry.example.com/admin/demo`

**Comment by usha-mandya** [comment]
@arunpnair Thanks for the feedback.

@thaJeztah Could you PTAL?

**Comment by thaJeztah** [comment]
Hm, yup, nice catch; looks like that was missed in that example

**Comment by YashasviChaurasia** [comment]
@usha-mandya @thaJeztah  I would like to work on this issue.
Can I be guided on how to proceed if possible?
Thank you.

**Comment by usha-mandya** [comment]
@YashasviChaurasia Could you follow the instructions in https://docs.docker.com/contribute/contribute-guide/ to create a PR with the changes?

**Comment by Panda-Abhisek** [comment]
@usha-mandya I would like to work on this issue.
And I have read the instructions in https://docs.docker.com/contribute/contribute-guide/ to create a PR with the changes.

**Comment by Panda-Abhisek** [comment]
can you assign me to this issue?
Thank You.

**Comment by YashasviChaurasia** [comment]
> @YashasviChaurasia Could you follow the instructions in https://docs.docker.com/contribute/contribute-guide/ to create a PR with the changes?

Yeah sure.
Sorry for the delayed reply.
Would get on to it asap.

**Comment by YashasviChaurasia** [comment]
@usha-mandya I am currently working on this issue could you please assign it to me?
Thank you

**Comment by YashasviChaurasia** [comment]
@usha-mandya Thank You for your guidance, I was finally able to submit a PR for this issue.
Thank you.

**Comment by NitishKumar06** [comment]
@usha-mandya We can close this issue if PR for this issue has been merged!
