### ISSUE TITLE
No link for previous step. Local getting-started image cannot be used.

### ISSUE THREAD

**Issue by minhtaile2712** [docker/docs#15359]
File: [get-started/kube-deploy.md](https://docs.docker.com/get-started/kube-deploy/)

1. Should have added a link to "the previous step in this tutorial" that created `bulletinboard:1.0`.
People start off this page don't have a clue which tutorial it is. After many hours searching on this page, I see the **prerequisites** part mentioning *Work through containerizing an application in [Part 2]*, but again, it's hard to guest that *previous step in this tutorial* is this part.
2. Kubernetes will not use the local built `getting-started` image. It will try to pull from some where on the internet.
As a result, when checking logs of the pod created, it will say "*Error from server (BadRequest): container "bb-site" in pod "bb-demo-9d55c6bd5-lq25z" is waiting to start: trying and failing to pull image*".
The row listed after running `kubectl get deployments` will always show `bb-demo` as not ready (`READY 0/1`).

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue and a PR. Closing as appears fixed in https://github.com/docker/docs/commit/87681a7b9946f9994cf8084dfeb3c3b71b023103 and https://github.com/docker/docs/commit/4f95480ed3a0546ca1773ea55c5dbb3328433ad9
