### ISSUE TITLE
I tried the installation steps, but I get an error

### ISSUE THREAD

**Issue by ioah86** [docker/docs#15638]
File: [desktop/install/archlinux.md](https://docs.docker.com/desktop/install/archlinux/)

```
sudo pacman -U docker-desktop-4.12.0-x86_64.pkg.tar.zst 
[sudo] password for aheinle: 
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (2) pass-1.7.4-3  docker-desktop-4.12.0-85629

Total Download Size:      0.02 MiB
Total Installed Size:  1283.63 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 pass-1.7.4-3-any                                                                                                             20.1 KiB  30.5 KiB/s 00:01 [##############################################################################################] 100%
(2/2) checking keys in keyring                                                                                                                           [##############################################################################################] 100%
(1/2) checking package integrity                                                                                                                         [##############################################################################################] 100%
(1/2) loading package files                                                                                                                              [##############################################################################################] 100%
(2/2) checking for file conflicts                                                                                                                        [##############################################################################################] 100%
error: failed to commit transaction (conflicting files)
docker-desktop: /usr/lib/docker/cli-plugins/docker-compose exists in filesystem (owned by docker-compose)
Errors occurred, no packages were upgraded.
```

This is the error I am getting. I guess the issue is that I already have docker-compose installed? Is the expectation here to uninstall docker-compose and use Docker desktop's bundled compose instead? Please advise.

**Comment by NitishKumar06** [comment]
Did you perform `sudo-apt-upgrade`?

**Comment by ioah86** [comment]
This is not ubuntu, but yeah, all my packages and package lists are up to date (regular run of `pacman -Syu`)

**Comment by OneCricketeer** [comment]
The error suggests you may have already installed docker compose binary. What happens when you remove that and try again?

**Comment by YashasviChaurasia** [comment]
Seems like a trivial problem, you might be able to fix it yourself.
Here is a headstart to a similar issue to better understand the problem:https://bbs.archlinux.org/viewtopic.php?id=56373.

**Comment by YashasviChaurasia** [comment]
It is suggested you read through these before running anything on your system.
Running random commands on the arch based system might break your system.
Kindly have a look. 

You have a similar instance of the below mentioned problem:
https://wiki.archlinux.org/title/Pacman#%22Failed_to_commit_transaction_(conflicting_files)%22_error

**Comment by ioah86** [comment]
Yes, I do know this one as a pacman error; it happens sometimes with manually installed python libraries where I accidentally sudo for a pip install. But, this is an external package, not distributed via pacman. My question is: Does it need to contain the docker-compose? Wouldn't it be enough that it states it as a requirement, and not force me to overwrite my existing docker-compose with the one shipped with this installer?

**Comment by usha-mandya** [comment]
@ioah86 This looks like a support question, rather than a documentation bug. You can get community support through the following resources:

- [Docker Community Forums](https://forums.docker.com/)
- [Docker Community Slack](https://dockercommunity.slack.com/)

Closing the issue here for this reason. Feel free to comment after I close.
