### ISSUE TITLE
Example or link to docs for --env-file file format.

### ISSUE THREAD

**Issue by magler** [docker/docs#15641]
File: [engine/reference/commandline/exec.md](https://docs.docker.com/engine/reference/commandline/exec/)

The format that is to be used in the file that is specified using `--env-file` is not obvious. Could use an example or a link to docs that show what the formatting of that file should look like.

**Comment by OneCricketeer** [comment]
`. env`  or dotenv files are frequently documented elsewhere.

Format is same as shell files for variable

```
KEY1=VALUE1
KEY2=VALUE2
```
