### ISSUE TITLE
Change in the command

### ISSUE THREAD

**Issue by bwadjass** [docker/docs#15751]
File: [get-started/05_persisting_data.md](https://docs.docker.com/get-started/05_persisting_data/)

Should be: docker run -d ubuntu bash -c "shuf -i 1-10000 -n 1 -o data.txt && tail -f /dev/null" instead of 

docker run -d ubuntu bash -c "shuf -i 1-10000 -n 1 -o /data.txt && tail -f /dev/null"

Change "/data.txt" to "data.txt"

**Comment by craig-osterhout** [comment]
Hi @bwadjass, thanks for sharing the issue. Can you help provide more details about why it is an issue?

**Comment by NitishKumar06** [comment]
@craig-osterhout he has mentioned to update the command. I believe that's what the issue is.

**Comment by craig-osterhout** [comment]
Thank you. I was trying to understand why it must be updated. 
Both commands appear to work and it looks like it's just a case of relative path vs absolute. Without knowing why one is more preferred, there appears to be no reason to change.
Closing as stale. If there's still and issue, please help provide details on why it is necessary to change.
