### ISSUE TITLE
New container created when binding to new port ( Why )  ?

### ISSUE THREAD

**Issue by narendrasinghrathore** [docker/docs#15750]
File: [config/containers/container-networking.md](https://docs.docker.com/config/containers/container-networking/)

**Comment by craig-osterhout** [comment]
Hi @narendrasinghrathore, thanks for sharing the issue.
Can you provide more details about this issue?
If it's a question about a command, please help provide an example of the command you ran and the expected output.

**Comment by craig-osterhout** [comment]
Closing as stale. If the issue still persists, please provide more details.
If it's a question about why `docker run` creates a new container every time, this may help https://stackoverflow.com/questions/54394041/why-docker-run-creates-new-container-every-time

Also, please join the Docker Community Slack if you need support, https://join.slack.com/t/dockercommunity/shared_invite/zt-1hl072yfr-ADKgaYgcv3AUTzd9BWtkwA
