### ISSUE TITLE
BIOS should be updated as well otherwise, WSL 2 will try to install and potentially break computer. I have seen this once recently. Updating BIOS is manufacturer dependent but should be mentioned in this guide. 

### ISSUE THREAD

**Issue by keithwm422** [docker/docs#15768]
File: [desktop/install/windows-install.md](https://docs.docker.com/desktop/install/windows-install/)

**Comment by usha-mandya** [comment]
@djs55 Could you let us know if we need to add this in addition to the list of prereqs detailed in https://docs.docker.com/desktop/install/windows-install/#wsl-2-backend? Thanks
