### ISSUE TITLE
Executing Roslaunch commands inside a running container

### ISSUE THREAD

**Issue by tecena** [docker/docs#15773]
Hi,

I am running a container for one of the applications in  a linux machine. The next commands have to be run inside the running container ,with out entering into the container.
basically the command to be executed is **roslaunch carla_autoware_agent carla_autoware_agent.launch town:=Town04 synchronous_mode:=true** without entering into the container.

I did try to run with docker exec but thats giving the error as 
**OCI runtime exec failed: exec failed: unable to start container process: exec: "roslaunch": executable file not found in $PATH: unknown**

please help me to run the commands inside a running container in a linux machine without entering into the container.

**Comment by craig-osterhout** [comment]
Hi @tecena, thanks for sharing the issue.
For support, please try the Docker Slack at https://join.slack.com/t/dockercommunity/shared_invite/zt-1fukl8thi-Iq2rTGyJGMAkCeQKuyfWIA

The following stackoverflow may help.
https://stackoverflow.com/questions/48001082/oci-runtime-exec-failed-exec-failed-executable-file-not-found-in-path
