### ISSUE TITLE
change from apt-get  to apt

### ISSUE THREAD

**Issue by jeas560** [docker/docs#15806]
File: [desktop/install/ubuntu.md](https://docs.docker.com/desktop/install/ubuntu/)
change:
sudo apt-get install ./docker-desktop-<version>-<arch>.deb
to:
sudo apt install ./docker-desktop-<version>-<arch>.deb

**Comment by thaJeztah** [comment]
Was there a specific issue you ran into when using `apt-get`? I know there's been some prior discussion on that; in general, we converge on using `apt-get` as (unlike `apt`), it has a stable API, and therefore is also suitable for users who want to script these commands. Also see https://github.com/docker/docs/pull/8135, and some issues/prs linking to that

**Comment by usha-mandya** [comment]
Closing this issue as there's no response. Feel free to comment on the issue after I close.
