### ISSUE TITLE
RHEL 8 x86_64 Repo Does Not Work

### ISSUE THREAD

**Issue by flakrat** [docker/docs#15822]
File: [engine/install/rhel.md](https://docs.docker.com/engine/install/rhel/)

https://download.docker.com/linux/rhel/8/x86_64/stable/repodata/repomd.xml produces a 404 error
<img width="803" alt="image" src="https://user-images.githubusercontent.com/1587409/194390947-61eccf8e-63c0-4b59-b1e0-78a7d54f9507.png">

The workaround is to replace `rhel` with `centos` in the `/etc/yum.repos.d/docker-ce.repo` installed via `sudo yum-config-manager --add-repo  https://download.docker.com/linux/rhel/docker-ce.repo`

Does the documentation need to change on the page to use the CentOS repo file, i.e.: `sudo yum-config-manager --add-repo  https://download.docker.com/linux/centos/docker-ce.repo`

Or is this a problem with the RHEL 8 repo, which at the top level of `linux/rhel/8` only contains:

```shell
[../](https://download.docker.com/linux/rhel/)
[s390x/](https://download.docker.com/linux/rhel/8/s390x/)
[source/](https://download.docker.com/linux/rhel/8/source/)
```
<img width="383" alt="image" src="https://user-images.githubusercontent.com/1587409/194391593-ac75a87b-b0a1-4a23-850f-0dda7c6ce571.png">

**Comment by toebivankenoebi** [comment]
Issue is still present and valid as described.
