### ISSUE TITLE
404 at /desktop/extensions-sdk/design/design-overview/

### ISSUE THREAD

**Issue by dejmedus** [docker/docs#15823]
I found a broken link : https://docs.docker.com/desktop/extensions-sdk/design/design-overview/

On https://www.docker.com/blog/build-your-first-docker-extension/ 
**Styling your extension**
Check out our [design guidelines](https://docs.docker.com/desktop/extensions-sdk/design/design-overview/).

<img width="1214" alt="docker url error" src="https://user-images.githubusercontent.com/59973863/194409487-a1e5f5d6-0c84-41da-aee1-672b9418f34b.png">

I'm guessing that design guidelines is meant to point to: https://docs.docker.com/desktop/extensions-sdk/design/design-guidelines/

**Comment by PMohanJ** [comment]
@thaJeztah does this issue belong to this repository?
