### ISSUE TITLE
I found a broken link

### ISSUE THREAD

**Issue by amysy** [docker/docs#15861]
Clicking on the link brought me to the broken link page. https://docker-docs.netlify.app/engine/reference/builder/
I'm trying to reach the complete building instructions guide.

**Comment by craig-osterhout** [comment]
Hi @amysy, thanks for sharing the issue.
On what page did you find that link?

The correct link is https://docs.docker.com/engine/reference/builder/

**Comment by amysy** [comment]
Thanks Docker/Docs (Craig)
I got to the broken link from this URL
https://docker-docs.netlify.app/develop/develop-images/baseimages/#more-resources
.
I clicked on the complete guide to ... hyperlink shown below.
Hope this helps.
More resources

There are lots more resources available to help you write your Dockerfile.

   - There’s a complete guide to all the instructions
   <https://docker-docs.netlify.app/engine/reference/builder/> available
   for use in a Dockerfile in the reference section.


Best,

A.Syeda

Que Cera Cera

**Comment by usha-mandya** [comment]
@amysy Thanks for the response. The link you've shared is not official Docker docs. Could you let me know where you got get this link from? 

Meanwhile, please use the link that Craig shared earlier.

**Comment by amysy** [comment]
Thanks. Got it.
 I'm sure, was on the docker hub reading and researching.
Thanks for sharing the link.

Best,

A.Syeda

Que Cera Cera

**Comment by usha-mandya** [comment]
@amysy Thanks. We'd like to take this site down as it has outdated information. Would it be possible to share more details re. the exact location of this URL in Docker Hub.

**Comment by craig-osterhout** [comment]
Closing as stale.
I was unable to find any netlify links in the Hub code. It's not in there unless it's pulling them in from some other source.
The netlify pages are indexed by Google, so depending on the ranking, some users may arrive via that route.
