### ISSUE TITLE
Docker Community edition link is dead

### ISSUE THREAD

**Issue by ben-sizer-io** [docker/docs#15901]
File: [install/index.md](https://docs.docker.com/install/)

The Docker Community edition link is dead, and there's no easy way to find out what the licence terms for that are.

**Comment by dvdksn** [comment]
hi @ben-sizer-io, please take a look at [Docker Engine](https://docs.docker.com/engine/)! You can install Docker Engine and get access to useful Docker utilities while avoiding the license terms of Docker Desktop

**Comment by ben-sizer-io** [comment]
Apologies, I clicked a 'request docs changes' link on another site - https://docker-docs.netlify.app/install/ - and it took me here. Looks like they're both out of date AND linking to the wrong place.
