### ISSUE TITLE
COMMAND is not always optional

### ISSUE THREAD

**Issue by KUGA2** [docker/docs#15924]
The COMMAND for docker create/run (and other commands?) is specified as optional:
```
docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
docker create [OPTIONS] IMAGE [COMMAND] [ARG...]
```

However, this is not true for every image. Only for images that have a default [CMD](https://docs.docker.com/engine/reference/builder/#cmd). This should be mentioned.

File: [engine/reference/commandline/create.md](https://docs.docker.com/engine/reference/commandline/create/)

**Comment by dvdksn** [comment]
Hi Kuga, thanks for your feedback. While you're right that some Docker images may require users to specify a command, it does not make it mandatory in the general sense. Therefore the command is indeed optional, but we will take your feedback into consideration for future improvements. Thank you.
