### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by sdxdavek** [docker/docs#15920]
File: [desktop/install/ubuntu.md](https://docs.docker.com/desktop/install/ubuntu/)
The linked .deb package:
https://desktop.docker.com/linux/main/amd64/docker-desktop-4.13.0-amd64.deb?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-linux-amd64
Throws a 403 error when attempting to download.

Example error message below:
403 Forbidden
Code: AccessDenied
Message: Access Denied
RequestId: 419NFKRDH5B7VCGD
HostId: eZpwYTJyI8fkKcKmV07kIKRQOk8IlcRLrpChl8KWBqemSG4lx1keutqtxbfqZZsMWmseIrDCygI=

**Comment by usha-mandya** [comment]
@sdxdavek Thanks for reporting this issue. We are working with the team to get the Desktop Linux download URLs updated. Apologies for the inconvenience.

**Comment by usha-mandya** [comment]
This issue has been resolved.
