### ISSUE TITLE
404 at /engine/install/ubuntu/https://docs.docker.com/desktop/

### ISSUE THREAD

**Issue by heng6236** [docker/docs#15953]
I found a broken link : https://docs.docker.com/engine/install/ubuntu/https://docs.docker.com/desktop/

**Comment by dvdksn** [comment]
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by aevesdocker** [comment]
There isn't any information on the ticket for us to take action on. I'm closing the issue here for that reason. Feel free to add more information to continue the conversation.
