### ISSUE TITLE
404 at /install/linux/docker-c%09e/ubuntu

### ISSUE THREAD

**Issue by akaash98** [docker/docs#15964]
I found a broken link : https://docs.docker.com/install/linux/docker-c%09e/ubuntu

**Comment by jerae-duffin** [comment]
Hey @akaash98 thank you for reporting this issue. Can you share how you arrived to this broken link?

**Comment by aevesdocker** [comment]
There isn't any information on the ticket for us to take action on. I'm closing the issue here for that reason. Feel free to add more information to continue the conversation.
