### ISSUE TITLE
Wrong download url for docker+wasm Docker Desktop

### ISSUE THREAD

**Issue by k8scat** [docker/docs#15963]
### Problem description

All platforms download url is https://www.docker.com/download/wasm-preview/linuxamd64deb

### Problem location

- I saw a problem at the following URL: https://docs.docker.com/desktop/wasm/

### Project version(s) affected

docker+wasm Docker Desktop preview

### Suggestions for a fix

Update download url for different platforms.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. It should be fixed by https://github.com/docker/docs/pull/15966
