### ISSUE TITLE
wasm

### ISSUE THREAD

**Issue by ratulb** [docker/docs#15976]
### Problem location

I am trying to deploy a wasm container from the announcement made in https://docs.docker.com/desktop/wasm/ with the following documented command:

docker run -dp 8080:8080 \
  --name=wasm-example \
  --runtime=io.containerd.wasmedge.v1 \
  --platform=wasi/wasm32 \
  michaelirwin244/wasm-example
But I run into following error message:

**docker: Error response from daemon: Unknown runtime specified io.containerd.wasmedge.v1.**
### Project version(s) affected
**This is in ubuntu 20.04 and Docker version 20.10.20.**

**Comment by craig-osterhout** [comment]
Hi @ratulb, to verify, did you install the technical preview version of Docker from [that topic](https://docs.docker.com/desktop/wasm/)?

**Comment by ratulb** [comment]
Yes - there was a mix up. It was not the beta preview that I ended up installing.
Finally - it worked when I used the beta version. 
Docker desktop intermittently fails to come up though. 
I am closing this issue.
