### ISSUE TITLE
404 at /compose/compose-file/

### ISSUE THREAD

**Issue by Ggflyben** [docker/docs#15971]
I found a broken link : https://docs.docker.com/compose/compose-file/%20--disable-features=RendererCodeIntegrity

**Comment by craig-osterhout** [comment]
Hi @Ggflyben, thanks for sharing the issue. Where did you find this broken link?

You may be able to find the information you're looking for at [https://docs.docker.com/compose/compose-file](https://docs.docker.com/compose/compose-file/)

**Comment by thaJeztah** [comment]
Could be some Chrome extension perhaps; see https://github.com/icy37785/chrome_plus/blob/9afbf51c8c1a04b7f35c7b54487ecb33f45ec191/src/portable.h#L103

(https://github.com/icy37785/chrome_plus)

**Comment by craig-osterhout** [comment]
Closing as stale. If the issue still persists, please provide more details.
