### ISSUE TITLE
Hard to figure out the source code written in docker docs while using a browser with a dark theme

### ISSUE THREAD

**Issue by Abdullah8006** [docker/docs#15983]
### Problem description
Very hard to figure out the code written in the docker documentation when the browser is using a dark theme.

![image](https://user-images.githubusercontent.com/6733980/197940787-7451cb3f-fa4a-4dfd-a8f0-c371e8512818.png)

### Problem location
Firefox browser with any dark theme(Firefox Alpenglow)

**Comment by craig-osterhout** [comment]
Hi @Abdullah8006, thanks for sharing the issue.
it looks like the image you provided is from the [getting started tutorial](https://github.com/docker/getting-started).
Does the issue only exist in that tutorial, or does it also exist on the documentation site? For example, https://docs.docker.com/get-started/03_updating_app/

**Comment by Abdullah8006** [comment]
Hey @craig-osterhout, the documentation site looks fine(see screenshot). I believe the issue is with the getting started tutorials page only.

![image](https://user-images.githubusercontent.com/6733980/198188743-222997ce-2fe7-4690-bc70-5c172ad7d454.png)

**Comment by craig-osterhout** [comment]
Thanks, @Abdullah8006. I'll close this as a duplicate of https://github.com/docker/getting-started/issues/82
Please carry on any conversation in that issue.
