### ISSUE TITLE
404 at /samples/django/

### ISSUE THREAD

**Issue by sanek200000** [docker/docs#16008]
I found a broken link : https://docs.docker.com/samples/django/
I arrived on this page through: https://docs.docker.com/

**Comment by usha-mandya** [comment]
@sanek200000 Thanks for reporting the broken link issue. Django samples are now available in the Awesome-Compose repository - https://github.com/docker/awesome-compose/tree/master/django

Could you let us know how you arrived at the broken link?

**Comment by sanek200000** [comment]
1. https://docs.docker.com/search/?q=django
2. open first link:
https://www.google.com/url?client=internal-element-cse&cx=005610573923180467403:iwlnuvjqpv4&q=https://docs.docker.com/samples/django/&sa=U&ved=2ahUKEwib34XhzIL7AhVXEncKHTGRBtAQFnoECAMQAQ&usg=AOvVaw1bariwlW9AxOZgHP-cezV2

пт, 28 окт. 2022 г. в 12:45, Usha Mandya ***@***.***>:
