### ISSUE TITLE
Update image on Docker Compose documentation ?

### ISSUE THREAD

**Issue by EmmaLa** [docker/docs#16018]
File: [compose/gettingstarted.md](https://docs.docker.com/compose/gettingstarted/)

After editing the file inside the volume to this code : 
`return 'Hello from Docker! I have been seen {} times.\n'.format(count)`

shouldn't we see this in the web page after the update : 

Hello from Docker! I have been seen 3 times.

Instead of this : 

Hello World! I have been seen 2 times.

![webpage](https://docs.docker.com/compose/images/quick-hello-world-3.png)

**Comment by NitishKumar06** [comment]
@EmmaLa When you entered the localhost on your web browser , it showed you for the first time (1 time). In the docs, it is mentioned to refresh it again, now you'd be seeing 2 time. 

After mounting, when you again try to refresh (now the data has been stored), it is going to show you 3 times.

I hope this solves your issue. Please let me know if you've any more doubt!

**Comment by EmmaLa** [comment]
@NitishKumar06 look at the image at the step 7, i didn't tested this myself but i'd expect to see the 
"Hello from Docker! I have been seen 3 times." and not "Hello World! I have been seen 3 times." i guess the image is wrong ?

**Comment by NitishKumar06** [comment]
@EmmaLa Ahannn! Nice catch - I thought you were mentioning about increment. I'll raise the PR for this issue. Thanks for mentioning it!
