### ISSUE TITLE
404 at /samples/django/

### ISSUE THREAD

**Issue by rosdie** [docker/docs#16012]
I found a broken link : https://docs.docker.com/samples/django/
I arrived on this page through: https://docs.docker.com/

If you search "Django" you get redirected to this link: https://docs.docker.com/search/?q=django
And there you can see as the first result `Quickstart: Compose and Django | Docker Documentation`. But if you click on it, you get a 404 message: `Sorry, we can't find that page`. Until yesterday this page was working properly.

**Comment by aevesdocker** [comment]
Thanks for reporting the issue. This has now been fixed
