### ISSUE TITLE
Networks field is not seen in docker-compose.yaml

### ISSUE THREAD

**Issue by Balamurugan-G** [docker/docs#16064]
File: [get-started/08_using_compose.md](https://docs.docker.com/get-started/08_using_compose/)

In the multi-container examples, there was a network todo-app defined which seems missing in docker-compose.yaml

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Under step 2 of the [following section](https://docs.docker.com/get-started/08_using_compose/#run-the-application-stack), there's a brief explanation that Compose creates a default network, so it's not necessary to define a network in the compose file.
