### ISSUE TITLE
[Java docs feedback]

### ISSUE THREAD

**Issue by PeiHongbing1223** [docker/docs#16072]
### Problem description

- When I look at the documentation and execute the following command, I get an error:
```
# docker compose -f docker-compose.dev.yml up --build
yaml: line 14: did not find expected key
```

### Problem location

- I saw a problem at the following URL: https://docs.docker.com/language/java/develop/

**Comment by craig-osterhout** [comment]
Hi @PeiHongbing1223, thanks for sharing the issue.
It may be an indentation or syntax issue in your Compose file. Without seeing the contents of your exact Compose file, it's hard to tell.

If you're unable to find the issue, please try to seek support in the Docker community Slack.
https://join.slack.com/t/dockercommunity/shared_invite/zt-1hl072yfr-ADKgaYgcv3AUTzd9BWtkwA

**Comment by PeiHongbing1223** [comment]
The contents of the docker-compose.dev.yml file are as follows (I copied this directly from the documentation):
`version: '3.8'
services:
 petclinic:
   build:
     context: .
     target: development
   ports:
     - 8000:8000
     - 8080:8080
   environment:
     - SERVER_PORT=8080
     - MYSQL_URL=jdbc:mysql://mysqlserver/petclinic
   volumes:
     - ./:/app
    depends_on:
      - mysqlserver

 mysqlserver:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
    mysql_data:
    mysql_config:`
