### ISSUE TITLE
Containerize an application

### ISSUE THREAD

**Issue by dairta** [docker/docs#16088]
From the getting started https://docs.docker.com/get-started/02_our_app/ 

I created a new Dockerfile in the app directory and put the following in it. 

`# syntax=docker/dockerfile:1
FROM node:12-alpine
RUN apk add --no-cache python2 g++ make
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "src/index.js"]
EXPOSE 3000`

Ran the following from the app directory where the newly created Dockerfile is
docker build -t getting-started .
docker run -dp 3000:3000 getting-started

It produces an image and runs but opens a nginx landing page not the app. Tried cloning in the repo again and just copying the app directory leaving everything else out, same process same result.

**Comment by craig-osterhout** [comment]
Hi @dairta, 
If you have multiple containers running, please ensure you are accessing the correct one and that there are no port conflicts.

I would suggest stopping all containers, and then running `docker run -dp 3000:3000 getting-started` again to ensure no conflicts.
You can use Docker Dashboard to stop all the containers. Go to the Containers section, and click the stop button next to the containers.

Please join the Docker community Slack for further troubleshooting help.
https://join.slack.com/t/dockercommunity/shared_invite/zt-1hl072yfr-ADKgaYgcv3AUTzd9BWtkwA
