### ISSUE TITLE
Code in Overview should use POST

### ISSUE THREAD

**Issue by eltoroit** [docker/docs#16096]
Under the overview section, please consider changing this:

===

Let’s open a new terminal then make a GET request to the server using the curl command.

 curl --request GET \
  --url http://localhost:8000/test \
  --header 'content-type: application/json' \
  --data '{"msg": "testing"}'

===

To this:

===
Let’s open a new terminal then make a POST request to the server using the curl command.

 curl --request POST \
  --url http://localhost:8000/test \
  --header 'content-type: application/json' \
  --data '{"msg": "testing"}'

===

The reason is that you are sending data to a server, and therefore to be consistent with the exercise it should be a POST method.

File: [language/nodejs/run-containers.md](https://docs.docker.com/language/nodejs/run-containers/)

**Comment by NitishKumar06** [comment]
Kindly refer to this issue: https://github.com/docker/docs/issues/16013
