### ISSUE TITLE
Mention that `.env` file is not loaded when `--env-file` option was provided

### ISSUE THREAD

**Issue by KES777** [docker/docs#16113]
### Problem description

There is no documentation that `--env-file` disables loading `.env` file

### Problem location
https://docs.docker.com/compose/environment-variables/

### Suggestions for a fix
Document this.

**Comment by aevesdocker** [comment]
@ulyssessouza @glours does the Environment Variables Precedence page cover this scenario?
https://docs.docker.com/compose/envvars-precedence/

**Comment by aevesdocker** [comment]
Hi @KES777, thank you for reporting the issue. We have made it clearer in the documentation that passing the `--env-file` argument overrides the `.env` file.

**Comment by KES777** [comment]
@aevesdocker Cool, thank you. Is there a link to that fix? So I could view the changes.
