### ISSUE TITLE
404 at /install/docker-ce/centos/

### ISSUE THREAD

**Issue by 7upupupup** [docker/docs#16124]
I found a broken link : https://docs.docker.com/install/docker-ce/centos/

**Comment by thaJeztah** [comment]
Thanks for reporting; you're probably looking for this page; https://docs.docker.com/engine/install/centos/


Can you tell us where (on which website) you found the broken link?

**Comment by aevesdocker** [comment]
I'm closing the issue here as there isn't enough information for us to take action. Feel free to add more information on the ticket to continue the conversation.
