### ISSUE TITLE
Change download URL to latest release auto-selection

### ISSUE THREAD

**Issue by ErMaqui** [docker/docs#16136]
File: [compose/install/linux.md](https://docs.docker.com/compose/install/linux/)

On line  curl -SL https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose,

The URL can be changed to https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 to auto-download the latest option available.

**Comment by aevesdocker** [comment]
Hi, thanks for opening the issue. In the MD file we already have '{{site.compose_version}}' which pulls in the latest version so users can auto download the latest option. v2.12.2 is not manually entered
