### ISSUE TITLE
State how to remove ENTRYPOINT in docs

### ISSUE THREAD

**Issue by mdavis-xyz** [docker/docs#16142]
I have a base image with an `ENTRYPOINT` defined. I want to remove the `ENTRYPOINT`. It's not clear from the docs how to do that.

I assumed I could just write in my `Dockerfile`:

```
FROM blah
ENTRYPOINT
```

But based on  #3465 it looks like I should do:

```
FROM blah
ENTRYPOINT []
```

The docs should mention that.

I can write a PR, if people are happy for me to add that.

**Comment by NitishKumar06** [comment]
Please feel free to raise a PR for this issue.

**Comment by mdavis-xyz** [comment]
Should I also say that ENTRYPOINT with no argument gives undefined behaviour? 
(Specifically, it gives a different behaviour based on whether you're using build kit or not. Without build kit it's like `ENTRYPOINT []`. With buildkit the image will immediately exit without doing anything, ignoring all CMD arguments (in the dockerfile and docker run command).)

**Comment by NitishKumar06** [comment]
@mdavis-xyz Push the changes via PR. The maintainers will approve those changes if they add some value.

**Comment by mdavis-xyz** [comment]
I'll write a PR soon.
