### ISSUE TITLE
docker-ce-rootless-extras is missing from the uninstall instructions

### ISSUE THREAD

**Issue by linesteppr** [docker/docs#16147]
File: [engine/install/debian.md](https://docs.docker.com/engine/install/debian/)

`sudo apt-get purge docker-ce docker-ce-cli containerd.io docker-compose-plugin`

should be

`sudo apt-get purge docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-ce-rootless-extras`

might be a good idea to include an `apt-get --purge autoremove` to remove dependencies no longer needed as well.

**Comment by dvdksn** [comment]
Fixed in #16148
