### ISSUE TITLE
404 at /docker-cloud/tutorials/installing-cli/

### ISSUE THREAD

**Issue by Narmadhamohan** [docker/docs#16145]
I found a broken link : https://docs.docker.com/docker-cloud/tutorials/installing-cli/
I arrived on this page through: https://hub.docker.com/

**Comment by dvdksn** [comment]
Hi @Narmadhamohan, did you find this broken link in the description of one of the images on Hub? Do you recall which image that was?

**Comment by aevesdocker** [comment]
There isn't any information on the ticket for us to take action on. I'm closing the issue here for that reason. Feel free to add more information to continue the conversation.
