### ISSUE TITLE
Connection from outside a VM

### ISSUE THREAD

**Issue by g974h** [docker/docs#16149]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)

Since a lot of people use Linux VM to learn Docker, and that the exposed port is reserved for localhost, the tutorial should mention that a port mapping (eg -p 8123:3000) is necessary to actually connect to the container from outside the VM.

**Comment by NitishKumar06** [comment]
@g974h Checkout here: https://docs.docker.com/get-started/02_our_app/#start-an-app-container

The line says `You use the -d flag to run the new container in “detached” mode (in the background). You also use the -p flag to create a mapping between the host’s port 3000 to the container’s port 3000. Without the port mapping, you wouldn’t be able to access the application.`

**Comment by g974h** [comment]
lol I know that it's more like port 3000 is not accessible outside
localhost that I did not know. But thanks for the effort.
