### ISSUE TITLE
404 at /opensource/project/who-written-for/

### ISSUE THREAD

**Issue by umarfchy** [docker/docs#16156]
I found a broken link : https://docs.docker.com/opensource/project/who-written-for/
I arrived on this page through: https://github.com/docker/compose/blob/v2/CONTRIBUTING.md

**Comment by NitishKumar06** [comment]
Thanks for raising this. I'm working on it.

**Comment by NitishKumar06** [comment]
The following PR has been raised in this repository and not in the docker/docs because the file which was to be modified was present inside docker/compose and not docker/docs.

**Comment by umarfchy** [comment]
Hi @NitishKumar06, thanks for taking on the issue. It was generated on the fly as the docker hub website redirected me here. Though not in the same repo, I presumed that they probably wanted changes pertinent to docs 🙂
