### ISSUE TITLE
ERROR [5/5] RUN yarn install --production   

### ISSUE THREAD

**Issue by sssrgo-dev** [docker/docs#16217]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)
what prerequisites are needed?

this happens:

 => ERROR [5/5] RUN yarn install --production                                                                                                         34.0s
------                                                                                                                                                      
 > [5/5] RUN yarn install --production:                                                                                                                     
#13 0.293 yarn install v1.22.18                                                                                                                             
#13 0.365 [1/4] Resolving packages...                                                                                                                       
#13 0.611 [2/4] Fetching packages...
#13 30.67 info There appears to be trouble with your network connection. Retrying...
#13 33.81 error jest@29.3.1: The engine "node" is incompatible with this module. Expected version "^14.15.0 || ^16.10.0 || >=18.0.0". Got "12.22.12"
#13 33.82 error Found incompatible module.
#13 33.82 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install --production]: exit code: 1

nvm, npm, node, yarn ara installed

**Comment by eoin71** [comment]
I get the same error trying the getting-started tutorial.

I was able to fix and continue by changing the node version to the most up to date available.

`# syntax=docker/dockerfile:1
FROM node:19-alpine3.15
RUN apk add --no-cache python2 g++ make
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "src/index.js"]
EXPOSE 3000`

**Comment by sssrgo-dev** [comment]
Thanx!
Yeah, lately me found this solution too.
Hope, that official guide will overcome this bone. (and others)
