### ISSUE TITLE
There is no uninstall section in Arch Linux page.

### ISSUE THREAD

**Issue by SalahAdDin** [docker/docs#16229]
File: [desktop/install/archlinux.md](https://docs.docker.com/desktop/install/archlinux/)

As you can check here, it used to be a uninstall section in there:
![Uninstall me this](https://user-images.githubusercontent.com/5034215/204107879-0779ab81-b92c-467f-add7-7cb3f283475c.png)
But, now, there isn't.

Why?

**Comment by SalahAdDin** [comment]
Where was it move to?

**Comment by SalahAdDin** [comment]
Where was it moved to?

**Comment by ChrisChinchilla** [comment]
@SalahAdDin It was moved to a consolidated section here - https://docs.docker.com/desktop/uninstall/
