### ISSUE TITLE
Examples in the `docker exec` doc executes with an error

### ISSUE THREAD

**Issue by h1zardian** [docker/docs#16267]
File: [engine/reference/commandline/exec.md](https://docs.docker.com/engine/reference/commandline/exec/)

Running the 1st command in the example, `docker run --name ubuntu_bash --rm -i -t ubuntu bash` makes the container exit itself, so all subsequent commands return error.

**Comment by dvdksn** [comment]
Hi @h1zardian, the command:

```sh
docker run --name ubuntu_bash --rm -i -t ubuntu bash
```

Should not cause the container to exit. It should open an interactive session in an ubuntu:latest container.

Can you provide more information about your environment? What's your output from `docker version` and `docker info`?

**Comment by h1zardian** [comment]
I'm sorry, I got confused reported about different issue from another docker repo with different command. I'll raise a new issue with the correct details.
