### ISSUE TITLE
404 at /get-docker/%20Docket

### ISSUE THREAD

**Issue by Geetam1919** [docker/docs#16275]

**Comment by thaJeztah** [comment]
Did you find this link somewhere in our docs, or did you arrive at that location from some external website? The `%20Docket` looks like some random text at the end of the URL that shouldn't be there;

The correct URL you're looking for is https://docs.docker.com/get-docker/

**Comment by craig-osterhout** [comment]
Closing as stale. If the issue still persists, please provide more details.
