### ISSUE TITLE
404 at /engine/userguide/eng-image/baseimages/%E3%80%82

### ISSUE THREAD

**Issue by fover123** [docker/docs#16278]
I found a broken link : https://docs.docker.com/engine/userguide/eng-image/baseimages/%E3%80%82

**Comment by jerae-duffin** [comment]
Thank you @fover123 for reporting this. Can you share how you arrived to the broken link?

**Comment by craig-osterhout** [comment]
Closing as stale. If the issue still persists, please provide more details.
