### ISSUE TITLE
How to redirect from https://docs.docker.com/desktop/mac/#file-sharing

### ISSUE THREAD

**Issue by mat007** [docker/docs#16355]
File: [desktop/settings/mac.md](https://docs.docker.com/desktop/settings/mac/)

I would like to redirect https://docs.docker.com/desktop/mac/#file-sharing to https://docs.docker.com/desktop/settings/mac/#file-sharing, just that section, but not the whole page.
Is that possible? @thaJeztah you may know? See linked PR for context.

**Comment by thaJeztah** [comment]
Don't think that'll be easy (or possible), as the anchors are something that's handled by the browser, so the server won't see them.

Ideally, for any link we include in Docker Desktop itself, we would use a `/go/<something>` redirect, e.g. `docs.docker.com/go/mac-filesharing/` or `docs.docker.com/go/mac/file-sharing/`. I originally added those in https://github.com/docker/docs/pull/11460, but they're now managed in `_redirects.yml`; see https://github.com/docker/docs/blob/37270cca1938f12ade6f7c6acbd487dd60a88e9f/_redirects.yml#L106-L118


Those links can be used as "permalinks" and we can change where they redirect to (including anchors and/or UTM codes if needed) to the right location in the docs, even if content moves around.
