### ISSUE TITLE
404 at /compose/install/compose-plugin/

### ISSUE THREAD

**Issue by erisukaeri234** [docker/docs#16364]
I found a broken link : https://docs.docker.com/compose/install/compose-plugin/#installing-compose-on-linux-systems

no access, please

**Comment by aevesdocker** [comment]
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by aevesdocker** [comment]
Closing as there hasn't been any activity on this issue. Add a new comment if you wish to continue the conversation. Thanks!
