### ISSUE TITLE
404 at /go/acess-token/

### ISSUE THREAD

**Issue by DaniloMarinelli** [docker/docs#16386]
I found a broken link : https://docs.docker.com/go/acess-token/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. 
Can you share where you found the broken link?

The link you're probably looking for is
https://docs.docker.com/go/access-tokens/

**Comment by aevesdocker** [comment]
There isn't any information on the ticket for us to take action on. I'm closing the issue here for that reason. Feel free to add more information to continue the conversation.
