### ISSUE TITLE
docker run command not working

### ISSUE THREAD

**Issue by StevenJUlbrich** [docker/docs#16396]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)

docker run -dp 3000:80 getting-started

works better

**Comment by OneCricketeer** [comment]
> 3000:80

> works better

No? How so? The Dockerfile on that page says `EXPOSE 3000`, not `80`. The Nodejs server starts on port 3000

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
The getting-started repo contains 2 apps, the getting started tutorial itself and the getting started sample app.

The sample app is contained in the `app` folder. You must create a Dockerfile and run the commands from within the `app` directory.
