### ISSUE TITLE
https://download.oracle.com/otn/java/jdk/8u20-b26/jdk-8u20-linux-x64.tar.gz

### ISSUE THREAD

**Issue by Ladees** [docker/docs#16402]
I found a broken link : https://docs.docker.com//install/linux/docker-ce/ubuntu/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Can you provide more details about where you found the broken link?

It looks like there's an extra `/` before `install`.
The link should be:
https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by OneCricketeer** [comment]
Docker doesn't require Java. Plus, Java 8 is end-of-life

**Comment by craig-osterhout** [comment]
Closing as stale. If the issue still persists, please provide more details.
