### ISSUE TITLE
Can not install docker deb file with "apt-get" any more so it should be only "apt"

### ISSUE THREAD

**Issue by desouky22** [docker/docs#16414]
File: [desktop/install/ubuntu.md](https://docs.docker.com/desktop/install/ubuntu/)

**Comment by dvdksn** [comment]
hi, this should work fine with `apt-get` - what problem are you seeing exactly?

**Comment by usha-mandya** [comment]
There's isn't any information on the ticket for us to take action on. I'm closing the issue here for that reason. Feel free to add more information on the ticket to continue the conversation.
