### ISSUE TITLE
Commands to add Docker’s official GPG key do not work when copy/pasted.

### ISSUE THREAD

**Issue by zachmorr** [docker/docs#16418]
File: [engine/install/ubuntu.md](https://docs.docker.com/engine/install/ubuntu/)

When commands in step 2 of "Install using the repository" are copy/pasted the docker.gpg file isn't downloaded. This causes a GPG error on the next step.

Here is the terminal output:

```
zach@DESKTOP-B1UUGUV:~/projects/npi$ sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpgcurl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpgzach@DESKTOP-B1UUGUV:~/projects/npi$ ll
total 8
drwxr-xr-x 2 zach zach 4096 Jan  2 10:38 ./
drwxr-xr-x 4 zach zach 4096 Jan  2 10:38 ../
zach@DESKTOP-B1UUGUV:~/projects/npi$
```

Notice the lack of newline after the second command, maybe that's related to whatever is causing the issue?

I am on Windows, using WSL, and this problem occurs in powershell, cmd, and ubuntu.exe but NOT Windows Terminal.

Copy/pasting each of the two commands individually fixed the problem for me.

**Comment by OneCricketeer** [comment]
I think the problem is that piping into `sudo` doesn't work.

> this problem occurs in powershell, cmd, and ubuntu.exe but NOT Windows Terminal

Windows Terminal (powershell/cmd) don't use `sudo`...?

**Comment by zachmorr** [comment]
Sorry, I forgot to mention, I  was opening wsl through those four apps before attempting the command.

**Comment by OneCricketeer** [comment]
Did the dollar sign accidentally get copied in your command? The commands are indeed meant to be ran separately. Typed, or copied one at a time

**Comment by zachmorr** [comment]
I don't think so, I don't see an extra dollar sign in the terminal output. It seems like the second command isn't being executed

**Comment by OneCricketeer** [comment]
Something got messed up when you pasted. Notice that `curl` got put twice. 

Plus, nothing is downloaded to the current folder, so I'm not sure what `ll` is supposed to show for this issue

**Comment by zachmorr** [comment]
Nice catch, I didn't see that curl was in there twice. For some reason the second command is being pasted twice. I played around with it some more, it appears to be related to WSL specifically. Here is the output I just tested in cmd.exe


```
Microsoft Windows [Version 10.0.19045.2364]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Zach>sudo mkdir -p /etc/apt/keyringscurl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
'sudo' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Zach>wsl
zach@DESKTOP-B1UUGUV:/mnt/c/Users/Zach$ sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpgcurl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpgzach@DESKTOP-B1UUGUV:/mnt/c/Users/Zach$ ll /etc/apt/keyrings/
total 8
drwxr-xr-x 2 root root 4096 Jan  3 11:38 ./
drwxr-xr-x 8 root root 4096 Oct 25 14:36 ../
zach@DESKTOP-B1UUGUV:/mnt/c/Users/Zach$
```

The first attempt is pasted correctly and we see the expected 'sudo' is not recognized error, but once WSL is started the problem appears. I only copied the commands once, before opening cmd.exe, so the problem isn't caused by a bad copy. 

It's looking like this is a problem with WSL, not the docker docs. No idea what could be causing it though.

Also, in the op I meant to do `ll /etc/apt/keyrights/` not `ll` to show that the file wasn't there, my mistake.

**Comment by OneCricketeer** [comment]
Interesting. 

In any case, you should not be following those docs at all for WSL. You can install [Docker for Windows](https://docs.docker.com/desktop/install/windows-install/#install-docker-desktop-on-windows), then in the Settings of Docker Desktop, you can enable WSL2 integration for your Ubuntu distro, which will install the `docker` CLI within it.

**Comment by OneCricketeer** [comment]
The service should ideally be managed as a Windows process, rather than a Unix one. There shouldn't be anything to "convert" since your built/pulled images would all work the same.
