### ISSUE TITLE
Private Registry not defined in documents

### ISSUE THREAD

**Issue by dixitrathi7** [docker/docs#16489]
link=https://docs.docker.com/get-started/04_sharing_app/

**Comment by FavourDaniel** [comment]
@dixitrathi7 Are you working on this?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Connecting to a private registry is not required to complete the getting started tutorial.
If you're looking for information about pushing/pulling from a private registry, please see:
- https://docs.docker.com/engine/reference/commandline/pull/#pull-from-a-different-registry
- https://docs.docker.com/engine/reference/commandline/push/
- https://docs.docker.com/registry/
