### ISSUE TITLE
Issue when cloning to case-insensitive file system

### ISSUE THREAD

**Issue by mdavis-xyz** [docker/docs#16481]
# Steps to reproduce

On a Mac, with APFS (case-insensitive) file-system, clone the repo.

# Expected behavior

Normal clone

# Actual behavior

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'desktop/extensions-sdk/extensions/images/open-share.PNG'
  'desktop/extensions-sdk/extensions/images/open-share.png'
```

The clone is successful. So as long as I don't need those files I can do what I want. But what if I did want to touch those files?

# Problem location

  'desktop/extensions-sdk/extensions/images/open-share.PNG'
  'desktop/extensions-sdk/extensions/images/open-share.png'

# Suggestions for a fix

The two files have the same hash, and only the lower-case one is used by `../share.md`. So we should delete the uppercase one. I'll submit a PR for that.

**Comment by aevesdocker** [comment]
Closing as PR for fix is now merged
