### ISSUE TITLE
404 at /samples/wordpress/%20

### ISSUE THREAD

**Issue by asroq1** [docker/docs#16493]
I found a broken link : https://docs.docker.com/samples/wordpress/%20
I arrived on this page through: https://epicarts.tistory.com/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The correct link is https://docs.docker.com/samples/wordpress
To correct the issue, please contact the owners of the site where the link occurs (https://epicarts.tistory.com/)
