### ISSUE TITLE
404 at /desktop/install/mac-install%20/

### ISSUE THREAD

**Issue by MonyHdezS** [docker/docs#16502]
I found a broken link : https://docs.docker.com/desktop/install/mac-install%20/
I arrived on this page through: https://www.google.com/

**Comment by craig-osterhout** [comment]
@MonyHdezS, thanks for sharing the issue.
The google search result appears to have the correct link. Can you provide more details about where you found the broken link?

The correct link is:
https://docs.docker.com/desktop/install/mac-install/
