### ISSUE TITLE
Requirements not listed for Mac with Apple silicon

### ISSUE THREAD

**Issue by nicwinn** [docker/docs#16500]
File: [desktop/install/mac-install.md](https://docs.docker.com/desktop/install/mac-install/)

There are no system requirements listed when you choose the **Mac with Apple silicon** tab. Or is t suggesting the base model is more than enough?

**Comment by aevesdocker** [comment]
Hi @nicwinn, you should be able to see the following when you select the Mac with Apple silicon tab:

> Beginning with Docker Desktop 4.3.0, we have removed the hard requirement to install Rosetta 2. There are a few optional command line tools that still require Rosetta 2 when using Darwin/AMD64. See the [Known issues section](https://docs.docker.com/desktop/troubleshoot/known-issues/). However, to get the best experience, we recommend that you install Rosetta 2. To install Rosetta 2 manually from the command line, run the following command:

> `softwareupdate --install-rosetta`
>For more information, see [Docker Desktop for Apple silicon](https://docs.docker.com/desktop/install/mac-install/).

Could you try again, and confirm?

**Comment by aevesdocker** [comment]
Closing this issue as I'm assuming this is now resolved.
