### ISSUE TITLE
Malformed output

### ISSUE THREAD

**Issue by crazy-max** [docker/docs#16529]
https://docs.docker.com/build/attestations/sbom/#sbom-generator

![image](https://user-images.githubusercontent.com/1951866/212499195-f3a134ff-d0f6-4940-9e59-8a4b5faf871f.png)

Wonder if markdownlint could detect this.

cc @dvdksn

**Comment by dvdksn** [comment]
might be possible to lint for this. But also, if/when we move to Hugo, we will not need these custom tags -- external links are automatically given the appropriate HTML attrs.
