### ISSUE TITLE
Request to change the expose port content

### ISSUE THREAD

**Issue by futureautomate** [docker/docs#16526]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)

Hi the expose port code is removed from the docker file in latest commit so this common will not run the app in local host -

# run -dp 3000:3000 getting-started

we need to use 
run -dp 3000:80 getting-started (this worked for me)

as the port 8000 is already bind in the docker file (I tried its not opening if we use 3000 to map 3000)

please take a look at the topic

thank youi

![image](https://user-images.githubusercontent.com/58046454/212461931-947cc2ac-874e-4519-9ac7-5ccef5662350.png)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The Dockerfile you're referring to is for the getting started tutorial. The example app is in a subfolder (`app`) within that tutorial.


After you clone the repo, you need to change directory to the `app` subfolder. There should be no Dockerfile in that folder. 
![image](https://user-images.githubusercontent.com/103533812/213027780-98561140-3da4-491f-9446-d6bb4a4d63a6.png)

Follow the instructions to create a new Dockerfile inside `app`.
