### ISSUE TITLE
404 at /desktop/install/windows-install/to%20install%20docker

### ISSUE THREAD

**Issue by kebun4529** [docker/docs#16548]
I found a broken link : https://docs.docker.com/desktop/install/windows-install/to install Docker

**Comment by jerae-duffin** [comment]
@kebun4529 
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by craig-osterhout** [comment]
Closing as stale. If the broken link still exists, please share the requested details so that we can fix it.

The correct link should be https://docs.docker.com/desktop/install/windows-install
