### ISSUE TITLE
There is no uninstall in macOS Docker Desktop as described on uninstall page

### ISSUE THREAD

**Issue by newyork10023** [docker/docs#16540]
File: [desktop/uninstall.md](https://docs.docker.com/desktop/uninstall/)

$ /Applications/Docker.app/Contents/MacOS/uninstall
-bash: /Applications/Docker.app/Contents/MacOS/uninstall: No such file or directory

**Comment by mat007** [comment]
Hi!
You need Docker Desktop 4.16+, what version are you on?

**Comment by usha-mandya** [comment]
Closing this issue here as there's no information for us to take further action.  Feel free to add more information on the ticket to continue the conversation.
