### ISSUE TITLE
404 at /opensource/project/who-written-for/

### ISSUE THREAD

**Issue by markjpT** [docker/docs#16576]
I found a broken link : https://docs.docker.com/opensource/project/who-written-for/
I arrived on this page through: https://github.com/docker/cli/blob/e1152b2418833c2e39b7114c1ebb12d2278792a3/CONTRIBUTING.md

**Comment by craig-osterhout** [comment]
Thank you for sharing the issue. Closing as duplicate of https://github.com/docker/cli/issues/937
