### ISSUE TITLE
Github Actions Matrix Strategy Multi-Arch built on multiple runners

### ISSUE THREAD

**Issue by kaovilai** [docker/docs#16593]
### Problem description
https://docs.docker.com/build/ci/github-actions/examples/#share-built-image-between-jobs
Shows how to pass data between jobs
https://docs.docker.com/build/ci/github-actions/examples/#multi-platform-images
Shows how to built multi-platform images

There should be documentation on how to use [matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) to speed up builds by having each runner do a single arch.. followed up by a single runner that load all the built images and push a multi-arch manifest list

### Problem location

- I saw a problem at the following URL: [<Add URL>](https://docs.docker.com/build/ci/github-actions/examples/#multi-platform-images)

- I couldn't find the information I wanted. I expected to find it near the following URL <Add the URL and briefly describe how we can improve the existing content>

- Other: <Add details that can help us understand the issue>

### Suggestions for a fix

Have documentation for matrix strategy so we could utilize multiple runners to complete multi-arch builds faster.

**Comment by dvdksn** [comment]
cc @crazy-max — is this the best practice for building multi-arch with buildx gha?

**Comment by kaovilai** [comment]
I did multi-arch this way with multiple runners before. Just want some opinions from folks in here.

It definitely works and cut time in 1/4 if you have 4 arches etc.. especially since qemu isn't the fastest way to get things done.

**Comment by kaovilai** [comment]
> is this the best practice for building multi-arch with buildx gha?

This was the method to build multi-arch prior to buildx.
Build for each arch separately then combine into manifest list.

The fact that each arch is a separate command, allows for us to use more GHA compute in parallel using matrix strategy.

Buildx requires that every arch be done in one machine which for the 2 core GHA runners can be slow with qemu emulation for anything other than amd64 especially if you add many platforms.

With this method we can utilize more than 2 cores concurrently.

```mermaid
graph TD;
    Workflow---|amd64|runner1;
    Workflow---|arm64|runner2;
    Workflow---|arm32v5|runner3;
    Workflow---|arm32v6|runner4;
    Workflow---|arm32v7|runner5;
    Workflow---|arm64v8|runner6;
    Workflow---|i386|runner7;
    Workflow---|ppc64le|runner8;
    Workflow---|s390x|runner9;
    runner1-->Z[docker manifest create]
    runner2-->Z
    runner3-->Z
    runner4-->Z
    runner5-->Z
    runner6-->Z
    runner7-->Z
    runner8-->Z
    runner9-->Z
```

> Ideally a manifest list is created from images that are identical in function for different os/arch combinations. For this reason, manifest lists are often referred to as “multi-arch images”. However, a user could create a manifest list that points to two images -- one for windows on amd64, and one for darwin on amd64.

https://docs.docker.com/engine/reference/commandline/manifest/#manifest-create

**Comment by crazy-max** [comment]
@kaovilai I will look at this but it should work with `imagetools create` command. I think we can merge them together without pushing to the registry. I will look at it and keep you posted.

**Comment by kaovilai** [comment]
After each arch is built a final job can run to create the manifest list. See [Defining prerequisite jobs](https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs)

ie.
```
jobs:
  jobWithMatrixStrategyForEachArch:
  jobManifestList:
    needs: jobWithMatrixStrategyForEachArch
```

Without pushing to registry, one could use following actions to pass data between runners.
https://github.com/actions/upload-artifact
https://github.com/actions/download-artifact

Tho I have only done this in GHA by just pushing to a registry first at `tag-<arch>`

**Comment by crazy-max** [comment]
@kaovilai Yes using artifacts and a local registry is the way to go imo. See https://github.com/docker/docs/pull/17180.
