### ISSUE TITLE
What is the -h option?

### ISSUE THREAD

**Issue by bradbulger** [docker/docs#16601]
As used in this example

` docker compose run db psql -h db -U docker`

File: [engine/reference/commandline/compose_run.md](https://docs.docker.com/engine/reference/commandline/compose_run/)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
The syntax is  `docker compose run [OPTIONS] SERVICE [COMMAND] [ARGS...]`

In this case, the first `db` is the service.
`psql` is the command
`-h db -U docker` are args for the `psql` command.
For more information about psql, please see https://www.postgresql.org/docs/current/app-psql.html
