### ISSUE TITLE
404 at /reference/commandline/run/

### ISSUE THREAD

**Issue by Gabrielbielbr** [docker/docs#16633]
I found a broken link : https://docs.docker.com/reference/commandline/run/
I arrived on this page through: https://pt.stackoverflow.com/

**Comment by ggold7046** [comment]
Hello, I'm new to open source. Can anyone guide me ? @jamtur01

**Comment by thaJeztah** [comment]
This looks like a very old URL from some Years ago; and that page is now located at https://docs.docker.com/engine/reference/commandline/run/

We're looking at restructuring some of the URLs, so I'm wondering if we should add a redirect for that, or keep it as-is for now.

@Gabrielbielbr do you recall what page on https://pt.stackoverflow.com/ you found that link on? (Perhaps better to update the link on StackOverflow).

/cc @dvdksn

**Comment by dvdksn** [comment]
Seems like this page is linked from a number of places, on SO and otherwise, from posts dated 2015. I think it doesn't hurt to add a redirect just in case.

**Comment by thaJeztah** [comment]
@dvdksn Yeah; all reference pages used that scheme (also no idea why no redirects were added at the time); was mostly wondering if we'd be returning to that URL scheme, and if adding redirects now would case issues with that (or would only be temporary)
