### ISSUE TITLE
404 at /go/wls2/

### ISSUE THREAD

**Issue by Mochi74** [docker/docs#16644]
I found a broken link : https://docs.docker.com/go/wls2/

**Comment by thaJeztah** [comment]
Hm.. I think that should be https://docs.docker.com/go/wsl2/

(`wsl2` instead of `wls2`)

Did you find this link somewhere on our website, or did you type it manually (and possibly made a typo?)

**Comment by craig-osterhout** [comment]
Closing as stale. To fix the issue, please provide the requested details.
