### ISSUE TITLE
Install apparmor instead of apparmor-utils

### ISSUE THREAD

**Issue by paddy-hack** [docker/docs#16658]
File: [engine/release-notes/23.0.md](https://docs.docker.com/engine/release-notes/23.0/)

The "Known Issues" section says to install `apparmor-utils` to workaround `apparmor_parser` not being the `$PATH`.  While that works, the `apparmor_parser` is part of the `apparmor` package.

The `apparmor-utils` depends on `apparmor` so it works but installing only `apparmor` is enough.  I suggest changing the instructions to install `apparmor` instead.

BTW, if `apparmor_parser` is a hard requirement for `docker-ce`, then the `Recommends:` for `apparmor` should be bumped to a `Depends:` (but I seem to remember being able to do without `apparmor` under certain conditions, see [this comment](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=989781#10)).

**Comment by privnote42** [comment]
Hi,
is also a solution without apparmor possible?
Because not everyone wants to install apparmor

**Comment by paddy-hack** [comment]
Based on comments in the link I provided, it seems you can do so by setting a kernel parameter.  For further information, please consult your favourite search engine.

**Comment by luckycloud-GmbH** [comment]
Setting a kernel parameter is not the nicest solution either.
I would appreciate it very much if there would be a solution directly from docker

**Comment by paddy-hack** [comment]
/remove-lifecycle stale

The [Known Issues](https://docs.docker.com/engine/release-notes/23.0/#known-issues) for 23.0.0 still advise to install `apparmor-utils` so the issue is still present.  However the "Bug fixes and enhancements" sections for 23.0.1 and 23.0.2 mention `apparmor` related fixes at their very top so I am not sure if the workaround is still needed.

I'll leave the decision to update the Known Issues or not to project.

**Comment by paddy-hack** [comment]
Just checked the [Known issues](https://docs.docker.com/engine/release-notes/23.0/#known-issues) again and they now advise installation of `apparmor`.
