### ISSUE TITLE
404 at /engine/storage/volumes/

### ISSUE THREAD

**Issue by iknowkis** [docker/docs#16653]
I found a broken link : https://docs.docker.com/engine/storage/volumes/
I arrived on this page through: https://chat.openai.com/chat

You shoud have to fix it to https://docs.docker.com/storage/volumes/
![image](https://user-images.githubusercontent.com/87289383/216269573-9481bc67-b52f-478a-b2df-f2e132e811e0.png)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. 
To correct the ChatGPT answer you received and the link it contains, you'll need to contact the owners of the ChatGPT service.
