### ISSUE TITLE
Confusing docker cloud for ECS documentation

### ISSUE THREAD

**Issue by xZero707** [docker/docs#16660]
**File:** [cloud/ecs-integration.md](https://docs.docker.com/cloud/ecs-integration/)
**Docker version:** 20.10.23, build 7155243
**OS version:** Fedora Linux 37 (Workstation Edition)
**Shell:** zsh (Tested under plain bash as well)

Docker context create command as demonstrated [here](https://docs.docker.com/cloud/ecs-integration/#create-aws-context), seems to be incorrect (outdated?). 
```shell
➜  example-project git:(master) ✗ docker context create ecs myecscontext
"docker context create" requires exactly 1 argument.
See 'docker context create --help'.

Usage:  docker context create [OPTIONS] CONTEXT

Create a context
```

Solution provided in this [article](https://stackoverflow.com/a/67236402/1797452) works, but this is not clarified in the documentation.

Under [prerequisites](https://docs.docker.com/cloud/ecs-integration/#prerequisites) is mentioned that "Docker Compose CLI for Linux" might be needed. 
I personally find this very confusing. What is the difference between "Docker Compose CLI for Linux" and "Docker compose" anyway? 

See: docker/compose-cli#901
Seems like common confusion and should be stated.

**Comment by madrover** [comment]
I'm on the same boat here. Supposedly, as per https://docs.docker.com/cloud/ecs-integration/#prerequisites, this should be included with the Docker Desktop distribution but I'm on the current latest Mac version, 4.16.2 (95914), and this command does not work and I'm unable to create a new ECS context.
