### ISSUE TITLE
Is Docker not supported for OpenSUSE x86_64?

### ISSUE THREAD

**Issue by bruma1994** [docker/docs#16666]
Why is Docker not available for download for x86_64 OpenSUSE/SLES architecture? Are there any other ways to install and run without using systemctl, because I'm using WSL2, where only running via sudo service docker start is supported?

**Comment by craig-osterhout** [comment]
Thanks for reaching out. The resources below are better suited to handle this request.

To request availability for additional architectures, please use:
Docker Engine: https://github.com/moby/moby
Docker Desktop: https://github.com/docker/desktop-linux/issues

To try to get support for unsupported architectures, please try the Community Slack at: https://join.slack.com/t/dockercommunity/shared_invite/zt-1jz09gjit-P2NPysg99kiWExFfof0oBA
