### ISSUE TITLE
Getting docker buildx working on WSL 2

### ISSUE THREAD

**Issue by mronstro** [docker/docs#16714]
File: [build/install-buildx.md](https://docs.docker.com/build/install-buildx/)

In /usr/local/lib/docker/cli-plugins there was a file named buildx-v0.10.2.linux-amd64.
By creating a link file here called docker-buildx docker buildx started working.
ln -s buildx-v0.10.2.linux-amd64 docker-buildx

Before this it would not recognize docker buildx commands.

**Comment by mikicho** [comment]
@mronstro upgrade to the latest Docker Desktop and `apt update & apt upgrade` solved it for me.

```
> docker build -f docker/Dockerfile --secret id=npmrc,src=$HOME/.npmrc .

failed to fetch metadata: fork/exec /usr/local/lib/docker/cli-plugins/docker-buildx: no such file or directory

DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

unknown flag: --secret
See 'docker build --help'.
```
