### ISSUE TITLE
404 at /compose/install/compose-plugin/

### ISSUE THREAD

**Issue by MikhailRubin** [docker/docs#16716]
I found a broken link : https://docs.docker.com/compose/install/compose-plugin/#installing-compose-on-linux-systems

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Where did you find the broken link?

The information you are looking for can be found on https://docs.docker.com/compose/install/

**Comment by aevesdocker** [comment]
I'm closing the issue here as there isn't enough information for us to take action. Feel free to add more information on the ticket to continue the conversation.
