### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by dautovri** [docker/docs#16713]
Link on this [BuildKit SBOM scanner protocol](https://github.com/moby/buildkit/blob/master/docs/sbom-protocol.md) is broken

File: [build/attestations/sbom.md](https://docs.docker.com/build/attestations/sbom/)

**Comment by pmogan77** [comment]
Hello @dautovri @craig-osterhout ! It looks like the updated link is at: 
https://github.com/moby/buildkit/blob/master/docs/attestations/sbom-protocol.md

If this looks right, I can make a PR to resolve this issue!

**Comment by dautovri** [comment]
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/4597187/227177155-428254bb-2d2b-4795-b007-d6f4023a0a8b.png">
<img width="1269" alt="Screenshot 2023-03-23 at 11 34 29" src="https://user-images.githubusercontent.com/4597187/227177208-1ad3f65f-8a31-4a24-ba59-26c3bba74567.png">
