### ISSUE TITLE
Documents localization

### ISSUE THREAD

**Issue by bconfiden2** [docker/docs#16728]
Is there any plan for localization like [kubernetes](https://kubernetes.io/docs/home/) does?

**Comment by usha-mandya** [comment]
@bconfiden2 Thanks for reaching out. We don't have any localized docs yet. If there's enough interest, we can review the requirement and plan accordingly. May I know in which language you'd prefer to read the docs?

**Comment by bconfiden2** [comment]
@usha-mandya For me, I prefer Korean. Thanks for your reply! 😃
