### ISSUE TITLE
404 at /compose/compose-file/compose-file-v3/install/linux/ubuntu

### ISSUE THREAD

**Issue by ortiqjon** [docker/docs#16725]
I found a broken link : https://docs.docker.com/compose/compose-file/compose-file-v3/install/linux/ubuntu

**Comment by usha-mandya** [comment]
@ortiqjon Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by aevesdocker** [comment]
Closing the issue here as there isn't enough information for us to take action. Feel free to add more information on the ticket to continue the conversation.
