### ISSUE TITLE
Fix absolute links

### ISSUE THREAD

**Issue by crazy-max** [docker/docs#16722]
Absolute links are back on the menu :disappointed:. Didn't go through all pages but here are some of them with a quick search: https://github.com/search?q=repo%3Adocker%2Fdocs+docs.docker.com+language%3AMarkdown&type=code&ref=advsearch

**Comment by ChrisChinchilla** [comment]
@crazy-max That link returns no results for me, do you still see the same issues?

**Comment by crazy-max** [comment]
@ChrisChinchilla

That's strange I clearly have smth on my side: https://github.com/search?q=repo%3Adocker%2Fdocs+docs.docker.com+language%3AMarkdown&type=code&ref=advsearch

![image](https://user-images.githubusercontent.com/1951866/222706063-42dbc319-4fb9-44b8-87ca-15820759492d.png)

Here are some of them:
* https://github.com/docker/docs/blob/9a91ee72455557df970ffe01db84273323f603f1/build/bake/compose-file.md?plain=1#L101
* https://github.com/docker/docs/blob/9a91ee72455557df970ffe01db84273323f603f1/desktop/extensions-sdk/dev/api/reference/interfaces/Docker.md?plain=1#L88
* https://github.com/docker/docs/blob/9a91ee72455557df970ffe01db84273323f603f1/desktop/extensions-sdk/dev/api/reference/interfaces/Docker.md?plain=1#L110
* https://github.com/docker/docs/blob/9a91ee72455557df970ffe01db84273323f603f1/get-started/06_bind_mounts.md?plain=1#L212

**Comment by ChrisChinchilla** [comment]
@crazy-max Odd, no worries, I'll take a look
