### ISSUE TITLE
Change the container name from drunk_visvesvaraya to humble_visvesvaraya in docker stats page

### ISSUE THREAD

**Issue by Harshith2396** [docker/docs#16720]
File: [engine/reference/commandline/stats.md](https://docs.docker.com/engine/reference/commandline/stats/)
In the section "Running docker stats with customized format on all (Running and Stopped) containers" it is found that there is a very offensive container name "drunk_visvesvaraya".
 "Visvesvaraya" is very respected name of a personnel  in the state of Karnataka, India. To brief about his history a little, he was a Civil engineer during the British India time, who is known as Sir Visvesvaraya, was exceptionally involved in the construction of the KRS Dam which feeds drinking water to over millions of people especially the City of Bengaluru which one of the biggest IT hub in India. On behalf of the state of Karnataka people and myself, it is advisable and highly respectful if this was changed  
![image](https://user-images.githubusercontent.com/27740183/218645223-2fe4889a-f261-4c7e-8cee-60ac55fcb88f.png)
from drunk_visvesvaraya to humble_visvesvaraya

**Comment by aslamahemad** [comment]
I have made the required changes and created the PR.

[ changed the container name in docker stats page #4026 ](https://github.com/docker/cli/pull/4026)

**Comment by aslamahemad** [comment]
I have made the required changes and created the PR.

https://github.com/docker/cli/pull/4027

**Comment by usha-mandya** [comment]
@Harshith2396 Thanks for the request. As someone who's from Karnataka, I can totally understand the sentiments associated with Sir M Visvesvaraya. I'll make sure the updates get back ported to Docs :)

**Comment by usha-mandya** [comment]
Thank you @aslamahemad for the upstream PR!

**Comment by Harshith2396** [comment]
Thank you  @aslamahemad and @usha-mandya for considering the changes :)

**Comment by thaJeztah** [comment]
- docs updates from upstream will be included through https://github.com/docker/docs/pull/17115
