### ISSUE TITLE
404 at /engine/examples/running_ssh_service/

### ISSUE THREAD

**Issue by Madhuvantihunagund** [docker/docs#16748]
I found a broken link : https://docs.docker.com/engine/examples/running_ssh_service/
I arrived on this page through: https://github.com/mmumshad/ubuntu-ssh-enabled

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as a duplicate of #16675
The example was removed from the docs. You can still view an example at https://github.com/linuxserver/docker-openssh-server

To update the link on the external site, please contact the owners of that site.
