### ISSUE TITLE
The given command does not work, throws an error message

### ISSUE THREAD

**Issue by CandaceSoVan** [docker/docs#16750]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)C

command: docker build -t getting-started
error message: ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Start a build

**Comment by aslamahemad** [comment]
Hey @CandaceSoVan please add . [dot] at the end of your command. 

``` shell
docker build -t getting-started .
```
for more info : https://stackoverflow.com/questions/46517241/docker-build-requires-exactly-1-arguments

**Comment by craig-osterhout** [comment]
Thank you @aslamahemad.
Closing this issue. @CandaceSoVan, if you still experience an issue, please seek support in the Community Slack https://join.slack.com/t/dockercommunity/shared_invite/zt-1jz09gjit-P2NPysg99kiWExFfof0oBA
