### ISSUE TITLE
404 at /en/latest/use/builder/

### ISSUE THREAD

**Issue by stgmviknesh** [docker/docs#16779]
I found a broken link : https://docs.docker.com/en/latest/use/builder/#cmd
I arrived on this page through: https://developer.hashicorp.com/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
As the link is on an external site, we are unable to fix it. Please contact the owners of the external site to fix the broken link.
The link you're looking for is now at https://docs.docker.com/engine/reference/builder/#cmd
