### ISSUE TITLE
Mocha not working properly

### ISSUE THREAD

**Issue by bestras023** [docker/docs#16780]
`mocha ./**/*.js`
This is not working properly.
`Invalid parser module name: ./**/*.js`,  I get this error.
Please let me know why this happens. I think it's related to mocha package.

**Comment by craig-osterhout** [comment]
Hi @bestras023, thanks for sharing the issue.
I assume this is for the node.js language-specific guide at https://docs.docker.com/language/nodejs/run-tests/

I was unable to reproduce that error by following the current steps in the docs. 

Can you help share the exact commands you ran and the exact output?

**Comment by craig-osterhout** [comment]
Closing as stale. If an issue still exists in the docs, please let us know.
If you need help troubleshooting, please try the community Slack at https://join.slack.com/t/dockercommunity/shared_invite/zt-1jz09gjit-P2NPysg99kiWExFfof0oBA
