### ISSUE TITLE
404 at /get-started/p

### ISSUE THREAD

**Issue by shanthashantha1** [docker/docs#16798]
I found a broken link : https://docs.docker.com/get-started/p

**Comment by craig-osterhout** [comment]
Hi @shanthashantha1, thanks for sharing the issue. Where did you find this broken link?


The page you're probably looking for is https://docs.docker.com/get-started/

**Comment by aevesdocker** [comment]
There isn't any information on the ticket for us to take action on. I'm closing the issue here for that reason. Feel free to add more information to the ticket to continue the conversation.
