### ISSUE TITLE
404 at /compose/install/)

### ISSUE THREAD

**Issue by sleman11** [docker/docs#16806]
I found a broken link : https://docs.docker.com/compose/install/)

**Comment by craig-osterhout** [comment]
Hi @sleman11, thanks for sharing the issue. Where did you find this broken link?

It looks like there's an extra `)` at the end. The correct link is https://docs.docker.com/compose/install/

**Comment by aevesdocker** [comment]
There's isn't any information on the ticket for us to take action on. I'm closing the issue here for that reason. Feel free to add more information on the ticket to continue the conversation.
