### ISSUE TITLE
Clarify semantics around `extends` + `profiles`

### ISSUE THREAD

**Issue by blast-hardcheese** [docker/docs#16810]
File: [compose/extends.md](https://docs.docker.com/compose/extends/)

It seems as though it's currently not possible to remove values from extended list of active profiles, and `profiles` is not covered in either of the two **multi-value options** sections.

If I were to propose something that works around this via `profiles: [null, "a", "b", "c"]` to reset the profiles before replacing with some new profiles, or `profiles: [null]` to "reset" the profiles list an permit it to be brought up via unscoped `docker compose up`.

This is somewhat awkward, but `null` is not a valid value so backwards compatibility doesn't need to be considered:

```
$ docker compose up -d
services.pytest.profiles.0 must be a string
```

If this isn't a desired feature that's fine, but having some acknowledgement around this would be helpful in the docs.

Thank you!

**Comment by glours** [comment]
Hey @blast-hardcheese 
You can now use the `!reset` value to achieve this
```yaml
services:
 a:
   image: nginx
   profiles: !reset []
   environment:
    DEBUG: 'true'
```

basically, you can have a main compose file which define your services and you can use an `compose.override.yml` file to clean the profile section as shown above

**Comment by blast-hardcheese** [comment]
Thank you for addressing this, I'm excited to use it!

**Comment by aevesdocker** [comment]
Closing this issue as it has now been resolved!
