### ISSUE TITLE
404 at /engine/examples/dotnetcore/

### ISSUE THREAD

**Issue by Saeed-Abdalwahab** [docker/docs#16818]
I found a broken link : https://docs.docker.com/engine/examples/dotnetcore/
I arrived on this page through: https://www.youtube.com/

**Comment by usha-mandya** [comment]
Thanks for reporting the broken link issue. Here's the link to our .NET Samples page - https://docs.docker.com/samples/dotnet/
Broken links must be fixed at the source. Closing this issue here for that reason.
