### ISSUE TITLE
[Java docs feedback]

### ISSUE THREAD

**Issue by frank-wuerffel** [docker/docs#16830]
### Problem description

On Windows machines the ./mvnw command fails due to difference in windows and linux files end of line encodings.
This can be easily solved by adding two lines to the Dockerfile. 

`RUN apt-get update && apt-get install dos2unixRUN apt-get update && apt-get install dos2unix`
AND
`RUN dos2unix ./mvnw && ./mvnw dependency:resolve`

### Problem location

- I saw a problem at the following URL: https://github.com/docker/docs/blob/main/language/java/build-images.md

### Project version(s) affected
https://github.com/docker/docs/commit/9a91ee72455557df970ffe01db84273323f603f1

### Suggestions for a fix

Add a hint for Windows users that the end of line issue can cause a failure to execute the ./mvnw command and an example how to fix

`FROM eclipse-temurin:17-jdk-jammy`
`RUN apt-get update && apt-get install dos2unix`
`WORKDIR /app`
`COPY .mvn/ .mvn`
`COPY mvnw ./`
`COPY pom.xml ./`
`RUN dos2unix ./mvnw && ./mvnw dependency:resolve`
`COPY src ./src`
`CMD ["./mvnw", "spring-boot:run"]`

**Comment by SashankMeka1** [comment]
I can work on this issue, if possible?
