### ISSUE TITLE
Missing the "start service" command between install and running hello-world in the Ubuntu Linux Install Instructions

### ISSUE THREAD

**Issue by Chris-Marlow** [docker/docs#16849]
File: [engine/install/ubuntu.md](https://docs.docker.com/engine/install/ubuntu/)

Install Docker Engine / Step 2

After installing docker via sudo apt-get install ........ there's a missing command:   sudo service docker start

This is missing for both the Latest and Specific Version tabs in this section.

It is, however, already added in the "install from package" section.

**Comment by chirag0002** [comment]
Hey @usha-mandya, is this issue still valid?
If yes, I can start working on this.

**Comment by usha-mandya** [comment]
@dvdksn Could you check if this is still a valid issue?

**Comment by thaJeztah** [comment]
The service should be started automatically after installation (assuming a regular setup with Ubuntu using systemd as process manager), so not sure what's the case here (might be something specific in the environment in which it's installed)

**Comment by Chris-Marlow** [comment]
Thanks for the feedback -- At the time of opening the ticket it definitely didn't start.  However I'll try it out today with a fresh Ubuntu install to see if it auto-starts and update w/ findings.

**Comment by Chris-Marlow** [comment]
I fully agree - not trying to make anything more complex than it needs to be.

Just ran the install instructions against a fresh Ubuntu 22.04.02 LTS, and everything started up correctly as you expected.  Not sure what I hit last time, but for now this can be closed.  Thanks for your feedback.

**Comment by dvdksn** [comment]
Thanks for double-checking and helping confirm!

**Comment by thaJeztah** [comment]
Thank you! If you happen to discover a situation where things don't work as expected (and which may be worth including somewhere in our docs (e.g. a troubleshooting section), feel free to open a new ticket 👍
