### ISSUE TITLE
404 at /engine/installation

### ISSUE THREAD

**Issue by lsm4p5** [docker/docs#16846]
I found a broken link : https://docs.docker.com/engin/installation

**Comment by usha-mandya** [comment]
@lsm4p5 Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by aevesdocker** [comment]
There isn't any information on the ticket for us to take action on. I'm closing the issue here for that reason. Feel free to add more information on the ticket to continue the conversation.
