### ISSUE TITLE
404+at+/install/linux/linux-postinstall//

### ISSUE THREAD

**Issue by id044** [docker/docs#16861]
I+found+a+broken+link+:+https://docs.docker.com/install/linux/linux-postinstall//#configure-docker-to-start-on-boot
I+arrived+on+this+page+through:+https://hub.docker.com/

**Comment by usha-mandya** [comment]
Hey @id044 Thanks for reporting the broken link issue. Could you let me know the specific page on Docker Hub where you spotted this broken link? Thanks.

**Comment by aevesdocker** [comment]
There isn't any information on the ticket for us to take action on. I'm closing the issue here for that reason. Feel free to add more information on the ticket to continue the conversation.
