### ISSUE TITLE
404 at /installation/centos/

### ISSUE THREAD

**Issue by ZaiZiJun** [docker/docs#16872]
I found a broken link : https://docs.docker.com/installation/centos/

**Comment by usha-mandya** [comment]
@ZaiZiJun Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

The link you need is https://docs.docker.com/engine/install/centos/

**Comment by aevesdocker** [comment]
There isn't any information on the ticket for us to take action on. I'm closing the issue here for that reason. Feel free to add more information on the ticket to continue the conversation.
