### ISSUE TITLE
404 at /desktop/install/windows-install/%20

### ISSUE THREAD

**Issue by Saiteja026** [docker/docs#16873]
I found a broken link : https://docs.docker.com/desktop/install/windows-install/%20

**Comment by usha-mandya** [comment]
@Saiteja026  Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by aevesdocker** [comment]
There isn't any information on the ticket for us to take action on. I'm closing the issue here for that reason. Feel free to add more information on the ticket to continue the conversation.
