### ISSUE TITLE
Incorrect documentation due to curly braces being lost in translation

### ISSUE THREAD

**Issue by sparrowt** [docker/docs#16875]
### Problem description

The published web version of the docs incorrectly omits some crucial content which is in curly braces in markdown (despite it being inside triple backticks) resulting in missing/wrong documentation on the website..

### Problem location

For example on https://docs.docker.com/engine/reference/builder/#label the command after "To view an image’s labels" shows up like this:
```
docker image inspect --format='' myimage
```
which is wrong - looking at [the markdown source](https://github.com/docker/cli/blame/daf5f126ad698f34548c21f672450afa5754b7a2/docs/reference/builder.md#L913-L915) it is supposed to show this:
```
docker image inspect --format='{{json .Config.Labels}}' myimage
```

I reported this on #12741 but it was sadly closed by a robot (I missed the notification so did not mark it as fresh in time) - however it is still a problem.

Please would one of the maintainers freeze this issue so it doesn't suffer the same fate?

(I do care about helping to improve the docs, but I don't spend my entire life on github and am unlikely to have the motivation to re-file this issue _again_ if it is left to languish again and I don't notice that a bot is about to close it...!)

**Comment by usha-mandya** [comment]
@sparrowt Apologies for the inconvenience caused. Thank you for taking the time again to report this issue.

@crazy-max Looks like the source file has this info -  https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md#label, but it doesn't appear on the published docs. Any idea what's happening here? Thanks.

**Comment by crazy-max** [comment]
I recall we had the same issue before https://github.com/docker/docs/pull/15622

Will this on BuildKit repo.
