### ISSUE TITLE
404 at /engine/install/centos/%20%C3%97%20%E8%8F%9C%E5%8D%95%E6%9F%A5%E7%9C%8B

### ISSUE THREAD

**Issue by luis1900** [docker/docs#16871]
I found a broken link : https://docs.docker.com/engine/install/centos/%20%C3%97%20%E8%8F%9C%E5%8D%95%E6%9F%A5%E7%9C%8B

**Comment by usha-mandya** [comment]
@luis1900 Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

The correct link is https://docs.docker.com/engine/install/centos/

**Comment by aevesdocker** [comment]
There isn't any information on the ticket for us to take action on. I'm closing the issue here for that reason. Feel free to add more information on the ticket to continue the conversation.
