### ISSUE TITLE
Docker DOES have an Arch package

### ISSUE THREAD

**Issue by qumberrizvi** [docker/docs#16913]
File: [desktop/install/archlinux.md](https://docs.docker.com/desktop/install/archlinux/)

Please refer to the first two steps of [Install Docker Desktop](https://docs.docker.com/desktop/install/archlinux/#install-docker-desktop) section.

First step of `Install Docker Desktop` states the following:

> Install client binaries. Docker does not have an Arch package repository. Binaries not included in the package must be installed manually before installing Docker Desktop.

However, in reality [there is an Arch package](https://archlinux.org/packages/community/x86_64/docker/) that installs Docker client as well as binaries.
You can install the package using `pacman`:
```bash
$ sudo pacman -S docker
```

Contrary to the aforementioned statement, the package does include the binaries and the binaries get installed on the system with the package, hence user does not need to download and install the binaries (referred to in step 2) manually.

There is also a development version of the package ([docker-git](https://aur.archlinux.org/packages/docker-git/)<sup>AUR</sup>) available in AUR. Please refer to the [Arch Wiki page](https://wiki.archlinux.org/title/docker) on Docker for more details.

**Comment by qumberrizvi** [comment]
Please share your thoughts on whether this in fact does warrant updating the documentation. I can share a pull request to do so.

**Comment by ChrisChinchilla** [comment]
@qumberrizvi Thanks! I am asking amongst our Linux team to see what the sort here is and hopefully we would love to accept that PR.

**Comment by ChrisChinchilla** [comment]
So… @qumberrizvi As you can see in the discussion here - https://github.com/docker/docs/pull/17319

We have actually decided to instead create an entirely new "community installers" page and this will form part of that. But thanks for sparking the suggestion!
