### ISSUE TITLE
When I tried to start the app stack with compose, the node didn't start till I manually edited a file

### ISSUE THREAD

**Issue by mpandulloOut** [docker/docs#16933]
app-app-1    | [nodemon] starting `node src/index.js`
app-app-1    | Waiting for mysql:3306............
app-app-1    | Timeout
app-app-1    | Error: connect ECONNREFUSED 172.19.0.2:3306
app-app-1    |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
app-app-1    |   errno: -111,
app-app-1    |   code: 'ECONNREFUSED',
app-app-1    |   syscall: 'connect',
app-app-1    |   address: '172.19.0.2',
app-app-1    |   port: 3306,
app-app-1    |   fatal: true
app-app-1    | }
app-app-1    | [nodemon] app crashed - waiting for file changes before starting...

File: [get-started/08_using_compose.md](https://docs.docker.com/get-started/08_using_compose/)

**Comment by craig-osterhout** [comment]
Hi @mpandulloOut, thanks for sharing the issue.
I'm unable to duplicate this error by following the steps in the guide. It appears to be specific to your environment. It looks like maybe the mysql server didn't start, or didn't start fast enough.

You can try stopping all running containers, and then run docker compose up again.
If the issue persists, you can seek support in the community slack at https://join.slack.com/t/dockercommunity/shared_invite/zt-1jz09gjit-P2NPysg99kiWExFfof0oBA
