### ISSUE TITLE
add letter spacing for better read experience

### ISSUE THREAD

**Issue by refs05** [docker/docs#16956]
File: [get-started/overview.md](https://docs.docker.com/get-started/overview/)

in this section/senteces : 
Fast, consistent delivery of your applications

**Comment by refs05** [comment]
i have make pull request on this issue, please review it.
Thankyou :)

**Comment by aevesdocker** [comment]
Closing this issue as the relevant PR was also closed https://github.com/docker/docs/pull/16987/files.
We'll be updating the look and feel of the docs soon and this will include improved letter spacing
