### ISSUE TITLE
Invalid link to source code

### ISSUE THREAD

**Issue by ahamez** [docker/docs#16963]
File: [storage/storagedriver/select-storage-driver.md](https://docs.docker.com/storage/storagedriver/select-storage-driver/)

The following link is invalid: https://github.com/moby/moby/blob/23.0.0/daemon/graphdriver/driver_linux.go#L52-L53

**Comment by ankitbhadoriya** [comment]
> File: [storage/storagedriver/select-storage-driver.md](https://docs.docker.com/storage/storagedriver/select-storage-driver/)
> 
> The following link is invalid: https://github.com/moby/moby/blob/23.0.0/daemon/graphdriver/driver_linux.go#L52-L53

If this issue is still open, I would like to contribute.
