### ISSUE TITLE
404 at /opensource/workflow/make-a-contribution/

### ISSUE THREAD

**Issue by developerjake** [docker/docs#16975]
I found a broken link : https://docs.docker.com/opensource/workflow/make-a-contribution/
I arrived on this page through: https://github.com/docker/cli/blob/f5d698a331f520e6fa1583911e5dedff428693f3/CONTRIBUTING.md#pull-requests-are-always-welcome
![image](https://user-images.githubusercontent.com/20282542/227748554-c8400a90-5013-4209-890b-8e1082d041cc.png)

**Comment by SashankMeka1** [comment]
I can work on this, but it seems like the issue is in a different repo! I believe it is meant to redirect to https://docs.docker.com/contribute/overview/.

**Comment by SashankMeka1** [comment]
I made the PR in docker/cli. The link is https://github.com/docker/cli/pull/4132.

**Comment by craig-osterhout** [comment]
Thank you for creating the issue in the cli repo. Closing this issue as the link exists in the cli repo.
