### ISSUE TITLE
Update documentation for Buildkit and Docker on Linux

### ISSUE THREAD

**Issue by anders-elastisys** [docker/docs#17042]
### Problem description

I noticed that when I run `docker build` on Ubuntu that Buildkit was enabled, although the documentation states that to use Buildkit when building images on Linux you need to either set `DOCKER_BUILDKIT=1` environment variable, or configure the Docker daemon through a `/etc/docker/daemon.json` file, which neither was set/configured in my case. After further investigations on the Docker engine (moby) release notes I noticed that both buildx and buildkit are used by default since [v23.0.0](https://github.com/moby/moby/releases/tag/v23.0.0).

### Problem location

- I saw a problem at the following URL: https://docs.docker.com/build/buildkit/#getting-started
The _Note_ in that section tells us that Buildkit is always enabled for Buildx , but it does not inform us that buildx is actually the [default](https://github.com/moby/moby/releases/tag/v23.0.0#:~:text=Set%20Buildx%20and,docker/cli%233314) when running `docker build` since v23.0.0.

### Project version(s) affected

Docker Engine 23.0.2

### Suggestions for a fix

Update the documentation so that it is more clear that Buildkit/Buildx is enabled and used by default for recent versions of the Docker Engine, even when installing on Linux.

**Comment by dvdksn** [comment]
Thanks for letting us now :bow:
