### ISSUE TITLE
404 at /docker/compose/releases/download/1.27.4/docker-compose-$9uname%20-s)-$(uname-m)%22%20-o%20/usr/local/bin/docker-compose

### ISSUE THREAD

**Issue by cherangithub** [docker/docs#17058]
I found a broken link : https://docs.docker.com/docker/compose/releases/download/1.27.4/docker-compose-$9uname%20-s)-$(uname-m)%22%20-o%20/usr/local/bin/docker-compose

**Comment by craig-osterhout** [comment]
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?

**Comment by thaJeztah** [comment]
I think the link above is meant to be used from the commandline to _generate_ the correct link for the platform (operating system and architecture) you're running on. The `$9uname%20-s)` part for example, is the URL-encoded presentation of `$(uname -s)`, which gets executed (and substituted) by the shell.

Based on that URL, I suspect this was from some example using cURL to download it;

```bash
curl -fsSL "https://docs.docker.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname-s)-$(uname -m)" -o /usr/local/bin/docker-compose
```

To install compose, I would either recommend;

- Install Docker Desktop, which includes Docker Compose: https://docs.docker.com/desktop/ (and follow the installation instructions for your platform)
- If you're running on Linux, and need to use Docker without Docker Desktop, follow the instructions to install Docker Engine (which also installs the Docker Compose CLI); https://docs.docker.com/engine/install/

**Comment by cherangithub** [comment]
Thank you

**Comment by thaJeztah** [comment]
Let me close this ticket, as I don't think this is a bug/broken link in our docs, but if you have the URL where you found those instructions (and if those instructions can be improved), that would be appreciated
