### ISSUE TITLE
404 at /compose/%EF%BC%89%E3%80%82

### ISSUE THREAD

**Issue by Lemontreepower** [docker/docs#17057]
I found a broken link : https://docs.docker.com/compose/%EF%BC%89%E3%80%82
I arrived on this page through: https://chat.gptman.top/

**Comment by Lemontreepower** [comment]
None yet

**Comment by craig-osterhout** [comment]
Thanks for sharing the broken link. As the source of the link appears in another site, please report the issue to the maintainers of that site.
The link you're probably looking for is https://docs.docker.com/compose
