### ISSUE TITLE
The installation procedure fails with Error: Failed to download metadata for repo 'updates' on Fedora 35

### ISSUE THREAD

**Issue by stevek-pro** [docker/docs#17065]
File: [engine/install/fedora.md](https://docs.docker.com/engine/install/fedora/)

Error: 
`
#4 28.92 Error: Failed to download metadata for repo 'updates': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried`

This is the command inside RedHat's Actions Runners Containerfile:

```
FROM fedora:35

# Adapted from https://github.com/bbrowning/github-runner/blob/master/Dockerfile
RUN dnf -y upgrade --security && \
    dnf -y --setopt=skip_missing_names_on_install=False install && \
    dnf -y install dnf-plugins-core && \
    dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo && \
    curl git jq hostname procps findutils which openssl docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin && \
    dnf clean all
```

See: https://stackoverflow.com/a/70358657/356759

Unsure on how to resolve.

**Comment by stevek-pro** [comment]
Using latest version like `FROM fedora:38` will find the repodata.xml at the various mirror's locations. But still, others are running into this issue, someone could kindly doublecheck if there is a documentation error.

**Comment by thaJeztah** [comment]
Fedora 35 reached EOL in december 2022, and probably package repositories have been shut down for it by now, which can explain those errors; https://docs.fedoraproject.org/en-US/releases/eol/

Closing this ticket as this is not a documentation issue
