### ISSUE TITLE
Clarify which port is the host and which is the container

### ISSUE THREAD

**Issue by genericmoniker** [docker/docs#17072]
File: [engine/reference/commandline/port.md](https://docs.docker.com/engine/reference/commandline/port/)

The majority of examples you encounter dodge the question by using the same port number for both (e.g. `-p 8000:8000`). It would be great if the documentation were clear about which port is which. The examples in this page indicate inconsistency between docker commands making it harder to know.

Using `docker ps` it has:

`0.0.0.0:1234->9876/tcp`

Using `docker port` it has:

`9876/tcp -> 0.0.0.0:1234`

**Comment by SashankMeka1** [comment]
I can handle this issue, if possible? I'm pretty certain that it has to map to the same port, but I am willing to make changes to the docs to clarify this further.

**Comment by Stuzanna** [comment]
Could probably do with including this explanation from the Python demo.

> To publish a port for our container, we’ll use the --publish flag (-p for short) on the docker run command. The format of the --publish command is [host port]:[container port]. So, if we wanted to expose port 5000 inside the container to port 3000 outside the container, we would pass 3000:5000 to the --publish flag.

https://docs.docker.com/language/python/run-containers/
