### ISSUE TITLE
404 at /compose/compose-file-v2/

### ISSUE THREAD

**Issue by Stevepurpose** [docker/docs#17075]
I found a broken link : https://docs.docker.com/compose/compose-file-v2/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. On what website/page did you find the broken link?

The page you may be looking for is at https://docs.docker.com/compose/compose-file/compose-file-v2/

**Comment by Stevepurpose** [comment]
ChatGPT actually

**Comment by Stevepurpose** [comment]
Ok
