### ISSUE TITLE
Networking documentation improvements

### ISSUE THREAD

**Issue by dvdksn** [docker/docs#17080]
The current section on [Networking](https://docs.docker.com/network/) could use some improvements.

This section, in it's current location and structure, is relatively new. This information was previously found under Guides > Run your app in Production. But, since we moved and restructured the Docker Engine content, networking is now a top-level concern under Docker Engine in manuals.

The current section suffers from the following issues:

- The [overview page](https://docs.docker.com/network/) only talks about networking drivers.
- The [Container networking page](https://docs.docker.com/config/containers/container-networking/) seems a better fit as an overview page for the networking section
- There is some overlap between information provided on (one of) the [Docker run reference](https://docs.docker.com/engine/reference/run/#network-settings) pages, and the Networking section.
- The documentation for drivers is lacking descriptions of the possible driver options.
- There's some duplication going on, between the pages describing a networking driver, and the corresponding "tutorial"-page. It's also not very clear what information goes where (sometimes inconsistent)

I believe that we can fix, to some extent, the above issues by:

1. Making the container networking page the new section overview
2. Moving information from the Docker run reference page to the networking overview page
3. Making the current overview page (about networking drivers) into an overview page for networking drivers
4. Consolidating information about drivers into one page per driver (no description/tutorial separation)
5. Adding descriptions for all networking driver options

There's also a page describing [legacy container links](https://docs.docker.com/network/links/). The information on that page requires a thorough review. I will raise a second ticket for this one.

**Comment by thaJeztah** [comment]
@dvdksn @akerouanton were there things remaining after https://github.com/docker/docs/pull/17176, or was this ok to be closed?

**Comment by thaJeztah** [comment]
Oh never mind this was the "lock" comment; it was already closed; ignore me 😂
