### ISSUE TITLE
Indicate MacOS version compatibility 

### ISSUE THREAD

**Issue by RandyMcMillan** [docker/docs#17090]
File: [desktop/release-notes.md](https://docs.docker.com/desktop/release-notes/)

Trying to DL a Docker.App version that is compatible with MacOS `10.15.7 (19H2026)`

The DL links indicate Intel but I still have to work thru the list to find a version that I can use on 

MacOS `10.15.7 (19H2026)`

Additionally it would be great to provide command prompts or a how to for installing
a compatible version via brew commands.

**Comment by ChrisChinchilla** [comment]
@RandyMcMillan Regarding the brew comment, we do have a "community installers" page on the to do list.

**Comment by RandyMcMillan** [comment]
Docker.amd64.93002.dmg seems to be the best option for MacOS x86_64 Catalina 10.15.7

I will also find the best version for MacOS x86_64 Mavericks
