### ISSUE TITLE
Update 4.18.0 download links

### ISSUE THREAD

**Issue by robsoned** [docker/docs#17100]
File: [desktop/release-notes.md](https://docs.docker.com/desktop/release-notes/)

Hello there,

I have noticed that the links provided on the release notes page for downloading the Debian, RPM, and Arch versions of Docker Desktop are pointing to the previous version (4.17.0) instead of the latest version (4.18.0). Thanks!

**Comment by SashankMeka1** [comment]
I can work on this issue!

**Comment by umairraza96** [comment]
There is already a PR #17098, Thanks for noticing though :)
