### ISSUE TITLE
Docker Desktop Download Links (4.18.0) for Linux packages are not pointing correctly

### ISSUE THREAD

**Issue by voonyee** [docker/docs#17119]
File: [desktop/release-notes.md](https://docs.docker.com/desktop/release-notes/)
It seems that the download links for Linux packages are not pointing to the correct files. The checksum file contains the following:

> 4d64ea1c9e9da66ca0a37820135926eb4bbcdf658cafdbe87497aae384bf65c7 docker-desktop-4.18.0-x86_64.rpm
> 0d6f8c54457f89cfaba3222ab4754caa8df547a0050aa8749d679609bad9456d docker-desktop-4.18.0-x86_64.pkg.tar.zst
> d579f653b5223a3c24234992203283c5a6da28146702f8899964e08b8ba45198 docker-desktop-4.18.0-amd64.deb

The Debian, RPM, and Arch package links point to:
> https://desktop.docker.com/linux/main/amd64/docker-desktop-4.17.0-amd64.deb
> https://desktop.docker.com/linux/main/amd64/docker-desktop-4.17.0-x86_64.rpm
> https://desktop.docker.com/linux/main/amd64/docker-desktop-4.17.0-x86_64.pkg.tar.zst

Though the links should point to the below?
> https://desktop.docker.com/linux/main/amd64/docker-desktop-4.18.0-amd64.deb
> https://desktop.docker.com/linux/main/amd64/docker-desktop-4.18.0-x86_64.rpm
> https://desktop.docker.com/linux/main/amd64/docker-desktop-4.18.0-x86_64.pkg.tar.zst

Case: 00061441

**Comment by SashankMeka1** [comment]
I've fixed this issue. Here is the PR: https://github.com/docker/docs/pull/17121
