### ISSUE TITLE
[Python docs feedback]

### ISSUE THREAD

**Issue by niketanjain** [docker/docs#17126]
### Problem description
Was unable to run `docker compose -f docker-compose.dev.yml up `  as getting errored out: 
```
[+] Building 1.0s (3/3) FINISHED                                                                                                                 
 => [internal] load build definition from Dockerfile                                                                                        0.0s
 => => transferring dockerfile: 32B                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                           0.0s
 => => transferring context: 2B                                                                                                             0.0s
 => ERROR resolve image config for docker.io/docker/dockerfile:1                                                                            0.9s
------
 > resolve image config for docker.io/docker/dockerfile:1:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = error getting credentials - err: docker-credential-desktop resolves to executable in current directory (./docker-credential-desktop), out: ``

```

### Problem location
 

- I saw a problem at the following URL: https://docs.docker.com/language/python/develop/#use-compose-to-develop-locally 

- I couldn't find the information I wanted. I expected to find it near the following URL <Add the URL and briefly describe how we can improve the existing content>

- Other: <Add details that can help us understand the issue>

### Suggestions for a fix
Had to change `credsStore` to `credStore` in .docker/config.json to make it working. Not sure same going to affect in OSs other than Linux (Ubuntu) but having a note in document can be helpful for people getting started with docker. 
Which one is right key `credStore` or `credsStore` or both based on configuration demands?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
The option is `credsStore` as specified in https://docs.docker.com/engine/reference/commandline/login/#credentials-store
You probably disabled the credential helper by using `credStore`.

If you believe this is an issue with Docker Desktop and not specific to your configured environment, please raise an issue in https://github.com/docker/desktop-linux/issues to report the bug.

If you believe it's an environment/configuration error and you'd like help troubleshooting, please try to seek help in the community slack https://join.slack.com/t/dockercommunity/shared_invite/zt-1jz09gjit-P2NPysg99kiWExFfof0oBA
If you have a paid Docker subscription, you can seek Docker support at https://hub.docker.com/support/contact/

Closing this as it appears to be a bug or support issue. Please use the resources above.
