### ISSUE TITLE
Mount command target value set

### ISSUE THREAD

**Issue by ThiyagarajanR** [docker/docs#17147]
### Problem description

- The command for the running the image with mount target was giving the error "Mount path must be absolute".
-  Ran the command inside VS code bash terminal inside windows 10 operating system 

### Problem location

- I saw a problem at the following URL: https://docs.docker.com/get-started/05_persisting_data/

- The issue was in the command "docker run -dp 3000:3000 --mount type=volume,src=todo-db,target=/etc/todos getting-started" under the heading "Persist the todo data"

- Other: <Add details that can help us understand the issue>

### Suggestions for a fix

- When I changed the command ( added one more / before the target path ) to "docker run -dp 3000:3000 --mount type=volume,src=todo-db,target=//etc/todos getting-started". It worked .

**Comment by dvdksn** [comment]
I wonder if this somehow relates to how the command is interpreted in WSL when used in combination with the integrated terminal in VS Code. What happens if you quote the parameter string for the `--mount` flag, like so:

```
$ docker run -dp 3000:3000 --mount="type=volume,src=todo-db,target=/etc/todos" getting-started
```
