### ISSUE TITLE
Legacy builder is deprecated

### ISSUE THREAD

**Issue by wwoofbum** [docker/docs#17182]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)

**Comment by craig-osterhout** [comment]
@wwoofbum, thanks for sharing the issue.
Can you provide more details about the issue. For example, if you received an error message, can you share the complete error message.

**Comment by craig-osterhout** [comment]
Closing as stale. Not enough info to replicate the issue. If the issue persists, please provide more details.
