### ISSUE TITLE
In Docker I'm always getting dameon error

### ISSUE THREAD

**Issue by Subbaraman-Sowmya** [docker/docs#17190]
![Uploading Always getting Dockerfile not found or build step failure or docker integration errors1904230510PM.png…]()

### Problem location

- I saw a problem at the following URL: <Add URL>

- I couldn't find the information I wanted. I expected to find it near the following URL <Add the URL and briefly describe how we can improve the existing content>

- Other: <Add details that can help us understand the issue>

**Comment by Subbaraman-Sowmya** [comment]
I am not able to work on my project since github repository of mine is not having proper authentication and is always giving error when generating personal Access Token (PAT) or generating SSH keys. I don't know how to fix this.
![After generating Personal Access Token also it is failing1104230107PM](https://user-images.githubusercontent.com/61080915/234565611-7335ce82-7945-4120-80f0-69a8d1fc6da5.png)
![docker ce error coming even if broken install run2604230455PM](https://user-images.githubusercontent.com/61080915/234565671-020a12a4-e41d-4ca8-a721-4012858a08b6.png)
![docker service failed exited with status 1 failure2304230150PM](https://user-images.githubusercontent.com/61080915/234565749-cd3e9f32-027a-472b-8298-27ac9a30bf8d.png)
![How to add the DNS Test record for verification0804230346PM](https://user-images.githubusercontent.com/61080915/234565798-7a5f848f-ab4b-4036-a5f1-9defba23d429.png)
![Failed to push some reference to master in git2404231241PM](https://user-images.githubusercontent.com/61080915/234565879-205903c7-ff35-4bc3-841f-b18856a4a912.png)
![How to resolve support for password authentication was removed on August 132021](https://user-images.githubusercontent.com/61080915/234565921-8edbbe31-9cb2-4b1f-9e1a-2b5e2ef38859.jpg)
![List of SSH keys associated with my account of git hub (Still it is not verified with enterprise account)0804230329PM](https://user-images.githubusercontent.com/61080915/234565964-5a61673b-cdb8-480a-b38c-433cceb76f96.png)
![Uploading Insecure registries error 2304230109PM.png…]()

**Comment by Subbaraman-Sowmya** [comment]
Please I have provided the screen shots of the problems which I encountered in docker and github. Please if possible resolve these issues.

**Comment by craig-osterhout** [comment]
Hi @Subbaraman-Sowmya, thanks for sharing the issue. Did you encounter the error when following a particular topic or guide at docs.docker.com?

If you're having issues with GitHub authentication and need support, you can try GitHub's support resources:
- https://docs.github.com/en
- https://support.github.com/
- https://support.github.com/request

If you need support with any issues related to Docker, please see https://docs.docker.com/support/

**Comment by craig-osterhout** [comment]
Closing as stale. If an issue persists in the docs, please let us know.
