### ISSUE TITLE
Error docs empty environment variable will produce an empty string

### ISSUE THREAD

**Issue by Kibubu** [docker/docs#17192]
https://github.com/docker/docs/blob/45e5838f13346e4e2d5ee4969ffb95352ea51363/compose/environment-variables/set-environment-variables.md?plain=1#L112

While the sentence is correct the conclusion is wrong. The final value is `postgres:` without the period. Since a colon is provided but not tag is given docker will refuse to run this image.

This should be either fixed in the docs or inside compose.

**Comment by aevesdocker** [comment]
Closing as this issue has now been resolved in the linked PR. Thanks again @Kibubu
