### ISSUE TITLE
docs: TYPE command for create new file in windows doesn't work correctly

### ISSUE THREAD

**Issue by SepandJP** [docker/docs#17215]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)
See in github: [Line71](https://github.com/docker/docs/blob/4d4a7352d1a60df0af09d74683ae16f2de84a5a6/get-started/02_our_app.md?plain=1#L71)

When i write this command:
```console
type nul > Dockerfile
```
 Dockerfile is created but receive an error in terminal:
```console
type : Cannot find path 'C:\Users\...\getting-started\app\nul'
because it does not exist.
At line:1 char:1
+ type nul >filename.log
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\...\app\nul:String) [Get-Content]
   , ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
```
while write
```console
type Dockerfile
``` 
command, file is created and don't get any error.

Does the command need to be updated? Or am I wrong?

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The command must be ran in **Command Prompt**. It looks like you may be running it in PowerShell.
