### ISSUE TITLE
rhel9 support

### ISSUE THREAD

**Issue by jbertozzi** [docker/docs#17259]
### Problem description

The [documentation ](https://docs.docker.com/engine/install/rhel/) states that for rhel9, only rpm packages for s390x architecture are provided while the official [repository](https://download.docker.com/linux/centos/9/x86_64/stable/Packages/) contains the packages for  x86_64 architecture.

Just asking for clarification as it could be an oversight.

### Problem location

https://github.com/docker/docs/blob/main/engine/install/rhel.md

**Comment by dvdksn** [comment]
As stated in the note, RPM packages for centos are provided and you may be able to install them on RHEL.
