### ISSUE TITLE
404 at /config/

### ISSUE THREAD

**Issue by DMTarmey** [docker/docs#17278]
I found a broken link : https://docs.docker.com/config/

-  Use the 'execute_python_file' command to execute the new Python file named 'test.py'
CRITICISM:  I need to ensure that the code in the new Python file is correct before executing it.NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'filename': 'C:\\Users\\Dell User\\Auto-GPT\\autogpt\\auto_gpt_workspace\\test.py'}
  Executing file 'C:\Users\Dell User\Auto-GPT\autogpt\auto_gpt_workspace\test.py'
  Could not run the script in a container. If you haven't already, please install Docker https://docs.docker.com/get-docker/

**Comment by dvdksn** [comment]
Hi, where did you find this link?

**Comment by aevesdocker** [comment]
There isn't any information for us to take action on. I'm closing the issue here for that reason. Feel free to add more information to the ticket to continue the conversation.
