### ISSUE TITLE
Make it clear that the command line is no place for secrets/passwords

### ISSUE THREAD

**Issue by MaxHearnden** [docker/docs#17285]
File: [get-started/07_multi_container.md](https://docs.docker.com/get-started/07_multi_container/)
```
docker run -d \
     --network todo-app --network-alias mysql \
     -v todo-mysql-data:/var/lib/mysql \
     -e MYSQL_ROOT_PASSWORD=secret \
     -e MYSQL_DATABASE=todos \
     mysql:8.0
```
This is bad practice for two reasons
1. Tools such as ps and top can show the command
2. Interactive bash terminals keep a history file which would contain the password if the command was entered by the user

**Comment by tnn4** [comment]
The instructions are good for quick starts and testing out commands but they should also offer alternative methods for entering  sensitive environment variables like telling the user to create and read from a file instead and explicitly telling them to keep that file out of the public with some method such as `.gitignore` , encryption or some other means.

e.g.

Define environment variables in .env file and use that as an argument for `--env-file`.

.env
```
# Warning: sensitive info
# keep private with .gitignore or by storing somewhere safe
super_secret_key="keepmeprivate"
MYSQL_ROOT_PASSWORD="secret"
```

```
docker run -d \
     --network todo-app --network-alias mysql \
     -v todo-mysql-data:/var/lib/mysql \
     --env-file .env
     -e MYSQL_DATABASE=todos \
     mysql:8.0
```

**Comment by polarathene** [comment]
It's an example and the security is not the focus of it. What would a better way be to emphasize that? Changing the password value to `not-secure`?

Some users think the Docker Swarm feature with secrets works outside of swarm deployments, but it is only supported via Compose as a convenience for local dev, but IIRC docs don't clarify that. The feature loses all of it's security benefits becoming an unencrypted volume bind mount no permission/ownership changes applied if specified.

Likewise with the ENV advise being suggested. You can lookup containers with `docker inspect`. Either from the host, or if an attacker has compromised access to the daemon from within a container. This will provide that information clearly visible. Within the container, a command like `env` (which is available in the `mysql` container) will likewise expose these.

Secrets management is it's own topic, but if it were to be addressed within the docs, it would be better to have a dedicated page that other pages can draw attention to where relevant. I agree avoiding passwords being captured in shell history or commit history are quite relevant precautions users should be aware of. Access to shell history may imply read access to other files like `.env` files though.
