### ISSUE TITLE
COPY line clarification

### ISSUE THREAD

**Issue by doyinosin** [docker/docs#17291]
File: [get-started/02_our_app.md](https://docs.docker.com/get-started/02_our_app/)

Hi,

Pardon me if this is not the right way to address this.

In the step, [Build the app’s container image](https://docs.docker.com/get-started/02_our_app/#build-the-apps-container-image), I'm confused about the COPY line in the Dockerfile content below:
   
```
# syntax=docker/dockerfile:1

FROM node:18-alpine
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "src/index.js"]
EXPOSE 3000
```

It looks like it's copying the contents of the current directory to the current directory (unlikely). In the [description of the COPY command](https://docs.docker.com/engine/reference/builder/#copy), it seems to me that the **_src_** is a reference to a location in the filesystem where the Dockerfile is and **_dest_** would be an intended location in the filesystem of the image to be built.

Could you clarify this, please?

Thank you

**Comment by craig-osterhout** [comment]
Hi, thanks for sharing the issue.
For the *src*, it's interpreted as relative to the source of the context of the build.
In the topic, the context for the build is the `/path/to/app` directory on your host computer, where the Dockerfile is. 

For the *dest*, the directory is determined by the previous `WORKDIR` instruction. In this case, the `/app` directory in the container.

Copy everything from the `path/to/app` directory on the host computer to the `/app` directory in the container.

If you're using the latest version of Docker Desktop, you can easily see what files are copied to the container.
Go through that topic to build and then start the container.
After the container is started, click on the container name in the **Containers** tab of Docker Desktop. Then click on **Files** to view the files in the container. In this case, you can see what was copied to the `/app` directory in the container.

![image](https://github.com/docker/docs/assets/103533812/0392b5a9-bd65-4ee3-adfb-e39f4e4473e4)


If you have more questions, please join the Community Slack at https://join.slack.com/t/dockercommunity/shared_invite/zt-1jz09gjit-P2NPysg99kiWExFfof0oBA

**Comment by doyinosin** [comment]
That clarifies things. Thank you.
