### ISSUE TITLE
Supervisord logs

### ISSUE THREAD

**Issue by shunkica** [docker/docs#17298]
File: [config/containers/multi-service_container.md](https://docs.docker.com/config/containers/multi-service_container/)

Please add an explanation how to show the stdout and stderr logs from the services ran with supervisord.

For example, if two npm processes are ran with supervisord, the only output is:

> INFO spawned: 'client' with pid 9
> INFO spawned: 'server' with pid 10
> INFO reaped unknown pid 8 (exit status 1)
> INFO success: client entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> INFO success: server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

If stdout and stderr are set to /dev/fd/1 and /dev/fd/2 in supervisord.conf like this:

> stdout_logfile=/dev/fd/1
> stderr_logfile=/dev/fd/2

Then the logs can be seen by docker, but under every log line this additional error is displayed:

> CRIT uncaptured python exception, closing channel <POutputDispatcher at 140077112601248 for <Subprocess at 140077112596016 with name client in state RUNNING> (stderr)> (<class 'OSError'>:[Errno 29] Invalid seek [/usr/lib/python3.10/site-packages/supervisor/supervisord.py|runforever|218] [/usr/lib/python3.10/site-packages/supervisor/dispatchers.py|handle_read_event|281] [/usr/lib/python3.10/site-packages/supervisor/dispatchers.py|record_output|215] [/usr/lib/python3.10/site-packages/supervisor/dispatchers.py|_log|184] [/usr/lib/python3.10/site-packages/supervisor/loggers.py|info|327] [/usr/lib/python3.10/site-packages/supervisor/loggers.py|log|345] [/usr/lib/python3.10/site-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3.10/site-packages/supervisor/loggers.py|doRollover|264])

It is a waste of time to research such stuff. This works:

```
[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:app]
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
```

**Comment by dvdksn** [comment]
Thanks for reporting the issue. Fixed in #17301
