### ISSUE TITLE
Why docker mount /etc/{resolv.conf,hostname,hosts}

### ISSUE THREAD

**Issue by azraelxuemo** [docker/docs#17315]
### Problem location

Hi there,I have a question about docker decison.
When we create a normal docker  ,such as docker run -it ubuntu:18.04 bash
And run mount command in docker
<img width="960" alt="截屏2023-05-15 12 01 00" src="https://github.com/docker/docs/assets/60163868/b5fdfb2c-994b-422f-8d72-81ae228cf0ef">
You can see docker mount /etc/{resolv.conf,hostname,hosts} from outside
<img width="1592" alt="截屏2023-05-15 12 01 23" src="https://github.com/docker/docs/assets/60163868/52860bea-8c8d-496d-b895-fd0cc585b588">
I wonder Why is it designed like this

**Comment by dvdksn** [comment]
Hi. Please raise this question on the [moby/moby](https://github.com/moby/moby) repository instead. Thank you.
