### ISSUE TITLE
Raspbian Docker Installation Documentation Does Not Work

### ISSUE THREAD

**Issue by bootsareme** [docker/docs#17311]
When using the latest Raspberry Pi OS (64-bit) *Raspbian*, following the dedicated webpage for installing docker on raspbian does not work. I ran the following command as stated **exactly** by the documentation:

Here are the commands in chronological order:

```sh
 sudo apt-get update
 sudo apt-get install ca-certificates curl gnupg
```

```sh
 sudo install -m 0755 -d /etc/apt/keyrings
 curl -fsSL https://download.docker.com/linux/raspbian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
 sudo chmod a+r /etc/apt/keyrings/docker.gpg
```

```sh
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/raspbian \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
```

```sh
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

When ran on an Raspberry Pi 4 Model B with latest operating system (literally flashed on May 11, 2023), I get the following error as exactly stated:

```sh
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package docker-ce-cli is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
E: Package 'docker-ce-cli' has no installation candidate
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'
E: Unable to locate package docker-buildx-plugin
E: Unable to locate package docker-compose-plugin
```

### Problem location

- I saw a problem at the following URL: [https://docs.docker.com/engine/install/raspbian/](https://docs.docker.com/engine/install/raspbian/)

**Comment by StefanScherer** [comment]
Thanks @bootsareme for this find.
Indeed, the described steps don't work on 64bit Raspbian, but they do for 32bit (armhf). We don't ship special 64bit packages for Raspbian.

On a 64bit Raspbian you need to replace `raspbian` with `debian` both in step 2 and step 3. Then the normal Debian 64bit ARM packages are installed. Looks like the convenient script already takes care of this difference.

I'll prepare a fix for the documentation.
