### ISSUE TITLE
build/bake/file-definition should redirect to build/bake/reference

### ISSUE THREAD

**Issue by crazy-max** [docker/docs#17360]
Looks like an orphan page: https://docs.docker.com/build/bake/file-definition/ that should be redirected to https://docs.docker.com/build/bake/reference/

It also does not display the sidebar nav:

![image](https://github.com/docker/docs/assets/1951866/e9f59e1f-972c-4012-b8a9-e9f6f2aa149e)

**Comment by dvdksn** [comment]
I was pretty sure I removed that page.
