### ISSUE TITLE
docker compose rm --dry-run unknown flag

### ISSUE THREAD

**Issue by Akronix** [docker/docs#17364]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Hi!

I just upgraded to the last version of docker compose in my system (Ubuntu 22.04): Docker Compose version v2.17.3, and the --dry-run flag for `docker compose rm` fails with: 

> unknown flag: --dry-run

[But the documentation shows there is such option](https://docs.docker.com/engine/reference/commandline/compose_rm/). Not sure if it's an addition in later release of docker compose or if it's the documentation just not accurate.

### Location

https://docs.docker.com/engine/reference/commandline/compose_rm/

**Comment by aevesdocker** [comment]
@glours @ndeloof Would you mind taking a quick look at this issue when you get a spare second? Looks a product issue

**Comment by ndeloof** [comment]
`--dry-run` applies to `compose` subcommand:
```
$ docker compose --dry-run rm app
? Going to remove truc-app-1 Yes
[+] Removing 1/0
 ✔ DRY-RUN MODE -  Container truc-app-1  Removed    
```
