### ISSUE TITLE
Post "https://hub.docker.com/v2/access-tokens/desktop-generate": EOF

### ISSUE THREAD

**Issue by wuxins** [docker/docs#17380]
### Location

Post "https://hub.docker.com/v2/access-tokens/desktop-generate": EOF

### Broken link

Post "https://hub.docker.com/v2/access-tokens/desktop-generate": EOF

### Comment

while trying  desktop login, following error occurs:
<img width="1368" alt="image" src="https://github.com/docker/docs/assets/40260824/f17efb73-538b-45f3-8ff4-a113c8f30224">

Post "https://hub.docker.com/v2/access-tokens/desktop-generate": EOF

docs without  any guide for solutions

**Comment by PittYao** [comment]
> ### Location
> Post "https://hub.docker.com/v2/access-tokens/desktop-generate": EOF
> 
> ### Broken link
> Post "https://hub.docker.com/v2/access-tokens/desktop-generate": EOF
> 
> ### Comment
> while trying desktop login, following error occurs: <img alt="image" width="1368" src="https://user-images.githubusercontent.com/40260824/239660629-f17efb73-538b-45f3-8ff4-a113c8f30224.png">
> 
> Post "https://hub.docker.com/v2/access-tokens/desktop-generate": EOF
> 
> docs without any guide for solutions

me too

**Comment by herongxhr** [comment]
我也碰到这个问题，我是mac os docker desktop，试了很多次都没有用
