### ISSUE TITLE
"apt-get remove" command doesn't remove installed packages if a package isn't found

### ISSUE THREAD

**Issue by noamraph** [docker/docs#17405]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The docs instruct to remove old versions by running:

```
sudo apt-get remove docker docker-engine docker.io containerd runc
```

However, it turns out that if a package isn't found, the command fails entirely:

![image](https://github.com/docker/docs/assets/1553464/397522a9-2d42-4e10-b873-aa33df2add93)

I'm on Ubuntu 22.04, WSL2.

### Location

https://docs.docker.com/engine/install/ubuntu/

### Suggestion

Perhaps replace the command with something like this:

```
for pkg in docker docker-engine docker.io containerd runc; do sudo apt-get remove -y $pkg; done
```

This would remove all packages, regardless of whether packages are known or not.

**Comment by dvdksn** [comment]
Thanks @noamraph! I've pushed your suggestion in #17415
