### ISSUE TITLE
Better document URL format for `registry-mirrors`

### ISSUE THREAD

**Issue by neersighted** [docker/docs#17414]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The example for setting up a pull-through mirror (as well as the [general config page](https://docs.docker.com/engine/reference/commandline/dockerd/)) does not explain the kind of URL that is expected.

Some users may attempt the following URL formats:
* `https://my-mirror.company.com/namespace`, which does not work as a mirror is responsible for all content.
* `https://dev-infra.company.com/registry`, which does not work as a mirror must be at the root (`/`) path of the domain.

These are not valid formats for a mirror URL:
https://github.com/moby/moby/blob/c651a535588402f27d8f1a1408c794fc3289f39f/registry/config.go#L331-L333

### Location

https://docs.docker.com/registry/recipes/mirror/#configure-the-docker-daemon

### Suggestion

The docs should make it clear that a pull-through registry must be at the root of a domain, and that the daemon configuration should include no path components, other than an optional trailing `/`.

**Comment by dvdksn** [comment]
Closing as done due to distribution/distribution#3933
