### ISSUE TITLE
[404]: /opensource/project/who-written-for/

### ISSUE THREAD

**Issue by amjadkofahi** [docker/docs#17418]
### Location

https://github.com/docker/cli/blob/5be21394cbbafc5627bb3e8a54014c108a534b52/CONTRIBUTING.md

### Broken link

https://docs.docker.com/opensource/project/who-written-for/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. closing as duplicate of https://github.com/docker/cli/issues/4036
