### ISSUE TITLE
Same download link for credential helpers

### ISSUE THREAD

**Issue by KevinSpringfield** [docker/docs#17428]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

I found that links of suggested credential helpers are the same and all refer to `https://github.com/docker/docker-credential-helpers/releases`.

I think there's no need to provide link for each credential helper except D-Bus and pass, because Apple macOS keychain and Microsoft Windows Credential Manager are built in the operating system.

How about keep only list of names like suggestion below?

### Location

https://docs.docker.com/engine/reference/commandline/login/#credentials-store

### Suggestion

- D-Bus Secret Service
- Apple macOS keychain
- Microsoft Windows Credential Manager
- [pass](https://www.passwordstore.org/)

**Comment by dvdksn** [comment]
Hi. This section is a little confusing, but essentially correct. The credential store helpers are there to help you integrate Docker with a credential store. I've raised pull request docker/cli#4322 to rephrase the section slightly.

**Comment by KevinSpringfield** [comment]
Thanks for improving this, I see that PR has been merged, issue closed.
