### ISSUE TITLE
Misplaced and repeated content

### ISSUE THREAD

**Issue by zer0to1ne** [docker/docs#17442]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Under the section `Communicate between a container and a swarm service`, the contents are misplaced and repeated as was under the section of `Use the default bridge network` on the previous page https://docs.docker.com/network/network-tutorial-standalone/.

### Location

https://docs.docker.com/network/network-tutorial-overlay/

**Comment by satyampsoni** [comment]
could you pls elaborate what is misplaced and repeated ?
And what is misinformed here?
