### ISSUE TITLE
[404]: /compose/install/%EF%BC%89%E6%8F%90%E4%BE%9B%E7%9A%84%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97%EF%BC%8C%E6%8C%89%E7%85%A7%E6%8C%87%E5%8D%97%E4%B8%AD%E7%9A%84%E6%AD%A5%E9%AA%A4%E9%87%8D%E6%96%B0%E5%AE%89%E8%A3%85

### ISSUE THREAD

**Issue by xiaoshan-ya** [docker/docs#17464]
### Location

https://poe.com/

### Broken link

https://docs.docker.com/compose/install/%EF%BC%89%E6%8F%90%E4%BE%9B%E7%9A%84%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97%EF%BC%8C%E6%8C%89%E7%85%A7%E6%8C%87%E5%8D%97%E4%B8%AD%E7%9A%84%E6%AD%A5%E9%AA%A4%E9%87%8D%E6%96%B0%E5%AE%89%E8%A3%85

**Comment by stephaurelio** [comment]
Thanks for reporting the broken link issue. Could you let us know how you arrived at the broken link?
