### ISSUE TITLE
[404]: /engine/install/%E3%80%82%E5%AE%89%E8%A3%85

### ISSUE THREAD

**Issue by jianghuayun23** [docker/docs#17470]
### Location

https://chatbot.theb.ai/

### Broken link

https://docs.docker.com/engine/install/%E3%80%82%E5%AE%89%E8%A3%85

**Comment by thaJeztah** [comment]
I suspect you accidentally copied some extra text as part of the URL (the last part of that link is `。安装` but encoded)

The URL your probably looking for is https://docs.docker.com/engine/install/

I'll close this ticket as I don't think there's anything to fix in the docs itself
