### ISSUE TITLE
[404]: /go/access-tokens/%EF%BC%89%E4%BA%86%E8%A7%A3%E6%9C%89%E5%85%B3%E5%A6%82%E4%BD%95%E7%94%9F%E6%88%90%E5%92%8C%E4%BD%BF%E7%94%A8%E4%B8%AA%E4%BA%BA%E8%AE%BF%E9%97%AE%E4%BB%A4%E7%89%8C%E7%9A%84%E6%9B%B4%E5%A4%9A%E8%AF%A6%E7%BB%86%E4%BF%A1%E6%81%AF%E3%80%82

### ISSUE THREAD

**Issue by 155039486** [docker/docs#17487]
### Location

155039486

### Broken link

https://docs.docker.com/go/access-tokens/%EF%BC%89%E4%BA%86%E8%A7%A3%E6%9C%89%E5%85%B3%E5%A6%82%E4%BD%95%E7%94%9F%E6%88%90%E5%92%8C%E4%BD%BF%E7%94%A8%E4%B8%AA%E4%BA%BA%E8%AE%BF%E9%97%AE%E4%BB%A4%E7%89%8C%E7%9A%84%E6%9B%B4%E5%A4%9A%E8%AF%A6%E7%BB%86%E4%BF%A1%E6%81%AF%E3%80%82

**Comment by aevesdocker** [comment]
Closing this issue as there no action for us to take.
