### ISSUE TITLE
Create an empty warehouse group, is supported, such as XXXX: 3000 / test/nginx: 1.19, I hope to create a test of this group, is there any API to create, just create the group alone

### ISSUE THREAD

**Issue by kubecto** [docker/docs#17529]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

Create an empty warehouse group, is supported, such as XXXX: 3000 / test/nginx: 1.19, I hope to create a test of this group, is there any API to create, just create the group alone

### Location

https://docs.docker.com

### Suggestion

Create an empty warehouse group, is supported, such as XXXX: 3000 / test/nginx: 1.19, I hope to create a test of this group, is there any API to create, just create the group alone

**Comment by craig-osterhout** [comment]
Hi, thanks for sharing the issue. Can you provide more context about the issue?

Documentation for all of Docker's supported APIs is at https://docs.docker.com/reference/
If you're asking about third-party APIs, you'll need to refer to the third-party's documentation.

**Comment by craig-osterhout** [comment]
Closing as stale.
