### ISSUE TITLE
Incomplete instructions: How was the Students table created?

### ISSUE THREAD

**Issue by abarberenaCPDS** [docker/docs#17522]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Hello 👋 ,

First of all, thank you for the great work making these series, they are indeed useful. 🚀 

I am doing the steps in the **_C# series_** 📝 , however, I've hit a couple of issues while following the instructions.

- The first one is about the _PostgreSQL_ image, there are _no instructions_ about how to create the `my_db` database and the current/default image, creates a different database. 

- Second is. the `Students` table and the script or steps needed to create it. Of course one can infer the table schema though, but I guess it needs a bit more clarification,

> <img width="825" alt="image" src="https://github.com/docker/docs/assets/43246964/83ad090f-8643-4c6f-bb0f-25f36d202ae7">

- One more is the `Run your tests` step, it is not clear how to run the test.

- Finally, the `Configure CI/CD for your application` and `Deploy your app` seem to not be in sync with the previous steps.

So, I am kindly asking to review or update them accordingly.

Thanks!

### Location

https://docs.docker.com/language/dotnet/develop/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The database and table are created by the app. I'll add a small hint about this. Going in-depth about C# is outside the scope of the guide.
If you don't see the db or table, make sure you start the postgres container before running the app container.

To run tests, run `dotnet test tests` from the dotnet-docker directory. I'll add this command to the guide. It appears that there is some issue with TestContainers example. The older example appears to work, so I'll revert it.

**Comment by abarberenaCPDS** [comment]
Excellent @craig-osterhout 🚀 ! thanks for getting back. I will ask my students to keep an eye of the content when it changes.

I am glad to 👀 that authors keep up with the content!
