### ISSUE TITLE
Missing upper letter on first word of sentence

### ISSUE THREAD

**Issue by MatiasMFM2001** [docker/docs#17520]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

There's a problem with the website

### Description

This sentence:
> **the** following command starts the `web` service and runs `bash` as its command:

Does not start with an uppercase `T`.

### Location

https://docs.docker.com/engine/reference/commandline/compose_run/#description

### Suggestion

This would be the fix:
```diff
- the following command starts the `web` service and runs `bash` as its command:
+ The following command starts the `web` service and runs `bash` as its command:
```

**Comment by aroramrinaal** [comment]
Hello @craig-osterhout , I have made the necessary change to address this issue. Please review PR #17555 .
