### ISSUE TITLE
[404]: /docker-hub/accounts-and-organizations/view-usage/

### ISSUE THREAD

**Issue by Hey1Ho** [docker/docs#17525]
### Location

bing.com/ai

### Broken link

https://docs.docker.com/docker-hub/accounts-and-organizations/view-usage/

**Comment by thaJeztah** [comment]
> bing.com/ai

I suspect this may be AI dreaming up URLs that don't exist. If you were looking for Docker Hub rate limits, you may be looking for this page; https://docs.docker.com/docker-hub/download-rate-limit/

What content were you looking for?

**Comment by craig-osterhout** [comment]
Closing as stale.
