### ISSUE TITLE
Docker RUN heredoc should be documented more

### ISSUE THREAD

**Issue by bneradt** [docker/docs#17559]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

I stumbled recently upon Dockerfile RUN heredoc functionality. It is wonderfully fantastic. I love doing this:

```
RUN <<EOF
  set -e
  wget https://github.com/Kitware/CMake/releases/download/v3.26.3/cmake-3.26.3-linux-aarch64.sh
  chmod +x cmake-3.26.3-linux-aarch64.sh
  bash ./cmake-3.26.3-linux-aarch64.sh --skip-license --prefix=/opt
  rm -f cmake-3.26.3-linux-aarch64.sh
EOF
```

Rather than:

```
RUN \
  wget https://github.com/Kitware/CMake/releases/download/v3.26.3/cmake-3.26.3-linux-aarch64.sh && \
  chmod +x cmake-3.26.3-linux-aarch64.sh && \
  bash ./cmake-3.26.3-linux-aarch64.sh --skip-license --prefix=/opt && \
  rm -f cmake-3.26.3-linux-aarch64.sh
```

It's a shame I never heard of this before. Notice that the reference doc for Dockerfile doesn't so much as refer to this feature:
https://docs.docker.com/engine/reference/builder/

### Location

https://docs.docker.com/engine/reference/builder/

### Suggestion

Please add a reference to Dockerfile heredoc support with an example here:
https://docs.docker.com/engine/reference/builder/

I suggest mentioning the following in the description:

* Briefly discuss how **variable expansion** works (both variables declared in the heredoc and ARG variables used inside of the heredoc...seems like both get expanded in place).
* Alert people to use `set -x` so that scripts with failures in their commands fail the build. This will almost certainly be what people expect.

**Comment by thaJeztah** [comment]
Thanks for opening this ticket! It looks like it's documented in a separate  "Here-Documents" section; https://docs.docker.com/engine/reference/builder/#here-documents

But that section may be hard to discover (unless you're specifically looking for it); perhaps it should be linked from the commands that support it. I must also admit that when using my browser's "search", I initially searched for "here doc" (with a space) and "heredoc" as keywords, which didn't help; perhaps we should somehow creatively mention those keywords in the section (something like "(Here documents, or "heredocs" for short)".

The `RUN` section mentions the "shell form" and "exec form", but doesn't mention Here documents as an alternative; the same applies to other commands that support this syntax (e.g. `COPY`)
https://docs.docker.com/engine/reference/builder/#run


/cc @jedevc

**Comment by jedevc** [comment]
cc @dvdksn, any chance you could help out with this?

**Comment by dvdksn** [comment]
Heredocs is my middle name

**Comment by daghack** [comment]
Looks like documentation around Heredoc was improved and relevant links added [here](https://github.com/moby/buildkit/commit/9c921c6322), so we can probably close this one now. :)

**Comment by bneradt** [comment]
Yes, this looks better. Thank you.
