### ISSUE TITLE
[404]: /desktop/install/windowsinstall/

### ISSUE THREAD

**Issue by LUUANHDUC** [docker/docs#17577]
### Location

https://github.com/

### Broken link

https://docs.docker.com/desktop/install/windowsinstall/#:~:text=Double%2Dclick%20Docker%20Desktop%20Installer,bottom%20of%20your%20web%20browser.

**Comment by aevesdocker** [comment]
Thanks for reporting the broken link. Please report this issue on the source page where the link is located.
