### ISSUE TITLE
[404]: /docker

### ISSUE THREAD

**Issue by chetugithub** [docker/docs#17582]
### Location

google

### Broken link

https://docs.docker.com/docker

### Comment

Is docker is free for use  or we can buy any subscription plan

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Google's index should automatically remove any 404 pages after a period of time. Closing this as it's a link on another site to a page that hasn't existed, at least not recently.

For information about pricing, please see https://docs.docker.com/subscription/details/ or https://www.docker.com/pricing/
