### ISSUE TITLE
Build Tutorial COPY go.mod go.sum . command yields an error

### ISSUE THREAD

**Issue by eewanco** [docker/docs#17602]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

In the **Update the instruction order** section of the _Build with Docker Introduction_, it requests you to add a `COPY go.mod go.sum .` command to the `Dockerfile` as an exercise. This yields the error:
```
~/src/buildme$ docker build --tag=buildme .
[...]
Step 3/8 : COPY go.mod go.sum .
When using COPY with more than one source file, the destination must be a directory and end with a /
```

### Location

https://docs.docker.com/build/guide/layers/#update-the-instruction-order

### Suggestion

The modified code, and the associated diagram, instead should read:
```
COPY go.mod go.sum ./
```

**Comment by aroramrinaal** [comment]
Can I solve this issue if it is already not taken by anyone?

**Comment by dvdksn** [comment]
Hi. It looks like you're using an older version of Docker Engine that uses the legacy builder. Recent versions of Docker (23.0 and later) use BuildKit by default. With BuildKit, the syntax in the guide works fine. Please update your Docker version, or set the environment variable `DOCKER_BUILDKIT=1` and try again.
