### ISSUE TITLE
content of Dockerfile to create differs form tutorial^in the getting-started repo

### ISSUE THREAD

**Issue by DerJungeMitDemHundVonMonika** [docker/docs#17613]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

In the documentation on this page the last line in the dockerfile to be created is: `EXPOSE 3000`
that line is missing in the docu tutorial started from the repo, see image:
![GettingStarted](https://github.com/docker/docs/assets/112170565/8bfaf991-8f2e-4b72-bc91-0ba35b654339)
I tried running the container with the `EXPOSE 3000` entry and the example app was not accessible by the browser via `localhost:3000`, without that entry everything works.

### Location

https://docs.docker.com/get-started/02_our_app/

### Suggestion

Remove the `EXPOSE 3000` entry in the documentation on this page.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. 
While the instructions in the getting-started repo are maintained, they're not updated as often as the documentation at https://docs.docker.com/get-started/02_our_app/. I highly recommend following the version in the documentation. 

For more details about `EXPOSE`, please see https://docs.docker.com/engine/reference/builder/#expose
The use of `EXPOSE` appears correct and should not affect the container whether it is there or not.
It's most likely something else causing the issue. One common problem is if you have another app or container already running on port 3000. 

For more help troubleshooting, please try the community Slack https://join.slack.com/t/dockercommunity/shared_invite/zt-1jz09gjit-P2NPysg99kiWExFfof0oBA
