### ISSUE TITLE
Change SSCM to SCCM

### ISSUE THREAD

**Issue by tharinda3** [docker/docs#17663]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Sub-bullet point 2 states "Deployment via SSCM to fail". 
SSCM in this point needs to be changed to SCCM.

### Location

https://6491622deac21100082e4ed3--docsdocker.netlify.app/desktop/wsl/best-practices/

**Comment by aroramrinaal** [comment]
@craig-osterhout , Can I work on this issue?
