### ISSUE TITLE
Running dev dependency mocha tests with production flag on?

### ISSUE THREAD

**Issue by jahmezz** [docker/docs#17673]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

I believe there is an issue with the current configuration making mocha "not available" when running

`docker compose -f docker-compose.dev.yml run notes npm run test`

Since mocha is a dev dependency, and the context of our compose build is a **production environment**, mocha will not be available when running this command.

I got this when running `docker compose -f docker-compose.dev.yml run notes npm run test`.

> > docker@1.0.0 test
> > mocha ./**/*.js
> 
> sh: mocha: not found

### Location

https://docs.docker.com/language/nodejs/run-tests/

### Suggestion

Two ways to fix...

1. Change mocha to a basic dependency.
2. Instruct to manually switch the flag to 'development' in the tutorial.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Fixed by https://github.com/docker/docs/pull/17659
