### ISSUE TITLE
Chrome on Windows required me to specify 127.0.0.1

### ISSUE THREAD

**Issue by jahmezz** [docker/docs#17674]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

I could not see the error listener to attach Chrome to... until I added `127.0.0.1:9229` to the list of hosts on the Chrome debugger.

This is specific to Windows, I believe.

### Location

https://docs.docker.com/language/nodejs/develop/

### Suggestion

Perhaps a Windows note would help save a bit of pain for the Windows peeps.

**Comment by dvdksn** [comment]
Will be fixed in #17659

**Comment by Nick-Damico** [comment]
I encountered the same issue this morning following that guide.

The only difference is that I'm not running Windows. I'm on Ubuntu 22.04
