### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by robbiegod** [docker/docs#17712]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

When I uninstall Docker Desktop, it is still leaving some information on the PC.

### Location

https://docs.docker.com/desktop/uninstall/

### Suggestion

I request that you add a new section to the uninstall page for users that want to remove everything related to Docker Desktop from the system.

I see the docker-users group stays in my user/groups settings even though I have uninstalled docker-desktop.

Can you offer some additional instructions to make it easier for users who want to completely remove so they can simply start over with a fresh install.

**Comment by aevesdocker** [comment]
Hi @robbiegod, thanks for raising the issue. Could you confirm if you're on Mac, Windows, or Linux, and what version of Docker Desktop you're using

**Comment by robbiegod** [comment]
I am on Windows 10 Pro.

Latest version of docker desktop as of today. I had just installed it to a new laptop, realized I messed up when installing it.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by aevesdocker** [comment]
Thanks for confirming that. 
It seems this is more of a product issue than a docs issues. Could you please report this in the[ Docker Desktop for Windows issue tracker. ](https://github.com/docker/for-win)
I'll also flag this internally as this is not intended behavior. 
Thank you again for raising the issue.
