### ISSUE TITLE
Wildcard use in "Create a Dockerfile for Node.js"

### ISSUE THREAD

**Issue by vpsx** [docker/docs#17725]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

In the COPY command

`COPY ["package.json", "package-lock.json*", "./"]`

surely if the wildcard is used, it should be used thus:

`COPY ["package*.json",  "./"]`

I found [this explanation](https://github.com/docker/docs/pull/12843/commits/3de4f9ddc98fd3bdb064551f7e7db42f14d1abfc#r643949444) from another pull request of why the asterisk is there, but it too suggests that the latter is correct.

### Location

https://docs.docker.com/language/nodejs/build-images/#create-a-dockerfile-for-nodejs

**Comment by vpsx** [comment]
Incidentally when reading the contributing guidelines [overview](https://docs.docker.com/contribute/overview/) I saw that
"Choose the right words for you content" should also have _your_ not _you_ :D

**Comment by thaJeztah** [comment]
> Incidentally when reading the contributing guidelines [overview](https://docs.docker.com/contribute/overview/) I saw that
> "Choose the right words for you content" should also have _your_ not _you_ :D

Nice catch; contributions welcome! 😅

**Comment by thaJeztah** [comment]
As to the issue itself, I think this may actually be an (undocumented) hack, where the wildcard triggers file-globbing for the source files, which I've seen people use to work around situations where a file may not exist (so if package-lock.json doesn't exist, the build doesn't fail).

I'm not sure if we should use that in our examples though, as I'm not even sure if it still works (and if it does, it may be using a bug / undocumented behavior as a "feature")

/cc @crazy-max @jedevc

**Comment by jedevc** [comment]
Heh, that's actually quite a neat hack :) (it does still seem to work)

However, agreed, it is super confusing, so if we want to keep the docs with this hack we should probably explain in the text what's going on.

But actually, I wonder how common this kind of scenario is - I can imagine wanting to do something similar for a `go.mod` in Go, for a project-generic Dockerfile. Maybe we might want some dedicated syntax or similar (that doesn't have the risk of actually matching other files in the project).

**Comment by vpsx** [comment]
Sorry for dropping this! Looks like Craig beat me to the typo :zany_face: :pray: 

Since the discussion has been around _whether or not_ to feature the globbing in the docs, I should probably clarify that my original question was: Given that right now it _is_ featured in the docs, isn't the asterisk in the wrong place? (It's `.json*` but should probably be `*.json`)

Either way, if it's helpful, here's some modified prose for that little section of the doc - one version for each option. If you guys would like me to make a PR for one or the other, or something else, just let me know. :grin: 

---

**Don't** feature globbing:

[...] We’ll copy the package.json and the package-lock.json file into our working directory /app.

`COPY ["package.json", "package-lock.json", "./"]`

Note that, rather than copying the entire working directory, we are only copying the package.json and package-lock.json files. [...]

---

**Do** feature globbing:

[...] We’ll copy the package.json, and the package-lock.json file if it exists, into our working directory /app.

`COPY ["package*.json", "./"]`

Note that, rather than copying the entire working directory, we are only copying the package.json and (optionally) package-lock.json files. [...]
