### ISSUE TITLE
Styling error / HighDPI problem

### ISSUE THREAD

**Issue by trysten** [docker/docs#17744]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

There's a problem with the website

### Description

Most or all of docs are broken on highDPI display with scaling in firefox. Same as #6060
![image](https://github.com/docker/docs/assets/4760903/61189a03-311e-48b4-8885-a3d3ac804f3a)

### Location

https://docs.docker.com/compose/compose-file/

### Suggestion

It has something to do with the sidebar exploding. I didn't comment until now because I wanted to find a solution first. But all I've found is a work around: scale page to 80% zoom and it displays ok
![image](https://github.com/docker/docs/assets/4760903/71e43e15-2ff1-43f4-96ab-8d7191c2d1f2)

**Comment by trysten** [comment]
1. Delete `.col-toc`
2. `.sidebar { width: unset; }`
![image](https://github.com/docker/docs/assets/4760903/1e3b0da5-461f-4332-be72-f5394f5650f1)

**Comment by dvdksn** [comment]
Hi. We've just updated the website. Can you please take a look and see if you're still seeing this issue @trysten ?

**Comment by trysten** [comment]
It appears to be fixed!! Excellent work @dvdksn and team.
