### ISSUE TITLE
Unclear how to use the secrets inside the container

### ISSUE THREAD

**Issue by kchawla-pi** [docker/docs#17768]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

For newbies, the how to mount secrets using Docker Compose is insufficiently explicit, increasing the need for trial and error to find the correct solution.

It does not clarify
-------------------
1. How the secret's text should be formatted. Should there be quotes, an env var variable name with a `=` or `:` symbol or only the text.
2. How to access the secret in the container.
. Must the secret's filename be same as secret name.

### Location

https://docs.docker.com/compose/use-secrets/

### Suggestion

I request the following be added
--------------------------------
1. An example secrets file including showing the content. For example `my_secret.txt` has `bhgby7y776tyfvblkg`, and not `my_secret=bhgby7y776tyfvblkg` or `my_secret="bhgby7y776tyfvblkg"`. It is useful to know the format one should store the secret in, instead of having to trial and error to the correct one.
2. It is not clear how one would access the secret in the docker container. It is at a file system path, so it would seem we must manually load it as environment variables. It would be helpful to have the details and examples for newbies.
3. Clarify whether the filename and secret name must be the same.

**Comment by securitypedant** [comment]
Also this issue leads to this problem, https://github.com/docker/docs/issues/17774
