### ISSUE TITLE
docker dev [OPTIONS] COMMAND

### ISSUE THREAD

**Issue by soloNic2** [docker/docs#17773]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

docker dev [OPTIONS] COMMAND

### Location

https://docs.docker.com/desktop/dev-environments/

### Suggestion

docker dev [OPTIONS] COMMAND

**Comment by neersighted** [comment]
It's unclear what this issue means/concerns; I'm going to close this, but please feel free to comment and clarify what issue you observed so we can re-open.
