### ISSUE TITLE
[404]: /engine/install/centos/%EF%BC%89

### ISSUE THREAD

**Issue by luomiluomi** [docker/docs#17839]
### Location

https://huaweicloud.csdn.net/63311a6ad3efff3090b521c8.html?spm=1001.2101.3001.6650.9&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromBaidu%7Eactivity-9-122193353-blog-127034331.235%5Ev38%5Epc_relevant_anti_t3&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromBaidu%7Eactivity-9-122193353-blog-127034331.235%5Ev38%5Epc_relevant_anti_t3&utm_relevant_index=10

### Broken link

https://docs.docker.com/engine/install/centos/%EF%BC%89

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. It looks like the source blog may have added some additional characters to the URL or they were accidently copied during copy-paste. If the issues is on the blog page, please contact the blog owner to resolve the issue.
The page you're probably looking for is https://docs.docker.com/engine/install/centos/
