### ISSUE TITLE
Get Started -> Persist the DB -> See this in practice -> Step 2 : Sample code not working

### ISSUE THREAD

**Issue by chris904apps** [docker/docs#17841]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

When I used the given code:
`docker exec <container-id> cat /data.txt`

 the file could not be found. Added a '.' to the beginning and value came up as expected.

![image](https://github.com/docker/docs/assets/19228678/d8feb0b0-b1dc-48af-9117-0c1bca2287a9)

### Location

https://docs.docker.com/get-started/05_persisting_data/#see-this-in-practice

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. 
If you're using git bash, please see https://docs.docker.com/desktop/troubleshoot/topics/#working-with-git-bash

Otherwise, please run the command using Windows Command Prompt or Powershell.
