### ISSUE TITLE
"What is the difference between Docker Desktop for Linux and Docker Engine" just explains Docker Desktop

### ISSUE THREAD

**Issue by lfrommelt** [docker/docs#17847]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

I would like to learn the difference between Docker Desktop (Linux) and Docker Engine. The respective doc page does a great job in explaining the details of Docker Desktop. However, these details are not put into context to Docker Engine. As a docker beginner, I find it hard get the relevant information from the Docker Engine pages.

### Location

https://docs.docker.com/desktop/faqs/linuxfaqs/

**Comment by cannarron** [comment]
Hi, is this open to external contributions? cc @craig-osterhout
