### ISSUE TITLE
Problem with 

### ISSUE THREAD

**Issue by CunningLobster** [docker/docs#17873]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

When I was trying to build the image I got an error. Briefly it said that I must specify a .csproj file to publish 

### Location

https://docs.docker.com/language/dotnet/build-images/

### Suggestion

I redesigned my Dockerfile and everything works good:
Before:
`RUN dotnet publish -c Release -o /publish`

After:
```
# Next, you’ll need to run the dotnet publish command to build the project.
WORKDIR "/src"
RUN dotnet publish "myWebApp.csproj" -c Release -o /publish
```

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
I'm unable to reproduce the error.
Can you share the complete build output with the error?

**Comment by craig-osterhout** [comment]
Closing as stale.
