### ISSUE TITLE
use the preferred filename in examples

### ISSUE THREAD

**Issue by AvdN** [docker/docs#17888]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

The preferred filename for file containing the docker compose YAML document is `compose.yaml` ( https://docs.docker.com/compose/compose-file/03-compose-file/ ). The documentation should use the preferred filename over the use of `docker-compose.yml`

Also note that there is a [YML](https://fdik.org/yml/) format which is XML based, and that the [officially recommended extension](https://yaml.org/faq.html) for files containing YAML documents has been `.yaml` since at least September 2006. So unless you are running VMS or MS-DOS there is probably no excuse to use `.yml` as an extension for files containing YAML documents at all.

### Location

https://docs.docker.com/compose/gettingstarted/

**Comment by aevesdocker** [comment]
Thanks @AvdN. Closing issue as this has now been fixed
