### ISSUE TITLE
The commands to create the img doesn't work like that anymore

### ISSUE THREAD

**Issue by CCHunter90** [docker/docs#17918]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The way the command build works is not like that anymore

### Location

https://docs.docker.com/language/python/build-images/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
If you received an error, please share the output.
If believe the command is not correct, please share more details about why.

**Comment by craig-osterhout** [comment]
Closing as stale. If the issue still persists, please provide more details.
