### ISSUE TITLE
Codeblock formatting on Diagnostics page

### ISSUE THREAD

**Issue by carterhimmel** [docker/docs#17931]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

There's a problem with the website

### Description

Howdy! The codeblocks for a section of the diag overview page doesn't display correctly. I'd try and fix it myself but I haven't the first clue to test before pr :p
![image](https://github.com/docker/docs/assets/45381083/0b01c304-eeb9-4910-b89b-ca196fbd0138)
![image](https://github.com/docker/docs/assets/45381083/97fb7e78-1fdb-4ad8-8f4b-81bc51cecb1b)

https://github.com/docker/docs/blob/7d0d57e52b4cf961a84ca2f14cc578cd545d8c76/desktop/troubleshoot/overview.md?plain=1#L150-L166

### Location

https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal

**Comment by aevesdocker** [comment]
Thanks for raising the issue @carterhimmel! This has now been fixed
