### ISSUE TITLE
Compose file version 3 reference is missing the "cgroup" key

### ISSUE THREAD

**Issue by aki-k** [docker/docs#17933]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

The following is missing from the compose reference:

https://docs.docker.com/compose/compose-file/05-services/#cgroup

cgroup

cgroup specifies the cgroup namespace to join. When unset, it is the container runtime’s decision to select which cgroup namespace to use, if supported.

    host: Runs the container in the Container runtime cgroup namespace.
    private: Runs the container in its own private cgroup namespace.

### Location

https://docs.docker.com/compose/compose-file/compose-file-v3/

**Comment by aevesdocker** [comment]
Hi @aki-k, Compose file version 3 is legacy content so does not need to be updated.
