### ISSUE TITLE
HealthCheck Retries=0

### ISSUE THREAD

**Issue by jinek** [docker/docs#17942]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

It's not clear what retries set to zero does. There was an issue about this https://github.com/docker/docs/issues/10929 but it was closed automatically. 

### Location

https://github.com/docker/docs/issues/10929

### Suggestion

I'm proposing to re-open original issue and close this one.

**Comment by dvdksn** [comment]
Thanks, re-opening the original issue.
