### ISSUE TITLE
Slack notifications documentation is misleading 

### ISSUE THREAD

**Issue by borisovano** [docker/docs#17966]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The documentation page describing how to set slack notifications is wrong.

Link: https://dockerdocs.cn/docker-hub/slack_integration/#:~:text=Set%20up%20a%20Slack%20integration&text=Click%20Account%20Settings%20in%20the,to%20the%20correct%20Slack%20team.

**There is no slack option on notifications menu**

![image](https://github.com/docker/docs/assets/10387151/643c782b-c435-4d1f-8ec0-792abe9b8026)

### Location

https://dockerdocs.cn/docker-hub/slack_integration/#:~:text=Set%20up%20a%20Slack%20integration&text=Click%20Account%20Settings%20in%20the,to%20the%20correct%20Slack%20team.

### Suggestion

Make sure your documentations matches reality.

**Comment by aevesdocker** [comment]
Thanks for opening the issue @borisovano. The link you provided is to an un-official Docker docs site that has out-of-date/incorrect information. Docker Hub does not provide a Slack integration
