### ISSUE TITLE
[404]: /get-started/docker_cheatsheet.pdf

### ISSUE THREAD

**Issue by AbdulQadoos-01** [docker/docs#17994]
### Location

https://www.google.com/

### Broken link

https://docs.docker.com/get-started/docker_cheatsheet.pdf

**Comment by dvdksn** [comment]
Thanks for reporting the broken link. Please report this issue on the source page where the link is located.

**Comment by dvdksn** [comment]
Sorry - I was wrong. The location of the file has changed. I've raised a pull request to fix this. Thanks for reporting.
