### ISSUE TITLE
Check your installing information

### ISSUE THREAD

**Issue by lbugnon** [docker/docs#18031]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

trixie Release throws a 404 error.

### Location

https://docs.docker.com/engine/install/debian/

### Suggestion

 Worked with bookworm Release

**Comment by nilsjha** [comment]
Still missing and throws a 404 from the repository unfortunately:  https://download.docker.com/linux/debian/dists/

Hope this can be addressed soon, as trixie has been moved into testing.
