### ISSUE TITLE
The Debian, RPM and Arch download links on release page all point to Deb file

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [docker/docs#18045]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The download links for Arch, Debian and RPM on the [release page](https://docs.docker.com/desktop/release-notes/) all point to a Deb file. I have checked a few of the most recent ones and they all seem to have this problem.

### Location

https://docs.docker.com/desktop/release-notes/

### Suggestion

Point to the correct downloads

**Comment by aevesdocker** [comment]
Thanks for catching this @TeaDrinkingProgrammer, this has now been fixed
