### ISSUE TITLE
Broken links on files

### ISSUE THREAD

**Issue by SychevIgor** [docker/docs#18052]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

There's a problem with the website

### Description

There are a lot of issues with links. 
1- links referencing master branch, but redirecting to main. it's not a problem, but still - it's better to avoid this redirect.
2- links on documents don't include "content" in the url/path. as a result - if I would like to open a link - I will recieve 404 code 
![image](https://github.com/docker/docs/assets/578954/c23092ed-5645-442f-9fc0-da740622cf4d)
![image](https://github.com/docker/docs/assets/578954/d65208a4-b074-42cc-933c-a7f2c341a57d)

Could you modify documentation to make navigation on published pages smooth without 404 codes. 

### Location

https://docs.docker.com/registry/configuration/

**Comment by Standard-IO** [comment]
I was reading the same section and I wanted to update these links by myself but I cannot find the whole `configuration.md` file in the `docs/tree/main/content/registry/` path.

**Comment by dvdksn** [comment]
The registry docs have moved to [distribution.github.io/distribution](https://distribution.github.io/distribution/)
