### ISSUE TITLE
Diagrams don't support dark mode

### ISSUE THREAD

**Issue by crazy-max** [docker/docs#18149]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

There's a problem with the website

### Description

Switching from svg to png looks like a regression to me in https://github.com/docker/docs/pull/18079. Does not render well in dark mode like:

![image](https://github.com/docker/docs/assets/1951866/0211fa60-49fd-4363-8469-b5d6119e16ce)

Before: https://docs-labs.docker.com/admin/

![image](https://github.com/docker/docs/assets/1951866/f9d6859c-0915-4174-a870-6cbcdc2df24d)

### Location

https://docs.docker.com/admin/

### Suggestion

Bring back SVG

**Comment by aevesdocker** [comment]
Thanks @crazy-max. In an effort to standardize the look and feel of diagrams across all of docs, I concede this is a slight regression. We do have it as a task in our backlog to make screenshots and diagrams work in both light and dark mode, and to also reduce the size of the images (David suggested converting to `webp`). Hopefully will get to this soon

**Comment by crazy-max** [comment]
Yes `webp` is also good
