### ISSUE TITLE
Link to the registry mirror md recipe/example file is broken

### ISSUE THREAD

**Issue by Renlor** [docker/docs#18172]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The link to the mirror.md doc is broken it points to `https://github.com/docker/docker.github.io/tree/master/registry/recipes/mirror.md` and the file has been moved to `https://github.com/docker/docs/tree/main/content/registry/recipes/mirror.md`

### Location

https://docs.docker.com/registry/configuration/

**Comment by dvdksn** [comment]
The registry docs have moved to [distribution.github.io/distribution](https://distribution.github.io/distribution/)
