### ISSUE TITLE
[404]: /opensource/project/who-written-for/

### ISSUE THREAD

**Issue by minshaf998** [docker/docs#18196]
### Location

In CONTRIBUTING.md file

### Broken link

https://docs.docker.com/opensource/project/who-written-for/

```[tasklist]
### Tasks
```

**Comment by minshaf998** [comment]
Found this link from contributing.md file on docker-cli cloned from here.
master branch

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as duplicate of https://github.com/docker/cli/issues/4036
