### ISSUE TITLE
[404]: /compose/install-linux/

### ISSUE THREAD

**Issue by kushalsubedi** [docker/docs#18194]
### Location

https://docs.docker.com/compose/install-linux/

### Broken link

https://docs.docker.com/compose/install-linux/

### Comment

docker-compose page is not loading

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. 
On what page did you find that broken link?

**Comment by aevesdocker** [comment]
There isn't any more information for us to take action on. I'm closing the issue here for that reason. Feel free to add more information to continue the conversation.
