### ISSUE TITLE
Link not rendered

### ISSUE THREAD

**Issue by crazy-max** [docker/docs#18214]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

There's a problem with the website

### Description

![image](https://github.com/docker/docs/assets/1951866/15de5025-58f1-44e3-a27e-159fd2108d0b)

### Location

https://docs.docker.com/build/attestations/sbom/#sbom-generator

### Suggestion

Could we have a way to detect and validate this? cc @dvdksn

**Comment by thaJeztah** [comment]
Is the source invalid on that one? Looks like a malformed markdown link

**Comment by dvdksn** [comment]
Source is technically valid, but broken. The [link] syntax lets you define a link later, in a different place from where it was used. By doing this:

```
Here's my paragraph with a [link] defined somewhere else.

[link]: www.example.com
```

**Comment by dvdksn** [comment]
@crazy-max they literally released a new option for markdownlint to check for broken `[link]` references a few days ago, so very good timing to ask for a lint rule on this. bumped the markdownlint version and enabled the rule in the PR: #18216

**Comment by thaJeztah** [comment]
That's great timing!
