### ISSUE TITLE
Sample configuration file specified for docker client configs is ill-formed

### ISSUE THREAD

**Issue by 13steinj** [docker/docs#18236]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

This currently shows

```
{% raw %}
{
  "HttpHeaders": {
    "MyHeader": "MyValue"
  },
  "psFormat": "table {{.ID}}\\t{{.Image}}\\t{{.Command}}\\t{{.Labels}}",
  "imagesFormat": "table {{.ID}}\\t{{.Repository}}\\t{{.Tag}}\\t{{.CreatedAt}}",
  "pluginsFormat": "table {{.ID}}\t{{.Name}}\t{{.Enabled}}",
  "statsFormat": "table {{.Container}}\t{{.CPUPerc}}\t{{.MemUsage}}",
  "servicesFormat": "table {{.ID}}\t{{.Name}}\t{{.Mode}}",
  "secretFormat": "table {{.ID}}\t{{.Name}}\t{{.CreatedAt}}\t{{.UpdatedAt}}",
  "configFormat": "table {{.ID}}\t{{.Name}}\t{{.CreatedAt}}\t{{.UpdatedAt}}",
  "serviceInspectFormat": "pretty",
  "nodesFormat": "table {{.ID}}\t{{.Hostname}}\t{{.Availability}}",
  "detachKeys": "ctrl-e,e",
  "credsStore": "secretservice",
  "credHelpers": {
    "awesomereg.example.org": "hip-star",
    "unicorn.example.com": "vcbait"
  },
  "plugins": {
    "plugin1": {
      "option": "value"
    },
    "plugin2": {
      "anotheroption": "anothervalue",
      "athirdoption": "athirdvalue"
    }
  },
  "proxies": {
    "default": {
      "httpProxy":  "http://user:pass@example.com:3128",
      "httpsProxy": "https://my-proxy.example.com:3129",
      "noProxy":    "intra.mycorp.example.com",
      "ftpProxy":   "http://user:pass@example.com:3128",
      "allProxy":   "socks://example.com:1234"
    },
    "https://manager1.mycorp.example.com:2377": {
      "httpProxy":  "http://user:pass@example.com:3128",
      "httpsProxy": "https://my-proxy.example.com:3129"
    }
  }
}
{% endraw %}
```

I would imagine that the `{% raw %}` is a mistake (or a bug in the generator), as I don't believe `~/.docker/config.json` supports golang text/template. Or at least, I couldn't get it to work.

### Location

https://docs.docker.com/engine/reference/commandline/cli/#sample-configuration-file

### Suggestion

Correct the example snippet / get the "raw" section to render correctly

**Comment by 13steinj** [comment]
Err, apparrently https://github.com/docker/docs/blob/main/_vendor/github.com/docker/cli/docs/reference/commandline/cli.md aka https://github.com/docker/cli/blob/master/docs/reference/commandline/cli.md ?

I'm not familiar with the doc generation system to know what I should be changing there.

**Comment by thaJeztah** [comment]
Thanks for reporting; these `{% raw %} / {% undraw %}` tags were leftovers from when we used Jekyll for generating our docs. They're no longer needed now that we switched to using Hugo, so I opened a PR to remove them;


- https://github.com/docker/cli/pull/4682
- https://github.com/docker/cli/pull/4681
