### ISSUE TITLE
Registry - Configuration of hooks

### ISSUE THREAD

**Issue by nkaaf** [docker/docs#18249]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

In the "List of configuration options" example configuration there is an indentation error, in my opinion.

### Location

https://docs.docker.com/registry/configuration/

### Suggestion

The "hooks" section should not be a child of "log", as far as I understand it.

**Comment by dvdksn** [comment]
The registry docs have moved to [distribution.github.io/distribution](https://distribution.github.io/distribution/)
