### ISSUE TITLE
Commands changes for installing Docker Desktop on Windows via windows terminal.

### ISSUE THREAD

**Issue by ThomasRiddle** [docker/docs#18264]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

I am using the Windows terminal to install Docker Desktop on another disk. After I copied the command and arguments from the website, the Windows terminal gave me an error: "Start-Process: Unable to check the parameter “ArgumentList”, which is Null or empty. Please provide a not Null or non-empty parameter, then try this command again. Position: line 1, character 10."
![wrong](https://github.com/docker/docs/assets/25854424/ff50c54c-cb29-4347-be83-c249bcf9f56f)
Later, I checked the document of the Windows Terminal on its [official website](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-7.3) and try the following command:
```sh
start "Docker Desktop Installer.exe" -ArgumentList "install --installation-dir=D:\Docker"
```
This one works.
![correct](https://github.com/docker/docs/assets/25854424/c625142a-27a7-4a21-a88d-4fafc62e2895)

### Location

https://docs.docker.com/desktop/install/windows-install/

**Comment by aevesdocker** [comment]
Hi @ThomasRiddle, thanks for raising the issue. We've tested the documentation and it is correct. From your screenshot it looks like you pasted in the command for the Windows Command Prompt, but you're using PowerShell. Running 'Start-Process 'Docker Desktop Installer.exe' -Wait install' should work
