### ISSUE TITLE
Show the location of the Resource Saver feature

### ISSUE THREAD

**Issue by jdstanhope** [docker/docs#18267]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

I am not able to find the Resource Saver feature mentioned in the page. It would be good to have a clear indication of where to find the feature or how to enable it through a CLI.

### Location

https://docs.docker.com/desktop/use-desktop/pause/

**Comment by aevesdocker** [comment]
Hi @jdstanhope, with the new release of Docker Desktop, you should be able to find it in in the Resources>advanced settings page https://docs.docker.com/desktop/use-desktop/resource-saver/
