### ISSUE TITLE
Clicking the link to DEB package downloads the amd64 version (I have x86_64 architecture).

### ISSUE THREAD

**Issue by GeorgeBatch** [docker/docs#18263]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Clicking the link to DEB package downloads the amd64 version (I have x86_64 architecture). After downloading, there is no option to install with the system installer, only to check with the archive manager. I think that's because the version downloaded is not installable.

### Location

https://docs.docker.com/desktop/install/ubuntu/

### Suggestion

Provide different links for downloading amd64 and x86_64 versions of the DEB package.

**Comment by GeorgeBatch** [comment]
Hi @aevesdocker, Thank you very much! It makes more sense now. After downloading docker DEB but before running these commands, do I need to run some install script?
```shell
sudo apt-get update
sudo apt-get install ./docker-desktop-<version>-<arch>.deb
```

Or do I just need to be in a directory where I downloaded the DEB package and the installation will be done by the second line? `sudo apt-get install ./docker-desktop-<version>-<arch>.deb`

**Comment by aevesdocker** [comment]
Yes, if you've followed step 1 `Set up Docker's package repository. See [Install using the Apt repository, step 1](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository).`, then the installation will be done by the second line `sudo apt-get install ./docker-desktop-<version>-<arch>.deb`

**Comment by GeorgeBatch** [comment]
Somehow, it worked today, and I was doing the same things I did before. Thank you for your help!

**Comment by aevesdocker** [comment]
No worries, glad you got it working!
