### ISSUE TITLE
Following the instructions on deleting containers and starting it again don't persist the data as expected by the documentation

### ISSUE THREAD

**Issue by abderrahmen-hadjadj-aoul** [docker/docs#18261]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The following part of the documentation does not match the result I get when executing instructions:

> In the terminal, run docker compose rm to remove your containers and then run docker compose up to run your application again.
> 
> ```
> $ docker compose rm
> $ docker compose up --build
> ```
> 
> Refresh [http://localhost:3000open_in_new](http://localhost:3000/) in your browser and verify that the todo items persisted, even after the containers were removed and ran again.

The documentation says that running the code above will still persist data.

But when I run it on my machine, the data is erased.

I can see that as the todo list is empty.

But if I stop (Ctrl-C) and start again (docker compose up) then the data persist.

**Version**

```
$ docker -v
Docker version 24.0.6, build ed223bc
```

### Location

https://docs.docker.com/language/nodejs/develop/

### Suggestion

Update the documentation or explain why this is happening.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.

Can you share the initial logs you see after running `docker compose up --build` and the contents of your `compose.yaml` file?

**Comment by abderrahmen-hadjadj-aoul** [comment]
Hello, I tried to reproduce the issue to give you a repository you could try.
But it seems to work like said in the documentation now.
Maybe I switched the docker version during the tutorial.
The fault is on my side.

I am closing the issue.
