### ISSUE TITLE
[404]: /opensource/project/software-required/

### ISSUE THREAD

**Issue by Aniketraj19** [docker/docs#18327]
### Location

https://gdevillele.github.io/opensource/code/#/quickstart-code-or-doc-contribution

### Broken link

https://docs.docker.com/opensource/project/software-required/

### Comment

I think that this link is pointing towards the wrong page as it should point towards the installation page of the essential software.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. 
The official documentation is at http://docs.docker.com
The source location in your issue that linked to the Docker site is not official and is very outdated. You'll need to contact the owner of that site to resolve any issues.

If you'd like to contribute to Docker docs, please see https://docs.docker.com/contribute/overview/
