### ISSUE TITLE
autoMemoryReclaim=true

### ISSUE THREAD

**Issue by mverdicchio** [docker/docs#18329]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

It appears this key is a string type, not boolean, with options of gradual or dropcache.

[info](https://devblogs.microsoft.com/commandline/windows-subsystem-for-linux-september-2023-update/)

adding what you suggest to .wslconfig generates an unknown key error when restarting terminal.

### Location

https://docs.docker.com/desktop/wsl/

**Comment by ctalledo** [comment]
Thanks @mverdicchio for noticing and filing the issue. Looks like the way WSL autoMemoryReclaim is configured has changed recently (used to be a boolean, now it's a string), so we will update the Docker Desktop docs accordingly.

PR: https://github.com/docker/docs/pull/18343
