### ISSUE TITLE
Doc-site-feedback image is missing

### ISSUE THREAD

**Issue by geoffreylgv** [docker/docs#18337]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

In the PR #18059, the doc-site-feedback has been removed and the README isn't updated.
![image](https://github.com/docker/docs/assets/52314615/e08aff92-b88f-4afb-94dd-df566e58cd9f)

### Location

https://github.com/docker/docs/blob/main/README.md

### Suggestion

Update the README by adding the correct image

**Comment by aevesdocker** [comment]
Thanks for raising the issue @geoffreylgv, this has now been fixed

**Comment by geoffreylgv** [comment]
> Thanks for raising the issue @geoffreylgv, this has now been fixed

Pleasure is mine. Thank you for the great work @aevesdocker !
