### ISSUE TITLE
wrong path for repodata on RHEL 9

### ISSUE THREAD

**Issue by MGdevSecure4now** [docker/docs#18353]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

While the directions may be correct, the docker-ce-stable repository is not setup correctly.  It references ..."rehel/9.x86_64/stable/repodata/repomd.xml" and fails, when instead it appears that it should reference "rehel/9/source/stable/repodata/repomd.xml", which is where the file is actually currently located.  Can you fix this issue please?  Unsure if there are any other path issues or not, but this is where it currently fails. 

### Location

https://docs.docker.com/engine/install/rhel/

### Suggestion

Correct the path to either match the current location, or change the location to match the path.

**Comment by thaJeztah** [comment]
It looks like you're trying to follow those instructions on an x86 machine, but we currently only provide RHEL packages for s390x; see the note at the top of that page;

> Note
>
> We currently only provide packages for RHEL on s390x (IBM Z). Other architectures are not yet supported for RHEL, but you may be able to install the CentOS packages on RHEL. Refer to the [Install Docker Engine on CentOS](https://docs.docker.com/engine/install/centos/) page for details.

**Comment by MGdevSecure4now** [comment]
Okay, thank you.  I'll give that a shot.

**Comment by neersighted** [comment]
Closing as this is not a docs issue/is as documented.
