### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by valentinasso** [docker/docs#18364]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Link in this sentence is 404 

The centos-extras repository must be enabled. This repository is enabled by default, but if you have disabled it, you need to re-enable it.

https://wiki.centos.org/AdditionalResources/Repositories

### Location

https://docs.docker.com/engine/install/centos/

### Suggestion

change to working link

**Comment by stephaurelio** [comment]
Thank you for filing this issue! We took a look at the broken link using the wayback machine and it didn't include steps on how to do this, so we removed it in #18464
