### ISSUE TITLE
https://docs.docker.com/language/python/build-images/

### ISSUE THREAD

**Issue by Dorado811** [docker/docs#18374]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

There's a problem with the website

### Description

The command shown: 
C:\Docker\Repository SourceCode\.venv>python -m pip install -r requirementts.txt

Does not work because there is no requirements.txt file. 
No explanation of the command provided. In fact, most of the commands are not explained at all.

Regards,
GA Hernandez.

### Location

https://docs.docker.com/language/python/build-images/

### Suggestion

Please, fix the issue as right now the information can't be  used as it is.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
The command you provided appears to have an extra `t` in `requirementts.txt`.

If the typo did not cause the issue, please share the output of `dir` to list the directory contents and the commands you ran along with the error you received.

**Comment by craig-osterhout** [comment]
Closing. If the issue still persists, please help share more details.
