### ISSUE TITLE
The image is not updated with the command that you provided

### ISSUE THREAD

**Issue by saikrishna1488** [docker/docs#18453]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

I follow the same process and got this error "docker: Error response from daemon: driver failed programming external connectivity on endpoint laughing_burnell 
(bb242b2ca4d67eba76e79474fb36bb5125708ebdabd7f45c8eaf16caaabde9dd): Bind for 127.0.0.1:3000 failed: port is already allocated." also but when i stopped the old conatiner, removed it and created new once i am getting the same old container with old image only the image is not updating.

### Location

https://docs.docker.com/get-started/03_updating_app/

### Suggestion

No idea need support from community

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
One thing to double check:
- When you update the `src/static/js/app.js` file, make sure you save the changes. This is a common thing to overlook and not explicit in the directions.
- After saving the changes, run the build command (`docker build -t getting-started .`) and then continue with the rest of the steps.

If you need more help troubleshooting, please try the community Slack at https://join.slack.com/t/dockercommunity/shared_invite/zt-1jz09gjit-P2NPysg99kiWExFfof0oBA
