### ISSUE TITLE
[404]: /language/python/run-containers/

### ISSUE THREAD

**Issue by benjnicholls** [docker/docs#18467]
### Location

https://docs.docker.com/language/python/build-images/

### Broken link

https://docs.docker.com/language/python/run-containers/

### Comment

I'm running on Google Chrome Version 118.0.5993.88 64-bit.
Tried to reach the above page for docker tutorial for python. Gave me a 404 error.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
The guide was just updated and the build & run topics are now merged into https://docs.docker.com/language/python/containerize/

The redirects appear to be broken. We'll get them fixed.

**Comment by benjnicholls** [comment]
Awesome! That was ridiculously fast.
