### ISSUE TITLE
Link to the WSL 2 instructions from the Docker install Page

### ISSUE THREAD

**Issue by pearcej** [docker/docs#18496]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The page is incomplete for those using WSL2 in Windows. I recommend linking to https://docs.docker.com/desktop/wsl/ in the section on docker for Windows.

### Location

https://docs.docker.com/get-docker/

### Suggestion

Link to https://docs.docker.com/desktop/wsl/ in the section on docker for Windows.

**Comment by aevesdocker** [comment]
Hi @pearcej, thank for opening an issue in our repo. There are plans to revamp this entire page soon so we've made a note of your suggestion.
