### ISSUE TITLE
Docs about deprecated "extends" feature leading to confusion

### ISSUE THREAD

**Issue by David-Lor** [docker/docs#18494]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Searching about the `extends` option from Docker Compose, this page can be found: https://docs.docker.com/compose/multiple-compose-files/extends/

However, I cannot see nowhere in that page that this feature was deprecated in version 3, as it's said here: https://docs.docker.com/compose/compose-file/compose-versioning/#version-3

On this last link it's included a text which says: "For more information on extends, see [Extending services](https://docs.docker.com/compose/multiple-compose-files/extends/)". The link on Extending services redirects back to the "extends" page (https://docs.docker.com/compose/multiple-compose-files/extends/), which is supposedly deprecated. The same problem is present in https://docs.docker.com/compose/compose-file/compose-versioning/#upgrading

### Location

https://docs.docker.com/compose/compose-file/compose-versioning/

### Suggestion

1. Fix or remove the links to the proposed alternatives to `extends` in Compose v3. As it is redirecting to the page https://docs.docker.com/compose/multiple-compose-files/extends which is showing the deprecated feature, I guess there's currently no alternative to it?
2. Add a deprecation warning or the maximum supported version to the `extends` page (https://docs.docker.com/compose/multiple-compose-files/extends/)

**Comment by aevesdocker** [comment]
Hi @David-Lor, thanks for opening an issue in the docs repo. 
I've removed the link to the extends page. 
However, please note that extends is no longer deprecated and Compose v3 is now a legacy feature and no longer supported (also why the content is no longer actively maintained). 
The Compose Specification, which is the merging of Compose v3 and Compose v2 is the latest file format that all Compose users should be using.

**Comment by David-Lor** [comment]
Hello @aevesdocker
Thanks for the clarification, I wasn't aware of the new Compose spec :smile_cat: 

Regards!
