### ISSUE TITLE
Incorrect System Requirements (Ambiguity)

### ISSUE THREAD

**Issue by T-Bax** [docker/docs#18502]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

[https://docs.docker.com/desktop/install/windows-install/](url)

This page specifies that the requirements to install on windows are Windows 21h2 (Build 19045).  Build 19045 is actually Windows 22H2.  It is therefore unclear which Windows version is required

### Location

https://docs.docker.com/desktop/install/windows-install/

### Suggestion

I recommend clarifying which version is required by either changing 21H2 to 22H2, or changing the build number to 19044

**Comment by aevesdocker** [comment]
Thanks for catching this @T-Bax!
