### ISSUE TITLE
Wrong Grammar

### ISSUE THREAD

**Issue by MarkowEduard** [docker/docs#18503]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

grammar is wrong

### Location

https://docs.docker.com/storage/volumes/

### Suggestion

Volume drivers let you store volumes on remote hosts or cloud providers, to encrypt the contents of volumes, or to add other functionality.

should read

Volume drivers let you store volumes on remote hosts or cloud providers, encrypt the contents of volumes, or add other functionality.

**Comment by Yachika9925** [comment]
@dvdksn pls review it and merge it
