### ISSUE TITLE
Update "Build your Go image" tutorial to use supported Go version

### ISSUE THREAD

**Issue by rafvasq** [docker/docs#18520]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The `Build Images` for Go tutorial uses a no-longer-supported version (1.19) and should be updated to reflect supported versions (1.20+). 

### Location

https://docs.docker.com/language/golang/build-images/

### Suggestion

Update the example to use supported version(s) of Go. Also happy to help contribute the changes myself!

**Comment by Yachika9925** [comment]
@rafvasq @rafvasq pls review it and merge
