### ISSUE TITLE
Docker Compose Watch `sync+restart` option doesn't work

### ISSUE THREAD

**Issue by thiskevinwang** [docker/docs#18522]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The docs say `sync+restart` is a valid action.
- https://docs.docker.com/compose/file-watch/#sync--restart

And the compose spec contains this as well
- https://github.com/compose-spec/compose-spec/blob/3e18a23ba8b53f8e67fb3f9e7d16f981d44ddd5f/schema/compose-spec.json#L478

Which is detected by my IDE intellisense:
- ![CleanShot 2023-10-26 at 01 24 14@2x](https://github.com/docker/docs/assets/26389321/842ef3b8-6e8a-4b4d-89d2-4254b90dfa16)

❌ But running `docker compose watch` returns:

```console
❯ docker compose watch    
validating /Users/kevin/repos/go-task-queue/docker-compose.yml: services.web.develop.watch.0.action services.web.develop.watch.0.action must be one of the following: "rebuild", "sync"
```

---

Docker version:

```console
❯ docker version          
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.24.2 (124339)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Location

https://docs.docker.com/compose/file-watch/

**Comment by thiskevinwang** [comment]
Related issues:
- https://github.com/compose-spec/compose-spec/pull/423
- https://github.com/docker/compose/issues/11062

**Comment by aevesdocker** [comment]
Hi @thiskevinwang, it was released in the Compose plugin, but has not reached Docker Desktop yet. New version of Docker Desktop is due to be released very soon

**Comment by thiskevinwang** [comment]
@aevesdocker oh good to hear! Thanks 😄 

Ok, for posterity & other readers, I got this working via https://formulae.brew.sh/formula/docker-compose, for mac.

```console
❯ brew install docker-compose
==> Caveats
Compose is now a Docker plugin. For Docker to find this plugin, symlink it:
  mkdir -p ~/.docker/cli-plugins
  ln -sfn /opt/homebrew/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose

❯ mkdir -p ~/.docker/cli-plugins
❯ ln -sfn /opt/homebrew/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose

❯ docker compose version
Docker Compose version 2.23.0
```
