### ISSUE TITLE
integrating with vs code

### ISSUE THREAD

**Issue by goodwillhunting9** [docker/docs#18544]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

can't integrate docker in my vs code, please check!

### Location

https://docs.docker.com/desktop/kubernetes/

### Suggestion

please check integration between docker and vs code branches

**Comment by aevesdocker** [comment]
Closing issue as the Kubernetes page makes no reference to VS Code, so there is nothing to take action on
