### ISSUE TITLE
Final compose.yaml not correct

### ISSUE THREAD

**Issue by ldebernardo** [docker/docs#18547]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

In the final version of the compose.yaml the mysql service port configuration is missing.
For the app working properly the following configuration is needed.

### Location

https://docs.docker.com/get-started/08_using_compose/

### Suggestion

Add the port configuration at the mysql service:

...
...
>   mysql:
    image: mysql:8.0
    **ports:
      - 0.0.0.0:3306:3306**
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
...
...

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. If you received and error message, please share more details.
It's not necessary to expose the database port to the host. The app container is able to access the db as they're running on the same network.
To learn more about networking in Docker, please see the previous part, https://docs.docker.com/get-started/07_multi_container/ or deep dive in https://docs.docker.com/network/ & https://docs.docker.com/compose/networking/

If the app is not working, please try the community slack for help troubleshooting. https://join.slack.com/t/dockercommunity/shared_invite/zt-1jz09gjit-P2NPysg99kiWExFfof0oBA
