### ISSUE TITLE
[404]: /desktop/win/configuring-wsl

### ISSUE THREAD

**Issue by ShemTovYosef** [docker/docs#18549]
### Location

Docker Desktop UI

### Broken link

https://docs.docker.com/desktop/win/configuring-wsl?uuid=1FE76255-2100-47E0-8296-D8C288B26A2F

### Comment

The link from this window Learn More is not working
![image](https://github.com/docker/docs/assets/2219045/fbb00f16-106e-4313-a309-2619528d67b7)

**Comment by aevesdocker** [comment]
Thanks @ShemTovYosef, I've flagged this with the relevant engineering team and it should be fixed shortly.
