### ISSUE TITLE
Mac OS uninstall not found

### ISSUE THREAD

**Issue by dmirtillo** [docker/docs#18556]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The command listed on the website to uninstall docker desktop from Mac is not working
Also, i don't seem to find any "troubleshoot" menu from the UI so i can't uninstall Docker by following the documentation on Mac OS

Here's the result of the command launched from terminal, the result is the same from both user and root account

:~ root# /Applications/Docker.app/Contents/MacOS/uninstall
-sh: /Applications/Docker.app/Contents/MacOS/uninstall: No such file or directory

### Location

https://docs.docker.com/desktop/uninstall/

**Comment by aevesdocker** [comment]
Hi @dmirtillo, thanks for raising the issue. If you are using Docker Desktop v4.25, this is a known issue (as stated in the release highlights https://docs.docker.com/desktop/release-notes/). 

The icon you're looking for, to uninstall from the Troubleshoot menu, on the Dashboard is in the top-right corner. 
![Screenshot 2023-10-31 at 08 45 00](https://github.com/docker/docs/assets/102604716/48301a6c-a1c0-4bbf-b5cd-8d3df4e8ac02)
