### ISSUE TITLE
why isn't this easier?

### ISSUE THREAD

**Issue by Sturmey66** [docker/docs#18553]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

Why, in this day and age, isn't there an easy way to point and click my way through building the docker container I need? Why do I need to spend a day and a half researching the 2-3 commands I need to learn so that I can build a simple web&php server? And Why for the love of God is the docker community so fucking toxic?

### Location

https://docs.docker.com/language/golang/build-images/

### Suggestion

Stop gatekeeping and make some actual entry level tutorials

**Comment by craig-osterhout** [comment]
Hi @Sturmey66, thanks for the feedback.
For PHP specifically, a PHP template for [docker init](https://docs.docker.com/engine/reference/commandline/init/) is in the [roadmap](https://github.com/docker/roadmap/issues/549).
It's not a point-and-click experience, but definitely easier than today. Keep an eye out as it should come out very very soon. If you have product requests, the [roadmap](https://github.com/docker/roadmap) is the best place to get them heard. 

Docker AI is also on the horizon and will help guide you through creating unique Docker assets and running commands. You may be able to see a demo of it in the [DockerCon](https://www.dockercon.com/) recordings. [Early Access](https://www.docker.com/press-release/announces-ai-boosting-developer-productivity-through-automated-guidance/) is also open.

In terms of docs, a language-specific guide is also in the works for PHP as a companion with the docker init template release. This will only cover the basics of a simple PHP project. As every project is unique, the [Dockerfile reference](https://docs.docker.com/engine/reference/builder/) will always be the best place to learn about the instructions. 

In addition to the [Dockerfile reference](https://docs.docker.com/engine/reference/builder/), I recommend the [Awesome Compose PHP sample](https://github.com/docker/awesome-compose/tree/master/apache-php) and the [PHP Official Docker Image](https://hub.docker.com/_/php). These are probably the best Docker resources that we have for PHP today. In terms of community, I highly recommend the [Slack community](https://join.slack.com/t/dockercommunity/shared_invite/zt-1jz09gjit-P2NPysg99kiWExFfof0oBA). I've never witnessed toxicity there and it's heavily trafficked by Docker devs and captains who have some unique insights.

**Comment by craig-osterhout** [comment]
Hi @Sturmey66, 
A [`docker init`](https://docs.docker.com/engine/reference/commandline/init/) template for PHP has been released and we've added a basic [PHP language guide](https://docs.docker.com/language/php/) showing how to use it. We're also planning to add another PHP guide soon.

Please take a look the guide and if you have any feedback, create an issue in GitHub or use the feedback widget on the doc's site. I'll close this particular issue. Thank you again for the feedback.
