### ISSUE TITLE
dockerfile_inline limitations

### ISSUE THREAD

**Issue by ToshY** [docker/docs#18566]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The `dockerfile_inline` documentation shows a basic example on how to use multi-line syntax to pass the contents of a Dockerfile, but it seems that it cannot replace a Dockerfile out of the box, as I noticed instructions like `ARG` do not work.

I've noticed that it was already stated in https://github.com/compose-spec/compose-spec/issues/298#issuecomment-1459965040 that the use-case for `dockerfile_inline` would be for simple commands, so I think it doesn't hurt to explicitly mention this in the documentation.

### Location

https://docs.docker.com/compose/compose-file/build/#dockerfile_inline

### Suggestion

Add a note to the `dockerfile_inline` section explicitly stating that it's use-case is for simple instructions only and that it cannot fully replace using a separate Dockerfile.

**Comment by denzuko** [comment]
In an ecosystem where buildpacks, helm charts, and the like. I would argue for the opposite and allow it to fully replace a Dockerfile.

**Comment by ndeloof** [comment]
`ARG` is well supported, but - like when using a plain Dockerfile - you need to inform Compose about build args and value to be set:

```
$  cat compose.yaml 
services:
  test:
    build:
      dockerfile_inline: |
        FROM alpine
        ARG FOO
        RUN echo $FOO > /foo
      args:
        - FOO
$ FOO=BAR docker compose build
[+] Building 0.1s (6/6) FINISHED                                                                                                docker:desktop-linux
 => [test internal] load .dockerignore                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                 0.0s
 => [test internal] load build definition from Dockerfile                                                                                       0.0s
 => => transferring dockerfile: 114B                                                                                                            0.0s
 => [test internal] load metadata for docker.io/library/alpine:latest                                                                           0.0s
 => CACHED [test 1/2] FROM docker.io/library/alpine                                                                                             0.0s
 => [test 2/2] RUN echo BAR > /foo                                                                                                              0.1s
...
```

**Comment by ndeloof** [comment]
Closing this issue as "work as documented"

**Comment by ToshY** [comment]
@ndeloof 

> ARG is well supported, but - like when using a plain Dockerfile - you need to inform Compose about build args and value to be set

Here's a simple example which uses `ARG` before `FROM` and include a default value.

`Dockerfile`
```Dockerfile
ARG PHP_VERSION=8.2
FROM php:${PHP_VERSION}
```

This does not work with `dockerfile_inline`.

`docker-compose.yml`
```yaml
version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile_inline: |
        ARG PHP_VERSION=8.2
        FROM php:${PHP_VERSION}
```

```console
$ docker compose up -d
WARN[0000] The "PHP_VERSION" variable is not set. Defaulting to a blank string.
[+] Building 0.0s (2/2) FINISHED                                                                                                                                             docker:default
 => [php internal] load build definition from Dockerfile                                                                                                                               0.0s
 => => transferring dockerfile: 68B                                                                                                                                                    0.0s
 => [php internal] load .dockerignore                                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                                        0.0s
failed to solve: failed to parse stage name "php:": invalid reference format
```

**Comment by ndeloof** [comment]
in your example, `FROM php:${PHP_VERSION}` is interpolated by docker compose during parsing, as demonstrated by the  warning message about unset variable. You need to double the dollar sign to prevent this:

```yaml
      dockerfile_inline: |
        ARG PHP_VERSION=8.2
        FROM php:$${PHP_VERSION}
```

**Comment by ToshY** [comment]
@ndeloof Thanks for the explanation!
