### ISSUE TITLE
Change text styles

### ISSUE THREAD

**Issue by PranitRout07** [docker/docs#18585]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

The word 'can' is written in italic where all other words are normal text style.
<img width="602" alt="Screenshot 2023-11-03 190953" src="https://github.com/docker/docs/assets/102309095/c188176d-85a6-4bcd-bbc5-cf9d37de82e9">

### Location

https://docs.docker.com/engine/reference/commandline/cli/

### Suggestion

change '_can_' to can

**Comment by divyansh2375** [comment]
I want to work on this issue can you please assign it to me

**Comment by PranitRout07** [comment]
@divyansh2375 you can get assigned by writing assign

**Comment by divyansh2375** [comment]
assign

**Comment by thaJeztah** [comment]
I guess the intent there was to put emphasis on "can" for that file specific (as other files may not be intended to manually modify). I agree that it may not be adding much though.


The file that's used to generate that page is in the docker/cli repository; https://github.com/docker/cli/blob/master/docs/reference/commandline/cli.md

If you're interested in contributing in that repository, make sure that your commits have a DCO sign-off line; 
https://github.com/docker/cli/blob/master/CONTRIBUTING.md#sign-your-work

Also /cc @dvdksn in case you were already working on this.

**Comment by thaJeztah** [comment]
I had to make some other changes on this page, so included a fix for this one as well;


- https://github.com/docker/cli/pull/4682
- https://github.com/docker/cli/pull/4681
