### ISSUE TITLE
Running Docker on Windows Server documentation is broken

### ISSUE THREAD

**Issue by jpulakka** [docker/docs#18604]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Link to [Install Docker Enterprise Engine on Windows Server](https://hub.docker.com/editions/enterprise/docker-ee-server-windows) in https://github.com/docker/labs/blob/master/windows/windows-containers/README.md is broken.

Referring to https://github.com/docker/docs/issues/18538 (which was just closed without fixing much) I believe not only that one link is broken, but the whole instruction is outdated and incorrect.

### Location

https://github.com/docker/labs/blob/master/windows/windows-containers/README.md

### Suggestion

Describe how to run Docker on Windows Server in 2023. A random blog post https://techcommunity.microsoft.com/t5/itops-talk-blog/docker-desktop-and-windows-what-s-the-best-option-for-you/ba-p/3851656 describes three options, Moby/DockerCE seems to be the preferred one. Also https://operavps.com/docs/configure-docker-on-windows-server/ describes a couple of approaches.

**Comment by aevesdocker** [comment]
Please report this issue in the labs repo. Thanks

**Comment by jpulakka** [comment]
https://github.com/docker/labs/issues/599
