### ISSUE TITLE
There are no errors happened after updating the source code

### ISSUE THREAD

**Issue by adrianenriquez** [docker/docs#18616]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Under the Update the Source code, tried the 3 steps and I didn't see the error as expected:

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint laughing_burnell 
(bb242b2ca4d67eba76e79474fb36bb5125708ebdabd7f45c8eaf16caaabde9dd): Bind for 127.0.0.1:3000 failed: port is already allocated.
```

I'm running Docker version 24.0.6, build ed223bc on Mac OS

### Location

https://docs.docker.com/get-started/03_updating_app/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Ensure that you went through all the previous parts in the guide.
In part 2, you run `docker run -dp 127.0.0.1:3000:3000 getting-started`.
If you didn't run that command, or you already stopped the container, you will not receive that error.
