### ISSUE TITLE
Document supported checksum digest algorithm

### ISSUE THREAD

**Issue by gilbertbw** [docker/docs#18682]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

The `--checksum` option for the `ADD` command does not indicate what digests are supported.

### Location

https://docs.docker.com/engine/reference/builder/

### Suggestion

Document the digests that are supported. n.b. I could not find the relevant source code for this.

**Comment by fcharron** [comment]
I'd add to better document the error you get when the digest algorithm is unsupported. I tried `ADD --checksum:md5` and the error I was getting from a `docker compose build` command was "unsupported digest algorithm", which IMO is not very clear. I didn't even know it was about the ADD command, and I was digging around the image digest for a good bit before thinking of looking at the ADD command.

**Comment by thiagomarafeli** [comment]
I believe this is really needed! It's not clear which algorithms are supported

**Comment by gilbertbw** [comment]
/remove-lifecycle stale
This is still not documented

**Comment by sashasimkin** [comment]
/remove-lifecycle stale
This is still not documented and not clear what algorithms are supported.

**Comment by thompson-shaun** [comment]
I believe this is the section being referenced https://docs.docker.com/reference/dockerfile/#add---checksum


Any thoughts @dvdksn?
