### ISSUE TITLE
Which one to use?

### ISSUE THREAD

**Issue by mrmorrandir** [docker/docs#18694]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

I don't know what I have to do... because the documentation contradicts itself!
Do I need to set the proxy in the `daemon.json` or in the `http_proxy.config`?

### Location

https://docs.docker.com/config/daemon/systemd/

**Comment by jojoob** [comment]
This seems to be a duplicate of #17880

**Comment by mrmorrandir** [comment]
Yes - you're right - #17880 is mostly the same.
Closing this Issue.
