### ISSUE TITLE
nvidia-container-runtime is deprecated

### ISSUE THREAD

**Issue by Mereks** [docker/docs#18699]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

https://github.com/NVIDIA/nvidia-container-runtime has been replaced by https://github.com/NVIDIA/nvidia-container-toolkit

### Location

https://docs.docker.com/config/containers/resource_constraints/

### Suggestion

Update documents with instructions for new software

**Comment by thaJeztah** [comment]
Thanks for reporting; looks like this is a duplicate of https://github.com/docker/docs/issues/18479
