### ISSUE TITLE
Annotations documentation

### ISSUE THREAD

**Issue by dvdksn** [docker/docs#18709]
Related to https://github.com/docker/build-push-action/pull/992#discussion_r1391691543

We already have some parts of our docs about annotations. Maybe we should borrow some bits from https://github.com/moby/buildkit/blob/master/docs/annotations.md?

**Comment by crazy-max** [comment]
Places where we have annotations without proper examples:
* https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md
* https://github.com/docker/buildx/blob/master/docs/reference/buildx_imagetools_create.md
* missing override in https://github.com/docker/buildx/blob/master/docs/reference/buildx_bake.md
* https://docs.docker.com/build/bake/reference/#targetannotations is ok but needs to explain how to set annotation at specific level uisng `<type>:` prefix.

**Comment by crazy-max** [comment]
I have some ongoing work for the metadata-action: https://github.com/crazy-max/docker-metadata-action/tree/annotations-alt#annotations
