### ISSUE TITLE
docker compose rm behaviour

### ISSUE THREAD

**Issue by CiprianaM** [docker/docs#18710]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Here: https://docs.docker.com/language/nodejs/develop/ the following information is provided:

In the terminal, run docker compose rm to remove your containers and then run docker compose up to run your application again.

content_copy
```
 docker compose rm
 docker compose up --build
```
Refresh http://localhost:3000 in your browser and verify that the todo items persisted, even after the containers were removed and ran again.

But the elements previously added to Postgres have been deleted when starting the containers again and refreshing the page.

### Location

https://docs.docker.com/language/nodejs/develop/

### Suggestion

Just describe the expected behaviour. Or, if behaviour is incorrect, then fix it. It is also not clear to me how this is possible (records from postgres being deleted by running `docker compose rm` since this behaviour is also not specified here: https://docs.docker.com/engine/reference/commandline/compose_rm/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. 

The [Volume](https://docs.docker.com/storage/volumes/) is responsible for persisting the data. I think the missing information is why the data needs to be persisted. You can find the answer here, https://docs.docker.com/storage/. In short, the data inside containers is deleted when the container is deleted (in this case, via `docker compose rm`). If you don't want the data deleted, you can use a volume.

In regards to why your items are not persisting, here are some common issues:
1. Check for any error messages in the console after you run `docker compose up`.
2. Make sure the volume is not commented out in your compose file and verify that every other instruction in the compose file matches the example.
3. Make sure you've created the `db/password.txt` file. If you ran the database before creating this file, you'll initialize the database without your password. The easiest way to fix this is delete the volume in the Volumes tab of Docker Desktop, then run `docker compose up` with the `db/password.txt` file present.

If you need more help troubleshooting, please try the Docker Community Slack at https://join.slack.com/t/dockercommunity/shared_invite/zt-1jz09gjit-P2NPysg99kiWExFfof0oBA

I also recommend starting with the [get-started guide](https://docs.docker.com/get-started/) or [walkthroughs](https://docs.docker.com/guides/walkthroughs/) as they cover the basic Docker concepts in more depth than the language-specific guides.

**Comment by CiprianaM** [comment]
Hi @craig-osterhout, yes, after following the steps above, I can see that the data is now persisted. I suppose I had run the database without the password.txt file, and was not aware of this behaviour, so maybe it is worth adding it to the documentation. Thanks for your help.
