### ISSUE TITLE
Typo in replicas example

### ISSUE THREAD

**Issue by scottlonghofer** [docker/docs#18747]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

> services:
>   fronted:
>     image: example/webapp
>     deploy:
>       mode: replicated
>       replicas: 6

### Location

https://docs.docker.com/compose/compose-file/deploy/#replicas

### Suggestion

Switch fronted to frontend.

**Comment by scottlonghofer** [comment]
Appears to be a regression of https://github.com/docker/docs/pull/14627

**Comment by aevesdocker** [comment]
Hi @scottlonghofer, please open an issue in the upstream repo where this content lives https://github.com/compose-spec/compose-spec
