### ISSUE TITLE
What does "Docker Desktop for Linux is now GA" mean?

### ISSUE THREAD

**Issue by ekoka** [docker/docs#18807]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

In the warning block at the top of that page there's this note about Docker Desktop

> Docker Desktop helps you build, share, and run containers on Mac and Windows as you do on Linux. [Docker Desktop for Linux](https://docs.docker.com/desktop/install/linux-install/) is now GA. For more information, see Docker Desktop for Linux.

What is GA?

### Location

https://docs.docker.com/engine/install/

### Suggestion

Define GA.

**Comment by polarathene** [comment]
[GA = General Availability](https://www.productplan.com/glossary/general-availability)

Basically, it's considered to be stable for wider adoption instead of only early adopters / testers.
