### ISSUE TITLE
Improve the documentation about network

### ISSUE THREAD

**Issue by craph** [docker/docs#18802]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

Is it possible to have a page where is it explain how networking / bridge mode works and how IP addresses are given.
With details of what are : 

- bip
- fixed-cidr
- what is the size vs the base in the default-address-pools
- what is the link between bip and base in default-address-pools

### Location

https://docs.docker.com

**Comment by polarathene** [comment]
Below is from recall, but should be easy enough for you to verify and respond with any corrections 👍 

---

> * what is the size vs the base in the default-address-pools

Separate PR related to that: https://github.com/docker/docs/issues/18782

The `base` defines a range that is split into subnets of `size`.

You might like this article on the topic: https://straz.to/2021-09-08-docker-address-pools/

---

> * bip
> * fixed-cidr

From the `dockerd` docs: https://docs.docker.com/engine/reference/commandline/dockerd/#daemon

> `--fixed-cidr string    IPv4 subnet for fixed IPs`
> `--bip string              Specify network bridge IP`

You can choose your own subnet to use for the legacy default bridge (`docker0`) with `fixed-cidr`, while `bip` AFAIK appears commonly set as the gateway address for that subnet.

You'll probably find `bip` defaults appropriately without setting it explicitly, it's only there if you know that you need to change it.

> * what is the link between bip and base in default-address-pools

If you don't set `fixed-cidr`, then AFAIK when the daemon starts it'll take the first available subnet from the default pools? Then the `bip` should default to the first available address in that subnet.

**EDIT:** `172.16.0.0/16` doesn't seem to be in `default-address-pools`, so I guess that default is configured elsewhere.
- I was recalling when I added IPv6 pools and enabled IPv6 on the default bridge it pulled from that IIRC.
- If this other subnet is in use (eg: by a VM guest), then I think Docker will still fallback to pulling a new subnet from the `default-address-pools`.
