### ISSUE TITLE
A typo in an example provided

### ISSUE THREAD

**Issue by RockmanR** [docker/docs#18819]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

In the "Example" box, under the "Environment replacement" section. The following:

FROM busybox
ENV FOO=/bar
WORKDIR ${FOO}   # WORKDIR /bar
ADD . $FOO       # ADD . /bar
COPY \$FOO /quux # COPY $FOO /quux

I believe the fifth line should be:
COPY \$FOO /quux # COPY ./bar /quux

As it was explained in the document, the "\$FOO" should have been replaced by "./bar".

### Location

https://docs.docker.com/engine/reference/builder/

### Suggestion

as mentioned in the description.

**Comment by dvdksn** [comment]
The example is correct. It shows an escaped variable.
