### ISSUE TITLE
Revert changes from previous PR ENGDOCS-1688.

### ISSUE THREAD

**Issue by ContoMartin** [docker/docs#18832]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

Download links for previous versions revert from change:
https://github.com/docker/docs/commit/4cfa07f8d6f959769a14a19cdc24fdf1e3a41b3a#diff-d5aaf013cfcfb5a45818ca85e018e16f68a1a86e81f7e300a87bc5c1033f81e5

### Location

https://docs.docker.com/desktop/install/mac-install/

### Suggestion

Revert back links to download docker desktop 3.6.0.

**Comment by aevesdocker** [comment]
Thanks for the issue @ContoMartin. Closing this PR as we will not be reverting the change. We no longer support those versions of Docker Desktop.
