### ISSUE TITLE
Install button not working.

### ISSUE THREAD

**Issue by sarthu210** [docker/docs#18858]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The install button not working it just loads something and stops so inspect the code click on that URL and then download where the started. (i am using chrome browser)

### Location

https://docs.docker.com/desktop/install/windows-install/

### Suggestion

Correct the href link so it will download and allow them to open new window for downloading

**Comment by dvdksn** [comment]
I can't reproduce, the markup for the download button looks correct to me and works as expected. Are you sure that it isn't just downloading the installer in the background? (without opening a new tab)

```
<a href="https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe" class="cursor-pointer py-2 px-4 rounded bg-blue-light-500 dark:bg-blue-dark-400 hover:bg-blue-light-400 dark:hover:bg-blue-dark-500 text-white">Docker Desktop for Windows</a>
```

**Comment by sarthu210** [comment]
Now its working!
