### ISSUE TITLE
Bash failure from cmd line

### ISSUE THREAD

**Issue by MouthOfMadness** [docker/docs#18853]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

This command:

    docker exec -it <pid> bash
 
 The bash command fails with this error:
 OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown
 
 I'm running from a Windows 10 computer. 
 

### Location

https://docs.docker.com/language/dotnet/develop/

**Comment by thaJeztah** [comment]
Is `<pid>` in your case the ID of the postgres container, or is it of another container?


Depending on the container you're trying to `exec` into, that command may fail if `bash` is not present inside your container; it's common for containers to only contain the minimum amount of tools (to have a smaller attack surface); if a shell is present inside the container, you may try using `sh` instead (which should be available for images based on a linux distro)

**Comment by MouthOfMadness** [comment]
This is your example when you install docker desktop.

These are the distro's I have installed:
docker-desktop
docker-desktop-data

Which distro do I need to run your example?

________________________________

**Comment by thaJeztah** [comment]
The `docker exec` part on that page describes running `docker exec` into the `postgres` container (which uses the `postgres:latest` image if I'm not mistaken);

<img width="257" alt="Screenshot 2023-12-06 at 16 46 33" src="https://github.com/docker/docs/assets/1804568/a15afa1d-cc14-4657-a7dd-ef21010abf30">

<img width="814" alt="Screenshot 2023-12-06 at 16 45 53" src="https://github.com/docker/docs/assets/1804568/51a51610-9f72-4dc3-8f8a-526b69b352b9">

I did not go through the full example, but trying a more minimal example with the `postgres` image, and running `docker exec` in that container works, so I wondered if you were trying to `docker exec` into another container (which may _not_ have `bash` installed);

```bash
docker run -d --name mypostgres -e POSTGRES_DB=example -e POSTGRES_PASSWORD=password postgres

docker ps
CONTAINER ID   IMAGE          COMMAND                  CREATED             STATUS             PORTS      NAMES
c0d124d2465d   postgres       "docker-entrypoint.s…"   3 seconds ago       Up 2 seconds       5432/tcp   mypostgres


docker exec -it c0d124d2465d bash
root@c0d124d2465d:/# exit
exit
```
