### ISSUE TITLE
uninstall no longer in Docker.app

### ISSUE THREAD

**Issue by hobzcalvin** [docker/docs#18851]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

MacOS Docs say to run `$ /Applications/Docker.app/Contents/MacOS/uninstall` which does not exist in 4.25.2

### Location

https://docs.docker.com/desktop/uninstall/

**Comment by aevesdocker** [comment]
Hi @hobzcalvin, this was a known issue in the 4.25 release https://docs.docker.com/desktop/release-notes/#4240. This is now fixed in version 4.26, so upgrading should resolve the issue.
