### ISSUE TITLE
.dockerignore file link is broken

### ISSUE THREAD

**Issue by i-ky** [docker/docs#18866]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

The link in [".dockerignore file" section](https://docs.docker.com/engine/reference/builder/#dockerignore-file) is broken. The associated link is correct, namely https://docs.docker.com/build/building/context#dockerignore-files/, but when I click it I get to https://docs.docker.com/build/building/context/#dockerignore-files/ (note the `/` that appeared before `#`). I wonder if that's related to https://github.com/docker/docs/blob/bdcf84efedc4dc38fc0cf1f3fc147ed2a57d79e6/data/redirects.yml#L642

### Location

https://docs.docker.com/engine/reference/builder/

**Comment by dvdksn** [comment]
Thanks this issue was fixed 👍🏻
