### ISSUE TITLE
Just use apt-get remove

### ISSUE THREAD

**Issue by andrewjmaguire** [docker/docs#18932]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The use of a for loop for removing all the packages is unnecessary, just pass all the packages on the apt-get remove command directly.

### Location

https://docs.docker.com/engine/install/ubuntu/

### Suggestion

sudo apt-get remove docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc

**Comment by dvdksn** [comment]
This is by design, see https://github.com/docker/docs/issues/17405
