### ISSUE TITLE
Overlay Networks & Swarms

### ISSUE THREAD

**Issue by EarningEvolved** [docker/docs#18958]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

There's a problem with the website

### Description

Hello.
I have been reading through your documentation on Networking and I've come to the Overlay section. I believe there is a problem with this section. Halfway through the documentation on Overlays, the page begins to talk about Docker Swarms. However, the page does not show the relationship between Overlays and Docker Swarms, so if you're reading to learn about Overlays, as a reader you're suddenly confronted with information about a feature (Swarms) and it isn't clear in the documentation what that feature is and how it relates to Overlay networks. That transition without explanation is very jarring for someone who is just trying to grasp Overlay networks and what they are. 

For example, this is a paragraph on the Overlay page

[Customize the docker_gwbridge interface](https://docs.docker.com/network/drivers/overlay/#customize-the-docker_gwbridge-interface)
The docker_gwbridge is a virtual bridge that connects the overlay networks (including the ingress network) to an individual Docker daemon's physical network. Docker creates it automatically when you initialize a swarm or join a Docker host to a swarm, but it is not a Docker device. It exists in the kernel of the Docker host. If you need to customize its settings, you must do so before joining the Docker host to the swarm, or after temporarily removing the host from the swarm.

The last sentence of the paragraph states that if you need to customize the docker_gwbridge setting, you must do so before joining the Docker host to the swarm, but this is a section in the Overlay networking area, and the text doesn't explain when an Overlay network becomes a swarm, what a swarm is or why you would need to consider a swarm in relation to the Overlay network you're using! It just says that this particular docker_gwbridge setting has to be customized before joining a host to "the" swarm without context of what "the" swarm is, why I would need to join it or how the swarm functions in relation to the Overlay! There's no context around what that actually means to someone creating an Overlay network or learning about creating an Overlay network.

There are a a host of other statements throughout the text that are like that. They offer information that is disjointed and leaves the new reader asking "OK, but why do I need that? I'm not joining a swarm! I'm just creating an Overlay!".  

Another topic on the Overlay page is "[Bypass the routing mesh for a swarm service](https://docs.docker.com/network/drivers/overlay/#bypass-the-routing-mesh-for-a-swarm-service)". Why do I need to bypass the routing mesh for a swarm service when I'm creating an Overlay? I don't know if this topic applies to the Overlay, if this information is there due to a cut and paste mistake or how it directly applies to an Overlay. Although I consider myself unique and special (lol), I'm sure I'm not the only person who may experience some confusion navigating this documentation. Please take a look when you have a chance.

Thank you!

### Location

https://docs.docker.com/network/drivers/overlay/

### Suggestion

To fix this issue, I think you can review the Overlay documentation, decide what is applicable to Overlay networks and then explain how the items presented are related to Overlay networks so the readers can know that what they are reading is relevant and applicable to Overlay networks.

**Comment by dvdksn** [comment]
Thanks a lot for your feedback. I notice we have a lot of duplication going on here too. I agree that information about Swarm should be narrowed down, especially about services. Though Swarm should likely still remain the recommended method of providing service discovery between daemons, but it shouldn't be assumed that containers are being managed by swarm.
