### ISSUE TITLE
Please add details on Image Access Management: Supported OSS images? 

### ISSUE THREAD

**Issue by akf** [docker/docs#18964]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

https://docs.docker.com/security/for-admins/image-access-management describes the effect of Image Access Management on access to Organization Images, Docker Official Images, Docker Verified Publisher Images, and Community Images. 
I'm trying to figure out where "Sponsored OSS" images fall among these categories (and the documentation on "Sponsored OSS" didn't enlighten me either). 

### Location

https://docs.docker.com/security/for-admins/image-access-management/

**Comment by stephaurelio** [comment]
Thanks for reporting this issue. I've updated this page PR #19021.
