### ISSUE TITLE
Duplicate tiltle ID causes URL anchors invalid

### ISSUE THREAD

**Issue by uiolee** [docker/docs#18983]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

There's a problem with the website

### Description

in page https://docs.docker.com/desktop/install/windows-install/ ,

the second subtitle is same with main title, which causes URL anchors invalid. The URL https://docs.docker.com/desktop/install/windows-install/#install-docker-desktop-on-windows point to main title, can't point to subtitle.

### title

```html
<h1 id="install-docker-desktop-on-windows" ......>
  Install Docker Desktop on Windows
</h1>
```

### subtitle

```html
<h2 ...... id="install-docker-desktop-on-windows">
  <a ......>Install Docker Desktop on Windows</a>
</h2>
```

### Location

https://docs.docker.com/desktop/install/windows-install/#install-docker-desktop-on-windows

### Suggestion

For the same title, different IDs should be generated.

OR, Avoid using the same title in the same page.

**Comment by SaiAdithya3** [comment]
Hi, I would like to solve this issue which you are facing with the same ID given to the tags!
