### ISSUE TITLE
[404]: /go.wsl2

### ISSUE THREAD

**Issue by Motjam** [docker/docs#18986]
### Location

docker app

### Broken link

https://docs.docker.com/go.wsl2

### Comment

![Screenshot 2023-12-22 201346](https://github.com/docker/docs/assets/154641371/eb1604ae-836c-4712-bfc0-932f830e7d54)
![111](https://github.com/docker/docs/assets/154641371/631bc7f7-4565-4a87-bfb1-b901f8806d64)

**Comment by dvdksn** [comment]
https://docs.docker.com/go/wsl2/ works
