### ISSUE TITLE
Missing step in "install using the repository"

### ISSUE THREAD

**Issue by sjf-control** [docker/docs#18989]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Step 3 is after installing the packages, and it tries to run 'Hello-World' It fails because Docker is not yet running, Need to run ```sudo service docker start``` first

### Location

https://docs.docker.com/engine/install/debian/

### Suggestion

Make it look like Step 6 in "Install from a Package"

**Comment by dvdksn** [comment]
Unless you've tampered with systemd, Docker should be set to start automatically with this installation method, no need to manually start the service. What version of Debian are you using?

**Comment by sjf-control** [comment]
Hmmm, I'm running Raspberry Pi OS Lite (64 bit) which is Debian Bookworm. BUT... I'm using Ansible to install everything. I just tried doing it by hand on a freshly-burned Pi, and yes, the Hello-World run was successful without a manual start. So you can close this.
