### ISSUE TITLE
Error building docker file... ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount2901637718/Dockerfile: no such file or directory

### ISSUE THREAD

**Issue by ckashby** [docker/docs#18991]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

git clone https://github.com/docker/getting-started-app.git

cd getting-started-app

create Docker file
FROM node:18-alpine
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "src/index.js"]
EXPOSE 3000

docker build -t getting-started .

# Error
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3577758206/Dockerfile: no such file or directory

### Location

https://docs.docker.com/get-started/02_our_app/

### Suggestion

Please advise...

clay.ashby@gmail.com

**Comment by dvdksn** [comment]
hi @ckashby - it looks like it's not able to find the Dockerfile in the working directory. Are you sure you named `Dockerfile` - no file extensions?

**Comment by ckashby** [comment]
Thank you for your quick response.

Please close this issue
