### ISSUE TITLE
404

### ISSUE THREAD

**Issue by khusuleen** [docker/docs#19001]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

There's a problem with the website

### Description

error 404 
 https://download.docker.com/linux/rhel/8/x86_64/stable/repodata/repomd.xml

### Location

https://docs.docker.com/engine/install/rhel/

**Comment by dvdksn** [comment]
This instruction is only for s390x. For x86, try the centos instructions
