### ISSUE TITLE
Missing supported formats from table

### ISSUE THREAD

**Issue by vtcifer** [docker/docs#19011]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

The table listing the options in config.json for customizing default format for commands is missing a number of options, e.g. `tasksFormat` (the one was trying to locate, to set a default for `docker stack ps <STACK>`).  My assumption is the full list that should be shown is referenced [here](https://github.com/docker/cli/blob/3c0c68a45ae5b729a8b3e91b60783d818c315738/cli/config/configfile/file.go#L18-L43) - others missing for example are `networksFormat`,  `volumesFormat` etc.

### Location

https://docs.docker.com/engine/reference/commandline/cli/

**Comment by dvdksn** [comment]
Thanks for reporting this issue 👍🏻 I've added the missing links to the relevant formatting sections (they were described in the CLI reference sections, we were just missing to cross-reference the ones you mentioned!)
