### ISSUE TITLE
Include email address change steps under Create an account

### ISSUE THREAD

**Issue by ytazky** [docker/docs#19027]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

At the moment, there isn't a step-by-step guide to change email address for users.
It would be great to include it in the Create an account section with the following steps:

1. Click the profile icon
2. Head over to Settings
3. Click on Edit under Email address
4. Insert the new email address and password 
5. Click "send verification email"
6. Once the verification email is sent, verify the new email address
7. Email address is now changed

### Location

https://docs.docker.com/docker-id/

**Comment by madiksh** [comment]
/

**Comment by dvdksn** [comment]
@sarahsanders-docker can you PTAL?

**Comment by sarahsanders-docker** [comment]
This information is available in [Manage an account](https://docs.docker.com/accounts/manage-account/), under the [Update general settings](https://docs.docker.com/accounts/manage-account/#update-general-settings) > [Update email address](https://docs.docker.com/accounts/manage-account/#update-email-address) headings.
