### ISSUE TITLE
Ambiguous terminology for Docker networking

### ISSUE THREAD

**Issue by eeecoder** [docker/docs#19041]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

There is an ambiguous term in this sentence:
"Each container can now look up the **hostname** web or db and get back the appropriate container's IP address."

It would be clearer to write "**service name**".
"hostname" is an ambiguous term. "hostname" can mean the computer name. However, docker compose also has a term "hostname" that means something else.

### Location

https://docs.docker.com/compose/networking/

**Comment by alex-ong** [comment]
```
| Service name | name on network | alt name on network | hostname of container | container name |
|--------------|-----------------|---------------------|-----------------------|----------------|
| web          | web             | myapp-web-1         | e7abd25e16b3          | myapp-web-1    |
| db           | db              | myapp-db-1          | e7abd25af314          | myapp-db-1     |
```
> Each container can now look up the **hostname web or db** and get back the appropriate container's IP address

From `web`s perspective, if you look up the hostname `db`, it indeed returns the correct ip address.
```py
# running from db.
>>> import socket
>>> socket.gethostbyname('web')
'172.18.0.3'
```

You can also look up the automatically created container name:
```py
# running from db
>>> import socket
>>> socket.gethostbyname('myapp-web-1')
'172.18.0.3'
```

You can also look up the the automatically created hostname of the container
```py
# running from db
>>> import socket
>>> socket.gethostbyname('e7abd25e16b3')
'172.18.0.3'
```

They can get the correct containers IP in the autogenerated network by:
* service name (web/db)
* container name (myapp-web-1 / myapp-db-1)
* *automatically generated* hostname of the container (e7abd25e16b3   / e7abd25af314)
* any links defined.

You cannot connect via:
* manual generated hostnames (e.g. if you used `hostname: "manual"` under the service, this does not work), as this only adds a line to the generated containers /etc/hosts/, and that's it.

Now i think that the "supported way" is probably the service name which is automatically alias'ed, but each container does indeed seem like it is doing a "hostname lookup" on the "service's name".

**Comment by eeecoder** [comment]
> They can get the correct containers IP in the autogenerated network by:
> automatically generated hostname of the container (e7abd25e16b3 / e7abd25af314)

> You **cannot** connect via:
> 
>     * manual generated hostnames (e.g. if you used `hostname: "manual"` under the service, this does not work)
> 
> 

My understanding is that you can connect by container_id, which is the automatically generated (default) hostname of the container. You cannot connect by hostname because hostname is not guaranteed to be unique per container.
