### ISSUE TITLE
port error in docker build with 'containerise a python application' tutorial

### ISSUE THREAD

**Issue by j-emberton** [docker/docs#19052]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

I am following this tutorial. At the conclusion of the build process I get the following error:
 ✔ Container python-docker-server-1  Recreated                                                                     0.1s
Attaching to server-1
server-1  | /bin/sh: 0: Illegal option -
server-1 exited with code 2

This prevents me viewing the html site at localhost:port

This appears to be a docker issue, as I have troubleshooted my browser and firewall settings.

After the build, the port info is still commented out in the docker_compose.yaml. Is this the issue? Uncommenting and changing the port numbers to the specified number didn't help me

Are the steps outlined in the tutorial incorrect?

### Location

https://docs.docker.com/language/python/containerize/

**Comment by craig-osterhout** [comment]
Hi @j-emberton, thanks for sharing the issue.
Typos when running `docker init` may be the cause of the issue.
If you can you share the contents of your `Dockerfile`, we can take a look.

**Comment by Tusheralo** [comment]
Login my Gmail account

**Comment by Tusheralo** [comment]
> Login my Gmail account 

zannatulislam5724@gmail.com

**Comment by craig-osterhout** [comment]
Closing as stale. If you need help troubleshooting, please try the Community Slack at https://join.slack.com/t/dockercommunity/shared_invite/zt-1jz09gjit-P2NPysg99kiWExFfof0oBA
