### ISSUE TITLE
Missing ';' in Environment replacement examples

### ISSUE THREAD

**Issue by dmedhora** [docker/docs#19054]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Missing ';' in Environment replacement examples for bash modifiers
For example:
str=foobarbaz echo ${str#f*b}     # arbaz
is incorrect. 
It should instead be:
str=foobarbaz ; echo ${str#f*b}     # arbaz
Note the semicolon after the str assignment.
The same applies to all examples in the Environment replacement topic.

### Location

https://docs.docker.com/engine/reference/builder/#environment-replacement

### Suggestion

Please put in the ';' so that it works in a bash shell for which it's meant to be copied and tried out. Thanks.

**Comment by dvdksn** [comment]
hi, it should work in a bash shell without the semi-colon as well. What issue are you seeing? it does seem like zsh requires the semicolon though. Maybe that's what you were trying?
