### ISSUE TITLE
RUN --mount option mentioned without info which version has it added.

### ISSUE THREAD

**Issue by AedisV** [docker/docs#19086]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

Add a link/notice to resource telling in which version --mount got introduced as an option for RUN command

### Location

https://docs.docker.com/build/cache/

### Suggestion

Add info which version of docker did introduce it.

**Comment by thaJeztah** [comment]
Any current (non EOL) version of Docker supports this option, but it does require BuildKit as builder (which is the default on Linux, but not (yet) supported for building native Windows images).
