### ISSUE TITLE
Wrong information about linking account tot GitHub. 

### ISSUE THREAD

**Issue by MarlinMr** [docker/docs#19102]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The documentation on how to link DockerHub accounts with GitHub is wrong. 

It says to select the `Linked Accounts` tab, but no such tab exists. 

### Location

https://docs.docker.com/docker-hub/builds/link-source/

**Comment by stephaurelio** [comment]
Hello thanks for submitting this issue! When trying to set up automated builds, were you logged in to an account with a subscription (Pro, Team, or Business)? I verified in my Pro account that the Linked Accounts tab is visible. It won't be visible if you're on a Personal subscription, though (see note at the top of the doc).
