### ISSUE TITLE
Encoding proxy passwords

### ISSUE THREAD

**Issue by zirkuswurstikus** [docker/docs#19118]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Hello,
the documentation should be more specific on how to encode password in  cat /etc/systemd/system/docker.service.d/proxy.conf.

see: https://docs.docker.com/config/daemon/systemd/#manually-create-the-systemd-unit-files

example:

proxyuser = "johndoe"
proxypass = "**asdf_/_hjkl_;_!**"

To url encode the password:
1) url encode the password ( **asdf_/_hjkl_;_! => asdf_%2F_hjkl_%3B_%21%0A** )
2) escape all % with an additional % ( **asdf_%2F_hjkl_%3B_%21%0A => asdf_%%2F_hjkl_%%3B_%%21%%0A**)

The resulting proxy.conf should look like:
```
[Service]
Environment="HTTP_PROXY=http://johndoe:asdf_%%2F_hjkl_%%3B_%%21%%0A@proxy.example.com:8080"
Environment="HTTPS_PROXY=http://johndoe:asdf_%%2F_hjkl_%%3B_%%21%%0A@proxy.example.com:8080"
Environment="NO_PROXY=127.0.0.1,localhost,.example.com,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
```

Note: AFAIK, this problem is related on how the systemd handle special characters.

Also it woulöd be nice to link to https://systemd.io/CREDENTIALS/ . So the proxy password can be stored encrypted.

Thanks for the good work,
zirkuswurstikus

### Location

https://docs.docker.com/config/daemon/systemd/

**Comment by dvdksn** [comment]
Hi, thanks for raising the issue. Two things I see here:

1. This is not within the scope of the documentation that we provide. Granted we do recommend using dockerd with systemd as the init system and you're behind a corporate proxy. But...
2. Specifying userinfo in HTTP URIs is deprecated in the HTTP spec. As such, we will likely remove instances of this in our documentation, or call it out as a bad practice. [ref](https://www.rfc-editor.org/rfc/rfc9110.html#name-deprecation-of-userinfo-in-)

For these reasons, I'm closing this request.
