### ISSUE TITLE
No explanation for what "..." means

### ISSUE THREAD

**Issue by SRNissen** [docker/docs#19147]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

Several commands use "..." to indicate... something?

Presumably "this command accepts a list" but it is not clear at all and there are no obvious examples that illustrate usage.

E.g.:

    ADD [--chown=<user>:<group>] [--chmod=<perms>] [--checksum=<checksum>] <src>... <dest>
    ADD [--chown=<user>:<group>] [--chmod=<perms>] ["<src>",... "<dest>"]

Especially in the context of comma in the second version of `ADD`

### Location

https://docs.docker.com/engine/reference/builder/

**Comment by polarathene** [comment]
Multiple sources, it's a common syntax for CLI usage when using `-h` / `--help` to indicate a list of 1 or more values.

In this case it's like `src-1 src-2 src-3 all-to-this-dest`.

Likewise the `[ ]` means it's optional, `<>` communicates context of what the value should represent.

**Comment by SRNissen** [comment]
I see this has been tagged with "cli" - in fact I am talking here about the syntax of the Dockerfile itself.
