### ISSUE TITLE
Less ambiguity about iptables and docker + firewalld

### ISSUE THREAD

**Issue by vidlb** [docker/docs#19148]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Location

https://docs.docker.com/network/packet-filtering-firewalls#integration-with-firewalld

### Description

Current text :
>If you are running Docker with [firewalld](https://firewalld.org/) on your system with --iptables enabled, Docker automatically creates a firewalld zone called docker and inserts all the network interfaces it creates (for example, docker0) into the docker zone to allow seamless networking.

It is unclear if we need to have docker with --iptables or firewalld with iptables backend (instead of nftables), since they both provide such an option. Which one is it ? It seems we talk about firewalld, but I guess we're talking about "DOCKER_OPTS=--iptables" ?  

### Suggestion

>If you are running Docker with --iptables and [firewalld](https://firewalld.org/) is enabled on your system, Docker automatically creates a firewalld zone called docker and inserts all the network interfaces it creates (for example, docker0) into the docker zone to allow seamless networking.

**Comment by dvdksn** [comment]
cc @robmry

**Comment by robmry** [comment]
The suggestion LGTM.

(There's no `--iptables` option in `firewalld` or `firewall-cmd` - so I think the existing text ends up being unambiguous, but the proposed text is clearer.)
