### ISSUE TITLE
Clearly document what is carried over in multi-stage builds

### ISSUE THREAD

**Issue by berzi** [docker/docs#19186]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

Information on whether things like `ARG`, `WORKDIR`, `USER` etc carry over when using `FROM previous-stage` is not clearly indicated on the multi-stage builds page.

### Location

https://docs.docker.com/build/building/multi-stage/

### Suggestion

If everything carries over, it should be mentioned. If something doesn't carry over and must be redefined, a table should clearly indicate what carries over and what doesn't.

**Comment by polarathene** [comment]
> Information on whether things like `ARG`, `WORKDIR`, `USER` etc carry over when using `FROM previous-stage` is not clearly indicated on the multi-stage builds page.

AFAIK, it's the same as if you extended an image via `FROM` without a multi-stage build.

You should be able to confirm any of those concerns locally fairly easily yourself, but sure it may be worthwhile to clarify that to the reader.

Not sure why you'd think `ARG` to carry over? The docs for this instruction are pretty good, you can define `ARG` prior to a `FROM`, and it'll be available in the scope of that instruction, anything after that `FROM` is then in a "stage" (_regardless of single or multi_), you need to use `ARG` again to make any build arg provided as a temporary `ENV` again, for multi-stage that likewise means each `FROM` requires you to declare `ARG` within it's own stage that you want to use it.
