### ISSUE TITLE
The 'closing-x' on the cookie-button is not centered properly.

### ISSUE THREAD

**Issue by leonden** [docker/docs#19193]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

There's a problem with the website

### Description

On the [Docker Website](https://docs.docker.com/), there is this cookie-button in the bottom left-hand corner of the page. The 'closing-x', that appears if you click on the button, is actually not centered properly. Though for me it seems, that the button may be provided as a component by the external company [onetrust](https://www.onetrust.com/).

### Location

https://docs.docker.com/

**Comment by dvdksn** [comment]
I'm not seeing this issue, would you mind sharing a screenshot that shows what you're explaining here?

**Comment by leonden** [comment]
> I'm not seeing this issue, would you mind sharing a screenshot that shows what you're explaining here?

It looks like it got solved in the meantime, therefore I can close this issue.
