### ISSUE TITLE
HomePage UI

### ISSUE THREAD

**Issue by SamarthKadam** [docker/docs#19202]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

In the homePage at the bottom there is button called  Cookies Settings. There is no proper gap between the button and its upper content

### Location

https://docs.docker.com/

### Suggestion

I'll provide some margin over it making it visually better

**Comment by dvdksn** [comment]
Thanks @SamarthKadam, we're redesigning our landing page, I'll make sure this is fixed
