### ISSUE TITLE
curl command error

### ISSUE THREAD

**Issue by FrediArro** [docker/docs#19228]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The curl command to get the gpg key from docker should use lower case o flag instead of uppercase O. 

### Location

https://docs.docker.com/engine/install/debian/

### Suggestion

The command for curl should be the following: 

`curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc`

**Comment by dvdksn** [comment]
Thanks @FrediArro for noticing and reporting. Fix about to roll out.
