### ISSUE TITLE
Wrong command for docker run in the 'Allocate a pseudo-TTY (-t, --tty)' section

### ISSUE THREAD

**Issue by mgross2** [docker/docs#19292]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

In [this](https://docs.docker.com/engine/reference/commandline/container_run/#tty) section, you describe how the behavior of `docker run` changes, if the `-t` is added to the `-i` option.
However, the example command in the second  code block does not contain the `-t` flag

The second bash command reads exactly as the first one:

`$docker run -i debian passwd root`

### Location

https://docs.docker.com/engine/reference/commandline/container_run/#tty

### Suggestion

The second bash command should read `$docker run -ti debian passwd root`

**Comment by ankitbhadoriya** [comment]
Hi if this issue is still open i would like to work on it

**Comment by dvdksn** [comment]
Thanks for reporting this issue, looks like I've made a typo indeed!

@ankitbhadoriya if you'd like to work on this issue, by my guest! Note that this content lives in a different repository, and is only vendored in docker/docs. To fix the issue, the following file needs to be updated: https://github.com/docker/cli/blob/master/docs/reference/commandline/container_run.md?plain=1#L1003
