### ISSUE TITLE
Include information about DSOS images

### ISSUE THREAD

**Issue by ytazky** [docker/docs#19294]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Currently, the page do not contain any information about the effect on DSOS images when IAM is being enabled. Could be improved to include that information to the page.

### Location

https://docs.docker.com/security/for-admins/image-access-management/

**Comment by stephaurelio** [comment]
This info was added to the [IAM](https://docs.docker.com/security/for-admins/image-access-management/#configure-image-access-management-permissions) page in #19021 as DSOS falls under community images.
