### ISSUE TITLE
docs for installing docker on raspberry pi are outdated

### ISSUE THREAD

**Issue by sunburntkamel** [docker/docs#19308]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

the instructions refer to docker-ce, and docker-ce-cli, which have no installation candidate on a 4b. might be worth linking to more standard install options there.  Additionally, containerd.io docker-buildx-plugin and docker-compose-plugin don't seem to be the right names anymore

```~  sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package docker-ce-cli is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
E: Package 'docker-ce-cli' has no installation candidate
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'
E: Unable to locate package docker-buildx-plugin
E: Unable to locate package docker-compose-plugin```

### Location

https://docs.docker.com/engine/install/raspberry-pi-os/

### Suggestion

on a 4b, `sudo apt-get install docker docker-compose` is enough to get hello world to run

**Comment by thaJeztah** [comment]
> Additionally, containerd.io docker-buildx-plugin and docker-compose-plugin don't seem to be the right names anymore

did you set up the repository correctly? 
https://docs.docker.com/engine/install/raspberry-pi-os/#install-using-the-repository

based on the package name (`docker`, which is not the package name for the packages we provide), I suspect you may not have the repository set up correctly, therefore the packages not being found. The buildx and other packages definitely should be there; eg for raspbian bookworm;

https://download.docker.com/linux/raspbian/dists/bookworm/pool/stable/armhf/

**Comment by sunburntkamel** [comment]
I did follow those instructions, i think the issue is that my 4b is 64 bit, and the instructions are for 32 bit only

**Comment by thaJeztah** [comment]
Correct, yes, it's mentioned at the top of the page, for 64-bit use the debian packages https://docs.docker.com/engine/install/debian/
