### ISSUE TITLE
Missing schema

### ISSUE THREAD

**Issue by mdiogene** [docker/docs#19324]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

Hello,

You are talking about schemas in the documentation while there are not.
https://gdevillele.github.io/swarm/plan-for-production/
best regards, 

### Location

https://gdevillele.github.io/swarm/plan-for-production/

**Comment by dvdksn** [comment]
Hi, this is not the official Docker documentation website. Please use docs.docker.com as the canonical source of information.

**Comment by thaJeztah** [comment]
Looks like an old fork of the docs repo https://github.com/gdevillele/gdevillele.github.io


@gdevillele 👋 (hope you're doing well <3); wondering if you're able to disable that repo to prevent confusion

**Comment by gdevillele** [comment]
> Looks like an old fork of the docs repo https://github.com/gdevillele/gdevillele.github.io
> 
> @gdevillele 👋 (hope you're doing well <3); wondering if you're able to disable that repo to prevent confusion

Thanks @thaJeztah ! I am fine, hope you are too!
(miss you and the rest of the Docker gang ☺️)

I deleted the repo 🧹

<img width="506" alt="Screenshot 2024-02-07 at 22 34 23" src="https://github.com/docker/docs/assets/939999/23e91db0-e97d-41f8-87c1-067bd7a105b5">

**Comment by thaJeztah** [comment]
Thanks @gdevillele !! Yes, doing great; hope to run into you again ... some where, some day ❤️

**Comment by dvdksn** [comment]
Thanks @gdevillele
