### ISSUE TITLE
Example for host-gateway doesn't work

### ISSUE THREAD

**Issue by rishid** [docker/docs#19335]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The example command on the page is invalid. It needs to be a colon between internal and host.
```
docker run \
  --add-host host.docker.internal=host-gateway \
  curlimages/curl -s host.docker.internal:8000/hello
```

### Location

https://docs.docker.com/engine/reference/commandline/container_run/#add-host

**Comment by dvdksn** [comment]
Hello. The `=` separator is new in Docker Engine 25.0.0: https://github.com/docker/cli/pull/4663

What version of Docker Engine are you using?

**Comment by rishid** [comment]
Ah, okay. Still using `24.0.5` - I will close as this is not an issue.
