### ISSUE TITLE
docker build is hanging

### ISSUE THREAD

**Issue by erichstuder** [docker/docs#19410]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

There's a problem with the website

### Description

When I build the container I get the following output and it seems just to hang after some warnings.

![image](https://github.com/docker/docs/assets/28953680/87315161-9005-4a51-b350-a1dbaa834602)

### Location

https://docs.docker.com/guides/walkthroughs/run-a-container/

### Suggestion

Maybe the Dockerfile needs some update.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
It's downloading and installing dependencies. It might be network related. For example, if you have a slower connection it may take a while to download all the dependencies.

If you've tried to build a few times and it still hangs, you can try to narrow down what's causing it to hang.
Update the instruction in the Dockerfile to be more verbose to help troubleshoot. For example, open the `Dockerfile` in a code or text editor, and then add `--loglevel=verbose` to the following line in the Dockerfile.

```
# Install node packages, install serve, build the app, and remove dependencies at the end
RUN npm install --loglevel=verbose \
    && npm install -g serve \
    && npm run build \
    && rm -fr node_modules
```

**Comment by erichstuder** [comment]
Thank you for your fast answer!

I tried it with verbosity and nothing showed up.
So I just let it run.
It took about 20 minutes to finish.
So everything works fine, basically.

My internet connection is not the fastest but also not the slowest.
Maybe other people might have the same problem.
Especially newbies like me with no idea what exactly is downloaded here, might be confused.
Also it implies here, that every example takes about 5 minutes (https://docs.docker.com/guides/get-started/)
So maybe there is a chance to speed this example up.

But that is just a suggestion. No problem so far.

Thank you.
