### ISSUE TITLE
[404]: /engine/reference/commandline/dockerd/

### ISSUE THREAD

**Issue by MichaIng** [docker/docs#19473]
### Location

https://docs.docker.com/config/daemon/

### Broken link

https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file

### Comment

The page with the Docker daemon config options is missing. Aside of the above origin page of the broken link, it is the same with the "Daemon CLI (dockerd)" navigation entry at https://docs.docker.com/reference/.

**Comment by dvdksn** [comment]
Thanks for reporting, and sorry about the inconvenience. It's fixed now.

**Comment by MichaIng** [comment]
Many thanks for the quick fix 🚀 .
