### ISSUE TITLE
Possible undocumented COPY case

### ISSUE THREAD

**Issue by javaDeveloperKid** [docker/docs#19500]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The documentation for `COPY` states:
> - The <src> path must be inside the build context; you can't use COPY ../something /something, because the builder can only access files from the context, and ../something specifies a parent file or directory of the build context root.

Let's say my Dockerfile is not in the project root directory but nested inside some directory, e.g.:
```sh
bin/
    file.go
docker/
    Dockerfile
```
Now I run `docker build -f docker/Dockerfile -t my-tag .` from the project root so the `.` means the build context root is the project root.
The following Dockerfile works:
```Dockerfile
FROM alpine

COPY bin/file.go /bin/file.go
```
However this Dockerfile **also works** (notice `../` in the <src> path for file.go):
```Dockerfile
FROM alpine

COPY ../bin/file.go /bin/file.go
```

I would expect this to fail as the build context is a project root and using `../` we go to the parent directory which is outside of the build context.
### Location

https://docs.docker.com/reference/dockerfile/

**Comment by dvdksn** [comment]
@tonistiigi how come `../bin/file.go` in the example outlined in this ticket works? (even `../../../../bin/file.go` works)

Are leading `../` automatically stripped? So in the case of e.g. `COPY ../../../bin/file.go /file.go` the effective source path becomes `bin/file.go`

**Comment by tonistiigi** [comment]
@dvdksn yeah, `../bin/file.go` is the same as `/../bin/file.go` what is a valid path.
