### ISSUE TITLE
--add-host host.docker.internal=host-gateway can't do it

### ISSUE THREAD

**Issue by R3habDroid** [docker/docs#19515]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

>    [root@VM-8-15-opencloudos ~]# docker run --name my-prometheus \
>     --mount type=bind,source=/tmp/prometheus.yml,destination=/etc/prometheus/prometheus.yml \
>     -p 9090:9090 \
>     --add-host host.docker.internal=host-gateway \
>     prom/prometheus
invalid argument "host.docker.internal=host-gateway" for "--add-host" flag: bad format for add-host: "host.docker.internal=host-gateway"
See 'docker run --help'.

### Location

https://docs.docker.com/config/daemon/prometheus/

**Comment by R3habDroid** [comment]
it should be:
 --add-host host.docker.internal:host-gateway

**Comment by dvdksn** [comment]
The = separator is valid since Moby 25.0
