### ISSUE TITLE
Consider adding port mapping to the run hello-world step

### ISSUE THREAD

**Issue by gskerry** [docker/docs#19543]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

There may be a low probability of Step 4 (`docker run hello-world`) working without a port mapping to the host system. For newer or less initiated users, this could lead to confusion about there being an issue with the install. 

### Location

https://docs.docker.com/engine/install/linux-postinstall/

### Suggestion

Consider adding an explicit port mapping to the command:
`docker run -p 127.0.0.1:3000:3000 hello-world`

**Comment by dvdksn** [comment]
The `hello-world` image doesn't require ports being published

**Comment by gskerry** [comment]
Hm, I might have misdiagnosed the issue. I got a connection refused on both localhost:3000 and 127.0.0.1:3000 until I set the port mapping. Then it worked fine. Could another config be off?

![Screenshot from 2024-02-29 11-12-31](https://github.com/docker/docs/assets/8867156/2e1693d4-4473-40f3-b3e5-c971eb4cde50)

(Ubuntu 22.04.4)
```
Client: Docker Engine - Community
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:09 2024
 OS/Arch:           linux/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by dvdksn** [comment]
`hello-world` just prints a message to standard output. It doesn't listen for connections on a TCP port;

```console
$ docker run hello-world && echo "exited"

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm64v8)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

exited
```

**Comment by gskerry** [comment]
Ah, I think I was pulling wrong image, from a different tutorial. Got it. Ok, many thanks.
