### ISSUE TITLE
Where can I find a copy of the legacy ECS integration user guide? (& recommendations for replacement?)

### ISSUE THREAD

**Issue by RobHoman** [docker/docs#19567]
### Location

https://github.com/docker/compose-cli/tree/main/docs

### Broken link

https://docs.docker.com/engine/context/ecs-integration/

### Comment

I am in search of a copy of the ECS integration user guide because I need to reference it briefly for legacy reasons. I do understand that it is deprecated & no longer supported as of November 2023. However, I am still reliant on this pathway to deploy to production, and it appears to function for the time being. I need to reference the guide in order to help train another colleague on deployments. Meanwhile we will be changing our deployment path. 

I was hopeful that this link that I found would save the day!
[ECS integration user guide](https://docs.docker.com/engine/context/ecs-integration/)
It lived at https://github.com/docker/compose-cli/tree/main/docs 
But, unfortunately it back links to https://docs.docker.com/engine/context/ecs-integration/ 

PS. What replacement would you recommend for this ECS integration and is there a guide for it?

Thanks so much!
-Rob Homan

**Comment by craig-osterhout** [comment]
Hi @RobHoman, you can pull up an old PR from before November 2023 and check the deploy preview to browse older content.
For example, https://deploy-preview-18404--docsdocker.netlify.app/cloud/aci-integration/

For recommendation for a replacement, you might get more visibility posting to [/docker on Reddit](https://www.reddit.com/r/docker/), [Docker's community forums](https://forums.docker.com/), or [Docker's community Slack](https://join.slack.com/t/dockercommunity/shared_invite/zt-1jz09gjit-P2NPysg99kiWExFfof0oBA).

**Comment by RobHoman** [comment]
I appreciate this! Thank you.
