### ISSUE TITLE
Docker 25.0.3 - host.docker.internal

### ISSUE THREAD

**Issue by robakiewiczj** [docker/docs#19582]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Usage example of host.docker.internal variable doesn't work on Docker Desktop without adding additional property
--add-host=host.docker.internal:host-gateway

That information is missing on the page so you may have defect in the code or documentation

### Location

https://docs.docker.com/desktop/networking/

### Suggestion

fix docs or docker desktop

**Comment by dvdksn** [comment]
hi,the `host.docker.internal` domain name should still work in Docker Desktop with Docker Engine 25.0.3

Could you please file an issue in the Docker Desktop tracker for the OS you're using? Thank you!

- https://github.com/docker/for-win/issues
- https://github.com/docker/for-mac/issues
- https://github.com/docker/for-linux/issues
