### ISSUE TITLE
yarn install is not working

### ISSUE THREAD

**Issue by infy77** [docker/docs#19598]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Getting the following error when trying to create container.

### Location

https://docs.docker.com/get-started/02_our_app/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
Can you share all the error output?

**Comment by craig-osterhout** [comment]
Closing as stale. Not enough info to reproduce. If the issue still persists, please provide more info.
