### ISSUE TITLE
collapsed code-blocks are easy to miss 

### ISSUE THREAD

**Issue by thaJeztah** [docker/docs#19664]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

There's a problem with the website

### Description

Our docs introduced collapsible code-blocks. While such collapsed blocks look to be useful to "reduce noise" and to distract from the general flow (topic at hand; you may not need all the details yet), the current presentation also makes these blocks easy to miss.

For example, when I was pointed to, https://docs.docker.com/build/ci/github-actions/secrets/#ssh-mounts, I glanced over the example, but while scanning the page, I could not find the related Dockerfile, and it took me some time to discover it (and to understand it was there, but collapsed);

<img width="819" alt="collapsed" src="https://github.com/docker/docs/assets/1804568/481af4e5-5301-48f4-9979-343c29c0fbe2">

Currently, the presentation is either _collapsed_ (only the title shown), or _expanded_ (which can be very verbose);

<img width="818" alt="expanded" src="https://github.com/docker/docs/assets/1804568/05d0d37d-fc38-4cd0-a6c5-c9e59a8b89af">

### Location

https://docs.docker.com/build/ci/github-actions/secrets/#ssh-mounts

### Suggestion

Perhaps we could consider something "in between"; show the first X lines of the code, but with some visual clue "there's more to this!"; e.g. (quick mock-up)

![alternative1](https://github.com/docker/docs/assets/1804568/d5064d69-7b79-4511-bfba-137e174f687d)

**Comment by thaJeztah** [comment]
HEH, I could've saved myself the time creating the mockup by just creating a screenshot from Slack, which does something similar 😂 

<img width="1205" alt="Screenshot 2024-03-22 at 12 16 41" src="https://github.com/docker/docs/assets/1804568/60e1de16-fe79-4b43-ad1b-45f48da4a835">

**Comment by dvdksn** [comment]
I opened #19731  to address this, adding the behavior in the screenshot (click to expand / collapse).
