### ISSUE TITLE
[404]: /reference/builder/

### ISSUE THREAD

**Issue by wkhosa-wizro** [docker/docs#19744]
### Location

https://hub.docker.com/

### Broken link

https://docs.docker.com/reference/builder/?_gl=1*1uhx9un*_ga*Mjg2MTY0MDA0LjE3MTAwNjU3MDc.*_ga_XJWPQMJYHQ*MTcxMjMxMDk3NS4xMS4xLjE3MTIzMTE2NTAuNC4wLjA.

### Comment

I think the link is broken. 
![image](https://github.com/docker/docs/assets/30345487/3b5bf366-c623-4273-8ab4-e80ed5e63d79)

**Comment by dvdksn** [comment]
hi @wkhosa-wizro thanks for reporting the issue. Where on Docker Hub did you find this link?

**Comment by wkhosa-wizro** [comment]
Hi @dvdksn, I found it at this [url](https://hub.docker.com/_/mysql) under **Initializing a fresh instance** section circled in red in the image. 
![image](https://github.com/docker/docs/assets/30345487/51807dc8-2f3f-49b5-844e-f11294623a8d)
