### ISSUE TITLE
Small adjustement in the docs' content

### ISSUE THREAD

**Issue by zhe1ka** [docker/docs#19761]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

"If the you name an environment variable without specifying a value"
=>
"If you name an environment variable without specifying a value"

### Location

https://docs.docker.com/engine/reference/run/#environment-variables

**Comment by dvdksn** [comment]
This is fixed upstream and will be updated with the next engine release.
