### ISSUE TITLE
Install instructions do not work on CentOS/Amazon Linux

### ISSUE THREAD

**Issue by mhweiner** [docker/docs#19803]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

I believe there is an error in the repo configuration:

```
Errors during downloading metadata for repository 'docker-ce-stable':
  - Status code: 404 for https://download.docker.com/linux/centos/2023.4.20240401/aarch64/stable/repodata/repomd.xml (IP: 108.156.172.20)
Error: Failed to download metadata for repo 'docker-ce-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: docker-ce-stable
```

It seems there was a change in the repo location for CentOS as per this thread:

https://stackoverflow.com/questions/70358656/rhel8-fedora-yum-dns-causes-cannot-download-repodata-repomd-xml-for-docker-ce

People in the thread suggest the documentation has been broken since 2 years ago ?!?

I still haven't quite understood what this means yet, or how to resolve the issue. I think it's really sad, concerning and disappointing that the install documentation for such an important project can be this out of date/broken for so long. Insane.

### Location

https://docs.docker.com/engine/install/centos/

**Comment by dvdksn** [comment]
Looks like the same issue as https://github.com/docker/docs/issues/19810#issuecomment-2058456182

**Comment by dvdksn** [comment]
I'm closing this issue since Amazon Linux is not, as of now, a supported distro.
