### ISSUE TITLE
CentOS 7 repo breaks `yum update`

### ISSUE THREAD

**Issue by zjtalia** [docker/docs#19810]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

I am trying to migrate to Compose V2 on Amazon Linux 2 (based on CentOS 7). I ran the command ` sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo` as recommended by the docs, and after doing so `yum update` gives the following error message:
```
failure: repodata/repomd.xml from docker-ce-stable: [Errno 256] No more mirrors to try.
https://download.docker.com/linux/centos/2/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

### Location

https://docs.docker.com/engine/install/centos/

### Suggestion

Verify that the links in the CentOS 7 repository are still valid.

**Comment by dvdksn** [comment]
I don't know much about `yum` but that `/2/` in the repo url seems like the issue. If you look at download.docker.com, these version subpaths represent centos versions, whereas I guess `2` represents the Amazon Linux version, and I gues

https://download.docker.com/linux/centos/

So the links to the centos mirrors are still valid. I don't know if there's a CLI flag or something that you can use with `yum` to override the release version.

**Comment by dvdksn** [comment]
I'm closing this issue since Amazon Linux is not, as of now, a supported distro.
