### ISSUE TITLE
Install process for Debian 12 is broken

### ISSUE THREAD

**Issue by CTI-Tim** [docker/docs#19847]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

if the instructions are followed you get the following error

tim@NVR:~$ sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package docker-ce-cli is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
E: Package 'docker-ce-cli' has no installation candidate
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'
E: Unable to locate package docker-buildx-plugin
E: Unable to locate package docker-compose-plugin

### Location

https://docs.docker.com/engine/install/debian/

### Suggestion

Fix the documentation it so these errors do not occur

**Comment by dvdksn** [comment]
Hello. Looks like maybe you haven't added the Docker APT repository.

```sh
sudo grep -rhE ^deb /etc/apt/sources.list* 
```

**Comment by CTI-Tim** [comment]
It shows it's there...  from the commands on the page ran it entered the bottom one

tim@NVR:~$ sudo grep -rhE ^deb /etc/apt/sources.list* 
deb http://deb.debian.org/debian/ trixie main non-free-firmware 
deb-src http://deb.debian.org/debian/ trixie main non-free-firmware 
deb http://security.debian.org/debian-security/ trixie-security main non-free-firmware 
deb-src http://security.debian.org/debian-security/ trixie-security main non-free-firmware 
deb http://deb.debian.org/debian/ trixie-updates main non-free-firmware 
deb-src http://deb.debian.org/debian/ trixie-updates main non-free-firmware 
deb https://packages.cloud.google.com/apt coral-edgetpu-stable main
deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian   trixie stable

Guessing the step 1 commands are not to be executed as they sit and need to be edited?

**Comment by dvdksn** [comment]
The issue title says Debian 12, but it looks like you're using Debian 13 (testing). There are no packages for Trixie at this time: https://download.docker.com/linux/debian/dists/

**Comment by CTI-Tim** [comment]
AHA Good point.  I installed Debian 12 but made the mistake of updating the distro.  Might be a good note to add to the page to not update debian 12.    Will reinstall and make sure I dont update until after installing docker.

**Comment by CTI-Tim** [comment]
I installed debian 12 but it seems apt-get upgrade forced it to debian 13.   Will reinstall OS and not update anything.
