### ISSUE TITLE
Change the answer to "How can I merge organizations in Docker Hub?" FAQ

### ISSUE THREAD

**Issue by kanwal-kaur** [docker/docs#19943]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The answer content should be changed to reflect more accurate answer.

### Location

https://docs.docker.com/admin/faqs/organization-faqs/

### Suggestion

Hi Team, 
Could we please change this answer to the following or something similar:

Follow the steps below:
1. [Purchase additional seats](https://docs.docker.com/subscription/core-subscription/add-seats/) for the primary organization account you want to keep.
2. Manually move users to primary account and remove the existing users from the secondary account
3. Move over your data manually as well, including all repos. 
4. Once you are done moving over everything, [downgrade](https://docs.docker.com/subscription/core-subscription/downgrade/) secondary account to free tier.

If you are a Business customer with Purchase order, contact Support or your Account Manager at Docker.

**Comment by stephaurelio** [comment]
Will get this updated, thanks for reporting!

**Comment by stephaurelio** [comment]
@kanwal-kaur PR is here: https://github.com/docker/docs/pull/19947 - if you could take a look and review that would be great! I opted to add these steps to the main docs page since we try to keep multi-step content there instead of FAQs, then linked to there from the FAQ page. Had one question for you that I left in the PR. Thanks!

**Comment by craig-osterhout** [comment]
Closing as it looks like this was resolved by the PR linked above.
