### ISSUE TITLE
Documentation about ruby and ruby on rails

### ISSUE THREAD

**Issue by W1ldr** [docker/docs#19957]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

add documentation for Ruby and Ruby on Rails on the official website would be helpful

### Location

https://docs.docker.com/language/

**Comment by vishalbidwe** [comment]
Hi Team,

I would like to work on this issue can you assign this to me?

Thanks!
