### ISSUE TITLE
Script didn't work on ubuntu 20.04

### ISSUE THREAD

**Issue by anguianoa** [docker/docs#20001]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

it references this in the script

https://download.docker.com/linux/debian

This URL didn't exist when I tried to install it

### Location

https://docs.docker.com/engine/install/debian/

### Suggestion

I renamed it to 

https://download.docker.com/linux/ubuntu

and it worked

**Comment by dvdksn** [comment]
You're referencing the installation instruction for Debian, but there's an installation instruction for Ubuntu which points to the correct repository. https://docs.docker.com/engine/install/ubuntu/
