### ISSUE TITLE
docker compose gave a error

### ISSUE THREAD

**Issue by yogved** [docker/docs#20018]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

Error:
$ docker compose up -d
[+] Running 1/1
 ✘ todo-database Error Head "https://registry-1.docker.io/v2/library/mongo/manifests/6": writing response to registry-1.docker.io:443: reading HTTP CONNECT...                      5.5s
Error response from daemon: Head "https://registry-1.docker.io/v2/library/mongo/manifests/6": writing response to registry-1.docker.io:443: reading HTTP CONNECT: unexpected EOF

### Location

https://docs.docker.com/guides/walkthroughs/multi-container-apps/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing this as the content has been removed in favor of the [Docker concepts](https://docs.docker.com/guides/docker-concepts/running-containers/multi-container-applications/) content.
