### ISSUE TITLE
[404]: Edit this page (https://docker-docs.uclv.cu/registry/spec/api/)

### ISSUE THREAD

**Issue by maltfield** [docker/docs#20028]
### Location

https://docker-docs.uclv.cu/registry/spec/api/

### Broken link

https://github.com/docker/docker.github.io/edit/master/registry/spec/api.md

### Comment

I wanted to find the source file for this page, but when I click the "Edit this page" link, it takes me to a 404

 * https://docker-docs.uclv.cu/registry/spec/api/

### Solution

The solution to this is *not* to *just* remove the `Edit this page` link.

The solution to this is to replace the destination of this link to wherever the actual source file lives that's used to generate this page.

### See also

1. https://github.com/docker/docs/issues/6102

**Comment by dvdksn** [comment]
Hi, the url you're using is not the official Docker docs.
