### ISSUE TITLE
Search for "inotify" incorrectly returns 0 results

### ISSUE THREAD

**Issue by benmccann** [docker/docs#20077]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

There's a problem with the website

### Description

I know that this text is present on the website. E.g. it's on https://docs.docker.com/desktop/wsl/best-practices/

### Location

https://docs.docker.com/

**Comment by thaJeztah** [comment]
cc @dvdksn

**Comment by dvdksn** [comment]
We don't have full-text search at the moment.

**Comment by benmccann** [comment]
Huh? What are you searching if not the text?

**Comment by dvdksn** [comment]
This is resolved now btw, we have full-text search, so you can search for `inotify` to your heart's content!
