### ISSUE TITLE
[404]: /go/scout-slack/

### ISSUE THREAD

**Issue by amccarter-JW** [docker/docs#20123]
### Location

https://scout.docker.com/org/<myorg>/settings/integrations/slack/add

### Broken link

https://docs.docker.com/go/scout-slack/

### Comment

Integrations >> Slack >> Documentation >> 404

**Comment by dvdksn** [comment]
🤔 We are still working on this feature, it hasn't been released yet (and neither have the docs, which is why it 404s). I'm curious, how did you end up on this page? `https://scout.docker.com/org//settings/integrations/slack/add`

**Comment by amccarter-JW** [comment]
Ah, apologies! A colleague of mine shared the direct link, and I didn't know this wasn't already GA. Feel free to close this issue if you'd like, since it sounds like it's a known part of development. 😄 Cheers!

**Comment by dvdksn** [comment]
That explains it! Hopefully we can launch this soon, which fixes the 404 :-) closing for now
