### ISSUE TITLE
ADD "--checksum" shows a HTTPS example - but claims only HTTP is supported

### ISSUE THREAD

**Issue by mykaul** [docker/docs#20159]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The example and the text contradict each other:
The --checksum flag lets you verify the checksum of a remote resource:

[ADD](https://docs.docker.com/reference/dockerfile/#add) --checksum=sha256:24454f830cdb571e2c4ad15481119c43b3cafd48dd869a9b2945d1036d1dc68d https://mirrors.edge.kernel.org/pub/linux/kernel/Historic/linux-0.01.tar.gz /
The --checksum flag only supports HTTP sources currently.

What's the point of providing an HTTPS example, when the checksum only supports HTTP?

### Location

https://docs.docker.com/reference/dockerfile/

**Comment by thaJeztah** [comment]
I suspect the intent here was to describe it's only for remote, HTTP(S) sources (and not for files copied from the local build-context).

cc @dvdksn
