### ISSUE TITLE
Proxy arguments need to be updated

### ISSUE THREAD

**Issue by harijsi533** [docker/docs#20172]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Stated info in the doc: 
     "httpProxy": "http://proxy.example.com:3128",
     "httpsProxy": "https://proxy.example.com:3129",
     "noProxy": "*.test.example.com,.example.org,127.0.0.0/8"

This, however, caused Docker to crash when inserting this into daemon.json

### Location

https://docs.docker.com/network/proxy/

### Suggestion

When corrected to the following, works as expected.
     "http-proxy": "http://proxy.example.com:3128",
     "https-proxy": "https://proxy.example.com:3129",
     "no-proxy": "*.test.example.com,.example.org,127.0.0.0/8"

Since this doc is the primary result when searching for Docker proxy config, I would suggest updating this documentation.

**Comment by dvdksn** [comment]
This page describes proxy settings for the Docker client, not the daemon. The daemon proxy configuration is described here https://docs.docker.com/config/daemon/systemd/#httphttps-proxy
