### ISSUE TITLE
[404]: /go/scout-slack/

### ISSUE THREAD

**Issue by zubes1** [docker/docs#20190]
### Location

https://scout.docker.com/

### Broken link

https://docs.docker.com/go/scout-slack/?_gl=1*sf2qi3*_ga*MTI2NzY2ODc3MS4xNzE3OTg3NjQ5*_ga_XJWPQMJYHQ*MTcxNzk4NzY0OC4xLjEuMTcxNzk4ODA3NS42MC4wLjA.

### Comment

This link from scout.docker.com is broken

**Comment by dvdksn** [comment]
Hi, this feature is not released yet, but hopefully soon!
