### ISSUE TITLE
mount/volume options are not explicitly listed

### ISSUE THREAD

**Issue by thedoc31** [docker/docs#20241]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

I'm trying to mount a volume using either `--mount` or `-v` in a container. These mounts need specific permissions. The  doucmentation says
```
The third field is optional, and is a comma-separated list of options, such as ro. These options are discussed below.
```
But there is no table or other useful list `below` in which I can identify all available options. `readonly`, `z`, and `Z` are mentioned, but there's no other information listed like whether or not I can configure a uid/gid or explicit linux permissions (e.g. 0640, 0644, 0755, etc) on a mount inside a container. The documentation for these in `docker run` [1,2], and Bind options [3] is also incomplete in the same way.
[1]
https://docs.docker.com/reference/cli/docker/container/run/#mount
[2]
https://docs.docker.com/reference/cli/docker/container/run/#volume
[3]
https://docs.docker.com/storage/bind-mounts/

### Location

https://docs.docker.com/storage/volumes/

### Suggestion

Add a table which lists all available options that can be added, and whether or not they're supported by `-v` or `--mount`
e.g.

| Option | -v | --mount |
| ------- | -- | -------- |
| readonly | ✅ | ✅ |
| z, Z | ✅ | ❌ |
...

Also, perhaps merge the bind and storage volume pages since they're substantially similar and repeat the same information in two places.

**Comment by mcneilrp1** [comment]
> ### Is this a docs issue?
> * [x]  My issue is about the documentation content or website
> 
> ### Type of issue
> I can't find what I'm looking for
> 
> ### Description
> I'm trying to mount a volume using either `--mount` or `-v` in a container. These mounts need specific permissions. The doucmentation says
> 
> ```
> The third field is optional, and is a comma-separated list of options, such as ro. These options are discussed below.
> ```
> 
> But there is no table or other useful list `below` in which I can identify all available options. `readonly`, `z`, and `Z` are mentioned, but there's no other information listed like whether or not I can configure a uid/gid or explicit linux permissions (e.g. 0640, 0644, 0755, etc) on a mount inside a container. The documentation for these in `docker run` [1,2], and Bind options [3] is also incomplete in the same way. [1] https://docs.docker.com/reference/cli/docker/container/run/#mount [2] https://docs.docker.com/reference/cli/docker/container/run/#volume [3] https://docs.docker.com/storage/bind-mounts/
> 
> ### Location
> https://docs.docker.com/storage/volumes/
> 
> ### Suggestion
> Add a table which lists all available options that can be added, and whether or not they're supported by `-v` or `--mount` e.g.
> 
> Option	-v	--mount
> readonly	✅	✅
> z, Z	✅	❌
> ...		
> Also, perhaps merge the bind and storage volume pages since they're substantially similar and repeat the same information in two places.
