### ISSUE TITLE
invalid argument "host.docker.internal=host-gateway" for "--add-host" flag

### ISSUE THREAD

**Issue by scottmmjackson** [docker/docs#20297]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

`invalid argument "host.docker.internal=host-gateway" for "--add-host" flag`

### Location

https://docs.docker.com/config/daemon/prometheus/

### Suggestion

`--add-host=host.docker.internal:host-gateway`

**Comment by dvdksn** [comment]
The `=` separator is supported since v25.0 https://github.com/docker/cli/pull/4663
