### ISSUE TITLE
Typo in `FromAsCasing`

### ISSUE THREAD

**Issue by FloEdelmann** [docker/docs#20358]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

At the very bottom of the `FromAsCasing` page, there is a link to the `FileConsistentCommandCasing`, but there is a typo in the link text (the URL and target page title are correct):

```diff
- FileConsistenCommandCasing
+ FileConsistentCommandCasing
```

### Location

https://docs.docker.com/reference/build-checks/from-as-casing/

**Comment by dvdksn** [comment]
This was fixed upstream in https://github.com/moby/buildkit/commit/bf1e1557a5fb1c6eaa3709655b2f88c73a93dd24

It will be fixed on the published site with the next buildkit release
