### ISSUE TITLE
Request for more examples for LegacyKeyValueFormat

### ISSUE THREAD

**Issue by AKorezin** [docker/docs#20355]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

The `LegacyKeyValueFormat` is part of the [moby/buildkit](
https://github.com/moby/buildkit/blob/1aee151f6c6a63002b228936d6e76215a8fb8ece/frontend/dockerfile/linter/docs/LegacyKeyValueFormat.md), but it's used in the docker docs. So it's not clear to me where to post about this problem.

I think there should be an example of a multiline `ENV` variable like in the [docker-library/php](
https://github.com/docker-library/php/blob/9cf25725489ff2dd1197d885455d77bbe93a3e8f/8.3/bookworm/apache/Dockerfile#L20-L29).
The php example is pretty simple, because the items are not that long, but the list can be larger, something like
```dockerfile
ENV DEPS \
      "libfreetype6=${FREETYPE_VERSION}" \
      "libjpeg62-turbo=${LIBJPEG_VERSION}" \
      "libmemcached11=${LIBMEMCACHED_VERSION}" \
      "libmemcachedutil2=${LIBMEMCACHED_VERSION}" \
      "libpng16-16=${LIBPNG_VERSION}" \
      "libwebp7=${LIBWEBP_VERSION}" \
      "libzip4=${LIBZIP_VERSION}"

ENV DEV_DEPS \
      "libbz2-dev=${BZIP_VERSION}" \
      "libfreetype-dev=${FREETYPE_VERSION}" \
      "libicu-dev=${ICU_VERSION}" \
      "libjpeg62-turbo-dev=${LIBJPEG_VERSION}" \
      "libldap2-dev=${OPENLDAP_VERSION}" \
      "libmemcached-dev=${LIBMEMCACHED_VERSION}" \
      "libpng-dev=${LIBPNG_VERSION}" \
      "libssl-dev=${OPENSSL_VERSION}" \
      "libwebp-dev=${LIBWEBP_VERSION}" \
      "libzip-dev=${LIBZIP_VERSION}"
```

### Location

https://docs.docker.com/reference/build-checks/legacy-key-value-format/

**Comment by dvdksn** [comment]
Thanks for your feedback! I'll get more examples added. (For future reference, either here or moby/buildkit are both fine places for this kind of feedback!)
