### ISSUE TITLE
Use Docker Compose Tutorial  -- Help Wanted

### ISSUE THREAD

**Issue by pravintargaryen** [docker/docs#20448]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

I am new to Docker and following the Docker Workshop section in the docs. When I tried to replicated the section in https://docs.docker.com/guides/workshop/08_using_compose/. I get the following error. Please advise
![2](https://github.com/user-attachments/assets/7e4184b6-fa2f-4294-84c0-1054c1985425)
 

### Location

https://docs.docker.com/guides/workshop/08_using_compose/

**Comment by vitas76** [comment]
I had a similar problem.
In my case, deleting the app and mysql container + deleting the todo-app network helped. Which I created during the Part 7 workshop: https://docs.docker.com/guides/workshop/07_multi_container/

**Comment by pravintargaryen** [comment]
Thanks the tip @vitas76, will try that out
