### ISSUE TITLE
Error in DOCKER_USERNAME vs. DOCKERHUB_USERNAME

### ISSUE THREAD

**Issue by sjdthree** [docker/docs#20447]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

this line:
3.  Create a new Repository variable named DOCKER_USERNAME and your Docker ID as value.

doesnt match the code later in the file here:

```
          username: ${{ vars.DOCKERHUB_USERNAME }}
```

and causes an error on login.

(also after i fixed that i'm now getting:  "Error: buildx failed with: ERROR: invalid tag "/clockbox:latest": invalid reference format" -- not sure how to fix.

### Location

https://docs.docker.com/build/ci/github-actions/

### Suggestion

pick one:  DOCKERHUB or DOCKER and make consistent.

**Comment by sjdthree** [comment]
Update:  The above "Error: buildx.."  I mentioned was the same issue.  I missed the second DOCKER_USERNAME within the file:

```
          tags: ${{ vars.DOCKERHUB_USERNAME }}/clockbox:latest
```

**Comment by thaJeztah** [comment]
cc @crazy-max

**Comment by thaJeztah** [comment]
Looks like this was fixed in https://github.com/docker/docs/commit/1c15b54316fe003924ec2873b1799ad835282451 (part of https://github.com/docker/docs/pull/20808)
