### ISSUE TITLE
Graphic not what I see: Engine 27.0.3; Compose v2.28.1-desktop.1

### ISSUE THREAD

**Issue by williamtellme123** [docker/docs#20492]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Graphic not what I see: Engine 27.0.3; Compose v2.28.1-desktop.1

### Location

https://docs.docker.com/guides/getting-started/get-docker-desktop/

### Suggestion

Wish I could see what you are showing.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Can you help provide more details or a screenshot of what you expect to see and what you are seeing.
