### ISSUE TITLE
cannot install docker compose v2 on Fedora using your guide

### ISSUE THREAD

**Issue by chipitsine** [docker/docs#20521]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

root@fedora:/home/ilia/boulder# dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
Last metadata expiration check: 0:59:49 ago on Fri 02 Aug 2024 10:26:27 AM CEST.
No match for argument: docker-ce
No match for argument: docker-ce-cli
No match for argument: containerd.io
No match for argument: docker-buildx-plugin
No match for argument: docker-compose-plugin
Error: Unable to find a match: docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
root@fedora:/home/ilia/boulder# 

Fedora 40

### Location

https://docs.docker.com/engine/install/fedora/

### Suggestion

test your guide on Fedora 40, fix it

**Comment by aksaswadkar** [comment]
Did you add the docker-ce repo as given in the guide?
> dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

If it is added, is it enabled?

If I disabled the the "docker-ce-stable" repo I can reproduce the same error as you.
`root@akshay:~# dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
Last metadata expiration check: 3:06:01 ago on Fri 16 Aug 2024 02:04:18 PM IST.
No match for argument: docker-ce
No match for argument: docker-ce-cli
No match for argument: containerd.io
No match for argument: docker-buildx-plugin
No match for argument: docker-compose-plugin
Error: Unable to find a match: docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

root@akshay:~# vim /etc/yum.repos.d/docker-ce.repo 

root@akshay:~# dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
Docker CE Stable - x86_64                                                                               6.6 kB/s | 3.5 kB     00:00    
Dependencies resolved.
========================================================================================================================================
 Package                                Architecture        Version                                 Repository                     Size
========================================================================================================================================
Installing:
 containerd.io                          x86_64              1.7.20-3.1.fc40                         docker-ce-stable               44 M
 docker-buildx-plugin                   x86_64              0.16.2-1.fc40                           docker-ce-stable               14 M
 docker-ce                              x86_64              3:27.1.2-1.fc40                         docker-ce-stable               27 M
 docker-ce-cli                          x86_64              1:27.1.2-1.fc40                         docker-ce-stable              7.8 M
 docker-compose-plugin                  x86_64              2.29.1-1.fc40                           docker-ce-stable               13 M
Installing dependencies:
 container-selinux                      noarch              2:2.232.1-1.fc40                        updates                        55 k
 flatpak-selinux                        noarch              1.15.8-1.fc40                           updates                        23 k
 fuse-overlayfs                         x86_64              1.13-1.fc40                             fedora                         67 k
 libcgroup                              x86_64              3.0-5.fc40                              fedora                         74 k
 nbdkit-selinux                         noarch              1.38.3-1.fc40                           updates                        29 k
 passt-selinux                          noarch              0^20240806.gee36266-1.fc40              updates                        34 k
 rpm-plugin-selinux                     x86_64              4.19.1.1-1.fc40                         fedora                         20 k
 selinux-policy                         noarch              40.27-1.fc40                            updates                        61 k
 selinux-policy-targeted                noarch              40.27-1.fc40                            updates                       6.9 M
 slirp4netns                            x86_64              1.2.2-2.fc40                            fedora                         47 k
 swtpm-selinux                          noarch              0.9.0-1.fc40                            updates                        23 k
Installing weak dependencies:
 docker-ce-rootless-extras              x86_64              27.1.2-1.fc40                           docker-ce-stable              4.0 M

Transaction Summary
========================================================================================================================================
Install  17 Packages
`

**Comment by chipitsine** [comment]
Yep, I messed with adding repo.
