### ISSUE TITLE
Guide doesn't specify that you'll need to clone the Welcome to docker git 

### ISSUE THREAD

**Issue by albrechtjess** [docker/docs#20574]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

I found through the desktop app itself that you need to clone the repository https://github.com/docker/welcome-to-docker to follow through with the guide. 

### Location

https://docs.docker.com/guides/getting-started/get-docker-desktop/

### Suggestion

I'd add a section above Run your first container called "Git your first container" with these instructions: 

Clone the repository at [https://github.com/docker/welcome-to-docker⁠](https://github.com/docker/welcome-to-docker).
using the command git clone https://github.com/docker/welcome-to-docker

The rest of this guide requires you to run commands in the new project directory. Run the following command before moving on.

cd welcome-to-docker

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
If you received an error when running `docker run -d -p 8080:80 docker/welcome-to-docker`, try running it again as intermittent network issues can cause issues. The command will pull and run a pre-built image from Docker Hub. No interaction with GitHub is necessary for this topic.
