### ISSUE TITLE
The sample application has issue

### ISSUE THREAD

**Issue by asfathahamed** [docker/docs#20575]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

when I run `docker compose watch` initially there was a failure because of caniuse tgz file. then I tried running `yarn install` once and then tried running `docker compose watch` the build was success. But the app did not run. In browser I face these issues.

![image](https://github.com/user-attachments/assets/e5b82a52-fa30-4e15-8b29-e5f99619ff0e)

### Location

https://docs.docker.com/guides/getting-started/develop-with-containers/

**Comment by romanstetsyk** [comment]
I've got the same issue. I hope it'll be fixed soon
