### ISSUE TITLE
Buildx concept needs introduction

### ISSUE THREAD

**Issue by Richsl** [docker/docs#20590]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

The term/concept 'buildx' as different or the same as 'build' (I don't know) is introduced without any explaination  

### Location

https://docs.docker.com/build/builders/

### Suggestion

Explain what 'buildx' is

**Comment by dvdksn** [comment]
This is now covered in https://docs.docker.com/build/concepts/overview/
