### ISSUE TITLE
Cannot get to the getGreeting.JS file on 'Develop with Containers' Guide

### ISSUE THREAD

**Issue by JHBlack** [docker/docs#20636]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The `backend/src/routes/getGreeting.js` cannot be found in the backend container of this project. Could there be a more detailed description on how to find that file? The src directory could not be found using the file patch instructions.

![image](https://github.com/user-attachments/assets/fdba4d21-bd8c-48ff-8682-0f8f631d1619)

### Location

https://docs.docker.com/guides/getting-started/develop-with-containers/

### Suggestion

Is there a different filepath to get to the getGreeting.js file?

**Comment by JHBlack** [comment]
I found that the file path on my machine to be on the backend container `usr/local/app/src/routes/getGreeting.js`. May I create a pull request for this change?

**Comment by dvdksn** [comment]
Hello, thank you for creating this issue.

I can see why this might be confusing. The reference in the instruction (`backend/src/routes/getGreeting.js`) assumes that the reader knows that it's the path _relative to the root_ of the _project directory_ on the _host filesystem_.

We need to clarify that:

- The source code files are [shared (bind-mounted)](https://github.com/docker/getting-started-todo-app/blob/da5f2502b8ce04b0905968ebe939d60114f58b4f/compose.yml#L79-L81) between the host and the container.
- The reader is expected to edit the files on the host system, and see those changes propagated through to the container.

If you feel like it, you are more than welcome to raise a PR with these changes @JHBlack. If you do, I'll help you review it.

**Comment by JHBlack** [comment]
Thanks will do. Should I @ you when i create the PR?

**Comment by dvdksn** [comment]
Please do!

**Comment by JHBlack** [comment]
Hey dvdksn,

I can't seem to get the docker compose watch file to work on my branch to do local development. Do you know what I can do to fix it? I get the "configuration file provided: not found"

**Comment by JHBlack** [comment]
Hey got further along, but I'm still stuck on trying to run the local development Docker container. Any chance we could discuss more on Discord?
