### ISSUE TITLE
[404]:  BuildKit extended syntax

### ISSUE THREAD

**Issue by jl-unitedlocating** [docker/docs#20653]
### Location

https://docs.docker.com/compose/compose-file/build/#ssh

### Broken link

https://github.com/compose-spec/compose-spec/pull/234/%5Bmoby/buildkit@master/frontend/dockerfile/docs/syntax.md#run---mounttypessh%5D%28https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md#run---mounttypessh%29

**Comment by dvdksn** [comment]
Indeed, this link looks spectacularly garbled

https://github.com/docker/docs/blob/73f137e77b16b942d25886fb33faa3d7f7e7d0c7/content/reference/compose-file/build.md?plain=1#L509
