### ISSUE TITLE
[404]: /engine/reference/commandline/cli/)%7Bdocumentation%7D

### ISSUE THREAD

**Issue by fastcoder33** [docker/docs#20703]
### Location

https://github.com/enkidevs/curriculum/edit/master/docker/docker-fundamentals/overview/docker-cli.md

### Broken link

https://docs.docker.com/engine/reference/commandline/cli/)%7Bdocumentation%7D

**Comment by thaJeztah** [comment]
It looks like you clicked a link from that repository's Markdown, but it's part of the file's metadata section, and therefore not in the right format to click from GitHub; https://github.com/enkidevs/curriculum/blob/2beaac8ab026e681864efd40f174afc2985c1166/docker/docker-fundamentals/overview/docker-cli.md

![Image](https://github.com/user-attachments/assets/ee535280-c60e-47a3-a4e3-064dbed9a5e1)


The URL you're looking for is `https://docs.docker.com/engine/reference/commandline/cli/`, but that page moved, and now redirects to; the new location https://docs.docker.com/reference/cli/docker/


In either case, this doesn't look to be a bug in the docs.docker.com website, so I'll close this ticket, but feel free to continue the conversation.
