### ISSUE TITLE
docker software not working

### ISSUE THREAD

**Issue by saroo77** [docker/docs#20713]
### Is this a docs issue?

- [ ] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

docker software is not working

### Location

https://docs.docker.com/support/

### Suggestion

docker software is not working

**Comment by saroo77** [comment]
docker software is not working

**Comment by saroo77** [comment]
![Screenshot (13)](https://github.com/user-attachments/assets/bcc61eff-a0fc-4750-bf39-127b5bd00f52)

**Comment by dvdksn** [comment]
Please raise a support ticket or file an issue on the relevant repository.
