### ISSUE TITLE
 Docker Engine stopped

### ISSUE THREAD

**Issue by canada-qu** [docker/docs#20729]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

Please i want to solve the problem of my docker engine unexpected error

### Location

https://docs.docker.com/subscription/core-subscription/details/

### Suggestion

know i have tried everything i could, but no result coming

**Comment by craig-osterhout** [comment]
Hi, for support options, please see https://docs.docker.com/support/
