### ISSUE TITLE
bug: Docker  Install using the apt repository for ubuntu based distros is broken

### ISSUE THREAD

**Issue by Mr-Sunglasses** [docker/docs#20768]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

I'm installing docker engine using apt repository in my Linux mint 22 ( based on Ubuntu), and it is not able to find the `VERSION_CODENAME` for the correct ubuntu, in the apt repository, due to linux mint has its own `VERSION_CODENAME` along with `UBUNTU_CODENAME` .

my `/etc/os-release`

```
NAME="Linux Mint"
VERSION="22 (Wilma)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 22"
VERSION_ID="22"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=wilma
UBUNTU_CODENAME=noble
```

### Location

https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

### Suggestion

I think it's good to change `$VERSION_CODENAME` to `$UBUNTU_CODENAME` to enable support for ubuntu along with all the other distros which are based on ubuntu.

**Comment by dvdksn** [comment]
<img width="793" alt="image" src="https://github.com/user-attachments/assets/1a458f3b-5ac0-4330-ae36-49d85086c402">
