### ISSUE TITLE
Add language specific guide for Bun

### ISSUE THREAD

**Issue by Pradumnasaraf** [docker/docs#20796]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

There is no language-specific guide for **Bun** unlike Go, Node.js, etc.

### Location

https://docs.docker.com/language

### Suggestion

I would like to add this. Already talked with the Docker docs team about this and started working on it.

**Comment by Michila0** [comment]
I like it
