### ISSUE TITLE
[404]: /engine/release-notes/26.1/

### ISSUE THREAD

**Issue by mariushosting** [docker/docs#20818]
### Location

https://docs.docker.com

### Broken link

https://docs.docker.com/engine/release-notes/26.1/#2610

### Comment

All changelogs release notes webpage links under Docker engine version 27 are not more visible since September 9, 2024.

**Comment by mariushosting** [comment]
@usha-mandya

**Comment by dvdksn** [comment]
huh, that's... interesting. thanks for reporting, I'll sort it out
