### ISSUE TITLE
2 Factor Authentication still states beta

### ISSUE THREAD

**Issue by danagilent** [docker/docs#20857]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

2 Factor Authentication still states beta:

### Location

https://docker-docs.uclv.cu/docker-hub/2fa/

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The link you provided is not the official documentation. Please see https://docs.docker.com/security/for-developers/2fa/

**Comment by danagilent** [comment]
Excellent thanks for the confirmation
