### ISSUE TITLE
[404]: /reference/cli/docker/scout/repo/disable/docker%20scout%20repo%20disable%20--all

### ISSUE THREAD

**Issue by Danysharma00** [docker/docs#20872]
I found a broken link : https://docs.docker.com/reference/cli/docker/scout/repo/disable/docker%20scout%20repo%20disable%20--all

**Comment by dvdksn** [comment]
Where did you find this link? I think it's meant to point here: https://docs.docker.com/reference/cli/docker/scout/repo/disable/
