### ISSUE TITLE
Linux Mint installation failed.

### ISSUE THREAD

**Issue by dawadam** [docker/docs#20914]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Linux Mint installation failed.

### Location

https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

### Suggestion

Please read this post : https://forums.linuxmint.com/viewtopic.php?t=414617

**Comment by dvdksn** [comment]
<img width="842" alt="image" src="https://github.com/user-attachments/assets/c22177f5-b8aa-4fa1-9130-b5df9c0b6b79">

<img width="709" alt="image" src="https://github.com/user-attachments/assets/98f4a4e6-702e-4b23-98ff-df049aed4df6">

**Comment by dawadam** [comment]
Thanks, that's clear. :)
