### ISSUE TITLE
Experimental support for RHEL x86_64 and aarch64.

### ISSUE THREAD

**Issue by MarawanAHassaan** [docker/docs#20921]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

1- What is the meaning of experimental and how long till it becomes fully supported?
2- Is it reliable to use in real life production of RHEL 9 systems?
3- Any security implications can occur while using docker containers in production?

### Location

https://docs.docker.com/engine/install/rhel/

**Comment by dvdksn** [comment]
Hello!

> 1- What is the meaning of experimental and how long till it becomes fully supported?

RHEL will be fully supported with the next Docker Desktop release. This includes Docker Engine x86/aarch64 on RHEL.

> 2- Is it reliable to use in real life production of RHEL 9 systems?

Yes! Note that Docker Inc does not provide support for using the Docker Engine as a standalone container runtime. It's an open source project supported by the Moby organization and its maintainers.

> 3- Any security implications can occur while using docker containers in production?

This is a very broad question. As long as you configure and secure your Docker daemon appropriately, there is no reason you couldn't use it to run production containers. No software is immune to security vulnerabilities or misconfiguration.

**Comment by dvdksn** [comment]
Closing as the questions were addressed - feel free to open a new issue if you encounter any problems with Docker on RHEL, or anything else for that matter.
