### ISSUE TITLE
init isn't from the docker commands!

### ISSUE THREAD

**Issue by efoda** [docker/docs#20947]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

just add the required files to the github account!!
docker init doesn't work 

### Location

https://docs.docker.com/guides/language/dotnet/containerize/

### Suggestion

just add the required files to the github account!!

**Comment by dvdksn** [comment]
`docker init` is a CLI plugin included with Docker Desktop, but not the open source Docker Engine and CLI. How are you running Docker?
