### ISSUE TITLE
ERROR 404

### ISSUE THREAD

**Issue by kmoralesj** [docker/docs#20969]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

There's a problem with the website

### Description

```
created by dnf config-manager from https://download.docker.c 326  B/s | 383  B     00:01
Errors during downloading metadata for repository 'download.docker.com_linux_centos_docker-ce.repo_':
  - Status code: 404 for https://download.docker.com/linux/centos/docker-ce.repo~/repodata/repomd.xml (IP: 3.162.199.54)
Error: Failed to download metadata for repo 'download.docker.com_linux_centos_docker-ce.repo_': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

### Location

https://docs.docker.com/engine/install/centos/

### Suggestion

URL incorrecta del repositorio: A veces la URL cambia o está mal configurada. La URL que has usado parece tener una tilde () adicional en el error reportado: docker-ce.repo~/repodata. Debería ser algo como https://download.docker.com/linux/centos/docker-ce.repo sin el símbolo tilde ().

Problemas en el servidor de Docker: Puede haber un problema temporal con los servidores de Docker, aunque es menos probable.

Translation:

> Incorrect repository URL: Sometimes the URL changes or is misconfigured. The URL you have used seems to have an additional tilde () in the reported error: docker-ce.repo~/repodata. It should be something like https://download.docker.com/linux/centos/docker-ce.repo without the tilde symbol ().
> 
> Problems with the Docker server: There may be a temporary problem with the Docker servers, although it is less likely.

**Comment by thaJeztah** [comment]
I think something is mis-configured on your system; the `https://download.docker.com/linux/centos/docker-ce.repo` does exist; not sure where the tilde (`~`) and/or the trailing underscore (`download.docker.com_linux_centos_docker-ce.repo_`) comes from in your case.


What version of CentOS are you running? Note that CentOS 7 and 8 reached EOL, and we no longer build updated packages for those.
