### ISSUE TITLE
Secrets aren't mounted by default, but there is default mount-path

### ISSUE THREAD

**Issue by sik-asn** [docker/docs#20973]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Secrets don't seem to be mounted to `/run/secrets/<id>` by default (in the sense that I don't have to mount them manually).

> By default, secrets are mounted as files located at /run/secrets/<id>. You can customize how the secrets get mounted in the build container using the target and env options for the RUN --mount flag in the Dockerfile.

According to suggestions on the internet, I should explicitly mount the secret if I want to be able to use it `RUN --mount=type=secret...`. 

### Location

https://docs.docker.com/build/building/secrets/#target

### Suggestion

Perhaps it could be made clearer that _the file-location_ has a default value, but that these files aren't mounted by default - you have to mount them explicity when running a command.

**Comment by dvdksn** [comment]
Thanks for the issue, yeah I agree that we can clarify this!

**Comment by sik-asn** [comment]
thanks :)
