### ISSUE TITLE
Example command for building multi-platform appears to be incorrect

### ISSUE THREAD

**Issue by switt4** [docker/docs#21033]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Under the "Build multi-platform images" sub-section in [this page](https://docs.docker.com/build/building/multi-platform/), the example command for building containers for multiple platforms appears to be incorrect:

This is what is in the documenation: `docker build --platform linux/amd64,linux/arm64 .`

This command gives this error: 
```docker build --platform linux/amd64 linux/arm64 .
ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Start a build
```

Should this example command be: `docker buildx build --platform linux/amd64,linux/arm64`?

Thanks.

### Location

https://docs.docker.com/build/building/multi-platform/#build-multi-platform-images

### Suggestion

It appears as if the `buildx` option is missing from this example command.  So, updating it to: `docker buildx build --platform linux/amd64,linux/arm64` should fix the error in the documentation.

**Comment by dvdksn** [comment]
`docker build` is an alias for `docker buildx build`. Both require a positional argument. In this example, that's `.`, declaring the build context to use. Unfortunately it's easy to miss a `.` in an example command. We could change it to `docker buildx build <context>`, but 9 times out of 10 that's `.`, and it's what we usually use as an example.
