### ISSUE TITLE
Mismatch between Dockerfile ARG reference and variable scoping documentation

### ISSUE THREAD

**Issue by srgoni** [docker/docs#21041]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The manual page about build variables describes automatic inheritance of ARGs between stages, but this is nowhere mentioned in the Dockerfile reference.

Variable scoping: https://docs.docker.com/build/building/variables/#scoping

> Once a build argument is declared or consumed in a stage, it's automatically inherited by child stages.

Dockerfile reference: https://docs.docker.com/reference/dockerfile/#scope

> An ARG instruction goes out of scope at the end of the build stage where it was defined. To use an argument in multiple stages, each stage must include the ARG instruction.

This can lead to confusion and unexpected behavior when relying on ARGs being scrubbed between stages.

### Location

https://docs.docker.com/reference/dockerfile/#scope

### Suggestion

Since the behavior described in the build variable manual matches what `docker build` does, it should also be mentioned in the Dockerfile reference.

**Comment by dvdksn** [comment]
Thanks for reporting, the fix has been merged upstream, and will be released with the next BuildKit release 👍🏻
