### ISSUE TITLE
Explain how to set GC policy

### ISSUE THREAD

**Issue by brent-moffit** [docker/docs#21054]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

The description of garbage collection makes it seem very useful, but the example of how to set it using Docker Desktop's JSON config doesn't explain what any of the parameters do.  How do I customize the GC policy?  What do the filters do?  What other options are supported?

### Location

https://docs.docker.com/build/cache/garbage-collection/

### Suggestion

Add info on the schema of the `gc` section, or link to where that info exists elsewhere.

**Comment by dvdksn** [comment]
There will be some changes soon to BuildKit's GC policy configuration. I have had this on my radar for a while, and I think now will be an excellent time to do it, when these new config options arrive.
