### ISSUE TITLE
Docker run page incorrectly describes the --unless-stopped restart policy

### ISSUE THREAD

**Issue by petr-larin** [docker/docs#21071]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Under Restart Policies we read:

> unless-stopped	Restart the container unless it's explicitly stopped or Docker itself is stopped or restarted.

However if we apply this policy and restart Docker, the container WILL restart.

### Location

https://docs.docker.com/reference/cli/docker/container/run/#restart

### Suggestion

Restart the container unless it's explicitly stopped.

**Comment by petr-larin** [comment]
On this page though the description is correct:

**Comment by petr-larin** [comment]
https://docs.docker.com/engine/containers/start-containers-automatically/#use-a-restart-policy

**Comment by dvdksn** [comment]
The fix is merged upstream and will be published with the next release of Docker Engine, so I'm closing this issue.
