### ISSUE TITLE
Running localhost:5000 in chrome doesn't start UI

### ISSUE THREAD

**Issue by Getz007** [docker/docs#21110]
Running localhost:5000 in chrome doesn't start UI

**Comment by thaJeztah** [comment]
Can you provide more information about your ticket? Does this related to an example in our documentation, or something else?

**Comment by Getz007** [comment]
Hello Sebastiaan,

Thank you so much for replying to my question.

I have installed Docker so I can use Frigate to monitor my Ip camera.

I followed the instructions from this link and successfully installed everything.

https://ipv6.rs/tutorial/Windows_10/Frigate/

However, when I try to connect to Localhost:5000 nothing happens.

Please look at the attached screenshots of my Docker page and see if I have done anything wrong.

Thank you

Sam


________________________________

**Comment by dvdksn** [comment]
Closing this issue since it isn't related to the documentation on docs.docker.com. Feel free to reach out to the authors of the tool that you're trying to use to get support.
