### ISSUE TITLE
logging: drivers: json-file

### ISSUE THREAD

**Issue by simaotwx** [docker/docs#21131]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

In section "JSON File logging driver" it says:

> **Warning**
> The json-file logging driver uses file-based storage. These files are designed to be exclusively accessed by the Docker daemon. Interacting with these files with external tools may interfere with Docker's logging system and result in unexpected behavior, and should be avoided.

This is confusing and likely incorrect. Why would someone want to log to JSON but not access the log files?
Isn't the point of logging to be able to read them?

Accessing a file includes `open` (and optionally, a `read` and/or `write` follows), so saying that the files are designed to be *exclusively **accessed** by the Docker daemon* contradicts the purpose of log files.

If it's okay to read from the log files, the documentation should be changed to reflect that, otherwise, the warning needs to be more clear and mention that even opening and reading from the file is bad.

### Location

https://docs.docker.com/engine/logging/drivers/json-file/

**Comment by simaotwx** [comment]
The page https://docs.docker.com/engine/logging/drivers/local/ has the same wording, it probably needs more clarity as well.

**Comment by dvdksn** [comment]
@thaJeztah do you have more context on this warning?

**Comment by thaJeztah** [comment]
Yes, the information is accurate; those files are not meant to be used by other tools. While it's not _impossible_ to consume those files, we're aware of various tools that do so, we also know that such tools have been at the root of various issues in doing so.

> contradicts the purpose of log files.

The json-file is the storage mechanism used by the daemon, and intended to provide reading back logs through the [logs API](https://docs.docker.com/reference/api/engine/version/v1.47/#tag/Container/operation/ContainerLogs).

If you want to aggregate logs in other tooling, the best option is to use one of the available logging driver, which allow sending logs to a log-aggregator, or to your system's [syslog](https://docs.docker.com/engine/logging/drivers/syslog/) or [journald](https://docs.docker.com/engine/logging/drivers/journald/)
