### ISSUE TITLE
parent image glossary link is broken

### ISSUE THREAD

**Issue by jessepanorama** [docker/docs#21216]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

In the [dockerfile reference](https://docs.docker.com/reference/dockerfile/), under the **Format** header, there is a broken link to a definition of the term "parent image". This link is in a sentence reading "The FROM instruction specifies the [parent image](https://docs.docker.com/glossary/#parent-image) from which you are building" but clicking that link arrives at a glossary page with no entry for the term "parent image".

### Location

https://docs.docker.com/reference/dockerfile/

**Comment by dvdksn** [comment]
Fix merged upstream, will be published with the upcoming BuildKit release.
