### ISSUE TITLE
Update the multi-stage builds Docker concept to not require Java

### ISSUE THREAD

**Issue by sbenhoff007** [docker/docs#21222]
Page to update: [https://docs.docker.com/get-started/docker-concepts/building-images/multi-stage-builds/)](https://docs.docker.com/get-started/docker-concepts/building-images/multi-stage-builds/)

This page uses a hands-on exercise that requires Java. @dvdksn has requested that we rewrite this concept so that Java is not required.

**Comment by dvdksn** [comment]
cc @ajeetraina could you PTAL at this one

**Comment by ajeetraina** [comment]
Look like Java is not a prerequisite here. I will raise PR and get the prerequisite removed.
