### ISSUE TITLE
bug: Search icon is overlapping on mobile view.

### ISSUE THREAD

**Issue by geekyharsh05** [docker/docs#21253]
### Is this a docs issue?

- [x] My issue is about the responsiveness of the website

### Description

On Mobile View The Search Icon is overlapping

![Image](https://github.com/user-attachments/assets/f77f4aaa-af23-4f88-bdff-bf85cf9b4062)

### Location

https://docs.docker.com/reference/dockerfile/

**Comment by thaJeztah** [comment]
Thanks for reporting!

@dvdksn looks like the same issue I reported on Slack last week

**Comment by dvdksn** [comment]
Fixed in https://github.com/docker/docs/pull/21260
