### ISSUE TITLE
sudo apt-get install ./docker-desktop-amd64.deb Command Doesn't Work

### ISSUE THREAD

**Issue by toobad3** [docker/docs#21296]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

THE COMMAND  sudo apt-get install ./docker-desktop-amd64.deb comes back with an error unsupported file.

### Location

https://docs.docker.com/desktop/install/linux/ubuntu/

**Comment by swivelmargarita** [comment]
Would you please provide a output of the command `sudo apt-get install ./docker-desktop-amd64.deb` so it is possible to understand what went wrong?

**Comment by toobad3** [comment]
Reading package lists... Done
E: Unsupported file ./docker-desktop-arm64.deb given on commandline.

**Comment by toobad3** [comment]
Ops

**Comment by toobad3** [comment]
Ops

**Comment by toobad3** [comment]
Ops

**Comment by MatchaMusturd** [comment]
same issue
