### ISSUE TITLE
Potential Typo in 'Getting Started' Guide: 'Each layer represents' vs. 'Each layer represented'

### ISSUE THREAD

**Issue by Camilo716** [docker/docs#21309]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Other

### Description

Hi! I was reading the "Getting Started" guide in the documentation and noticed a potential typo. In this line:

> "Each layer **represented** a set of file system changes that..."

I believe it should say:

> "Each layer **represents** a set of file system changes that..."

Is this correct, or have I misunderstood the intended message?

Thank you!

https://github.com/docker/docs/blob/e228236ce243c43309ff5e29ecc2f543507db2a5/content/get-started/docker-concepts/the-basics/what-is-an-image.md?plain=1#L26

### Location

https://docs.docker.com/get-started/docker-concepts/the-basics/what-is-an-image/

**Comment by dvdksn** [comment]
You're reading it correctly! Will fix this typo; thanks for catching it.
