### ISSUE TITLE
Dockerfile reference has duplicate parser directive section

### ISSUE THREAD

**Issue by t-dub** [docker/docs#21315]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

There is a duplicate "the following parser directives are supported" section on the [dockerfile reference](https://docs.docker.com/reference/dockerfile/) page.  The duplicate is incomplete, unlinked, and appears to simply be a leftover from a previous revision of the page that never got cleaned up.  I made a [PR](https://github.com/docker/docs/pull/21314) before I realized that it wasn't something to be maintained in the docs repo 😅 

### Location

https://docs.docker.com/reference/dockerfile/

**Comment by ender700** [comment]
@ #

> [``](url)

**Comment by sarahsanders-docker** [comment]
Thanks for reporting @t-dub! Getting this updated, see https://github.com/docker/docs/pull/21332 for more info

**Comment by dvdksn** [comment]
hi @sarahsanders-docker, OP already opened #21314 to address this one. Both of these PRs are currently updating a vendored file however, we need to update the file upstream, see: https://github.com/docker/docs/pull/21314#pullrequestreview-2413172765

**Comment by dvdksn** [comment]
Closed in https://github.com/moby/buildkit/pull/5527
