### ISSUE TITLE
Redis image tags in Docker Swarm tutorial no longer available

### ISSUE THREAD

**Issue by ithacamurals** [docker/docs#21330]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

`redis:3.0.6` as mentioned [here](https://docs.docker.com/engine/swarm/swarm-tutorial/rolling-update/) is no longer available on DockerHub.  A newer version would work instead.

### Location

https://docs.docker.com/engine/swarm/swarm-tutorial/rolling-update/

### Suggestion

Use `redis:7.4.0` and upgrade to `redis:7.4.1` during the tutorial.

**Comment by ithacamurals** [comment]
The image tag will need to be updated here as well to be consistent https://docs.docker.com/engine/swarm/swarm-tutorial/drain-node/

**Comment by dvdksn** [comment]
Oof, those are some old tags :-) Thanks for pointing it out!
