### ISSUE TITLE
getting-started - part8 image building - image tag

### ISSUE THREAD

**Issue by mjbear** [docker/docs#21391]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Hello!

I noticed that part1 (or part02 as the Markdown name is) refers to `node:lts-alpine` image tag.

**Later on in part8 (or part09), there are references to `node:18` tag.**
I think these could be changed up to be an `node:lts-alpine` tag, but wanted to ask first.
(I've already started a fork so given guidance I'd be glad to submit a PR! :rocket:)

Thank you!

https://docs.docker.com/get-started/workshop/09_image_best/#react-example
https://github.com/docker/docs/blob/main/content/get-started/workshop/09_image_best.md#react-example

### Location

https://docs.docker.com/get-started/workshop/09_image_best/#react-example

### Suggestion

See above description for details.

`node:lts-alpine` image tag

**Comment by dvdksn** [comment]
hi @mjbear - you are absolutely correct! I recently changed it from 18 to alpine, but seems I missed a spot. We'll gladly take your PR to fix it!

**Comment by mjbear** [comment]
Sure enough there's a `lts` tag in addition to the `lts-alpine` for the node image.
https://hub.docker.com/_/node/tags?name=lts&ordering=-name

* In one commit I changed all the `18-alpine` to `lts-alpine`.
* Next commit comes along as a (lazy) sync merge from the GitHub webui. :neutral_face:
   * While cherry-picking should be possible, I can locally fix the commit history if needed (though you'll probably squash merge anyway).
* And finally the `node:18` to `node:lts`

Submitted PR #21424
