### ISSUE TITLE
Only running containers with Docker Engine binaries on Windows Server?

### ISSUE THREAD

**Issue by mtautra** [docker/docs#21478]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The documentation for installing the Docker Engine binaries for Windows Server only talks about the ability to run containers. However, with the docker client and the docker daemon you can also build containers, correct? Can this be clarified in the documentation please?

Background: Have been trying to understand how you support building container images in a windows server environment. Docker Desktop is only for Windows 10 and 11, so what are the officially supported options for servers?

### Location

https://docs.docker.com/engine/install/binaries/

**Comment by dvdksn** [comment]
Hello. The open source Docker Engine, incl. the Windows builds of dockerd, are supported by the Moby project https://docs.docker.com/engine/install/#support

For more information, I suggest you try using the moby/moby [issue tracker](https://github.com/moby/moby) or the community slack.

Docker Desktop is the only officially supported Windows product from Docker.
