### ISSUE TITLE
[404]: /build/guide/intro/

### ISSUE THREAD

**Issue by Pafo-carlos** [docker/docs#21489]
### Location

android-app://com.linkedin.android/

### Broken link

https://docs.docker.com/build/guide/intro/

### Comment

Erreur 404 le lien n'existe plus j'aimerais y accéder à la ressource.

**Comment by dvdksn** [comment]
The build guide on the above URL does not exist anymore, but you can try this one: https://docs.docker.com/get-started/docker-concepts/building-images/
