### ISSUE TITLE
It is not clear which instruction installing QEMU using binfmt for platform emulation is the up to date one.

### ISSUE THREAD

**Issue by YutaHiguchi-bsn** [docker/docs#21486]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

It is not clear which instruction installing QEMU using binfmt for platform emulation is the up to date one.

In the [Install QEMU manually](https://docs.docker.com/build/building/multi-platform/#install-qemu-manually) section, instruction suggests installing them using `tonistiigi/binfmt`.
But in the official [blog post from 2020](https://www.docker.com/blog/multi-platform-docker-builds/)
it uses specific image from docker/ `docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64`.

This docker/binfmt hasn't been updated for 5 years, 
and when I look at the GitHub repo https://github.com/docker/binfmt, they are now archived pointing towards linuxkit.

Linuxkit seem to have their image published as [linuxkit/binfmt](https://hub.docker.com/r/linuxkit/binfmt).

What is the current recommended way to setting up the environment for multi-platform build using emulation?

### Location

https://docs.docker.com/build/building/multi-platform/

**Comment by dvdksn** [comment]
Hello. The current recommended approach is to use the method described in the docs, with the `tonistiigi/binfmt` image run as a privileged container.
