### ISSUE TITLE
Instrucciones incorrectas para la instalación en Ubuntu

### ISSUE THREAD

**Issue by karapanza** [docker/docs#21491]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Las instrucciones para la instalación de Docker en Ubuntu no mencionan la necesidad de actualizar el índice de paquetes antes de la instalación.

### Location

https://docs.docker.com/get-started/get-docker/

### Suggestion

Agregar el comando sudo apt-get update antes de sudo apt-get install docker-ce docker-ce-cli containerd.io.

**Comment by dvdksn** [comment]
It's right there in step 1 https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

**Comment by karapanza** [comment]
thanks
