### ISSUE TITLE
RE: JSONArgsRecommended

### ISSUE THREAD

**Issue by totszwai** [docker/docs#21563]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

Following up of https://github.com/docker/docs/issues/21219

Followed the example to the dot:
```
# Entrypoint wrapper script
COPY --chmod=755 <<EOT /entrypoint.sh
#!/usr/bin/env bash
set -e
service rsyslog start
service dbus start
bash
EOT

ENTRYPOINT ["/entrypoint.sh"]
```

It looks like launching it such way, doesn't work... does it make any difference whether I am using Docker Desktop or Docker CLI..? 

I am building and launching it this way in `package.json`:
```
"switch-linux": "DockerCli.exe -SwitchLinuxEngine",
"switch-windows": "DockerCli.exe -SwitchWindowsEngine",
"build-ubuntu18": "npm run switch-linux &&  docker build -t test-ubuntu18 -f Ubuntu18-04.Dockerfile .",
"ubuntu18": "npm run switch-linux && cross-env-shell docker run --hostname=localhost.test --cap-add=NET_ADMIN -it --rm test-ubuntu18",
```

I had no trouble launching it with the old `ENTRYPOINT` syntax, but it refuse to run using the `JSONArgsRecommended` syntax, the error I am getting:

```
exec /entrypoint.sh: exec format error
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: spawn docker ENOENT
    at notFoundError (C:\source\docker\test\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\source\docker\test\node_modules\cross-spawn\lib\enoent.js:40:16)
    at cp.emit (C:\source\docker\test\node_modules\cross-spawn\lib\enoent.js:27:25)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
Emitted 'error' event on ChildProcess instance at:
    at cp.emit (C:\source\docker\test\node_modules\cross-spawn\lib\enoent.js:30:37)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn docker',
  path: 'docker',
  spawnargs: [
    'run',
    '--hostname=localhost.test',
    '--cap-add=NET_ADMIN',
    '-it',
    '--rm',
    'test-ubuntu18'
  ]
}

Node.js v21.6.2
```

### Location

https://docs.docker.com/reference/build-checks/json-args-recommended/

**Comment by dvdksn** [comment]
I'm not a Windows guy but I wonder if `exec format error` could mean the script has Windows line endings. You could try running your Dockerfile through dos2unix or similar to make sure the heredoc doesnt have Windows line endings. I'm afraid I can't help you with how `npm`, `DockerCli.exe` and other programs you use interact with each other. I suggest you try the Docker forums or slack.
