### ISSUE TITLE
Unable to disable inter-container connectivity by setting network.bridge.enable_icc false in docker 20.10.17

### ISSUE THREAD

**Issue by syedwasim1107** [docker/docs#21634]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Other

### Description

I wanna disbale inter-container connectivity. I tried setting enable_icc flag to false. Still one docker is able to reach to another 
Please let me know what setting should i set to disable it 

### Location

https://docs.docker.com/engine/network/drivers/bridge/

**Comment by syedwasim1107** [comment]
FYI : 
docker daemon.json is set with iptables:false

**Comment by dvdksn** [comment]
Hi, please raise an issue on [moby/moby](https://github.com/moby/moby) instead. FYI, your Docker version is really old, you'll probably have to reproduce it on a recent version, e.g., 27.4.0
