### ISSUE TITLE
"Emptry" typo

### ISSUE THREAD

**Issue by torchiaf** [docker/docs#21687]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

There is an `Emptry` typo in https://github.com/docker/docs/blob/2742bbaca88993249619e0c700385dd15137bc93/content/manuals/build/images/build-variables.svg?plain=1

### Location

https://docs.docker.com/build/building/variables/

**Comment by dvdksn** [comment]
Thanks for spotting
