### ISSUE TITLE
Add examples, more documentation around health checks  

### ISSUE THREAD

**Issue by thaJeztah** [docker/docs#3282]
### Problem description

Healthchecks are a powerful feature, but the documentation is currently sparse. There is some basic information on its usage in the [`builder documentation`](https://github.com/moby/moby/blob/83a4afe2645d2e39cf6b10a86e9e681a7ff06eb2/docs/reference/builder.md#healthcheck), and the flags are included in the [`docker container run`](https://github.com/moby/moby/blob/ebe0a489a5cc66406345f1aafa0f2f866fd64172/docs/reference/commandline/run.md) and [`docker service create`](https://github.com/moby/moby/blob/5fc912d2c87c1986e830a7d4f6b62bec385e9a14/docs/reference/commandline/service_create.md) command line reference, but no practical examples are included in the documentation.

### Suggestions for a fix

Docker 17.05 and up adds additional options for health checks (start period), and I wrote a comment on that pull request to illustrate the functionality which may be useful as a starting point https://github.com/moby/moby/pull/28938#issuecomment-301736698, https://github.com/moby/moby/issues/35881#issuecomment-356619230, and I saw @tomwillfixit has a demo repository to show health checks (https://github.com/tomwillfixit/healthcheck).

Those examples are very basic, but can be useful in itself (possibly we may want to add a "real" example as well).

/cc @mstanleyjones 

also /cc @dongluochen @tianon who may be able to provide more information on this subject 👍

**Comment by mikesir87** [comment]
If I were to contribute some documentation, any recommendation on where that documentation should go? Since it appears, as you mentioned, in the builder, container run, and service create, should the healthchecks be their own page that each of those link to?  Thoughts?

**Comment by mistyhacks** [comment]
This would be a great contribution! As a first guess, I'd say that it should go under the "Run your app in production" top-level item in the TOC. As far as where to put it in the filesystem, `/engine/admin/` might be a good home, for now. We can decide this in the PR at any time -- I can always commit with you and help you get it into the right place. Thanks!

**Comment by L-Hudson** [comment]
Closing this ticket due to its age, and the impending refactor. If you think this is in error, feel free to reopen. Thanks!
