### ISSUE TITLE
The docs for docker-compose ps do not match the --help page

### ISSUE THREAD

**Issue by nerdkid93** [docker/docs#7289]
Running `docker-compose ps --help` for `docker-compose version 1.21.2, build a133471` shows that there are 3 possible CLI arguments, but the docs only show the `-q` argument, omitting documentation on how to use `--filter` and `--services`.

File: [compose/reference/ps.md](https://docs.docker.com/compose/reference/ps/)

**Comment by nerdkid93** [comment]
This is probably a dup of #7173

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. The docs now contain the arguments.
