### ISSUE TITLE
Make clearer what a legacy plugin is

### ISSUE THREAD

**Issue by SimonHeimberg** [docker/docs#7320]
File: [engine/extend/legacy_plugins.md](https://docs.docker.com/engine/extend/legacy_plugins/)

Only the url shows the word legacy. If it is really legacy, please add the word at least to the title.
And I do not see any explication about why the plugins are legacy. This should somewhere also.

**Comment by nigelpoulton** [comment]
Thanks @SimonHeimberg 

I'll look into adding something like the following to the top of the doc:

This document refers to the legacy plugin system available in Docker Engine 1.12 and earlier. For information on the new _managed plugin system_, see https://docs.docker.com/engine/extend/plugin_api/ and https://docs.docker.com/v17.09/engine/extend/

I'll also see about getting the title of the doc changed to something like **Legacy Docker Engine plugins**
