### ISSUE TITLE
After docker install traffic can not cross existing bridges

### ISSUE THREAD

**Issue by tharple** [docker/docs#7370]
File: [network/iptables.md](https://docs.docker.com/network/iptables/)
Real server running latest debian KVM/QEMU connecting VMs to br0.
Install docker, traffic not longer allowed thru bridge.
Please add something besides "Don't change dockers iptables rules, add your own...
dockers iptables assumptions during install caused the issue someone should document it.
Just my 2 cents. May be the wrong place, but I was only looking for documentation on the docker iptables rules so that I customize them so that they don't mess with my existing system.

**Comment by gustavosr98** [comment]
Seems related to https://serverfault.com/questions/963759/docker-breaks-libvirt-bridge-network

I am hitting this too with
- Ubuntu 20.04
- Docker snap 20.10.12
- libvirt version: 6.0.0 package 0ubuntu8.8  
- qemu version: 4.2.1Debian 1:4.2-3ubuntu6.14
- kernel: 5.4.0-70-generic
