### ISSUE TITLE
More detail in --filter

### ISSUE THREAD

**Issue by arnauvc** [docker/docs#7424]
File: [engine/reference/commandline/ps.md](https://docs.docker.com/engine/reference/commandline/ps/)

It should be stated whether is OR / AND when using more than one filter.
Some logical expressions would be great, for example:  --filter status!=running

Much appreciated

**Comment by nigelpoulton** [comment]
Two things @arnauvc 

1. The logical expressions thing is a great idea, but more of a feature request than something related to docs
2. The OR/AND thing has me scratching my head. It's late here, but it seems to be an AND operation when combining multiple filters, such as a `status` filter and an `is-task` filter.  But if you combine two of the same filter on the same command it acts differently.

E.g.

`docker ps --filter is-task=true --filter status=running` appears to be an AND.

Whereas

`docker ps --filter status=running --filter status=dead` is not an AND or an OR, at least so far as I see it.
