### ISSUE TITLE
Django with python 3 docker image crashing

### ISSUE THREAD

**Issue by ifalex** [docker/docs#7508]
### Problem description

In django documentation (https://github.com/docker/docker.github.io/blob/master/compose/django.md) using the docker image for python 3 will lead to an error:

```
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/widgets.py", line 152
web_1  |     '%s=%s' % (k, v) for k, v in params.items(),
web_1  |     ^
web_1  | SyntaxError: Generator expression must be parenthesized
```
Point to python 3.6 instead, maybe.

### Problem location

- I saw a problem on the following URL: <URL>
https://github.com/docker/docker.github.io/blob/master/compose/django.md

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

### Suggestions for a fix

Modify Dockerfile to point to python 3.6 instead of generic python 3 which will download the latest version.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as this content is no longer contained in the docs.
