### ISSUE TITLE
network/iptables looks a bit outdated

### ISSUE THREAD

**Issue by soulne4ny** [docker/docs#7575]
File: [network/iptables.md](https://docs.docker.com/network/iptables/)

It mentions DOCKER-USER that is missing in real with docker 18.06.1-ce,
and tells nothing on DOCKER-ISOLATION-STAGE-[12].

**Comment by Perdjesk** [comment]
Reference for docker isolation stages documentation:
https://github.com/docker/libnetwork/blob/5b9fe1e1628d6077d1ba7a8c9a4310d09c8702ed/drivers/bridge/setup_ip_tables.go#L16
