### ISSUE TITLE
Change redis volume in docker-compose.yml

### ISSUE THREAD

**Issue by bpringe** [docker/docs#7700]
File: [get-started/part5.md](https://docs.docker.com/get-started/part5/)

The docs say

```
volumes:
      - "/home/docker/data:/data"
```

But the recap video at the end of the tutorial, and what worked for me, is

```
volumes:
      - ./data:/data
```

I'm not sure if the lack of double quotes matters but I didn't put them in mine and they weren't in the recap video.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as this appears to be no longer applicable.
