### ISSUE TITLE
Incomplete manual installation instructions for Ubuntu

### ISSUE THREAD

**Issue by lfielke** [docker/docs#7725]
There appears to be some missing steps in the Ubuntu "Install from a package" instructions for the latest version of the Ubuntu Xenial packages (`docker-ce_18.09.0~3-0~ubuntu-xenial_amd64`).

File: [install/linux/docker-ce/ubuntu.md](https://docs.docker.com/install/linux/docker-ce/ubuntu/)

The instructions say to "Download the .deb file for the Docker version you want to install.", which I took as download the highest version numbered docker-ce deb file, which currently is:
https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_18.09.0~3-0~ubuntu-xenial_amd64.deb

The next instruction is to install this deb using dpkg:
`$ sudo dpkg -i /path/to/package.deb`
however this package depends on two other docker packages: `docker-ce-cli` and `containerd.io`, and that command fails with message:
```
dpkg: dependency problems prevent configuration of docker-ce:
 docker-ce depends on docker-ce-cli; however:
  Package docker-ce-cli is not installed.
 docker-ce depends on containerd.io; however:
  Package containerd.io is not installed.
```

I think the instructions should be made clearer that these two packages need to be installed first.

This may have only become an issue with this version, as the previous deb file (`docker-ce_18.06.1~ce~3-0~ubuntu_amd64.deb`) doesn't depend on those two packages.

**Comment by JorgeRSG** [comment]
Hi @lfielke, did ou manage to get the other required packages? I'm not sure where to get them.

**Comment by lfielke** [comment]
Yes, I downloaded those other two packages from the same directory as the main deb file. Which you can get from the first instruction on https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-from-a-package

This got me to this directory, with `docker-ce-cli_*.deb` and `containerd.io_*.deb`:
https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/

After downloading these, I installed them with `sudo dpkg -i ...`. It's been a while, so I can't remember if there was a specific installation order required for these two.
