### ISSUE TITLE
Provide command to reset repository state.

### ISSUE THREAD

**Issue by kavikat** [docker/docs#7901]
File: [engine/security/trust/trust_key_mng.md](https://docs.docker.com/engine/security/trust/trust_key_mng/)

Currently, documentation suggests customers contact support to reset repo state. All support does is provide users with the following command, why is this "tribal knowledge"?

> Any account with admin access to the repository should be able to reset it using the account with the command: 'notary delete -s https://notary.docker.io docker.io/<namespace>/<repository> --remote'

**Comment by kizbitz** [comment]
Adding link to slack conversation we had in 2017: https://docker.slack.com/archives/C02FVEK5M/p1498494855883975
