### ISSUE TITLE
Documentation still explaining devicemapper support although devicemapper support has been removed

### ISSUE THREAD

**Issue by meyca** [docker/docs#7929]
File: [storage/storagedriver/device-mapper-driver.md](https://docs.docker.com/storage/storagedriver/device-mapper-driver/)

That documentation should be deleted.

see Pull request https://github.com/docker/cli/pull/1424

**Comment by thaJeztah** [comment]
The driver is marked deprecated, which is a notice that it will be removed at some point in the future, however it's still supported

**Comment by CarstenMeyer** [comment]
https://github.com/docker/for-linux/issues/452#issuecomment-437232948

At least it has been removed in debian-ce for stretch... I just ran into that... :-(

**Comment by CarstenMeyer** [comment]
Switching to overlay2 and recreating containers was a lot of work but solved the problem for me. 

Regarding the referenced documentation I would at least suggest a (first?) paragraph like:

Note: As of Docker 18.09 support for Device Mapper storage driver is deprecated and will be removed in a future release (s. Deprecation Notice in Release Notes for 18.09; https://docs.docker.com/engine/release-notes/#1809).

**Comment by thaJeztah** [comment]
> At least it has been (and still is) removed in docker-ce for debian stretch... I just ran into that... :-(

Ah, yes, I think that was a packaging issue, not sure what the status is on that one

> Regarding the referenced documentation I would at least suggest a (first?) paragraph like:

A note was added on the "Select a Storage Driver" page; https://docs.docker.com/storage/storagedriver/select-storage-driver/#docker-engine---community

<img width="919" alt="screen shot 2018-12-27 at 20 42 04" src="https://user-images.githubusercontent.com/1804568/50492436-e55b4400-0a17-11e9-8989-a70979a225b9.png">


But I agree that a note on the devicemapper page would be good to have; perhaps it's being worked on (there's work in progress for the legacy overlay storage driver https://github.com/docker/docker.github.io/pull/7803)

**Comment by meyca** [comment]
https://docs.docker.com/storage/storagedriver/device-mapper-driver/#prerequisites

is still omitting deprecation information.
