### ISSUE TITLE
Indicate that swarm restore requires restoring to the same IP address

### ISSUE THREAD

**Issue by trapier** [docker/docs#7931]
### Problem description

Please add a note to https://docs.docker.com/engine/swarm/admin_guide/#restore-from-a-backup

That indicates swarm **must** be restored to a host with the same IP address.

In other words, one cannot take a backup from an environment and restore it to an environment with different IP addresses.

See https://github.com/docker/swarmkit/issues/642 for more information.

**Comment by nigelpoulton** [comment]
@aaronlehmann @aluzzardi @wsong @TheJeztah Anyone know if this is still the case? I know htere's been talk around ability to change IPs of managers and the likes...

The doc is talking through the process of backing up a swarm and restoring it.

The process in the docs basically says, copy the `/var/lib/docker/swarm` directory somewhere, restore it to a new host, start Docker on the new host, force a new cluster with `docker swarm init --force-new-cluster`, add more managers and nodes, drink beer.

Does the requirement for the restore to be to a manager node with the same IP as the original??

Cheers.

**Comment by wsong** [comment]
I believe that that is still a requirement for Swarmkit restores, yes. Ping @dperny to confirm.

**Comment by thaJeztah** [comment]
Yes, I don't think anything changed in this area
