### ISSUE TITLE
Misleading information under docs.docker.com/install

### ISSUE THREAD

**Issue by Dxvid** [docker/docs#8000]
The information under docs.docker.com/install is misleading and will probably not suit most people who want to install Docker CE. There's a lot of thumbs down on several of the pages there, and not without a good reason.
https://docs.docker.com/install/

First of all, most people will want to use a stable version of Docker CE which is tested and compatible with their Linux distro, NOT go through the hassle of uninstalling the tested stable version, then have the choice of installing nightly or test. Some people MIGHT however want to install the latest stable version from Docker's own repo, but only if the distro doesn't already provide the latest version in their own repo.
 
Secondly, people who need to read documentation for installing docker ce are most likely not experienced sysadmins and might only understand half of the information and might end up following totally unnecessary steps when their distro already offers the latest stable version of docker for them or a previous stable version of docker ce which will suit them well. For example OpenSUSE makes it super easy for beginners to install both the official tested version for the distro version, or the latest stable version of docker ce here on the web: https://software.opensuse.org/package/docker or in a graphical tool called yast2 that works both on servers with ascii graphics and on desktops running X or Wayland graphics. Other Linux distros also already provide Docker CE in a much more user friendly way than what is described at docs.docker.com

Thirdly, the information is very misleading making people believe that docker ce is only available on servers running CentOS, Ubuntu, Fedora or Debian.
https://docs.docker.com/install/linux/docker-ce/centos/
This is of course not true, docker ce runs fine under any Linux distro who packages it and makes it available to their users. There's many distros who could run docker ce just fine and without complicated changes of repositories and uninstallation of the official packages.

Solution:
The text should be changed so that beginners are encouraged to use the repos provided by their distro as primary choice, with information that installing nightly or test builds is strongly discouraged for production or for anyone not being a beta tester of future docker versions, and the information should be that Docker also provides it's own builds for Ubuntu, Debian, Fedora and CentOS, but there are TONS of other distros who can run Docker CE and in a much more user friendly way. Maybe also provide links to all the excellent distros out there who provide Docker CE?

**Comment by lloydie** [comment]
I second this sentiment, although i would not charaterise the imformation as very misleading. "The django getting started guide" takes the cake for totally misleading.
That said i would be happy to test and help making the onboarding process with docker-ce as simple as possible.

Identify misleading / incorrect information should be triaged to. boot2docker.iso version issue is absolutely incorrect and without some further investigation it is not possible to follow the guide without failure.

I have a install script with takes a few consideration but no were near release.
