### ISSUE TITLE
Windows daemon.json does not show log-opts as an available option

### ISSUE THREAD

**Issue by drnybble** [docker/docs#8047]
File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/)

Is 'log-opts' really not available for Windows?

**Comment by L-Hudson** [comment]
@drnybble, I think this is probably better asked in forums instead of docs, unless there's a specific ask for the documentation?

**Comment by L-Hudson** [comment]
Gotcha. Moving this into queue, thanks!

**Comment by uditjh** [comment]
It's not working for me as well. What am I missing? I'm running the latest docker engine.

![image](https://user-images.githubusercontent.com/7944262/54327687-5c4cb580-45e1-11e9-8b59-7e05dcab2434.png)

**Comment by nigelpoulton** [comment]
I've just tested my laptop, and Docker Desktop allows `log-opts` in Linux containers mode, but rejects it in Windows containers mode. This behavior supports the current state of the docs. 

Obviously this could be a bug in Docker Desktop Windows containers mode.

I'll spin up a Windows Server at some point and test behavior and see if we need to loop someone else in for a definitive response.

@drnybble have you tested behavior on Docker on Windows Server?

**Comment by drnybble** [comment]
It is a valid daemon.json on Windows Server.

{
    "log-opts": {
        "max-size": "5m",
        "max-file": "10"
    }
}

**Comment by nigelpoulton** [comment]
> It is a valid daemon.json on Windows Server.
> 
> ```
> {
>     "log-opts": {
>         "max-size": "5m",
>         "max-file": "10"
>     }
> }
> ```
> If you rename the key to something else the Daemon fails to start.

Cool, and not that I'm doubting you at all, but have you tested that it actually does anything, rather than being accepted but not actually doing anything?

Cheers.

**Comment by drnybble** [comment]
I have not tested it but given that daemon/logger/jsonfilelog/jsonfilelog.go is cross platform I don't have any reason to doubt it.
