### ISSUE TITLE
Use shell script to start stack

### ISSUE THREAD

**Issue by siaarzh** [docker/docs#8097]
File: [compose/django.md](https://docs.docker.com/compose/django/)

Instead of starting the Django container as root and being forced to `chown` the files created by the container, consider making the following changes:

1. Add `user:` to docker-compose.yml:
```docker-compose
version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    user: ${CURRENT_UID}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
```

2. Start the Django project with a shell script:
```bash
$ sudo CURRENT_UID=$(id -u):$(id -g) docker-compose run web django-admin startproject composeexample .
```

---
References:
- [Running a Docker container as a non-root user](https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as this content is no longer contained in the docs.
