### ISSUE TITLE
"bare metal" when meaning "physical host"?

### ISSUE THREAD

**Issue by hmijail** [docker/docs#8134]
File: [machine/concepts.md](https://docs.docker.com/machine/concepts/)
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)
File: [engine/security/security.md](https://docs.docker.com/engine/security/security/)

I would try editing the docs myself, but one of the files seems off-limits (probably because it's security-related?), so I'd like to check here first and get feedback.

There are at least 3 mentions of "bare metal" hosts in the documentation. But AFAIK, "bare metal" has always referred to "metal" (physical hardware) that is "bare" (without an OS)[1]. 

I come from a low-level software background, so this sent me off researching how this was done until I understood that this had to be some misuse of the term, and that in the Docker context this actually seems to refer to any non-virtual host that must be running an OS or hypervisor. This seems to be misleading others too [2].

So, I would propose changing "bare metal" for something more appropriate. Since the purpose seems to be to refer to non-virtual hosts, I'd suggest "physical hosts".

[1] https://en.wikipedia.org/wiki/Bare-metal_server
[2] https://stackoverflow.com/questions/20088835/docker-on-bare-metal

**Comment by hmijail** [comment]
Another example of people confused by the "bare metal" thing: https://stackoverflow.com/questions/27437092/difference-docker-on-bare-metal-and-docker-on-ubuntu?noredirect=1&lq=1

**Comment by L-Hudson** [comment]
Thanks for the ticket! You should have the ability to edit, and since the Docs team is wildly understaffed at the moment, that might be faster. In the meantime, I'll move this over to our queue.

**Comment by usha-mandya** [comment]
Not sure if this issue is still relevant with Docker machine being deprecated and the other pages mentioned above have been updated. I'm closing this issue for this reason. Please open a PR and suggest changes if the updates are still relevant. Thank you.
