### ISSUE TITLE
tmpfs topic : tmpfs-size in place of tmpfs-type in "Choosing the --tmpfs or --mount flag"

### ISSUE THREAD

**Issue by fdaschmidt** [docker/docs#8140]
File: [storage/tmpfs.md](https://docs.docker.com/storage/tmpfs/)

tmpfs-size in place of tmpfs-type in "Choosing the --tmpfs or --mount flag"

**Comment by L-Hudson** [comment]
I'm not seeing the specific place where the error is. The only tmpfs-size in that section is in fact referring to size. Can you cut and paste the problem section? Thanks.
