### ISSUE TITLE
The heading says communicate between swarm service and standalone container but explanation is for communication between two standalone containers

### ISSUE THREAD

**Issue by wlmpoc** [docker/docs#8387]
File: [network/network-tutorial-overlay.md](https://docs.docker.com/network/network-tutorial-overlay/)

**Comment by wlmpoc** [comment]
https://docs.docker.com/network/network-tutorial-overlay/#communicate-between-a-container-and-a-swarm-service

This mainly explains about running two alpine Linux containers attached to default bridge network with the ping <hostname> and ping <ip address> outputs.

Please update this with an example for standalone container and swarm service

Thanks
Sathya

**Comment by eeechoo** [comment]
same problem.
It's sad when read the official doc to learn docker network and find there are problems in the doc.
