### ISSUE TITLE
Docs updates for  "--no-interpolate" argument

### ISSUE THREAD

**Issue by usha-mandya** [docker/docs#8410]
### Problem description

Create a PR for documentation updates related to the addition of the new argument.

**Comment by usha-mandya** [comment]
@xificurC Could you create a PR for the Docs updates? Thanks.

**Comment by xificurC** [comment]
Hi @usha-mandya , there's an open PR [here](https://github.com/docker/docker.github.io/pull/8409). If you'd like to improve the documentation of this new flag please let me know what are your thoughts/suggestions so I can better reflect the changes in the docs.

**Comment by usha-mandya** [comment]
Sure, thanks.

**Comment by usha-mandya** [comment]
Closing this as the PR has been merged
