### ISSUE TITLE
Update startup-order doc to leverage depends_on

### ISSUE THREAD

**Issue by zaquestion** [docker/docs#8447]
File: [compose/startup-order.md](https://docs.docker.com/compose/startup-order/)

The above doc can be a bit misleading as it implies theres no way to wait for a container to be healthy/ready, which was supported in https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on

**Comment by ulyssessouza** [comment]
@zaquestion which part of the startup-order.md page is misleading? Can you please point to a specific section in the doc?

**Comment by zaquestion** [comment]
Basically the entire doc which talks about using a `wait-for.sh` script to control start up order instead of using the healthchecks added in v2.1

The same is true on: https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on 
> Note: depends_on does not wait for db and redis to be “ready” before starting web - only until they have been started. If you need to wait for a service to be ready, see Controlling startup order for more on this problem and strategies for solving it.

where "see Controlling startup order" links out to https://docs.docker.com/compose/startup-order/

but if you scroll down it tells you about the additions in v2.1

I think the entire startup order doc could be renamed "controlling startup order for compose v2.0" or something and it should probably just link out to a new doc or to the >v2.1 doc on `depends_on`

> A healthcheck indicates that you want a dependency to wait for another container to be “healthy” (as indicated by a successful state from the healthcheck) before starting.
