### ISSUE TITLE
Correction to SSH Service Page

### ISSUE THREAD

**Issue by odundar** [docker/docs#8552]
### Problem location

- I saw a problem on the following URL: <URL>

https://docs.docker.com/engine/examples/running_ssh_service/

There is a fault or a missing char in dockerfile so sshd server don't work when tried to login, access denied error is given, even the password is correct.

### Suggestions for a fix

Problem is that, sshd_config's default file starts with '#' sign but below command don't have it.

RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

So, it is being fixed with adding '#' as below

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as the content is no longer contained in the docs.
