### ISSUE TITLE
Non-blocking log docs conflicting with the actual implementation

### ISSUE THREAD

**Issue by libesz** [docker/docs#8629]
File: [config/containers/logging/configure.md](https://docs.docker.com/config/containers/logging/configure/)

The documentation for the non-blocking log option describes a ring-buffer mechanism:
`When the buffer is full and a new message is enqueued, the oldest message in memory is dropped.`

The [code](https://github.com/moby/moby/blob/master/daemon/logger/ring.go#L155) however seemingly does the opposite. The comment of the function also documenting a non-ring buffer: `If the message is too big for the buffer it drops the new message.`

A possible solution could be to align either to the other one.

**Comment by karlpokus** [comment]
This is unfortunate :/ I was just reading the docs about the log delivery mode

https://docs.docker.com/config/containers/logging/configure/#configure-the-delivery-mode-of-log-messages-from-container-to-log-driver

and then got confused when it's not allowed in daemon.json

https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file

Now I find out it's not even a ring buffer at all?

**Comment by cpuguy83** [comment]
Correct, not a ring. It could be turned into a ring... the original implementation was but was changed before merging just due to overhead.

**Comment by karlpokus** [comment]
Alright then.

@cpuguy83 do you know why the option is missing from the daemon.json docs?

**Comment by cpuguy83** [comment]
Probably just never got added to the docs. No reason other than that.
