### ISSUE TITLE
Build version is not the right one for 1.24.0

### ISSUE THREAD

**Issue by anthony-o** [docker/docs#8816]
File: [compose/install.md](https://docs.docker.com/compose/install/)

Mine is the following:
```bash
$ docker-compose --version
docker-compose version 1.24.0, build 0aa59064
```

**Comment by thaJeztah** [comment]
Hm, yes, I think that part is just to illustrate  (the important bit is the version number) We should probably replace that part of the output with something like `[build number]` to make clear that it might not match your actual output

@ulyssessouza wdyt?

**Comment by anthony-o** [comment]
@thaJeztah in that case, is there an official document that list every build number for every docker-compose version ? I didn't find such a file...

**Comment by thaJeztah** [comment]
The build-number is the commit that the version was built from, so in this case https://github.com/docker/compose/commit/0aa59064 those "should" match the corresponding tag on github; https://github.com/docker/compose/releases

However, I do see there's an inconsistency where the tag/release on GitHub uses the merge commit (https://github.com/docker/compose/commit/d9fa8158c39f9f4b9d60865e7cf44909b57f5c31), but the build using the commit itself; https://github.com/docker/compose/compare/0aa59064...d9fa8158c39f9f4b9d60865e7cf44909b57f5c31

Possibly something that should be addressed in the release scripts 🤔 

If the purpose is to verify the downloaded binary though, you can use the checksums that are listed on the releases page for each release; https://github.com/docker/compose/releases/tag/1.24.0

**Comment by anthony-o** [comment]
@thaJeztah thank you for this precision. Indeed, I need to verify the downloaded binary.

**Comment by thaJeztah** [comment]
Also had a quick chat with the compose maintainers, and the inconsistent commit was a known issue, which is being worked on as part of a rewrite of the release-tooling. The checksums should still be the best approach to verify the downloads though.
