### ISSUE TITLE
note `--user` args usage restriction

### ISSUE THREAD

**Issue by yuchengwu** [docker/docs#8831]
File: [engine/reference/run.md](https://docs.docker.com/engine/reference/run/)

Explicit state when passing a username, it must be already exist in container's `/etc/passwd`

xref: https://github.com/moby/moby/issues/22323#issuecomment-215449380

**Comment by craig-osterhout** [comment]
Thanks for sharing this issue. The content is maintained in an upstream repo. If the issue/PR is still applicable, please help create an issue in the upstream repo.
