### ISSUE TITLE
`Sorry, we can't find that page` from godoc link

### ISSUE THREAD

**Issue by magnuswahlstrand** [docker/docs#8952]
### Problem description

On the godoc API description, clicking the link in `
For more information about the Docker API, see the documentation: `<https://docs.docker.com/develop/api>` `, takes you to a `Sorry, we can't find that page
`.  

### Problem location

- I saw a problem on the following URL: https://godoc.org/docker.io/go-docker

### Suggestions for a fix

The link should probably go to <https://docs.docker.com/develop/sdk/> instead, e.g. change the url from from `/api/` to `/sdk/`?

**Comment by thaJeztah** [comment]
Note that the docker.io/go-docker package is still a work-in-progress project that hasn't been worked on for a long time ("(Still WIP) Official Go SDK for Docker") (probably that repository should be archived https://github.com/docker/go-docker  - @tiborvass wdyt?)

Looking through history of the docs, I don't think we ever had a page at that URL, so I'm a bit in doubt if we should add a redirect 🤔
