### ISSUE TITLE
Example does not work with go modules

### ISSUE THREAD

**Issue by ewxrjk** [docker/docs#9126]
File: [develop/sdk/examples.md](https://docs.docker.com/develop/sdk/examples/)

The Go example under 'SDK and API quickstart' does not build in a modules environment. `go mod` finds v1.13.1 of github.com/docker/docker which is too old for NewClientWithOpts (and others).

**Comment by PaperBag42** [comment]
It seems that this was fixed - the examples now all use `NewClientWithOpts`.
