### ISSUE TITLE
Note about "fake secrets" in non-swarm Docker mode

### ISSUE THREAD

**Issue by brezanac** [docker/docs#9156]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

Docker documentation unanimously claims that Docker secrets are available exclusively in swarm mode (i.e. https://docs.docker.com/engine/swarm/secrets/)

However, due to https://github.com/docker/compose/pull/4368 all the defined secrets in `docker-compose.yml` will become available to the running services even if Docker is running in non-swarm mode. 

The mechanism used for exposing the secrets to the services in those two modes is completely different though. In swarm mode the actual Docker secrets mechanism is used. In non-swam mode the "secrets" are just bind mounts to appropriate `/run/secrets` items.

Could you please add notes to the documentation that make the reader aware of this side effect because it could be really confusing if the documentation keeps insisting on secrets being exclusive to swarm mode, yet they are obviously available in non-swarm mode too through bind mounts.

**Comment by siddjain** [comment]
Thanks @brezanac . This is really important note.

**Comment by helderco** [comment]
I wish I knew this, I have to try!
