### ISSUE TITLE
Docker compose docs are incorrect about the EXPOSE config

### ISSUE THREAD

**Issue by nerdoftech** [docker/docs#9206]
### Problem description

The docs for docker-compose state the following about the expose configuration:

> Expose ports without publishing them to the host machine - they'll only be accessible to linked services. 

However, this is incorrect as any containers within the same docker network have unfettered network access between each other, e.g., I do not have to have an expose statement for a container to access ports on another container in the same network.

### Problem location

https://github.com/docker/docker.github.io/blame/master/compose/compose-file/index.md#L1157-L1158

### Project version(s) affected

All versions of docker compose I have ever worked with in the past 2 years.

### Suggestions for a fix

Add some clarification of the expose configuration.

**Comment by Bafff** [comment]
Yeah, but if the linked (manually or by default settings) to the same network they can talk to each other. But not to the host.

So I think that nothing is wrong there

**Comment by nerdoftech** [comment]
@Bafff What would be an example use case for the behavior you are describing? 

There seems to be a belief (based on the docs) on stackoverflow and various blogs that EXPOSE has to do with inter-container communication, so I am wondering if we have different use cases in mind.

**Comment by Bafff** [comment]
Ooops, I didn't understand what do you mean first.

So you know that you do not need to use EXPOSE so containers can talk with each other.

And maybe here what you need so you can point them?

**Comment by nerdoftech** [comment]
Hi Bafff, sorry to get back so late.

The thing with `-P` flag is that is only available to the `docker run` command, but is not for docker-compose (at least according to the docs). It seems the only purpose that expose in docker  compose is for documenting the internal ports of the container.

**Comment by Bafff** [comment]
@nerdoftech I think here is the best description https://stackoverflow.com/a/56826180

So maybe you'll make a pull request? :)
