### ISSUE TITLE
Unexplained elements in eg_sshd Dockerfile

### ISSUE THREAD

**Issue by samuela** [docker/docs#9424]
File: [engine/examples/running_ssh_service.md](https://docs.docker.com/engine/examples/running_ssh_service/)

There are two lines in this Dockerfile that are not commented or documented anywhere and it's not immediately clear what they do:
```Dockerfile
ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile
```

I get that the `RUN echo "export VISIBLE=now" >> /etc/profile` line wants that environment variable to be set in ssh sessions, but it's not clear what its purpose is. It's also not clear what the `ENV NOTVISIBLE "in users profile"` line is for.

**Comment by samuela** [comment]
See also https://stackoverflow.com/questions/36292317/why-set-visible-now-in-etc-profile

**Comment by integerbasic** [comment]
I don't believe those two lines have any _functional_ effect.  They are just examples.  Here is another way this section could be written that might be easier to understand:

    ENV EDITOR=/usr/bin/vim                                # warning: this line is not sufficient to set EDITOR for ssh session
    RUN echo "export EDITOR=/usr/bin/vim" >> /etc/profile  # this line is sufficient to set EDITOR for ssh session

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as the content is no longer contained in the docs.
