### ISSUE TITLE
Dockerize an ASP.NET Core application: ENTRYPOINT doesn't work 

### ISSUE THREAD

**Issue by awbacker** [docker/docs#9507]
File: [engine/examples/dotnetcore.md](https://docs.docker.com/engine/examples/dotnetcore/)

A few issues here, separated by dashes.  Thanks for the page, I used and modified it to get everything running on my first dockerized .net core service.  Also, handy way to suggest updates.  When I was first on the page there was the option to "edit this page" above to it, that disappeared on reload though.

----

`ENTRYPOINT ["dotnet", "myapp.dll"]` fails with the message:
> Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

Changing this to `CMD ["dotnet", "myapp.dll"]` works correctly.

----
The docker inspect line doesn't work on docker for mac.  

`docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" app`

Changing the name to `bridge` worked.  Easy enough if you know to just run `inspect` alone,  and I have no clue about windows or previous versions of docker and the network names.

`docker inspect -f "{{ .NetworkSettings.Networks.bridge.IPAddress }}" app`

---- 

The dockerfile has these comments.
> `# Copy csproj and restore as distinct layers`
> `# Copy everything else and build`

I think it would be good to say why (I have no idea, personally).  

Why copy one then build then copy everything else  Does this have some effect?  Does it make the `COPY --from` more efficient?  I'm sure there is a good reason, but I don't know why it isn't just 2 steps:  copy everything not in docker-ignore and then build.  This seems like a good place to educate people, I know I'd appreciate it.

----

`out/` should be added to the `.dockerignore` file recommendations.

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Closing as the content is no longer contained in the docs.
