### ISSUE TITLE
Golang SDK samples do not work

### ISSUE THREAD

**Issue by drewandersen** [docker/docs#9536]
File: [develop/sdk/examples.md](https://docs.docker.com/develop/sdk/examples/)

`go.mod` specifies `github.com/docker/docker v1.13.1`

Using go v1.13.1 on Ubuntu 16.04

Executing `go build` against the "Run a container" example produces the following errors:

```
./main.go:16:14: undefined: client.NewClientWithOpts
./main.go:16:39: undefined: client.FromEnv
./main.go:16:55: undefined: client.WithAPIVersionNegotiation
./main.go:40:53: undefined: container.WaitConditionNotRunning
```

Obviously this can be fixed with a few simple changes:

```
cli, err := client.NewEnvClient()`
```

```
if _, err := cli.ContainerWait(ctx, resp.ID); err != nil {
    panic(err)
}
```

However, what I'm not clear on is why the output from the command won't print to the host console unless the `Tty` field is set to `false` in the `config` parameter passed to the `ContainerCreate` function. Is there any additional documentation beyond those provided in the API docs, which appear to be incomplete?

**Comment by jpicht** [comment]
> Obviously this can be fixed with a few simple changes:
It is not at all obvious to me.

Sorry to say it, but broken docs are worse than useless. I'd rather not spend half an hour trying to find a version these examples actually compile against, until giving up and looking at the godocs.

Don't get me wrong: I appreciate the effort this whole project represents, but please rather link current auto-generated API-docs than include broken examples and waste peoples time.

Side note: why does the website say 19.x but there is no 19.x branch or tag in the git repository?

**Comment by tnir** [comment]
Related to #8310 #9126
