### ISSUE TITLE
List available properties for "docker-compose ps --filter"

### ISSUE THREAD

**Issue by cweiske** [docker/docs#9594]
There is no documentation for the `--filter` option in "docker-compose ps"

File: [compose/reference/ps.md](https://docs.docker.com/compose/reference/ps/)

Similar to #6682 and #7173, which have been closed "due to its age".

**Comment by n-insaidoo** [comment]
As of now the documentation is still outdated. If I didn't see this [comment](https://github.com/docker/compose/pull/5384#discussion_r156209966) I would've never figured out that the only filter states allowed are `running` and `stopped`.

**Comment by joostfunkekupper** [comment]
Still outdated, but now it's the opposite, the `--filter` option has now (annoyingly) been removed from the `docker compose ps` command.

**Comment by ndeloof** [comment]
@joostfunkekupper it's still there (for backward compatibility), just hidden to suggest users to adopt the more friendly `--status=xx` flag

**Comment by yariksheptykin** [comment]
@ndeloof , @joostfunkekupper , I've created a PR in documentaion summarizing the current state of `--filter` compatibility between compose v1 and v2. I hope this helps.

**Comment by joostfunkekupper** [comment]
@yariksheptykin Thanks for improving the documentation for the `--status` flag.
